### ISSUE TITLE
showMatrix throwing ImportError

### ISSUE THREAD

**Issue by wintersbane** [prody/ProDy#1005]
When trying to import DivergingNorm from Matplotlib throws this error, looks like function has been renamed to TwoSlopeNorm ( see https://matplotlib.org/3.2.1/api/api_changes.html#divergingnorm-renamed-to-twoslopenorm ).

**Comment by SHZ66** [comment]
Thanks a lot for reporting this issue. Please see if #1006 fixes the problem.
