### ISSUE TITLE
How to pass rmsd=False to showCrossProjection()

### ISSUE THREAD

**Issue by MigueLugo** [prody/ProDy#1012]
Thanks

**Comment by jamesmkrieger** [comment]
showCrossProjection and calcCrossProjection actually use calcProjection, so you can just give it rmsd=False in exactly the same way e.g.

`showCrossProjection(ensemble, mode1, mode2, rmsd=False)`

**Comment by jamesmkrieger** [comment]
I've updated the documentation to make this clearer and I think it's now ok to close this issue.
