### ISSUE TITLE
When parsing PDB files, is ACSIndex equivalent to model minus 1?

### ISSUE THREAD

**Issue by jonathanking** [prody/ProDy#1018]
Are the following two statements equivalent?

```
x = prody.parsePDB("1v88", model=2, chain="A")
```

```
x = prody.parsePDB("1v88", chain="A")
x.setACSIndex(1)
```

Am I correct in understanding that the `ACSIndex` is equal to `model` value minus 1?

Thank you.

**Comment by jamesmkrieger** [comment]
Yes, the `ACSIndex` is a Python index and starts at 0 while `model` index comes from the PDB file and starts at 1.

The two code statements are however different. The first one only parses model 2 (index 1) whereas the second statement parses all of them then makes the model with index 1 active. The first statement is better for not using up as much memory but the second one gives you more flexibility.

**Comment by jonathanking** [comment]
Thank you for clarifying, @jamesmkrieger!
