### ISSUE TITLE
calcPerturbResponse on extrenally supplied covariance matrix

### ISSUE THREAD

**Issue by mmagithub** [prody/ProDy#1042]
Hi,
I am trying to use the calcPerturbResponse function on a covariance matrix generated from an MD simulation using "WORDOM". The matrix shape is (3642, 3642).
I tried to use the function directly on this matrix, but it keeps complianing that an ANM or GNM instances have to exist. 

I tried:
covar_mat = np.genfromtxt('pca1-matrix.txt')
calcPerturbResponse(covar_mat)

But I am getting:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-83-92fb1a68b645> in <module>
      1 covar_mat = np.genfromtxt('pca1-matrix.txt')
----> 2 calcPerturbResponse(covar_mat)

~/anaconda3/envs/my-rdkit-env/lib/python3.8/site-packages/prody/dynamics/perturb.py in calcPerturbResponse(model, atoms, **kwargs)
     47 
     48     if not isinstance(model, (NMA, ModeSet, Mode)):
---> 49         raise TypeError('model must be an NMA, ModeSet, or Mode instance')
     50 
     51     if isinstance(model, NMA) and len(model) == 0:

TypeError: model must be an NMA, ModeSet, or Mode instance

Any clue how can I do that.

Thanks,
marawan

**Comment by jamesmkrieger** [comment]
Hi Marawan,

I think I need to change the code to let you do that. I'll have a look and get back to you.

Best wishes
James

**Comment by jamesmkrieger** [comment]
I think my changes should work now so this functionality should be available to you soon. Thanks for your pull request.

**Comment by jamesmkrieger** [comment]
Actually, the best way to do this is to provide the matrix to a PCA model. I've updated the docs in #1044 to explain this.

**Comment by jamesmkrieger** [comment]
(#1043 where I updated the code is closed without merging as we can do this without that)

**Comment by jamesmkrieger** [comment]
We are also planning to update the online tutorial to help with this.

**Comment by mmagithub** [comment]
Thanks James, I tried the following:

pca = PCA()
pca.setCovariance(covar_matrix)
pca.calcModes()
prs_mat, eff, sens = calcPerturbResponse(pca)

But I got this error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-09c483a4add3> in <module>
      2 pca.setCovariance(covar_matrix)
      3 pca.calcModes()
----> 4 prs_mat, eff, sens = calcPerturbResponse(pca)

~/anaconda3/lib/python3.6/site-packages/ProDy-1.10.11-py3.6-macosx-10.7-x86_64.egg/prody/dynamics/perturb.py in calcPerturbResponse(model, atoms, **kwargs)
     78     else:
     79         cov_squared = cov**2
---> 80         n_by_3n_cov_squared = np.zeros((n_atoms, 3 * n_atoms))
     81         prs_matrix = np.zeros((n_atoms, n_atoms))
     82         i3 = -3

TypeError: 'float' object cannot be interpreted as an integer

Any clue?

**Comment by jamesmkrieger** [comment]
Hi Marawan,

This problem comes from setCovariance because of how Python 3 does divisions, which returns floats rather than integers. I have now fixed it in #1046. 

Best wishes
James

**Comment by jamesmkrieger** [comment]
See https://en.wikibooks.org/wiki/Python_Programming/Operators#Division_and_Type_Conversion

**Comment by mmagithub** [comment]
Thanks, James,
So, can I reinstall prody now (through pip or conda) and I should find this issue fixed ?

**Comment by jamesmkrieger** [comment]
Almost. I still need to merge the change and then you'll need to pull the newest version from github and run `pip install -U .` in your directory. You can't run `pip install -U prody` until we make a new release to PyPI, which is probably weeks away.

**Comment by mmagithub** [comment]
Good. Can you point out to me which script/modules you have modified and I can simply copy and paste the changes to my existing codebase (or replace the module completely by the new one) and retry if you think this will work!

**Comment by jamesmkrieger** [comment]
If you look at https://github.com/prody/ProDy/pull/1046/files then you'll see that I made a change to line 47 of prody/dynamics/pca.py and you should be able to just make that change. You probably don't even need to reinstall anything actually as it's a python code change. There are other changes we've made recently that might need actually installing but none that I remember recently.

**Comment by mmagithub** [comment]
Thanks James, I will try and let you know if it works.
Have a wonderful day

**Comment by jamesmkrieger** [comment]
You're welcome. Hope you have a wonderful day too

**Comment by mmagithub** [comment]
it works, thanks so much James.

**Comment by jamesmkrieger** [comment]
You're welcome. I've now merged that change and I'm closing this issue
