### ISSUE TITLE
error: "ModuleNotFoundError: No module named 'setuptools' " ; How to mitigate 

### ISSUE THREAD

**Issue by ajaymltr** [prody/ProDy#1053]

**Comment by SHZ66** [comment]
Could you provide more details such as which platform are you running ProDy on, Python version, and what kind of installation (e.g. pip install or install from the source)?

**Comment by ajaymltr** [comment]
> Could you provide more details such as which platform are you running ProDy on, Python version, and what kind of installation (e.g. pip install or install from the source)?

@SHZ66 I'm using python2.7 and used pip for the installation .. then it said biopython requires python 3.6 so i tried pip3 ,then it said there is no module called "setuptools". Again I tried using the source, The same error came
this was the entire output
![screenshot](https://user-images.githubusercontent.com/64061197/83487318-731e4700-a4c8-11ea-9210-6675aa19c56f.png)

Thanks and regards
Ajay

**Comment by SHZ66** [comment]
Thanks for providing the info. Could you try the solution provided in this [post](https://stackoverflow.com/questions/22531360/no-module-named-setuptools)?

**Comment by ajaymltr** [comment]
@SHZ66 Thank you it worked !!

**Comment by SHZ66** [comment]
Great! You are very welcome. I am closing this post for now.
