### ISSUE TITLE
VMD NMWiz Application Error

### ISSUE THREAD

**Issue by cvoleti** [prody/ProDy#1090]
Hi,

I'm getting this error message when I try to use the ProDy Interface from Normal Mode Wizard in VMD:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/prody", line 5, in <module>
    from prody.apps import prody_main
ImportError: No module named prody.apps
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/prody", line 5, in <module>
    from prody.apps import prody_main
ImportError: No module named prody.apps
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody anm --quiet -s $selstr {*}$args "$pdbfn""
    (procedure "::NMWiz::prodySubmitANMjob" line 42)
    invoked from within
"::NMWiz::prodySubmitANMjob"
    (procedure "::NMWiz::prodySubmitJob" line 22)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

I have Python 3.8.3, ProDy 1.10.11, and VMD 1.9.4a38. I used pip to install ProDy and when I do $python3.8, import prody works.

I would appreciate any help. Thank you.

**Comment by ConradJohnston** [comment]
@cvoleti - It would be great if you could share the resolution to this issue, please?

**Comment by jamesmkrieger** [comment]
I agree. Please share more details about what the problem was and how you solved it so that it can benefit the developers and other users. Please include information such as what operating system you have as well.

**Comment by ConradJohnston** [comment]
@jamesmkrieger - I had selfish motivation for suggesting this as I'm seeing the same issue. 
VMD 1.9.4a43 and OSX 10.15.7. I suspect @cvoleti is also a Catalina user and this is why they're using a development version of VMD.

**Comment by jamesmkrieger** [comment]
Thanks @ConradJohnston. That makes sense.
