### ISSUE TITLE
Building ANM for Cryo-EM map

### ISSUE THREAD

**Issue by gmk19001** [prody/ProDy#1113]
I am trying to build an ANM model for a cryo-em map using the tutorial listed on the ProDy website. However, after I parse the structure using parseEMD and create the ANM instance, I cannot build the hessian matrix. The error listed says: "coords must be a Numpy array or an object with `getCoords` method"

I then try to convert my emd to numpy array and receive errors. 

Is there a step that I am missing or something that I can do to resolve these errors?

**Comment by jamesmkrieger** [comment]
As it says, you need an object with the `getCoords` method or a coordinate array to build a Hessian matrix. If you use `parseEMD` with the appropriate parameters then you should get an `AtomGroup`, which has that method and contains a set of pseudoatoms that have been fit to the cryo-EM density map using the topology representing network algorithm (using the `TRNET` class, which you can also use yourself). However, that function by default gives you the EM density map (an `EMDMAP` object) directly. Can you check what your output is and what ProDy version you're using please?

**Comment by jamesmkrieger** [comment]
It looks like the same behaviour of building coordinates using TRNET is triggered by the command on the website tutorial with both the latest PyPI release (version 1.10.11 from 25th October 2019) and the latest development version on Github (which has been version 1.11 for a long time). Can you update your ProDy to one of those and see if that fixes it?

Many thanks
James

**Comment by jamesmkrieger** [comment]
I definitely get an AtomGroup with both ProDy versions and the Hessian gets built fine too.

**Comment by gmk19001** [comment]
Hi James,

Thank you for getting back to me and for this useful information. I think that it was my version of that was giving me trouble. I was using 1.10.10. I reinstalled and everything is working well now.
All the best,
Genny
---

Genevieve Kunkel
Graduate Student, Tarakanova Lab
Dept. of Mechanical Engineering, University of Connecticut

genevieve.kunkel@uconn.edu (mailto:genevieve.kunkel@uconn.edu)

**Comment by jamesmkrieger** [comment]
Hi Genny,

You're welcome. I'm glad to hear it works now.

Best wishes
James
