### ISSUE TITLE
Cannot add parameter files in DruGUI

### ISSUE THREAD

**Issue by lezonlab** [prody/ProDy#1133]
When trying to add parameter files in DruGUI (a necessary step after using AutoPSFbuilder in VMD) on Ubuntu, the following error appears:
Error: Can't read "tempfiles": no such variable

Its details:
can't read "tempfiles": no such variable
can't read "tempfiles": no such variable
    while executing
"if {$tempfiles!=""} {
          foreach tempfile $tempfiles {
            if {[lsearch $::druggability::par_files $tempfile] > -1} {
              tk_..."
    (in namespace inscope "::druggability" script line 3)
    invoked from within
"::namespace inscope ::druggability {
        set tempfile [tk_getOpenFile -multiple 1 -filetypes { {{CHARMM parameter files} {.prm .inp}} {{All files}..."
    invoked from within
".druggui.main_frame.prepare.output_options.par_add invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .druggui.main_frame.prepare.output_options.par_add"
    (command bound to event)

**Comment by jamesmkrieger** [comment]
Can you tell us which version of DruGUI, VMD, AutoPSFbuilder and Ubuntu you are using please?

**Comment by lezonlab** [comment]
DruGUI 1.1 (as identified in drugui.tcl) was downloaded as a .tgz from the ProDy website on 08/28/2020.
The error occurs using VMD 1.9.3 (autopsf1.6) on Ubuntu 20.04.

Minimum action required to reproduce the error:

  1.  Launch VMD
  2.  Open DruGUI window from Extensions -> Modeling tab
  3.  By "additional parameters" entry at bottom, click "Add"
  4.  Click "Cancel" in pop-up

________________________________

**Comment by jamesmkrieger** [comment]
Thanks

**Comment by jamesmkrieger** [comment]
We have an MMBioS workshop in 10 days and a paper due at the end of the month, and then I'll work on DruGUI and Pharmmaker after that. Just thought I'd let you know

**Comment by jamesmkrieger** [comment]
I can confirm that this problem is seen in the version of DruGUI from the ProDy website (downloaded today) on my Windows computer too, but not with the GitHub version (https://github.com/prody/DruGUI) so please use that one instead. We will update the ProDy website with this version soon.

Many thanks again for reporting this problem.

**Comment by jamesmkrieger** [comment]
The drugui plugin tgz and zip files are now replaced on the website.
