### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by simonbray** [prody/ProDy#1146]
Hi,

Just to let you know I've submitted a conda recipe for ProDy to conda-forge. Please feel free to comment here: https://github.com/conda-forge/staged-recipes/pull/12605. I can also add any ProDy developers as package maintainers, if desired.

All the best,

Simon

**Comment by jamesmkrieger** [comment]
Thanks Simon! 

I did have a conda recipe on my radar as other users have started developing them on their own forks before, but I really appreciate you systematically doing it and getting in touch.

Please do add us as package maintainers and also mention the Bahar lab generally in the description somewhere. I am currently the main developer as the other major developers have left the group, but I recently updated the list so all of them can be found at https://github.com/prody/ProDy/pull/1142/files.

Best wishes
James

**Comment by simonbray** [comment]
You're welcome!

I pinged you on the conda-forge PR, could you please comment there to confirm you're willing to act as a maintainer?

**Comment by jamesmkrieger** [comment]
Ok, done. Thanks Simon

**Comment by jamesmkrieger** [comment]
ProDy is now successfully incorporated into conda-forge so I'm closing this issue. Thanks so much again!

**Comment by jamesmkrieger** [comment]
Actually, there are still problems, so I'm reopening it.

Any idea what's going wrong?

**Comment by jamesmkrieger** [comment]
Also, I'm trying to setup Travis CI to checks the conda-forge version (see https://github.com/prody/ProDy/pull/1152), but it's not triggering.

**Comment by simonbray** [comment]
> Actually, there are still problems, so I'm reopening it.

What kind of problems? I can install on linux without any issues.

**Comment by simonbray** [comment]
> Also, I'm trying to setup Travis CI to checks the conda-forge version (see #1152), but it's not triggering.

It seems to be failing: https://travis-ci.org/github/prody/ProDy/jobs/727318237

**Comment by jamesmkrieger** [comment]
> > Also, I'm trying to setup Travis CI to checks the conda-forge version (see #1152), but it's not triggering.
> 
> It seems to be failing: https://travis-ci.org/github/prody/ProDy/jobs/727318237

It failed twice, but then I tried making some more changes and it didn't trigger any more checks. I also agree with your point about not needing that anyway.

**Comment by jamesmkrieger** [comment]
> > Actually, there are still problems, so I'm reopening it.
> 
> What kind of problems? I can install on linux without any issues.

The checks failing, which now aren't any more. I could install it on Windows too.
