### ISSUE TITLE
Bio.SubsMat has been deprecated

### ISSUE THREAD

**Issue by tekpinar** [prody/ProDy#1150]
Hi,
I am using prody in a project to parse MSA files (and some other stuff). When trying to package it, it gives the following warning: 

/prody/sequence/msa.py:11:from Bio.SubsMat import MatrixInfo as matlist
BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.

It would be nice to consider it in a future release. 
Best,
Mustafa

**Comment by jamesmkrieger** [comment]
Hi Mustafa,

Thanks for the message. 

I also noticed this deprecation warning too so I looked into it and we do not actually use the substitution matrices from Biopython so I removed this import in https://github.com/prody/ProDy/pull/1138. The next release should, therefore, not give the deprecation warning. 

If you can find a way to incorporate the substitution matrices, that would of course be much better.

Best wishes
James
