### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yeseniamacevedo** [prody/ProDy#1171]
pip install ProDy  and pip install -U prody are not working and gives errors. Help!

**Comment by jamesmkrieger** [comment]
Please give us more information. What are the errors? What is your operating system? etc.

**Comment by yeseniamacevedo** [comment]
Hi there,

I waited a few days and tried to reinstall it and it worked. I don't know
what was the problem, but it resolved itself.

Thank you for your assistance.

Yesenia
