### ISSUE TITLE
EDA Comparison

### ISSUE THREAD

**Issue by tangdavid** [prody/ProDy#1174]
Hi,

I computed the top modes of motion for two sets of PDB's of the same protein and was wondering whether or not there was a way to compare the similarity of the two results in ProDy.

Thanks,
David

**Comment by jamesmkrieger** [comment]
Hi David,

The functions you would need for that are `calcOverlap` or `showOverlapTable`. 

You need to make sure that the two ensembles are aligned first. The best way to do that is create one ensemble with both sets of structures in it, iteratively superpose that ensemble with its `iterpose` method, then create two new ensembles by indexing it, and then perform the EDA analysis on those two ensembles.

Best wishes
James
