### ISSUE TITLE
mmCIF file for 4V88 does not include correct chains

### ISSUE THREAD

**Issue by jonathanking** [prody/ProDy#1175]
When parsing the RCSB protein [structure](https://www.rcsb.org/structure/4v88) `4V88`, prody seems to only parse a few chains from the many available chains in the structure.

For instance, the chain `BU` (along with many other 2-letter chains) is present in the structure file, but not when parsing with prody.

```
>>> ag = pr.parseCIF('4v88')
>>> ag
<AtomGroup: 4v88 (413613 atoms)>
>>> ag['BU']
>>> ag
>>> ag = pr.parseCIF('4v88', chid='BU')
>>> ag
<AtomGroup: 4v88 (413613 atoms)>
>>> ag.getChids()
array(['A', 'A', 'A', ..., 'D', 'C', 'D'], dtype='<U1')
>>> set(ag.getChids())                                                                                                                
{'D', 'B', 'A', 'C'}
```

Perhaps this is due to some complexity I am unaware of regarding the file type. Thanks in advance for your help!

**Comment by jamesmkrieger** [comment]
Hi Jonathan,

I'll have a look and get back to you. 

You should be using `chain='BU'` not `chid='BU'` in parseCIF by the way. Also, you may want to pull the latest changes from github again and see whether that helps. 

Best wishes
James

**Comment by jamesmkrieger** [comment]
Hi Jonathan,

It looks like it works for me using the current GitHub ProDy master:

```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from prody import *

In [2]: import numpy as np

In [3]: ag = parseMMCIF('4v88')
@> 413613 atoms and 1 coordinate set(s) were parsed in 8.46s.

In [4]: ag['BU']
Out[4]: <Segment: BU from 4v88 (1 chains, 1 atoms)>

In [5]: ag.select('chain BU')
Out[5]: <Selection: 'chain BU' from 4v88 (796 atoms)>

In [6]: np.array(set(ag.getChids()))
Out[6]:
array({'AF', 'DX', 'DI', 'Dg', 'BM', 'DK', 'Cd', 'Di', 'BI', 'DM', 'CP', 'AK', 'Ce', 'Bo', 'Db', 'Dm', 'DC', 'AB', 'A5', 'CA', 'Ba', 'CY', 'Af', 'AQ', 'Bb', 'Bk', 'BW', 'Bl', 'Dq', 'Dr', 'Dj', 'DG', 'CZ', 'AV', 'AE', 'BR', 'BJ', 'DL', 'CH', 'CO', 'CQ', 'Df', 'Bc', 'CE', 'AL', 'BZ', 'CM', 'AP', 'A4', 'Be', 'AC', 'DS', 'BV', 'DR', 'CV', 'Do', 'DN', 'AN', 'BE', 'CN', 'AY', 'DV', 'DH', 'Dn', 'CD', 'CR', 'A8', 'DP', 'CS', 'CB', 'BP', 'BQ', 'Ad', 'Bf', 'DA', 'Dp', 'BL', 'Cg', 'DB', 'Ac', 'AM', 'A6', 'CL', 'AW', 'BD', 'DF', 'Ds', 'Cf', 'Cb', 'AO', 'BA', 'Cc', 'DE', 'CT', 'De', 'AD', 'DW', 'DO', 'Dh', 'AZ', 'Bg', 'BY', 'AH', 'Bn', 'AU', 'CF', 'DZ', 'AA', 'BO', 'BT', 'CW', 'AG', 'CX', 'CJ', 'BS', 'Dc', 'A1', 'AI', 'AX', 'AJ', 'Bi', 'BH', 'Ah', 'DD', 'Bm', 'Bj', 'Ch', 'CK', 'DQ', 'BX', 'Bp', 'AR', 'AT', 'DJ', 'Ae', 'BN', 'DY', 'CG', 'Bh', 'BC', 'Dd', 'Bd', 'Ab', 'CU', 'BG', 'Aa', 'AS', 'CI', 'A3', 'CC', 'Dl', 'A7', 'BF', 'BB', 'A2', 'Ag', 'Da', 'Ca', 'DU', 'DT', 'BU', 'Dk'},
      dtype=object)
```

I'd suggest you update your ProDy with the latest changes.

Also, please note that the indexing operation `ag['BU']` indexes by the first part of the hierarchical view, which is segments when they are present as they are here. If you want to get the chain without knowing the segment name then you need to use the `select` method instead as I did. 

If you then want to get a `Chain` object you need to do either of the following.

1. query the selection for its segment names and then index using them:

```
In [43]: set(ag.select('chain BU').getSegnames())
Out[43]: {'FB'}

In [44]: ag['FB','BU']
Out[44]: <Chain: BU from Segment FB from 4v88 (100 residues, 796 atoms)>
```

2. instantiate a `Chain` object directly:

```Chain(ag, ag.select('chain BU')._indices, ag.getHierView(), ag._acsi)```

It would be nice if you didn't need to do that. I'll see what I can do.

Best wishes
James

**Comment by jamesmkrieger** [comment]
Once I merge the pull request, then it should work if you update your ProDy again.

**Comment by jamesmkrieger** [comment]
Ok, merged.

**Comment by jonathanking** [comment]
Thank you, @jamesmkrieger! This is super helpful.

After your merge, what's the recommended method for extracting a chain object? By providing a chain argument to `parseMMCIF` or by first turning it into a Hierarchical View, and then calling `.getChain()`? Are they equivalent?

**Comment by jamesmkrieger** [comment]
You're welcome. They are very much not equivalent. If you provide an argument to parseMMCIF then you only parse that chain, but into an AtomGroup object. Using indexing is the same as using the hierarchical view  and calling .getChain and then you get a Chain object, which still has access to the AtomGroup.
