### ISSUE TITLE
Empty lines return issue

### ISSUE THREAD

**Issue by pascalschlaepferprivate** [prody/ProDy#1185]
If the result from pfam comes back with empty lines for whatever reason, then that yields an error.

File "/path/to/.pyenv/versions/3.8.2/lib/python3.8/site-packages/prody/database/pfam.py", line 146, in searchPfam
    root[i][key] = line.split('\t')[j]
IndexError: list index out of range

can be resolved by adding the last line in pfam.py:
lines = tsv.split('\n')
keys = lines[0].split('\t')
lines = list(filter(None, lines))

**Comment by pascalschlaepferprivate** [comment]
I found that this is not helping.
The issue is already with PFAM.
I found another bug in the tsv result file.

**Comment by jamesmkrieger** [comment]
Files on databases can have strange things in them. I think being able to parse those files anyway could still be helpful. Can you share an example that triggers this problem please?

Many thanks

**Comment by pascalschlaepferprivate** [comment]
I'm currently not in the office.
I contacted pfam. They redirected to hmmer site. I contacted them. No reply
sofar.

I send you the sample as soon as I can.
Thanks,
Pascal

Am Di., 13. Okt. 2020 um 12:49 Uhr schrieb James Krieger <
notifications@github.com>:

**Comment by jamesmkrieger** [comment]
Thanks for trying, Pascal. Good luck getting through but don't worry too much if you can't.

**Comment by pascalschlaepferprivate** [comment]
Dear James,

Please report if this helps:

So here is the issue, if you run this sequence:
>Tpseu
EDEGEDGYKVGGYHRVKVGEIYNQRYVVIKKLGWGHFSTVWMVKDRRVVANKPPGGTANQ
PVFFALKVQKSAEHYTEAAMDEVELLDCIAQERKRCEGTLVSKGPMSRDSDGIRAIDNVD
HSRHVATLYDSFFHNGPHGRHMSMVFSMLGCNLLSVIKAHNYRGIPIPAVKRMIKGVCKG
LDFLHRRCQIIHTDLKPENILLQFPDQICPPSVFDDDAGDEHAEDDDTIGQNSQQEGVSI
EELEASLKNPKLSTEERKKLKKRLKKKRQKERRKQASVTDLDHALEEDDDDDTITEADLR
STVSEAEMQSYFKKMSASPSMNGNGTPFEGNKFAAIARASYQPDLKDMDILMRCRAVIVD
LGNACWTHRHFSEDIQTRQYRAPEVLIGSKYDASADMWSLGCITFELLTGDLLFDPRAGD
DYDRDEDHLAMFQELLGKMPKKLATAGKYSKNFFDKKGNLKNIKQLKFWPVEEVLHEKYH
FATEDAEEVADFMTPCLDFDPTERATGLECLRSDWLQDDAEERGR

You generate something like this result request:
https://www.ebi.ac.uk/Tools/hmmer/download/5D14BBF2-1614-11EB-85A1-0370F75AEC3D/score?format=tsv

Which generates the attached file.

In the file you see this:
Family id Family Accession Clan Env. Start Env. End Ali. Start Ali. End
Model Start Model End Bit Score Ind. E-value Cond. E-value Description
Pkinase PF00069.25 CL0016 105 209 113 203 49 132 41.91 7.4e-11 8.2e-15
Protein kinase domainPkinase PF00069.25 CL0016 341 516 344 516 123 264
74.96 6.1e-21 6.8e-25 Protein kinase domain
Pkinase_Tyr PF07714.17 CL0016 109 226 117 204 56 138 23.78 2.4e-05 2.6e-09
Protein tyrosine kinase

You can see that the first and second hit are fused and should be
Family id Family Accession Clan Env. Start Env. End Ali. Start Ali. End
Model Start Model End Bit Score Ind. E-value Cond. E-value Description
Pkinase PF00069.25 CL0016 105 209 113 203 49 132 41.91 7.4e-11 8.2e-15
Protein kinase domain
Pkinase PF00069.25 CL0016 341 516 344 516 123 264 74.96 6.1e-21 6.8e-25
Protein kinase domain
Pkinase_Tyr PF07714.17 CL0016 109 226 117 204 56 138 23.78 2.4e-05 2.6e-09
Protein tyrosine kinase

Interestingly, if you search manually, you get two significant and two
insignificant results.
I'm not sure what happens if you bulksearch.

Cheers,
Pascal

Am So., 18. Okt. 2020 um 15:08 Uhr schrieb James Krieger <
notifications@github.com>:

**Comment by jamesmkrieger** [comment]
Thanks Pascal. I guess you’re right this isn’t really something that ProDy can work out so I agree to close the issue.
