### ISSUE TITLE
add mmCIF writer and maybe others

### ISSUE THREAD

**Issue by jamesmkrieger** [prody/ProDy#1186]
We currently only have `parseMMCIF` but not `writeCIF` or `writeMMCIF`. We do have `parseSTAR` and `writeSTAR`, but that may not be specific enough.

It could be good to provide a connection to some other library such as mdanalysis, mdtraj, chemfiles or gemmi so we can use their writers for mmCIF files and other formats.

**Comment by jamesmkrieger** [comment]
MDTraj doesn't have one but there is a also PDBx/mmCIF writer in BioPython that we could use (see https://github.com/mdtraj/mdtraj/issues/652).

**Comment by danny305** [comment]
Has this been implemented yet? And has it been implemented to write pqr data to cif? 
Also, if not I would like to vote for gemmi.

**Comment by jamesmkrieger** [comment]
Thanks Danny. Someone else suggested GEMMI to me too

**Comment by jamesmkrieger** [comment]
This is now solved in #1816
