### ISSUE TITLE
Add option to parse alternating chain labels as separate chains for PDB parser 

### ISSUE THREAD

**Issue by nffaruk** [prody/ProDy#1192]
Hello, our research group uses ProDy to parse PDBs during input generation for our [coarse grained MD simulation package](https://github.com/sosnicklab/upside-md). We are trying to go to bigger systems with 100s of protein molecules. To compose the initial configuration of these systems and pack our simulation box, we are hoping to use [Packmol](http://m3g.iqm.unicamp.br/packmol/examples.shtml), which provides an option to output PDB structures with alternating chain labels (ABABABA...) to denote different molecules (considering that the PDB format is limited in the number of chains).

Is it possible to add an option to ProDy's PDB parser to recognize alternating chain labels as completely new chains? Thank you.

**Comment by jamesmkrieger** [comment]
I don't think it's currently possible but it's probably possible to add that functionality.

**Comment by jamesmkrieger** [comment]
I think I have code that now works for this. I'm yet waiting for it to go through the checks and if it works I'll merge the pull request.

**Comment by nffaruk** [comment]
Great, we'll give it a test on our end. Thanks!

**Comment by nffaruk** [comment]
Hello, it appears that I wasn't clear enough in the original description. Assume 2 atoms per chain and 3 chains for illustration, the new code seems to be looking for alternating chain labels for each atom:

atom 0 chain A
atom 1 chain B
atom 2 chain A
atom 3 chain B
atom 4 chain A
atom 5 chain B

Whereas the Packmol output is structured like this:

atom 0 chain A
atom 1 chain A
atom 2 chain B
atom 3 chain B
atom 4 chain A
atom 5 chain A

We'd like the third chain (atom 4, 5) to be considered a separate chain from the first chain, which is also labeled "A". See the attached pdb file for a realistic example with 5 chains with alternating labels. Thank you.
[1IYT_multi.zip](https://github.com/prody/ProDy/files/5487480/1IYT_multi.zip)

**Comment by nffaruk** [comment]
I've submitted a fix that works for the intended scenario when chain ids alternate in blocks, as output from Packmol. Also, numeric chain ids are used instead of letter ones if the alternating case is detected, since it's more natural for 100s of chains.

**Comment by jamesmkrieger** [comment]
Ok. I’ll revert the original fix. Sorry for not giving you time to reply on it. Also, please include a keyword argument for controlling this. It could be that other users don’t want that behaviour.

**Comment by jamesmkrieger** [comment]
Actually, `_parsePDBLines` doesn't have any kwargs so I suggest you move your code to `parsePDBStream` like we have for assigning secondary structures and building biomolecular assemblies. You could also put it in a wrapper function to make things cleaner like is done for them. 

You'd add a kwarg around like 246 and then have a block for checking if the value is True then running your function around line 336. I'm happy to adapt your code for that.

Best wishes
James

**Comment by jamesmkrieger** [comment]
Also, we currently can't support hundreds of chains with numbers because chainids can only be two characters so we'd need to add support for that too. There's a tradeoff here because in most cases it doesn't need to be long and we want to save memory when we have large PDB files. I'm thinking I'll just lengthen the data type specification on the fly as the length gets exceeded.

**Comment by nffaruk** [comment]
Your new code code is looking good, thanks.

**Comment by jamesmkrieger** [comment]
You're welcome. Thanks for checking it.
