### ISSUE TITLE
ImportError: from splinter import Browser

### ISSUE THREAD

**Issue by fongchun** [prody/ProDy#1214]
Recently, I installed a new ProDy in a new machine from the source code. There is an ImportError raised when I was testing it. 

Maybe we don't have to import the Browser from splinter when the ProDy is imported. We can import it only if we are using the quartataweb.py. The importing codes could be moved and placed inside the function of the class. 

----------------

In [1]: from prody import *
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/mnt/raid1/hongchun/Codes/ProDy/prody/database/quartataweb.py in <module>
     18 try:
---> 19     from splinter import Browser
     20 except ImportError:

ModuleNotFoundError: No module named 'splinter'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-5d14cc12dc44> in <module>
----> 1 from prody import *

/mnt/raid1/hongchun/Codes/ProDy/prody/__init__.py in <module>
     96 __all__.append('measure')
     97
---> 98 from . import database
     99 from .database import *
    100 __all__.extend(database.__all__)

/mnt/raid1/hongchun/Codes/ProDy/prody/database/__init__.py in <module>
     40 __all__.extend(goa.__all__)
     41
---> 42 from . import quartataweb
     43 from .quartataweb import *
     44 __all__.extend(quartataweb.__all__)

/mnt/raid1/hongchun/Codes/ProDy/prody/database/quartataweb.py in <module>
     19     from splinter import Browser
     20 except ImportError:
---> 21     raise ImportError('Browser module could not be imported. '
     22                       'install splinter package to solve the problem.')
     23 else:

ImportError: Browser module could not be imported. install splinter package to solve the problem.

**Comment by jamesmkrieger** [comment]
Hi Hongchun,

I noticed this bug and thought I fixed it. Sorry I didn't push that commit. I will do so now and let you know when I'm done.

Best wishes
James

**Comment by jamesmkrieger** [comment]
Just waiting for the checks

**Comment by jamesmkrieger** [comment]
This should be fixed now. Sorry about that
