### ISSUE TITLE
Choice of ProDy tools for conformational changes

### ISSUE THREAD

**Issue by chiendarret** [prody/ProDy#1216]
With classical MD for a protein and its peptide ligand I am observing repeating sudden raising of RMSD vs frame followed by flat regions, typical of conformational changes. As a novice to ProDy, I would appreciate receiving advice on which ProDy tool  might be best to unravel such changes. Thanks

**Comment by jamesmkrieger** [comment]
You may be better off watching the simulation than using ProDy to analyse what’s happening. 

I’d imagine your problem is something to do with the periodic boundary, which is something you could fix gromacs trjconv or vmd pbctools.

**Comment by chiendarret** [comment]
I believe the periodic boundary does not need fixing.
I am reading from "Altered conformational sampling along an evolutionary
trajectory
changes the catalytic activity of an enzyme Joe A. Kaczmarski et al"
bioRxiv preprint doi: https://doi.org/10.1101/2020.02.03.932491 ; t

Distances between the α-carbons of the
> tagged residues and the radii of gyration were calculated using the ProDy
> package on
> snapshots sampled every 0.1 ns 64 . In addition, representative snapshots
> (with a range of
> Cα–Cα distances) corresponding to the closed, open and wide-open states
> (if sampled)
> were selected for modelling of Gd(III)–Gd(III) distances. Allocation of
> states
> (closed/open/wide-open) was done based on Cα–Cα measurements. One snapshot,
> which was initially allocated as open based on its Cα–Cα distance, could
> also be
> grouped as wide-open based on principal component analysis (PCA, performed
> in
> ProDy), and was therefore included in both groups.
>

Is not that what might solve my problem?

**Comment by jamesmkrieger** [comment]
Sounds like they used a range of ProDy tools there. You can find the ones they mentioned as the calcDistance and calcGyradius functions and the PCA class (also known as essential dynamics analysis or EDA), which can be applied to trajectory or ensemble objects as in http://prody.csb.pitt.edu/tutorials/trajectory_analysis/

There is a lot of documentation and tutorials but please let me know if something isn’t clear.

Best wishes 
James

**Comment by jamesmkrieger** [comment]
I'll close this issue for now but feel free to open it again if you have any problem

Best wishes
James

**Comment by chiendarret** [comment]
Continuing, what I am interested most is evaluating the evolution of
distances between selected atoms of the protein and its peptide ligand

**Comment by jamesmkrieger** [comment]
You can see how to do that in http://prody.csb.pitt.edu/tutorials/trajectory_analysis/trajectory2.html. Basically what you need to do is the following:

1. Load a trajectory (DCD file) into ProDy along with a structure (PDB or PSF) and link them together.

2. Make selections of the atoms you want to find the distances between. You can have either 1 atom in each selection, 1 atom in one selection and another number of atoms in the other, or the same number of atoms that isn't 1 in both. 

3. Initialise a list or array for the values.

4. Loop through frames and calculate the distances and add the values into the list or array. If you make one of the selections have multiple atoms then it will calculate the distance between those atoms and the one atom in the other selection. If you provide the same number of atoms in both selections then it will calculate distances between pairs of atoms based on their order in the selection.  

We don't have any GUI tools for doing that so you have to do it using Python. You can find a tutorial on Python and ProDy basics at http://prody.csb.pitt.edu/_static/ipynb/workshop2019/prody_basic.html too

Best wishes
James
