### ISSUE TITLE
Cannot assign extension for beta-factors with `-x` flag

### ISSUE THREAD

**Issue by igordub** [prody/ProDy#1281]
## Descritption
A small bug in assigning extensions. Seems to apply only to a beta-factors file.

## Expected Behavior
``` bash
$ prody anm 1g6n --beta-factors -x ".csv"
$ ls *.csv
1g6n_anm_beta.csv
````

## Current Behavior
``` bash
$ prody anm 1g6n --beta-factors -x ".csv"
$ ls *.csv
$ ls *.txt
1g6n_anm_beta.txt
````

**Comment by jamesmkrieger** [comment]
Thanks for reporting, Igor.

I have found the problem and fixed it at in #1282. You should be able to use the fixed version by updating your ProDy from GitHub soon. 

Best wishes
James

**Comment by jamesmkrieger** [comment]
The checks have passed so I am now merging it and then you can use it. Thanks again

**Comment by igordub** [comment]
Thanks, James!

**Comment by jamesmkrieger** [comment]
You’re welcome
