### ISSUE TITLE
Fetching non-redundant set of the PDB no longer works.

### ISSUE THREAD

**Issue by potterton48** [prody/ProDy#1293]
`fetchPDBClusters` function no longer works, since around October 2020. This is when the PDB changed its website and API.

The error I get when I run `fetchPDBClusters(sqid=70)`:

```
@> WARNING Clusters at 70% sequence identity level could not be downloaded.
@> WARNING PDB clusters could not be downloaded.
```

The issue is irrespective of sequence identity; also tried and failed to download for 30, 40, 50 % sequence identity.

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. I’ll take a look and hopefully fix it soon

**Comment by jamesmkrieger** [comment]
The problem was that the url changed so I've updated it in #1294 and you should be able to use this feature again once I've merged it.

**Comment by potterton48** [comment]
Thanks James - super speedy :smile:

**Comment by jamesmkrieger** [comment]
You're welcome
