### ISSUE TITLE
Problem with the calculation of PCA projection

### ISSUE THREAD

**Issue by MigueLugo** [prody/ProDy#1313]
I'm preparing an Ensemble of configuration, but the problem is that the loading on PC changes in relation to the original loading. See the following code and results

# mode one
coord = calcProjection(cov2_cord[0],cov2_pca[0,1],rmsd = False,norm=False)
print(coord)

[[1.96933283 1.09201138]]

# mode two
B= Ensemble('')
B.setAtoms(sel)
B.setCoords(sel)
B.addCoordset(cov2_cord[0].getCoords())

coord= calcProjection(B,cov2_pca[0,1],rmsd = False,norm = False)
print(coord)

[[-1.01804099  0.12572336]]

and B is indeed a 1 conf. ensemble:

<Ensemble:  (1 conformations; 298 atoms)>

Please, what is going on?  
Thanks

**Comment by jamesmkrieger** [comment]
Is sel used to setCoords for the original ensemble cov2_cord and could this have been changed by iterpose or something? That's the only thing I can think of for now. 

Could you add more details such as which structures you used and what other code you have before this? You can send it to me at jamesmkrieger@gmail.com if you don't want it so public.

Best wishes
James

**Comment by MigueLugo** [comment]
Yes... The setCoords was another. That is why.

Thanks

**Comment by jamesmkrieger** [comment]
You’re welcome. Issue closed
