### ISSUE TITLE
DrugUI plugin

### ISSUE THREAD

**Issue by CodingLemon** [prody/ProDy#1321]
Dear Community,
I have been trying to install DrugGUI plugin following the instructions but it seems that there are still issues to get that on Windows 10.
Any advice on configuration would be appreciated as while plugin shows up in GUI it fails to be initiated. 
I think the issue is Numpy and Python 2.7 installation on Win.

I would appreciate your advice!

CL

The error that prevents GUI loading
![image](https://user-images.githubusercontent.com/48950820/109285407-b6c09a00-7829-11eb-83ec-7b4f19718ed7.png)

**Comment by kaynakb** [comment]
Dear All,

Please see the attached installation guide for both ProDy and DruGUI, which was used in Virtual Hands-on Workshop on Computational Biophysics 2020.

Best

[ProDy_and_DruGUI_Installation.pdf](https://github.com/prody/ProDy/files/6069410/ProDy_and_DruGUI_Installation.pdf)

**Comment by CodingLemon** [comment]
Thank you for your help!
