### ISSUE TITLE
gnm.calcModes returns KeyError: '_anm_calc_modes'

### ISSUE THREAD

**Issue by cgseitz** [prody/ProDy#1322]
Hello,

I am trying to calculate the normal modes of my system. When I use ```gnm.calcModes``` with any value between 1 - 50, it returns ```KeyError: '_anm_calc_modes'```. However, it still allows me to proceed with visualizing the normal modes and the rest of the analysis. Being new to ProDy, I am not experienced enough to know whether the analysis has been affected by that error or not. Here is the full error:
```---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-26-b7fdad459dc2> in <module>
----> 1 gnm.calcModes(n_modes=1, zeros=False, turbo=True)

/net/gpfs-amarolab/cseitz/from_jam/projects/phage/2_simulation_files/prody/ProDy/prody/dynamics/gnm.py in calcModes(self, n_modes, zeros, turbo)
    271         else:
    272             LOGGER.report('{0} mode was calculated in %.2fs.'
--> 273                         .format(self._n_modes), label='_anm_calc_modes')
    274 
    275     def getNormDistFluct(self, coords):

/net/gpfs-amarolab/cseitz/from_jam/projects/phage/2_simulation_files/prody/ProDy/prody/utilities/logger.py in report(self, msg, label)
    322         at *debug* logging level."""
    323 
--> 324         self.debug(msg % (time.time() - self._times[label]))
    325 
    326 LOGGER = PackageLogger('.prody')

KeyError: '_anm_calc_modes'
```

Do you know why this error is happening and how to get around/fix it? Thank you!

**Comment by jamesmkrieger** [comment]
Hi Christian,

It looks like I recently introduced that bug by accident so thank you for reporting it. I will fix it now. Sorry for the inconvenience.

Best wishes
James

**Comment by jamesmkrieger** [comment]
The problem was that the LOGGER was initialised with the label '_gnm_calc_modes' and I had copied in some code that had the label '_anm_calc_modes' for reporting the number of modes depending on whether there were 1 or more without changing it to the right label. I've now changed it back in #1324 so everything should be fine again once I've merged it and that will close this issue too.

**Comment by cgseitz** [comment]
fantastic! thank you james, it works without error now :)

**Comment by jamesmkrieger** [comment]
You're welcome
