### ISSUE TITLE
fetchPDBviaFTP and fetchPDBviaHTTP do not download .cif files

### ISSUE THREAD

**Issue by jonathanking** [prody/ProDy#1323]
There doesn't seem to be a way to download `.cif` files programmatically. `parsePDB` seems to be able to download a structure when only a `.cif` file is available, but the corresponding behavior in `fetchPDBfromFTP` to download the file (as its documentation suggests is possible) does not seem to work.

```python
>>> import prody as pr
>>> pr.parsePDB("4u6f")
<AtomGroup: 4u6f (411881 atoms)>
>>> pr.fetchPDBviaFTP("4u6f")
>>>

```

If my goal is to download a set of PDB entries and be able to access their local paths programmatically, which function should I be using? I assumed `fetchPDBfromFTP` but perhaps I'm mistaken. 

Thank you!

**Comment by jamesmkrieger** [comment]
Hi Jonathan, 

I’ll have to look at the code and get back to you but I think you may need to write your own try/except wrapper around fetchPDBviaFTP to try out the options with different file formats. I believe that’s what I did in parsePDB.

Best wishes 
James

**Comment by jamesmkrieger** [comment]
It’s probably best not to put the try/except into those lower level functions but it may be fine

**Comment by jamesmkrieger** [comment]
Actually, you can't use a try/except approach with fetchPDB because it just returns None rather than failing if it doesn't find anything. I'm making a function now that you can use instead. It uses multiple if tests.

**Comment by jamesmkrieger** [comment]
This is now merged so issue closed. Feel free to reopen it if you have any problems.

Best wishes
James

**Comment by jonathanking** [comment]
James, thank you as always for your quick response and helpful solution! My Monday is starting off on a good note!

**Comment by jamesmkrieger** [comment]
You're very welcome! Hope the rest of your week goes well too!

**Comment by jamesmkrieger** [comment]
I've now improved this function to handle multiple IDs (see #1331) so all you have to do is the following:
```
fnames = fetchPDBs(["3h5v", "4u6f", "2680"])
```
