### ISSUE TITLE
pip install cannot build wheels

### ISSUE THREAD

**Issue by mccool-ryan** [prody/ProDy#1327]
I tried using pip install -U ProDy as instructed here: http://prody.csb.pitt.edu/downloads/
The error is as follows:
 
 ERROR: Failed building wheel for ProDy
Failed to build ProDy
ERROR: Could not build wheels for ProDy which use PEP 517 and cannot be installed directly

I have tried pip installing PEP517, SciPy, NumPy, and Biopython, all to no avail. I am currently running python version 3.7.9 and pip 21.0.1.

**Comment by jamesmkrieger** [comment]
What operating system?

**Comment by SHZ66** [comment]
Please try pip install -U prody —no-binary

**Comment by jamesmkrieger** [comment]
Any luck with this?

**Comment by ConradJohnston** [comment]
@jamesmkrieger , I suspect this was on OSX Catalina and relates to XCode.

The suggestion from @SHZ66 didn't work in my case, but what did was:
`ARCHFLAGS="-arch x86_64" pip install prody`

**Comment by jamesmkrieger** [comment]
Thanks for the suggestion

**Comment by jamesmkrieger** [comment]
Is this still a problem with the latest ProDy version, 2.1.2?

**Comment by LysSanzMoreta** [comment]
@jamesmkrieger  I am still having the same issue, with **2.0.0 and higher**  I am trying to upgrade my environment to python 3.8

```
Python 3.8.13
Pip version 21.2.2
```
```
  ERROR: Failed building wheel for prody
Failed to build prody
ERROR: Could not build wheels for prody which use PEP 517 and cannot be installed directly
```
I tried to run `python -m pip install --no-use-pep517 prody` without luck

#####################################################################
Different error when upgrading pip
```
Python 3.8.13
Pip version 22.1.2
```
```
 × Building wheel for prody (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [289 lines of output]
...
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ProDy
Failed to build ProDy
ERROR: Could not build wheels for ProDy, which is required to install pyproject.toml-based projects
```

##########################################################################

I had ProDy working in Python 3.7.3 though. 

```
Python 3.7.3 
Pip version  21.2.2 
```

My gcc compiler is : 

```
gcc (crosstool-NG 1.23.0.449-a04d0) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
```

Let me know if you require more information. The summary is that I have tried several combinations without luck. 

Thanks in advance!

**Comment by jamesmkrieger** [comment]
I don't really know what to do to help.

What I could suggest is to try installing from conda or from source. 

What operating system are you using?

**Comment by LysSanzMoreta** [comment]
@jamesmkrieger Thanks for your reply. I am using Ubuntu 20.04.4 LTS. I will try conda as soon as I can.

**Comment by jamesmkrieger** [comment]
Oh ok. It really should work then

**Comment by jamesmkrieger** [comment]
Great to know. Thanks

I have managed to use the pip installer on Ubuntu 20.04 I think but maybe it's quite sensitive somehow. We'll probably have to figure it out at some point.

Sorry for the inconvenience

**Comment by jamesmkrieger** [comment]
Is this working now with 2.3.0? I know 2.3.1 has problems so I'm not asking about that one

**Comment by LysSanzMoreta** [comment]
@jamesmkrieger `pip install prody==2.3.0` worked on Ubuntu 20.04.4 LTS with python 3.18.13

**Comment by jamesmkrieger** [comment]
ok. Good. I think I'll make 2.3.2 over the next few days and hopefully that will work too

**Comment by jamesmkrieger** [comment]
please try again with prody 2.4.0 that I just released

**Comment by LysSanzMoreta** [comment]
Worked in `python 3.8.13`! However I was feeling adventurous and I tested it on  `python 3.9.12 `and it could not install the wheels.

**Comment by jamesmkrieger** [comment]
oh, that's a shame. I'll try and figure out why. Thanks

**Comment by SciKidSirish** [comment]
Hello, I am trying to install this using pip, and I get a similar error, ending with:

ERROR: Could not build wheels for prody, which is required to install pyproject.toml-based projects

I am using python 3.11.2. Is the version I'm using the issue? I have pip 23.0.1. I am using Windows 11.

**Comment by SciKidSirish** [comment]
Here's some background:
ProDy is a dependency for a protein-protein docking software (lightdock) I'm trying to install.

**Comment by LysSanzMoreta** [comment]
@SciKidSirish My recommendation is to downgrade python to 3.8 or so, most bioinformatic tools are still behind python updates

**Comment by jamesmkrieger** [comment]
> @SciKidSirish My recommendation is to downgrade python to 3.8 or so, most bioinformatic tools are still behind python updates

Thanks. Yes, 3.8 or 3.9 should be good. I think 3.10 should be too, but there may be some problems there

**Comment by jamesmkrieger** [comment]
> Hello, I am trying to install this using pip, and I get a similar error, ending with:
> 
> ERROR: Could not build wheels for prody, which is required to install pyproject.toml-based projects
> 
> I am using python 3.11.2. Is the version I'm using the issue? I have pip 23.0.1. I am using Windows 11.

Please don't comment in multiple places. This issue was a Mac and Linux one

**Comment by jamesmkrieger** [comment]
Ignoring Python 3.11, are people now managing to install ProDy ok?
