### ISSUE TITLE
NMD Parser--Required categories?

### ISSUE THREAD

**Issue by emleddin** [prody/ProDy#1328]
Hello,

Versions:
- Python: 3.8
- ProDy: 1.11

I am using an NMD file generated with cpptraj, which lists the attributes for `chainids` and `bfactors`,  but those attributes contain no information for each residue (the rest of the line is blank).

When trying to read an NMD file generated with cpptraj using:
```python
import prody as prd

filename = "first_100_modes.nmd"

NMA_data,Atom_Group = prd.parseNMD(filename)
```

I get this error:
```
@> WARNING Blank data associated with label 'chainids'.
@> WARNING Blank data associated with label 'bfactors'.
@> WARNING The data label 'segnames' was not found in 'first_100_modes.nmd'.
@> WARNING Data with label 'chainids' in 'first_100_modes.nmd' at line 6 is corrupt, expected 1533 values, parsed 0.
@> WARNING Data with label 'bfactors' in 'first_100_modes.nmd' at line 7 is corrupt, expected 1533 values, parsed 0.
Traceback (most recent call last):
  File "get-nma.py", line 65, in <module>
    NMA_plots(filename,outfile)
  File "get-nma.py", line 43, in NMA_plots
    NMA_data,Atom_Group = prd.parseNMD(filename)
  File "~/anaconda3/lib/python3.8/site-packages/prody/dynamics/nmdfile.py", line 287, in parseNMD
    if len(data) == n_atoms:
TypeError: object of type 'NoneType' has no len()
```
I was able to circumvent the issue by setting all the `chainids` and `segnames` to `A`, and the `bfactors` to `0`. 

I've been using this command in scripts for years, with NMD files written with blank `chainids`, `bfactors`, and missing `segnames`. It used to just skip those sections after printing the "Blank data" warning. The loop that gives the error got updated a few months ago (https://github.com/prody/ProDy/commit/14c257d08abe9c8e83e2a49f2994450dcfde99ed). I don't think this is related to cpptraj as a) my version hasn't changed and b) the code for the NMWiz component was [last updated in 2016](https://github.com/Amber-MD/cpptraj/blob/9e5c2e36a597003359188287c56bfed2c3683d50/src/Analysis_Matrix.cpp#L205).

I tried a few other tests, like removing the `chainids` and `bfactors` lines entirely, but that also threw an error.
```
@> WARNING The data label 'chainids' was not found in 'test-nocbs.nmd'.
@> WARNING The data label 'bfactors' was not found in 'test-nocbs.nmd'.
@> WARNING The data label 'segnames' was not found in 'test-nocbs.nmd'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/anaconda3/lib/python3.8/site-packages/prody/dynamics/nmdfile.py", line 287, in parseNMD
    if len(data) == n_atoms:
TypeError: object of type 'NoneType' has no len()
```

Similarly, it errors out without `segnames` when there are defined `chainids` and `bfactors`:
```
@> WARNING The data label 'segnames' was not found in 'test-noseg.nmd'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/anaconda3/lib/python3.8/site-packages/prody/dynamics/nmdfile.py", line 287, in parseNMD
    if len(data) == n_atoms:
TypeError: object of type 'NoneType' has no len()
```

Are all of the categories now hard-required?

**Comment by jamesmkrieger** [comment]
No, they shouldn’t be hard required. I must have made a mistake in the fix I made. Could you send me a file to test please to help work out the solution?

**Comment by jamesmkrieger** [comment]
My email address is jamesmkrieger@gmail.com

**Comment by jamesmkrieger** [comment]
Actually, I think I can see the problem from the error report anyway.

**Comment by jamesmkrieger** [comment]
It comes from the deletion of the block that made the loop continue if data is None, which was right before what's now line 287. I'm also adding back the entries in NMD_LABEL_MAP, which I probably shouldn't have deleted. Besides that, the changes are addition and fixing of warnings so should be good.

**Comment by jamesmkrieger** [comment]
I have made the fix in pull request #1330 and am about to merge it. If you then install ProDy from github, it should fix the problem. If it doesn't, please feel free to reopen this issue or just comment on it again.

**Comment by emleddin** [comment]
I don't have reopen permission, but I do have a test case. Thanks so much for working on this!

I used the [DPDP cpptraj test case](https://github.com/Amber-MD/cpptraj/blob/master/test/DPDP.nc) to make an example NMD file this time.

### Example NMD: 
[DPDP_100.nmd.txt](https://github.com/prody/ProDy/files/6070420/DPDP_100.nmd.txt)
It only has the `.txt` extension to get around GitHub's file rules. 

### Test:
```python
import prody as prd

filename = "DPDP_100.nmd"

NMA_data,Atom_Group = prd.parseNMD(filename)
```

### Newer edition result:
Python version: 3.8.5
ProDy version: 2.0

```
@> WARNING Blank data associated with label 'chainids'.
@> WARNING Blank data associated with label 'bfactors'.
@> WARNING The data label 'resnums' was not found in 'DPDP_100.nmd'.
@> WARNING The data label 'segnames' was not found in 'DPDP_100.nmd'.
@> WARNING The data label 'segments' was not found in 'DPDP_100.nmd'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emmett/anaconda3/lib/python3.8/site-packages/prody/dynamics/nmdfile.py", line 291, in parseNMD
    if len(data) == n_atoms:
TypeError: object of type 'NoneType' has no len()
```

### Older edition result:
Python version: 3.6.7
ProDy version: 1.10.11

```
NMA_data,Atom_Group = prd.parseNMD(filename)
@> WARNING Data label 'resids' is found more than once in 'DPDP_100.nmd'.
@> WARNING Data label 'resids' is found more than once in 'DPDP_100.nmd'.
```
`NMA_data` and `Atom_Group` are defined.

**Comment by jamesmkrieger** [comment]
Ok, I've reopened it. I tested my fix with your file and it didn't work but I've just made a new one that should. Thanks again

**Comment by jamesmkrieger** [comment]
The output is now as follows:
```
In [1]: from prody import *

In [2]: nma, atoms = parseNMD('DPDP_100.nmd')
@> WARNING Blank data associated with label 'chainids'.
@> WARNING Blank data associated with label 'bfactors'.
@> WARNING The data label 'resnums' was not found in 'DPDP_100.nmd'.
@> WARNING The data label 'segnames' was not found in 'DPDP_100.nmd'.
@> WARNING The data label 'segments' was not found in 'DPDP_100.nmd'.
@> WARNING Data with label 'chainids' in 'DPDP_100.nmd' at line 6 is corrupt, expected 332 values, parsed 0.
@> WARNING Data with label 'bfactors' in 'DPDP_100.nmd' at line 7 is corrupt, expected 332 values, parsed 0.

In [3]: nma
Out[3]: <NMA: default_name (100 modes; 332 atoms)>

In [4]: atoms.getChids()

In [5]: atoms.getBetas()
```

We get warnings but it still returns nma and atoms.

**Comment by jamesmkrieger** [comment]
They are actually redundant warning so I think I'll clean that up too.

**Comment by jamesmkrieger** [comment]
Actually I think I'll leave it.

**Comment by jamesmkrieger** [comment]
The warnings you had in ProDy 1.10.11 were wrong. It accidentally reported about resids twice for you and it was another field that got reported twice for me (I think it chainids) so that's why I made the changes in the first place.
