### ISSUE TITLE
Error in Blast search and blast_record.fetch() command

### ISSUE THREAD

**Issue by mnaqvi-code** [prody/ProDy#1333]
I am running the following code as in the tutorial for Homologous Proteins: 
Jupyter QtConsole 4.7.7
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

from prody import *

from pylab import *

ion()

name = 'cyt_c'

ref_pdb = '1hrc'

ref_prot = parsePDB(ref_pdb)
@> PDB file is found in working directory (1hrc.pdb.gz).
@> 993 atoms and 1 coordinate set(s) were parsed in 0.08s.

ref_hv = ref_prot.getHierView()['A']

sequence = ref_hv.getSequence()

exclude = ['3nbt', '3nbs']

seqid = 44

blast_record = blastPDB(sequence)
@> Blast searching NCBI PDB database for "GDVEK..."
@> WARNING Blast search time out.                       

while not blast_record.isSuccess:
   ....:    blast_record.fetch()
   ....:
@> Blast searching NCBI PDB database for "GDVEK..."
@> WARNING Blast search time out.                       
@> Blast searching NCBI PDB database for "GDVEK..."
@> WARNING Blast search time out.                       
@> Blast searching NCBI PDB database for "GDVEK..."
@> WARNING Blast search time out.                       
@> Blast searching NCBI PDB database for "GDVEK..."
@> WARNING Blast search time out.                       
@> Blast searching NCBI PDB database for "GDVEK..."
@> WARNING Blast search time out.                       
@> Blast searching NCBI PDB database for "GDVEK..."
---------------------------------------------------------------------------
timeout                                   Traceback (most recent call last)
<ipython-input-12-fb2635de0290> in <module>
      1 while not blast_record.isSuccess:
----> 2    blast_record.fetch()
      3 

~\anaconda3\lib\site-packages\prody\proteins\blastpdb.py in fetch(self, xml, sequence, **kwargs)
    183             LOGGER.info('Blast searching NCBI PDB database for "{0}..."'
    184                         .format(sequence[:5]))
--> 185             handle = openURL(url, data=data, headers=headers)
    186 
    187             html = handle.read()

~\anaconda3\lib\site-packages\prody\utilities\pathtools.py in openURL(url, timeout, **kwargs)
    406 
    407     try:
--> 408         return urlopen(request, timeout=int(timeout))
    409     except URLError:
    410         raise IOError('{0} could not be opened for reading, invalid URL or '

~\anaconda3\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

~\anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    523 
    524         sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

~\anaconda3\lib\urllib\request.py in _open(self, req, data)
    540 
    541         protocol = req.type
--> 542         result = self._call_chain(self.handle_open, protocol, protocol +
    543                                   '_open', req)
    544         if result:

~\anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~\anaconda3\lib\urllib\request.py in https_open(self, req)
   1391 
   1392         def https_open(self, req):
-> 1393             return self.do_open(http.client.HTTPSConnection, req,
   1394                 context=self._context, check_hostname=self._check_hostname)
   1395 

~\anaconda3\lib\urllib\request.py in do_open(self, http_class, req, **http_conn_args)
   1352             except OSError as err: # timeout error
   1353                 raise URLError(err)
-> 1354             r = h.getresponse()
   1355         except:
   1356             h.close()

~\anaconda3\lib\http\client.py in getresponse(self)
   1345         try:
   1346             try:
-> 1347                 response.begin()
   1348             except ConnectionError:
   1349                 self.close()

~\anaconda3\lib\http\client.py in begin(self)
    305         # read until we get a non-100 response
    306         while True:
--> 307             version, status, reason = self._read_status()
    308             if status != CONTINUE:
    309                 break

~\anaconda3\lib\http\client.py in _read_status(self)
    266 
    267     def _read_status(self):
--> 268         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    269         if len(line) > _MAXLINE:
    270             raise LineTooLong("status line")

~\anaconda3\lib\socket.py in readinto(self, b)
    667         while True:
    668             try:
--> 669                 return self._sock.recv_into(b)
    670             except timeout:
    671                 self._timeout_occurred = True

~\anaconda3\lib\ssl.py in recv_into(self, buffer, nbytes, flags)
   1239                   "non-zero flags not allowed in calls to recv_into() on %s" %
   1240                   self.__class__)
-> 1241             return self.read(nbytes, buffer)
   1242         else:
   1243             return super().recv_into(buffer, nbytes, flags)

~\anaconda3\lib\ssl.py in read(self, len, buffer)
   1097         try:
   1098             if buffer is not None:
-> 1099                 return self._sslobj.read(len, buffer)
   1100             else:
   1101                 return self._sslobj.read(len)

timeout: The read operation timed out

**Comment by jamesmkrieger** [comment]
Hi, this doesn't seem to be a ProDy problem. It behaved as expected many times before this error came up.

Maybe your internet went down or something? Can you try again?

**Comment by jamesmkrieger** [comment]
I'm not sure whether this is really a ProDy problem. Everything behaves fine except that there is a timeout during the fetch stage that goes a long way down into the dependencies. It may be that you had an internet connection problem or something. 

This function seems to be working on my machine.

**Comment by jamesmkrieger** [comment]
Ok, I did have a similar error, but it worked another time. I think it's just temperamental and you should try again.

**Comment by mnaqvi-code** [comment]
thanks for informing. I tried multiple times and now it worked.

Best Regards

Mohsin

**Comment by mnaqvi-code** [comment]
thanks for informing. I tried multiple times and now it worked.

**Comment by jamesmkrieger** [comment]
You're welcome. I'm glad to hear that.

I'll close the issue now.

Best wishes
James
