### ISSUE TITLE
parsepdb command : TypeError: stat: path should be string, bytes, os.PathLike or integer, not dict

### ISSUE THREAD

**Issue by mnaqvi-code** [prody/ProDy#1335]
Hi
I am following the steps in the Heterogeneous X ray structure tutotrial and I am getting this error when I am using parsePDB command in In [8]: of the tutorial. :

Jupyter QtConsole 4.7.7
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

from prody import *

from pylab import *

ion()

pdbids = ['1P38', '1A9U', '1BL6', '1BL7', '1BMK', '1DI9', '1IAN', '1KV1', '1KV2',
   ...:           '1LEW', '1LEZ', '1M7Q', '1OUK', '1OUY', '1OVE', '1OZ1', '1P38',
   ...:           '1R39', '1R3C', '1W7H', '1W82', '1W83', '1W84', '1WBN', '1WBO',
   ...:           '1WBS', '1WBT', '1WBV', '1WBW', '1WFC', '1YQJ', '1YW2', '1YWR',
   ...:           '1ZYJ', '1ZZ2', '1ZZL', '2BAJ', '2BAK', '2BAL', '2BAQ', '2EWA',
   ...:           '2FSL', '2FSM', '2FSO', '2FST', '2GFS', '2GHL', '2GHM', '2GTM',
   ...:           '2GTN', '2I0H', '2NPQ', '2OKR', '2OZA', '3HVC', '3MH0', '3MH3',
   ...:           '3MH2', '2PUU', '3MGY', '3MH1', '2QD9', '2RG5', '2RG6', '2ZAZ',
   ...:           '2ZB0', '2ZB1', '3BV2', '3BV3', '3BX5', '3C5U', '3L8X', '3CTQ',
   ...:           '3D7Z', '3D83', '2ONL']

p38_sequence = '''GLVPRGSHMSQERPTFYRQELNKTIWEVPERYQNLSPVGSGAYGSVCAAFDTKTGHRV
  ...: AVKKLSRPFQSIIHAKRTYRELRLLKHMKHENVIGLLDVFTPARSLEEFNDVYLVTHLMGADLNNIVKCQKLTDDH
  ...: VQFLIYQILRGLKYIHSADIIHRDLKPSNLAVNEDCELKILDFGLARHTDDEMTGYVATRWYRAPEIMLNWMHYNQ
  ...: TVDIWSVGCIMAELLTGRTLFPGTDHIDQLKLILRLVGTPGAELLKKISSESARNYIQSLAQMPKMNFANVFIGAN
  ...: PLAVDLLEKMLVLDSDKRITAAQALAHAYFAQYHDPDDEPVADPYDQSFESRDLLIDEWKSLTYDEVISFVPPPLD
  ...: QEEMES'''

blast_record = blastPDB(p38_sequence)
@> Blast searching NCBI PDB database for "GLVPR..."
@> Blast search completed in 30.7s.                    

pdbids = blast_record.getHits(90, 70)

structures = parsePDB(pdbids, subset='ca', compressed=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-e8f65767af75> in <module>
----> 1 structures = parsePDB(pdbids, subset='ca', compressed=False)

~\anaconda3\lib\site-packages\prody\proteins\pdbfile.py in parsePDB(*pdb, **kwargs)
    121 
    122     if n_pdb == 1:
--> 123         return _parsePDB(pdb[0], **kwargs)
    124     else:
    125         results = []

~\anaconda3\lib\site-packages\prody\proteins\pdbfile.py in _parsePDB(pdb, **kwargs)
    202     title = kwargs.get('title', None)
    203     chain = ''
--> 204     if not os.path.isfile(pdb):
    205         pdb, chain = _getPDBid(pdb)
    206         if title is None:

~\anaconda3\lib\genericpath.py in isfile(path)
     28     """Test whether a path is a regular file"""
     29     try:
---> 30         st = os.stat(path)
     31     except (OSError, ValueError):
     32         return False

TypeError: stat: path should be string, bytes, os.PathLike or integer, not dict

**Comment by mnaqvi-code** [comment]
I now tried this : structures = parsePDB([pdb for pdb in pdbids], subset='ca', compressed=False) and it worked.

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. I’ll look into what gave the error and update ProDy or the tutorial accordingly

**Comment by jamesmkrieger** [comment]
It may well be that your fix is the best one.

**Comment by jamesmkrieger** [comment]
I've also made a fix that would make the original code work.

**Comment by jamesmkrieger** [comment]
I’m merging my fix so you should be able to update ProDy from GitHub and have it work
