### ISSUE TITLE
PCA project Plots

### ISSUE THREAD

**Issue by metehance** [prody/ProDy#1342]
Hi. 

I am sharing a graphic with you in the attachment. I got this with Prody. I need the file with this graphic drawn. Where can I get this file? That's why I need this file, I want to plot the top 5, 7 and 20 modes from my trajectory file. So how can I extract these files up to the number of modes I want?

Thank you so much ! 

[3mode.pdf](https://github.com/prody/ProDy/files/6111117/3mode.pdf)

**Comment by jamesmkrieger** [comment]
Hi,

I don't understand what you're asking. Did you get this image from someone else and you want to do something similar? You can do that by following the tutorial at http://prody.csb.pitt.edu/tutorials/trajectory_analysis/eda.html (I don't know why the figure isn't showing properly). 

As for the number of modes point, I don't think this makes much sense. Each axis of one of these plots is normally one mode e.g. principal modes 1, 2 and 3 from a trajectory. You could add together multiple modes (see http://prody.csb.pitt.edu/tutorials/enm_analysis/normalmodes.html#linear-combination) and provide the resulting vectors to showCrossProjection, but I don't know if that would make sense. 

What you could do instead is manually ask for different combinations such as modes 1, 2 and 3 in the first plot and modes 4, 5 and 6 in the second plot. Alternatively, it may be better to keep some shared axes. See Figure 1 of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3739829/ and the related text for more information.

Best wishes
James

**Comment by metehance** [comment]
Thank your answer. 

The question I wanted to ask was that we want to plot the graphics ourselves using the gnuplot software.  For this, what we need is the calculations ProDy has made from the trejectory.  We need these calculations.  How can we access these files?

Thank toy so much.

**Comment by jamesmkrieger** [comment]
Oh, I see. There are no files. You could use calcProjection instead of showProjection and write the resulting array to some file of your choosing. showProjection acts as a wrapper for calcProjection and matplotlib plotting functions.

**Comment by metehance** [comment]
Thank you. 

It is so much helpful for me. May I ask you sometime else. How can I use calcProjection function. 

Thank you for your help.

**Comment by jamesmkrieger** [comment]
Just provide it with the same input as showProjection e.g.

instead of ```showProjection(mdm2ca_sim1, eda[:3])```, use ```proj = calcProjection(mdm2ca_sim1, eda[:3])```

**Comment by jamesmkrieger** [comment]
You can also change the number of modes to get results for all modes from the eda object or a different subset.

**Comment by metehance** [comment]
Oh, really thank you so much for your help. 

I wish healthy day.

**Comment by jamesmkrieger** [comment]
You're welcome. Same to you

**Comment by metehance** [comment]
Dear James,

Hi again. 

I couldn’t write calculated projection values to a txt file. I am giving you a python file. How can I do that in this python file ? 
I would be glad if you could help. Here I want to print the projection calculation of the first 3 modes to a file. In this way, I will draw a 3D plot in gnuplot.

**Comment by jamesmkrieger** [comment]
There’s a writeArray function in ProDy. I think that’s what it’s called. Numpy has one too, which I think is called savetext.

**Comment by jamesmkrieger** [comment]
I didn’t receive any python files

**Comment by metehance** [comment]
I have attached a python file in the mail. Has it reached you?



On 11 Mar 2021, at 22:29, James Krieger ***@***.******@***.***>> wrote:



I didn’t receive any python files

**Comment by jamesmkrieger** [comment]
No. Please send directly to jamesmkrieger@gmail.com

**Comment by jamesmkrieger** [comment]
Thanks. I got it.

After `proj = calcProjection(dcd, pca[:3])`, you want to use a command line `writeArray('proj_3_modes.txt', proj)`. See http://prody.csb.pitt.edu/manual/reference/dynamics/functions.html?highlight=writearray#prody.dynamics.functions.writeArray for more information.

**Comment by metehance** [comment]
Dear James,

Thanks a lot for your help. It worked just like what I want.

**Comment by kaynakb** [comment]
Dear metehance,

Let's assume that you have an ensemble of trajectories and stored in a variable "traj". I assume that their atoms are properly set and the conformers are aligned. You can compute a set of principal components for this ensemble by

import prody as pr   # I am using the alias pr here, you do not need to do that.
pca = pr.PCA()
pca.buildCovariance()
pca.calcModes()   # You can define the number of modes that you would like to use.

Now, we can get the projection by

proj =  pr.calcProjection(ens, pca[:3])

Above, you can also specify which principal components you would like to use via changing the indices in "pca". As we have now the projection, you can write them as a "dat" or "txt" file to open in gnuplot just by typing

np.savetxt('projecton.txt', proj)

After launching gnuplot, the only thing you are going to do is to type

splot 'projection.txt'

Of course, you can customize your plot by the options in gnuplot. Please check the functions, the corresponding ProDy documentation and the links that James provided.

Best

**Comment by metehance** [comment]
Dear Burak,

Thank you so much for your help and attention. Your statements contain very valuable information for me. Thanks to James and you, I found the answer to my question in a very descriptive way.

Thank you, wish you healthy days.
