### ISSUE TITLE
can adaptive ANM use exANM modes?

### ISSUE THREAD

**Issue by kuraisle** [prody/ProDy#1347]
Using exANM on structures of the transporter I'm interested in, I get some interesting results that suggest it's picking up something physiologically relevant. I had hoped that adaptive ANM between the apo and substrate-bound structures might give an idea of the transition between states. It doesn't really work though; adaptive ANM makes small changes at either end, then there's a jump between states and they never really converge. I was wondering if there was a way to use exANM modes instead to see if this helps.

Thanks for a very useful project!

**Comment by jamesmkrieger** [comment]
Yes, exANM could be good to incorporate into adaptive ANM. But please feel free to give it a try and let us know what happens. I think it should work fine but can't say for sure.

You should be able to do this by giving adaptive ANM the keyword argument `model=exANM`.

**Comment by kuraisle** [comment]
Thanks for your help. Unfortunately, if you supply a model argument to calcAdaptiveANM, it throws the error "prody.dynamics.functions.calcENM() got multiple values for keyword argument 'model'". Even if this weren't a problem, I didn't think calcENM could run membrane ANM as these are done by creating imANM or exANM objects

**Comment by jamesmkrieger** [comment]
Thanks for reporting that. I should be able to fix the multiple model arguments problem quite easily.

calcENM should manage to create exANM objects. Please try just giving model=‘exANM’ to calcENM and let me know if it can’t.

many thanks

**Comment by kuraisle** [comment]
No dice, I'm afraid. I get told "model should be either ANM or GNM instead of exanm"

**Comment by jamesmkrieger** [comment]
That's a shame. Can you download the latest ProDy from GitHub? I recently did try and incorporate that (see https://github.com/prody/ProDy/pull/1302 and https://github.com/prody/ProDy/pull/1306).

**Comment by jamesmkrieger** [comment]
Instructions how to do that are available at http://prody.csb.pitt.edu/manual/devel/develop.html

**Comment by kuraisle** [comment]
That's brilliant! Sorry it took a little while to test, I didn't have a C++ compiler installed so had to sort that out. It works now! My structures don't quite converge still, but perhaps there's some tinkering I can do. Thanks so much for your help!

**Comment by jamesmkrieger** [comment]
You’re welcome. You could try using more modes or playing with some of the other parameters.
