### ISSUE TITLE
NameError: name 'parsePDB' is not defined

### ISSUE THREAD

**Issue by mordurx** [prody/ProDy#1348]
I install prody in various ways both as in windows and in linux, from source and pip, but
when running examples I have the error
NameError: name 'parsePDB' is not defined

**Comment by jamesmkrieger** [comment]
You need to open Python before you can run commands such as parsePDB. Are you sure you did that?

**Comment by jamesmkrieger** [comment]
You can also do this with an interactive python (ipython) terminal or a jupyter notebook.

**Comment by mordurx** [comment]
with ipython and jupyter is fine
my problem is with vscode, don't fine path.
