### ISSUE TITLE
Problem determining RMSD to mean (NMR bundle RMSD)

### ISSUE THREAD

**Issue by paulschanda** [prody/ProDy#1351]
I try to determine the RMSD over an ensemble of NMR structures.
I use the code at the bottom of this message, and get the error message shown below, related to ens.iterpose. Any hints ?

ERROR:
In [26]: run rmsd_ens2mean.py 1ud7.pdb 'resnum 23:60 ca'
resnum 23:60 ca
@> 1230 atoms and 20 coordinate set(s) were parsed in 0.09s.
@> Starting iterative superposition:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/Users/paul/Desktop/test_rmsd/rmsd_ens2mean.py in <module>()
     21 ens.setCoords(nmr)
     22 ens.setAtoms(nmr.select(sel))
---> 23 ens.iterpose()
     24 
     25 

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ProDy-2.0-py2.7-macosx-10.14-x86_64.egg/prody/ensemble/pdbensemble.pyc in iterpose(self, rmsd)
    200     def iterpose(self, rmsd=0.0001):
    201         confs = copy(self._confs)
--> 202         Ensemble.iterpose(self, rmsd)
    203         self._confs = confs
    204         LOGGER.info('Final superposition to calculate transformations.')

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ProDy-2.0-py2.7-macosx-10.14-x86_64.egg/prody/ensemble/ensemble.pyc in iterpose(self, rmsd, quiet)
    691 
    692         while rmsdif > rmsd:
--> 693             self._superpose(quiet=quiet)
    694             if weights is None:
    695                 newxyz = self._confs.sum(0) / length

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ProDy-2.0-py2.7-macosx-10.14-x86_64.egg/prody/ensemble/pdbensemble.pyc in _superpose(self, **kwargs)
    185             confs_selected = self._confs
    186         else:
--> 187             weights = self._weights[:, indices]
    188             coords = self._coords[indices]
    189             confs = self._confs

IndexError: index 350 is out of bounds for axis 1 with size 0

CODE:
#!/usr/bin/python

from prody import *
import numpy
import sys

if len(sys.argv)>2:
    nmrFF=sys.argv[1]
    sel=sys.argv[2]
else:
    print "use: %s structures.pdb 'resnum 5:29 43:73 100:124 ca'"
    sys.exit()

print sel

ens=PDBEnsemble()
for nmrF in nmrFF.split(':'):
  nmr=parsePDB(nmrF)
  ens.addCoordset(nmr)

ens.setCoords(nmr)
ens.setAtoms(nmr.select(sel))
ens.iterpose()

rmsd=ens.getRMSDs()
print rmsd
print 'mean: %8.2f' % rmsd.mean()
itemindex_min = numpy.where(rmsd==rmsd.min())
itemindex_max = numpy.where(rmsd==rmsd.max())
print 'min:  %8.2f for # %d' % (rmsd.min(),itemindex_min[0][0]+1)
print 'max:  %8.2f for # %d' % (rmsd.max(),itemindex_max[0][0]+1)
print 'stddev:  %8.2f: ' % (numpy.std(rmsd))

**Comment by jamesmkrieger** [comment]
The problem was that addCoordset couldn't handle the case where the ensemble was empty at the start. It was setting the weights using n_atoms = 0 from the ensemble rather than n_nodes from the atomgroup. I have now fixed that in #1352 so you can download ProDy from github again when I've merged it, which I will do once it passes the checks.

Best wishes
James

**Comment by paulschanda** [comment]
Thanks for the feedback.
I downloaded it today from https://pypi.org/project/ProDy/#files ***@***.***/0?redirect=https%3A%2F%2Fpypi.org%2Fproject%2FProDy%2F%23files&recipient=cmVwbHkrQUlJM0pXSE5INVBNQVpDSkIyQ0NNUk42U1Y0SkRFVkJOSEhESFhIVkFJQHJlcGx5LmdpdGh1Yi5jb20%3D)
and I do have this issue, after this fresh installation.
So I assume that it was fixed on GitHub, but not on pypi, or I did something wrong.

So I just downloaded it from GitHub and installed it again. Unfortunately, the error persists.
Again, I could have made mistakes -- do I need to uninstall the ProDy that I had?

**Comment by paulschanda** [comment]
I am sorry, I have not properly read your message, sorry.
I'll wait, and download ProDy again in a while, once you have done the checks.
Thanks!
Paul

**Comment by jamesmkrieger** [comment]
You’re welcome. You should also be able to build the ensemble another way, which I can check tomorrow. The pull request checks are taking longer than normal

**Comment by paulschanda** [comment]
If there is another way to measure the "bundle RMSD", i.e. the RMSD over a bundle of (NMR) structures to the mean structure, I am happy to use it. I just don't know how, and the script rmsd_ens2mean.py seemed to do the job I wanted.
cheers.

**Comment by jamesmkrieger** [comment]
1. I think the best way would be to use buildPDBEnsemble with degeneracy=False e.g. 

ens = buildPDBEnsemble([nmrF for nmrF in nmrFF], degeneracy=False)

or even

ens = buildPDBEnsemble(nmrF, degeneracy=False)

if you don’t need multiple files. 

2. You could also try your script as is except for using Ensemble instead of PDBEnsemble.

3. Alternatively, you could use calcRMSD on the AtomGroup without building an ensemble at all.

Nevertheless, if you’re patient what you have should work. It just needs to be checked that my bug fix doesn’t break something else.

best wishes 
James

**Comment by jamesmkrieger** [comment]
Apologies for the delay. I fixed a problem with the checks not triggering and they are running now. I'll let you know when they're done.

**Comment by jamesmkrieger** [comment]
Ok, it passed the checks and I am merging it so you should be able to get the revised version from github any moment now.

**Comment by paulschanda** [comment]
Dear James,
Thanks!
Is this issue now solved both in installation with pip and GitHub? Or only on GitHub?
cheers,
paul

**Comment by jamesmkrieger** [comment]
Only on GitHub. We make releases to PyPI/pip about twice a year when we’ve made quite big changes
