### ISSUE TITLE
SignDy: obtaining an MSA from an ensemble object, & writing modes to file

### ISSUE THREAD

**Issue by gtzotzos** [prody/ProDy#1355]
I'd like to inspect the multiple sequence alignment obtained from:
**ens = buildPDBEnsemble(pdbs, mapping='ce', seqid=0, overlap=0, title='OBP', subset='ca')**

The closest I got, was by generating a pdb file of the ensemble:  **writePDB('ens.pdb', ens)**
Is there an alternative way?

The second question is how does one generate and write to file a 2D array from an object such as **gnms[:, 0]**

I'd appreciate any suggestions regarding the above

**Comment by jamesmkrieger** [comment]
Yes, you can extract the msa directly as follows and write it to file too:

msa = ens.getMSA()
writeMSA('ens.fa', msa)

For the second question, you can use writeArray.

Please let me know if you need any further clarification.

Best wishes
James

**Comment by gtzotzos** [comment]
Many thanks James. Much appreciated.

The writeMSA function generates the following error:

In [15]: ens
Out[15]: <PDBEnsemble: OBP (17 conformations; 125 atoms)>

writeMSA('ens.fa', msa)

NameError: name 'msa' is not defined

I also have problems with the writeArray function.

I have generated a gnms object as shown below

In [12]: gnms[:, 0]
Out[12]: <ModeEnsemble: 17 modesets (1 mode, 125 atoms)>

When I try 

writeArray('mode1', gnms[:, 0])

I get the following error.

TypeError: array must be a Numpy ndarray, not <class 'prody.dynamics.signature.ModeEnsemble'>

Many thanks in advance for any suggestions

George

**Comment by jamesmkrieger** [comment]
For the second one, you need to use getArray as follows:

writeArray('mode1', gnms[:, 0].getArray())

For the first problem, I'm not sure what's wrong. I tested it myself and it worked - with one change from what I said. I needed to have fasta instead of fa as the file extension.

```
In [1]: from prody import *

In [2]: ags = parsePDB('3hsyA', '3h5vA')
@> 2 PDBs were parsed in 4.42s.

In [3]: ags
Out[3]: [<AtomGroup: 3hsyA (3101 atoms)>, <AtomGroup: 3h5vA (3225 atoms)>]

In [4]: ens = buildPDBEnsemble(ags, mapping='ce', seqid=0, overlap=0, title='OBP', subset='ca')
@> Starting iterative superposition:
@> Step #1: RMSD difference = 6.6210e-01
@> Step #2: RMSD difference = 1.0832e-14
@> Iterative superposition completed in 0.02s.
@> Final superposition to calculate transformations.
@> Superposition completed in 0.00 seconds.
@> Ensemble (2 conformations) were built in 0.15s.

In [5]: ens
Out[5]: <PDBEnsemble: OBP (2 conformations; 354 atoms)>

In [6]: msa = ens.getMSA()

In [7]: msa
Out[7]: <MSA: OBP (2 sequences, 354 residues)>

In [10]: writeMSA('ens.fasta', msa)
Out[10]: 'ens.fasta'
```

Best wishes
James

**Comment by gtzotzos** [comment]
James, I’m grateful. Both suggestions work. 

Best regards

George

**Comment by jamesmkrieger** [comment]
You’re very welcome, George
