### ISSUE TITLE
Hereroatoms in CA selection

### ISSUE THREAD

**Issue by ga01** [prody/ProDy#1358]
Deat Prody Team,
I noticed that when I select Ca-s in a pdb using: 

parsePDB(pdb, subset='ca')

the CA-s of modified residues (heteroatoms) in the protein chain, e.g. MSE are not selected. I wonder whether there is a workaround for this. 

Best wishes,
George

**Comment by jamesmkrieger** [comment]
Hi George, how about if you use a selection instead of a subset?

X = parsePDB(pdb)
Y = X.select(“name CA”)

Ideally MSE shouldn’t be a hetatm though so maybe we need to change the residue list

**Comment by ga01** [comment]
Thanks, that works.
Best wishes, 
George

**Comment by jamesmkrieger** [comment]
Hi George,

I just checked the code of ProDy and non-standard amino acids such as MSE are included when applying subset in _parsePDBLines. I then tried using subset='ca' for a structure with MSE residues and it seems to have worked:
```
In [21]: ag = parsePDB('4kwa', subset='ca', compressed=False)
@> 385 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Secondary structures were assigned to 336 residues.

In [22]: ag.select('resnum 224')
Out[22]: <Selection: 'resnum 224' from 4kwa_ca (2 atoms)>

In [23]: ag.select('resnum 224')[0]
Out[23]: <Atom: CA from 4kwa_ca (index 131)>

In [24]: ag.select('resnum 224')[0].getResname()
Out[24]: 'MSE'
```

Can you please give me the PDB ID where it didn't work for me to look into it?

Many thanks
James

**Comment by ga01** [comment]
Hi James, 
Thanks; I processed a large number of structures (thousands), and in many of them modified residues weren't selected. I didn't really check in detail which modified residues work and which do not. Looks like MSE is an exception, but many others are not selected, like MEN (in 1cpc), or CSB (in 1b6g). I will try to find structures where also MSE is not selected, and if there are such I will let you know, but I suspect that MSE, as the most common one, works everywhere.

Best wishes, 
George

**Comment by jamesmkrieger** [comment]
I think MSE should be selected as it is in the non-standard amino acids list. We may need to add others though. I haven't seen MEN or CSB before, for example. These kinds of modifications are very rare. In fact, CSB (Cysteine bonded to lead) is only seen in that one structure.

**Comment by jamesmkrieger** [comment]
I have started a pull request adding these. We can see that this allows them to be included very easily.

In the unmodified ProDy master branch, we only get 308 residues from 1b6g:
```
james@DESKTOP-QL82H8Q MINGW64 ~/code/ProDy (prody-master)
$ ipython
Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from prody import *

In [2]: ag = parsePDB('1b6g', compressed=False, subset='ca')
@> PDB file is found in working directory (1b6g.pdb).
@> 308 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Secondary structures were assigned to 183 residues.
```

However, in my new branch that makes the pull request, we get 310 because CSB is included:
```
james@DESKTOP-QL82H8Q MINGW64 ~/code/ProDy (nonstd_aas)
$ ipython
Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from prody import *

In [2]: ag = parsePDB('1b6g', compressed=False, subset='ca')
@> Connecting wwPDB FTP server RCSB PDB (USA).
@> 1b6g downloaded (1b6g.pdb)
@> PDB download via FTP completed (1 downloaded, 0 failed).
@> 310 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Secondary structures were assigned to 184 residues.
```

**Comment by ga01** [comment]
Hi James, 
Sounds good, but don't forget that these heteroatoms can also be ligands. For example, 4got or 4k3f have MSE as modified residue, but also have MSE ligands. The current subset='ca' picks both, and, for example a downstream PRS will use the ligand CA as well. To get these things right I have to process the structure twice, once to find out which is a mod. residue and which one is a ligand, and again to select the full protein chain.  

Best wishes, 
George

**Comment by jamesmkrieger** [comment]
Hi George,

This is something that we cannot handle automatically and will always be an issue for the user. Sometimes its helpful to have a node for a ligand in NMA anyway to better incorporate ligand effects so it's up to the user what they want to do about it.

There is not enough consistency in how people uploading to the PDB handle amino acid ligands for us to have a good way to deal with this as software developers I think. 

Best wishes
James

**Comment by jamesmkrieger** [comment]
If you could let me know other residues that you'd like me to include, that would be great.

Many thanks

**Comment by jamesmkrieger** [comment]
I'm assuming you're happy as is and closing the issue.

Best wishes
James
