### ISSUE TITLE
PCA as .txt

### ISSUE THREAD

**Issue by schwabem** [prody/ProDy#1359]
Hello, 

I have followed the tutorial to create a landscape and projected simulations frames into this space. I would now like to save the data points as a text file for analysis in a separate program. I have tried pca.getEigvecs() and calcProjection(ensemble, pca[:2]), but both of these results do not look like the landscape output file. The calcProjection output matches more closely than getEigvecs, but the magnitude is much smaller than the output. I am currently testing this on the landscape and plan to apply the same workflow to the simulation frames containing a couple thousand frames. Below is my script: 

ref_structure = parsePDB('Ref.pdb')
ref_selection = ref_structure.select('calpha')
ref_chain = ref_selection.getHierView()
ref_chain = ref_selection.getHierView().getChain('A')
repr(ref_chain)

ensemble = PDBEnsemble('Landscape')
ensemble.setAtoms(ref_chain)
ensemble.setCoords(ref_chain)

pdbfiles= ['Files.pdb']

for pdbfile in pdbfiles:
 structure = parsePDB(pdbfile, subset='calpha')
 mappings = mapOntoChain(structure, ref_chain,)
 atommap = mappings[0][0]
 ensemble.addCoordset(atommap, weights=atommap.getFlags('mapped'))

ensemble.superpose()
saveEnsemble(ensemble)
writePDB('Rap1A_ensemble.pdb', ensemble)
pca = PCA('Landscape')
pca.buildCovariance(ensemble)
pca.calcModes()
saveModel(pca)

color_list= ['colors']
marker_list= ['markers']
color2label= {'color': 'Name'} 
marker2label= {'marker':'Name'}
label_list= [color2label[color] for color in color_list]

fig = plt.figure(figsize=(25,25), tight_layout='true')
showProjection(ensemble, pca[:2], color=color_list, label=label_list, marker=marker_list, ms=45)
legend(loc='center left', bbox_to_anchor=(1,0.5), borderpad=1, labelspacing=2, fontsize=35)

plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.xlabel('PC1', fontsize=30)
plt.ylabel('PC2', fontsize=30)
plt.savefig('PCA_landscape.pdf')

proj= calcProjection(ensemble, pca[:2]) 
writeArray('PCA_eigvecs.txt', proj)

Any help is greatly appreciated.

**Comment by jamesmkrieger** [comment]
calcProjection should be the right answer. You may have to play with the rmsd and norm kwargs to get the output to scale how you want

**Comment by schwabem** [comment]
Thank you for the suggestion and quick response. rmsd=True, norm=False solved this issue.

**Comment by jamesmkrieger** [comment]
You’re welcome
