### ISSUE TITLE
Scree Plot

### ISSUE THREAD

**Issue by conor-mckay98** [prody/ProDy#1362]
I have retrieved the nmd files from a protein simulation using 25 modes. I want to determine how each of the modes contribute to the system. Is there a way I can create a scree plot in ProDy to do this. 

Thanks for any help

Conor.

**Comment by jamesmkrieger** [comment]
You can use showFractVars to show the fractional variance and there's a function calcFractVars to get the numbers. Is that what you mean?

**Comment by conor-mckay98** [comment]
I have used the showFractVars function at I have achieved what I was intending. Thanks for your help!

**Comment by jamesmkrieger** [comment]
This is essentially the same thing. In PCA, the eigenvalues are the fractional variance and you use showFractVars (http://prody.csb.pitt.edu/_modules/prody/dynamics/plotting.html#showFractVars) for this. In NMA, you can just plot the eigenvalues yourself using a code based on that with getEigvals().

**Comment by jamesmkrieger** [comment]
You're welcome
