### ISSUE TITLE
Visualising one Subunit in a complex

### ISSUE THREAD

**Issue by conor-mckay98** [prody/ProDy#1367]
Hi,

I am running NMA on a complex with multiple subunits within. I want to visualise the square fluctuations for one subunit using showSqFlucts() but obviously this gives me the fluctuations of the whole complex. Is there a way I can visualise the square fluctuations of one subunit in the context of the entire complex?

Thank you.

Conor

**Comment by jamesmkrieger** [comment]
Yes, you can use sliceModel or reduceModel before showSqFlucts. The latter modifies the Hessian to treat the rest of the complex as the environment and then you calculate modes for the subunit of interest again. They have different but related meanings. 

You can see an example of this by comparing the results in Fig 4 of Krieger et al. 2015 (sliceModel; https://pubmed.ncbi.nlm.nih.gov/26255587/) and Fig 5 of Dutta et al. 2015 (reduceModel; https://pubmed.ncbi.nlm.nih.gov/26256538/).

**Comment by jamesmkrieger** [comment]
You use it as a selection string as the third argument. The first two are the names of model and atoms objects. If you have an ANM object called `anm` and an AtomGroup object called `ag`, then you can put the following:

`sliceModel(anm, ag, 'chain A and resnum 1 to 929')`

**Comment by jamesmkrieger** [comment]
Did this do what you wanted or do you still need something else?

**Comment by conor-mckay98** [comment]
Sorry, I had forgotten about this thread.  How is it that I can create an atom group?

**Comment by conor-mckay98** [comment]
By that I mean creating an atom group to be used in the slicemodel().

**Comment by jamesmkrieger** [comment]
An atomic object should be the second of the results from sliceModel():

`sliced_anm, sliced_atoms = sliceModel(anm, ag, 'chain A and resnum 1 to 929')`

You can also use sliceAtoms instead of sliceModel if you only want the atoms and not the dynamics:

`slicing_indices, sliced_atoms2 = sliceAtoms(ag, 'chain A and resnum 1 to 929')`

or just select:

`selected_atoms = ag.select('chain A and resnum 1 to 929')`

**Comment by jamesmkrieger** [comment]
In all cases, it is actually a Selection that you get and not an AtomGroup. If you wanted to get an AtomGroup, you need to use `sliced_ag = sliced_atoms.copy`

**Comment by conor-mckay98** [comment]
Okay thank you. I think my problem is that I haven't defined an atom group as ag before the sliceModel command, how is it that I can do this? 

Apologies if I am misunderstanding you.

**Comment by jamesmkrieger** [comment]
But you performed NMA on an AtomGroup, no? That's what you get when you use parsePDB:

`ag = parsePDB(pdb)`

**Comment by conor-mckay98** [comment]
Ah yes okay I've done that writing: sliced_anm, sliced_atoms = sliceModel(complex_anm, complex, 'chain A and resnum 1 to 929')

It has returned an error saying ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-1a1f78d50b9f> in <module>
----> 1 sliced_anm, sliced_atoms = sliceModel(complex_anm, complex, 'chain A and resnum 1 to 929')

~/miniconda3/lib/python3.7/site-packages/prody/dynamics/editing.py in sliceModel(model, atoms, select)
    286                         .format(type(atoms)))
    287     if atoms.numAtoms() != model.numAtoms():
--> 288         raise ValueError('number of atoms in model and atoms must be equal')
    289 
    290     which, sel = sliceAtoms(atoms, select)

ValueError: number of atoms in model and atoms must be equal

**Comment by jamesmkrieger** [comment]
Can you give me your full list of commands please? Otherwise it’s very hard to work out what’s happening. 

My guess at this point would be that you took the calpha atoms by selecting and not during parsing and therefore you have a separate calpha object you need to give to sliceModel. It should be whatever you used for buildHessian for the ANM.

**Comment by conor-mckay98** [comment]
Of course,

from prody import *

from pylab import *

ion()

complex = parsePDB('NSP12_NSP8a_NSP7_NSP8b.pdb')

complex

showProtein(complex);

complex_ca=complex.ca

complex_ca


complex_anm = ANM('complex ca')

complex_anm

complex_anm.buildHessian(complex_ca)

complex_anm

complex_anm.calcModes(n_modes=25)

complex_anm

showSqFlucts(complex_anm);

sliced_anm, sliced_atoms = sliceModel(complex_anm, complex, 'chain A and resnum 1 to 929')

**Comment by jamesmkrieger** [comment]
Ok, yep, that’s what I thought. You should use complex_ca in sliceModel

**Comment by jamesmkrieger** [comment]
Incidentally, almost all the show functions including showSqFlucts can take an atoms argument to show the residue numbers along the axes and chains as coloured bars underneath

**Comment by conor-mckay98** [comment]
Brilliant that has sorted out my problem. Thank you for being so patient and helpful!

**Comment by jamesmkrieger** [comment]
You're welcome.

(issue closed)
