### ISSUE TITLE
Creating NMD file with single subunit

### ISSUE THREAD

**Issue by conor-mckay98** [prody/ProDy#1375]
I am looking at a complex which has multiple subunits and I was hoping to create an NMD file which I can view in NMWiz extension of VMD. From this I want to view the mobility at each mode for each subunit individually.

Here are my commands: 

from prody import *

from pylab import *

ion()

x = parsePDB('master_modelled_full_complex.pdb')

x

showProtein(x);

x_ca=x.ca

x_ca

x_anm = ANM('x ca')

x_anm

x_anm.buildHessian(x_ca)

x_anm

x_anm.calcModes(n_modes=25)

x_anm

showSqFlucts(x_anm);

for mode in x_anm:
   ....:     print('{}\tcollectivity: {}'.format(str(mode), calcCollectivity(mode)))

writeNMD('x_anm.nmd', x_anm, x_ca)

showCrossCorr(x_anm)

showFractVars(x_anm)

NSP12

sliced_anm, sliced_atoms = sliceModel(x_anm, x_ca, 'chain A and resnum 1 to 929')

showSqFlucts(sliced_anm);

writeNMD('sliced_anm.nmd', x_anm, x_ca)

When I visualise the sliced molecule in VMD it shows the whole complex rather than the specified subunit. Would I be able to get some help as to how I can visualised the subunit alone?

Thank you for any help you can give!

**Comment by jamesmkrieger** [comment]
The problem is you used x_anm, x_ca rather than sliced_anm, sliced_atoms in writeNMD 

it always helps to have another pair of eyes, doesn’t it?

**Comment by conor-mckay98** [comment]
It really does! thank you again for your quick reply!

**Comment by jamesmkrieger** [comment]
You’re very welcome
