### ISSUE TITLE
Generate ensemble (ens) from existing alignment

### ISSUE THREAD

**Issue by gtzotzos** [prody/ProDy#1376]
I have a multiple sequence alignment generated by Mustang (**my_msa.fasta**). Is it possible to load this and generate an ensemble to be used in Prody for the calculation of signature dynamics?

Thanks in advance for any suggestions

**Comment by jamesmkrieger** [comment]
Yes, there is an option to buildPDBEnsemble to provide an MSA object as a mapping. See mapChainOntoChain and its documentation for more details. 

buildPDBEnsemble calls alignChains, which calls mapOntoChains, which calls mapChainOntoChain, which calls getAlignedMapping if it receives a predefined alignment as a list or MSA object.

**Comment by gtzotzos** [comment]
James,

Thank you very much. I went through the documentation and tried various permutations of the syntax but got rather stuck. 

Finally, I tried

OBPs = [prt1, prt2, etc]

pdb_ids = OBPs

pdbs = parsePDB(*pdb_ids)

ens = buildPDBEnsemble(pdbs, mapping='aln2.fasta', seqid=0, overlap=0, title='OBP', subset='ca’) ##### aln2.fasta is my MSA

msa = ens.getMSA()

writeMSA('ens23.fasta', msa)

I then inspected ens23.fasta and found that the alignment is quite different to the one that I submitted for mapping (aln2.fasta)

It’s clear that I got it all wrong. I would be grateful for any suggestions

Many thanks in advance

**Comment by jamesmkrieger** [comment]
You need to use parseMSA and not just provide the filename. It just thinks the filename is a string to be used for mapping otherwise.

you also don’t need a star before pdb_ids. It’s actually faster if you don’t use one.

the code should be as follows:

pdb_ids = [prt1, prt2, etc]

pdbs = parsePDB(pdb_ids)

msa1 = parseMSA('aln2.fasta')

ens = buildPDBEnsemble(pdbs, mapping=msa1, seqid=0, overlap=0, title='OBP', subset='ca’)

**Comment by gtzotzos** [comment]
James, many thanks for the prompt and very helpful response

**Comment by jamesmkrieger** [comment]
You're very welcome as usual. Is it working now?

**Comment by gtzotzos** [comment]
Yes, it is. No problem.

All the best

**Comment by jamesmkrieger** [comment]
Perfect. Issue closed then
