### ISSUE TITLE
Error with ESSA and scanPockets()

### ISSUE THREAD

**Issue by AChatzigoulas** [prody/ProDy#1381]
Hello,

when I try to scan for allosteric pockets with ESSA/fpocket I get the following error:
```Console
AttributeError: Atom object has no attribute `getChids` and 'getChids' is not a valid selection string
```

Code to reproduce:
```python
prot = parsePDB('1s6x')
essa = ESSA()
essa.setSystem(prot)
essa.scanResidues()
essa.scanPockets()
```

I think this error results when fpocket predicts exactly one pocket

Thank you!

**Comment by rwxayheee** [comment]
Hello, 

Not a contributor to ESSA but I'm also using this application in ProDy. Does it work for you if you add "toAtomGroup()" here in essa.py: 

        pcn = {int(pdb.getTitle().partition('_')[0][6:]):
               set(zip(pdb.**toAtomGroup()**.getChids().tolist(),
                       pdb.**toAtomGroup()**.getResnums().tolist())) for pdb in pdbs}

Hope this would be of some help.. Let me know if it works for you. 

Amy H

**Comment by jamesmkrieger** [comment]
Hi Alexios,
Thanks for reporting this. I have fixed it in #1382.

Hi Amy,
While that would in theory fix it, it is a workaround and not an actual fix for the real problem, which is that `pdbs` is an AtomGroup not a list of AtomGroups. Rather the fix is to put the single AtomGroup in a list as in #1382 

Best wishes
James

**Comment by rwxayheee** [comment]
Hi James, 

Thank you for your kind reply. Yes the way you fix it is exactly correct! 

Many Thanks,
Amy H

**Comment by jamesmkrieger** [comment]
You're welcome.

**Comment by AChatzigoulas** [comment]
Thank you very much James.

**Comment by jamesmkrieger** [comment]
You're very welcome
