### ISSUE TITLE
Exporting a cross-correlation map from Jupyter notebook

### ISSUE THREAD

**Issue by conor-mckay98** [prody/ProDy#1387]
Hi,

I am trying to export a cross-correlations map for a protein which has 2000 residues. Due to the size of the protein i dont want to screenshot the cross- correlation graph as the resolution will not be high enough to distinguish the individual residues. Is it possible to export write out a file from jupyter notebook giving the cross-correlation map?

Thank you for your help.

**Comment by jamesmkrieger** [comment]
Yes, there is a writeArray function that you can use for that.

**Comment by conor-mckay98** [comment]
Okay thanks. How would I write that? I am using a protein called NSP12, and to show the cross correlations I have written showCrossCorr(NSP12_anm)

**Comment by jamesmkrieger** [comment]
I think the follow should work

```
cross_corr_matrix = calcCrossCorr(NSP12_anm)
writeArray('NSP12_anm_cross_corr_matrix', cross_corr_matrix)
```

**Comment by conor-mckay98** [comment]
It returned an error ---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-49-a7276dc54085> in <module>
----> 1 writeArray('NSP12_anm_cross_corr_matrix', cross_corr_matrix)

NameError: name 'cross_corr_matrix' is not defined

Sorry, I haven't defined cross_corr_matrix, how would I do this?

Thank you for you patience.

**Comment by jamesmkrieger** [comment]
I just gave you two commands. The first should define it. Did that not work?

**Comment by conor-mckay98** [comment]
My bad! it has worked. I only typed the second command
