### ISSUE TITLE
Cross-correlations

### ISSUE THREAD

**Issue by conor-mckay98** [prody/ProDy#1389]
Is it possible to only include a certain range of modes in cross-correlation maps? If so how would I do this?

Thank you for you help.

**Comment by jamesmkrieger** [comment]
Yes, just index them out, e.g.

x = calcCrossCorr(anm[0])

or

show = showCrossCorr(anm[:3])

**Comment by conor-mckay98** [comment]
Thanks James! extremely helpful as ever!

**Comment by jamesmkrieger** [comment]
You’re very welcome
