### ISSUE TITLE
Structural waters in GNM calculation

### ISSUE THREAD

**Issue by rwxayheee** [prody/ProDy#1391]
Dear ProDy experts, 

I'm wondering if there's a way to incorporate structural waters in the GNM calculation. I have some closed cavities in my protein structure with structural waters inside the cavities. 

I saw a post (#1083) about how to add covalent links in network models. It was very helpful. I'm thinking about using the custom gamma functions for residues that interact directly with the structural waters. But I'm not very sure how much I should add to the string constant for such non-bonded interaction. 

Any comments and suggestions will be appreciated. Thank you for your kind help in advance! 

Thanks,
Amy H

**Comment by jamesmkrieger** [comment]
Hi Amy,

This is a complicated topic that likely needs its own detailed analysis. 

However, overall the approach you suggest of including but modifying springs for structural waters makes sense. Ivet suggests using ~5x weaker spring constants for interactions with waters. Ideally, there should probably be different values for water-water and water-protein interactions, but using the same for both might be ok.

Best wishes
James
