### ISSUE TITLE
Error in model detection in the MMCIF parser

### ISSUE THREAD

**Issue by aozalevsky** [prody/ProDy#1392]
There seems to be a bug in the model detection routine in the MMCIF parser. Example:

```
fname = prody.fetchPDBviaFTP('2gt5', format='pdb')
pdb = prody.parsePDB(fname)
print(fname, pdb.numCoordsets())
2gt5.pdb.gz 30

fname = prody.fetchPDBviaFTP('2gt5', format='cif')
pdb = prody.parseMMCIF(fname)
print(fname, pdb.numCoordsets())
2gt5.cif.gz 29

```

I tried both 2.0 release and git version - both produce the same result. PyMOL also parses both files correctly returning 30 models. I tried to look in the code to find the possible problem, but nothing has caught my eye.

**Comment by aozalevsky** [comment]
Guess I found the problem:

https://github.com/prody/ProDy/blob/cc875e0e59a829bc5ff7ec73cf1a4e461b29c76b/prody/proteins/ciffile.py#L233-L236

when it's the very first ATOM line, asize is 0, thus models[0] == models[0-1] returns True, because it is the same element and nModels does not increment. So we miss the very first model. Later it causes problems because of: 

https://github.com/prody/ProDy/blob/cc875e0e59a829bc5ff7ec73cf1a4e461b29c76b/prody/proteins/ciffile.py#L349 

thus some atoms become mixed between models. 

My immediate fix was:

```
if len(models) == 1 or (models[asize] != models[asize-1]):
    nModels += 1

```

It also makes redundant the following check (at least it seems so): https://github.com/prody/ProDy/blob/cc875e0e59a829bc5ff7ec73cf1a4e461b29c76b/prody/proteins/ciffile.py#L242-L243

Hope this would help!

**Comment by jamesmkrieger** [comment]
Thanks very much for spotting this. I have confirmed that it works for cases with one model too and created a pull request for it (#1393).

Best wishes
James

**Comment by aozalevsky** [comment]
Glad I was able to help. ProDy is an extremely useful package and I use it (and cite, of course) in almost all of my projects.

**Comment by jamesmkrieger** [comment]
Thanks very much. I’m glad you think so!
