### ISSUE TITLE
Error of fetchPDBclusters()

### ISSUE THREAD

**Issue by KeiYura** [prody/ProDy#1400]
We encountered following warnings when we use fetchPDBclusters() and couldn't fetch the PDB sequence identity clustering information.
@> WARNING Clusters at 30% sequence identity level could not be downloaded.
@> WARNING Clusters at 40% sequence identity level could not be downloaded.
@> WARNING Clusters at 50% sequence identity level could not be downloaded.
@> WARNING Clusters at 70% sequence identity level could not be downloaded.
@> WARNING Clusters at 90% sequence identity level could not be downloaded.
@> WARNING Clusters at 95% sequence identity level could not be downloaded.
@> WARNING Clusters at 100% sequence identity level could not be downloaded.
@> WARNING PDB clusters could not be downloaded.
It seems that the database is not available. How can we obtain the data?

**Comment by jamesmkrieger** [comment]
Maybe the server was down or something. I've just checked and https://cdn.rcsb.org/resources/sequence/clusters/bc-30.out is there now, and fetchPDBClusters() is working on my laptop.

**Comment by jamesmkrieger** [comment]
Can you try again please?

**Comment by KeiYura** [comment]
Dear ProDy;
Dear James;

    This is Kei Yura.
    My student tried again and had the same
    error as before (attached).

KY

**Comment by jamesmkrieger** [comment]
Dear Kei Yura,

The attachment didn’t work. Can you copy and paste again please? Also, please can you provide more information, especially ProDy version and how your student got it.

Many thanks 
James

**Comment by KeiYura** [comment]
Dear James;

    This is Kei Yura.
    My student use Macintosh. She said it worked on Windows.
    But on Mac, it did not. She used python version 3.8.5 and
    used command 'pip install prody' to install.

@> WARNING Clusters at 30% sequence identity level could not be downloaded.
@> WARNING Clusters at 40% sequence identity level could not be downloaded.
@> WARNING Clusters at 50% sequence identity level could not be downloaded.
@> WARNING Clusters at 70% sequence identity level could not be downloaded.
@> WARNING Clusters at 90% sequence identity level could not be downloaded.
@> WARNING Clusters at 95% sequence identity level could not be downloaded.
@> WARNING Clusters at 100% sequence identity level could not be downloaded.
@> WARNING PDB clusters could not be downloaded.

    She also tried 'fetchPDBClusters()'
    in python IDLE after warnings on the terminal, but the same thing
    happened.

    Looking forward to good news.

Best wishes,
KY

**Comment by jamesmkrieger** [comment]
Can she confirm that she downloaded it to the Mac with pip after the 7th of February and has ProDy 2.0 not an earlier version? This function changed just before we made that release. 

She may also need to use `pip install -U prody` to ensure that it updates it to the latest version rather than reinstalling version that was there before.

Best wishes
James

**Comment by KeiYura** [comment]
Dear James;

    This is Kei Yura.
    Thank you for the follow up.
    The following is what she has done.

*********
I tried "pip install -U prody" and checked prody verision by pip freeze. 
Then open the python and run "fetchPDBclusters()".

chaseonsin-macui-iMac:~ sscha$ pip install -U prody
Requirement already satisfied: prody in 
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages 
(2.0)
Requirement already satisfied: numpy>=1.10 in 
./Library/Python/3.8/lib/python/site-packages (from prody) (1.19.1)
Requirement already satisfied: pyparsing in 
./Library/Python/3.8/lib/python/site-packages (from prody) (2.4.7)
Requirement already satisfied: biopython in 
./Library/Python/3.8/lib/python/site-packages (from prody) (1.77)
Requirement already satisfied: scipy in 
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages 
(from prody) (1.5.2)
chaseonsin-macui-iMac:~ sscha$ pip freeze
biopython==1.77
certifi==2020.6.20
cycler==0.10.0
et-xmlfile==1.0.1
jdcal==1.4.1
kiwisolver==1.2.0
matplotlib==3.3.1
numpy==1.19.1
openpyxl==3.0.6
pandas==1.2.2
pdbx==0.3.0
Pillow==7.2.0
ProDy==2.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
scipy==1.5.2
six==1.15.0
chaseonsin-macui-iMac:~ sscha$ python
Python 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 >>> from prody import *
 >>> fetchPDBClusters()
@> WARNING Clusters at 30% sequence identity level could not be downloaded.
@> WARNING Clusters at 40% sequence identity level could not be downloaded.
@> WARNING Clusters at 50% sequence identity level could not be downloaded.
@> WARNING Clusters at 70% sequence identity level could not be downloaded.
@> WARNING Clusters at 90% sequence identity level could not be downloaded.
@> WARNING Clusters at 95% sequence identity level could not be downloaded.
@> WARNING Clusters at 100% sequence identity level could not be downloaded.
@> WARNING PDB clusters could not be downloaded.
*********

     Something is going wrong.

Best wishes,
KY

**Comment by SHZ66** [comment]
Hi,

This seems to be an internet connection issue on your end. Could you please try if you could manually download files from the [RCSB site](https://www.rcsb.org/docs/programmatic-access/file-download-services#sequence-clusters-data)?
