### ISSUE TITLE
Prody job submission error

### ISSUE THREAD

**Issue by Fredlsw** [prody/ProDy#1412]
Dear all, 

I am trying to perform PCA analysis using prody interface of VMD 1.9.3 in Ubuntu virtual box. However, when i submit the job following errors occurred.

**invalid command name ".nmwizprody.pcaFrame.infoentry"
invalid command name ".nmwizprody.pcaFrame.infoentry"
    while executing
".nmwizprody.pcaFrame.infoentry configure -text [format "$count frames (~%.2f MB)" $size]"
    (procedure "::NMWiz::calcOutputSize" line 34)
    invoked from within
"::NMWiz::calcOutputSize"
    (procedure "::NMWiz::prodyUpdateSelection" line 13)
    invoked from within
"::NMWiz::prodyUpdateSelection"
    (procedure "::NMWiz::prodyUpdateMolinfo" line 7)
    invoked from within
"::NMWiz::prodyUpdateMolinfo"
    (procedure "::NMWiz::prodyUpdateMolList" line 21)
    invoked from within
"::NMWiz::prodyUpdateMolList"
    (procedure "::NMWiz::initProdyGUI" line 31)
    invoked from within
"::NMWiz::initProdyGUI"
    invoked from within
".nmwizgui.mainframe.prody invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizgui.mainframe.prody"
    (command bound to event)**

Any ideas how to solve this? Thanks in advance!

Fred

**Comment by jamesmkrieger** [comment]
Can you try running the prody command line app instead and seeing if that works? http://prody.csb.pitt.edu/tutorials/prody_tutorial/apps.html

**Comment by jamesmkrieger** [comment]
Could you also confirm whether you are using the latest ProDy from github installed within a conda environment?
