### ISSUE TITLE
Residue Contribution to PCA

### ISSUE THREAD

**Issue by schwabem** [prody/ProDy#1423]
Hello,

I want to examine the residue contribution to a component after projecting MD frames into the PCA space of the crystal structures (same script as Issue #1359). I have seen this done in the R-based Bio3D software and wanted to know if similar analysis was possible in ProDy before I change languages. I came across the calcDynamicFlexibilityIndex function and was unsure if this was the same parameter, but wanted to give it a try. I received the 'name is not defined error'. I tried updating to the lasted version to no avail. I also found a separate module (https://github.com/avishekrk/DFI) which appears to be slightly different and wanted to ask for help before preceding. Any insight provided would be greatly appreciated.

**Comment by jamesmkrieger** [comment]
DFI is based on perturbation response scanning so you need to use that first. Thanks for sharing that other package. I’ll have a look what it does.

For seeing residue contributions from PCA itself the better option is to use calcSqFlucts

**Comment by schwabem** [comment]
Thank you for the quick response. Using calcSqFluct(pca[0]) to examine the first component worked.
