### ISSUE TITLE
Iteratively parsing PDB files from local directory

### ISSUE THREAD

**Issue by jlefebre** [prody/ProDy#1426]
Dear all,

I have been using the Prody module ESSA (http://prody.csb.pitt.edu/tutorials/essa_tutorial/index.html) for single proteins by directly retrieving them from the PDB. This worked fine and as described in the tutorial they provide. Now I would like to extend this and do the same calculation on ~200 structures by iterating over downloaded PDB files in a directory. However, it seems like the parser that prody uses doesn't recognize my downloaded PDB files and I don't understand why. Here is my code:

```
from prody import *
from numpy import *
from matplotlib.pyplot import *
from pandas import *
import os
ion()

directory = '/home/lefebrej95/Documents/PDB_ESSA_test_format'
ext = ('.pdb')
for f in os.listdir(directory):

   if f.endswith(ext):

      fetchPDB(f)  

      atoms = parsePDB(f, compressed = True)
      essa = ESSA()

      essa.setSystem(atoms)

      essa.scanResidues()

      with style.context({'figure.dpi': 600}):
           essa.showESSAProfile()
```
I am getting this error message, no matter what PDB file I am trying to parse: 

```
@> WARNING '7l67.pdb' is not a valid identifier. @> Matching 10 modes across 136 modesets... [ 99%] 1s@> WARNING '7l62.pdb' is not a valid identifier. Traceback (most recent call last):

File "/home/lefebrej95/.config/spyder-py3/untitled1.py", line 35, in <module> atoms = parsePDB(f, compressed = True)

File "/home/lefebrej95/anaconda3/lib/python3.8/site-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/proteins/pdbfile.py", line 123, in parsePDB return _parsePDB(pdb[0], **kwargs)

File "/home/lefebrej95/anaconda3/lib/python3.8/site-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/proteins/pdbfile.py", line 205, in _parsePDB pdb, chain = _getPDBid(pdb)

File "/home/lefebrej95/anaconda3/lib/python3.8/site-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/proteins/pdbfile.py", line 192, in _getPDBid raise IOError('{0} is not a valid filename or a valid PDB '

OSError: 7l62.pdb is not a valid filename or a valid PDB identifier.
```
Any help is highly appreciated! 

Best regards, 

Jonathan

**Comment by jamesmkrieger** [comment]
Probably the problem is that you're using compressed=True but your pdb files aren't compressed. 

The fetchPDB command is also wrong when you already have the files from the PDB in your directory.

**Comment by jlefebre** [comment]
You are right. I corrected both, but I still get the same error message. I don't understand the problem, because, also checking the files in the text editor didn't show any abnormalities in the pdb files I downloaded. I am using the batch download script provided by RCSB PDB to download larger numbers of PDBs as .gz files and then I unzip them. Is this 'harming' the PDB files?

**Comment by jamesmkrieger** [comment]
It shouldn't do. 

Oh, another problem could be that your computer isn't finding those files. If you're running outside the directory then you need to include the path in the filename for parsePDB e.g.

`atoms = parsePDB(directory + '/' + f)`

**Comment by jlefebre** [comment]
Dude, thanks a lot! That worked out well. 

Best regards, 

Jonathan

**Comment by jamesmkrieger** [comment]
You're very welcome. Glad I could help.

Best wishes
James
