### ISSUE TITLE
Analyzing mode ensembles generated from ESSA in VMD

### ISSUE THREAD

**Issue by jlefebre** [prody/ProDy#1441]
Sorry, this might be an easy one, but I am quite confused. Is it possible to analyze modes generated in ESSA in VMD via the NMWiz plugin? In other words, can I write an NMD file from a mode ensemble (.npz) file?

Best, 

Jonathan

**Comment by jamesmkrieger** [comment]
Hi Jonathan,

I think the answer is yes. The ESSA object has an attribute _ensemble, which is a ModeEnsemble containing sets of modes for each of the perturbations reordered to match the original unperturbed modes. You can loop through them and save them to NMD files as follows:
`[writeNMD('essa_modeset_{0}.nmd'.format(i), modeset, essa._ca) for i, modeset in enumerate(essa._ensemble)]`

Best wishes
James

**Comment by jamesmkrieger** [comment]
One called also use the ModeEnsemble for comparative analyses of mode shapes like in SignDy

**Comment by jlefebre** [comment]
Thanks James, that worked! 

Best 
Jonathan
