### ISSUE TITLE
PCA vectors on vmd

### ISSUE THREAD

**Issue by TianmingQu** [prody/ProDy#1443]
Hi all, could anybody tell me how to generate the nmd file using the eigenvectors generated from the pytraj pca calculation?

**Comment by jamesmkrieger** [comment]
I'll look into it and get back to you. Probably it's going to require us to write new code.

**Comment by jamesmkrieger** [comment]
Assuming you have something like https://amber-md.github.io/pytraj/latest/tutorials/tutorial_pca.html, I think we'd need the following:
```
pca = PCA()
pca.setEigens(data[1][1], data[1][0])
```

You also need an atomic object for writeNMD and you could get that by writing a pdb file with pytraj's `save` method and then parsing it back into ProDy with `parsePDB`

**Comment by jamesmkrieger** [comment]
> I'll look into it and get back to you. Probably it's going to require us to write new code.

I guess it doesn't really as the code in my above message is something that the user can do easily
