### ISSUE TITLE
Confusing pairwise alignment logging when pairwise=True

### ISSUE THREAD

**Issue by RMeli** [prody/ProDy#1464]
I was testing `matchChains` on a PDB file containing only two residues (because of a problem that I have yet to identify):
```python
import prody

p1 = prody.parsePDB("t1.pdb")
p2 = prody.parsePDB("t1.pdb")

cutoff = 90

m = prody.matchChains(p1, p2, subset="all", overlap=cutoff, seqid=cutoff, pwalign=True)
```
and I got the following output:
```text
@> 16 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 16 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> Checking AtomGroup t1: 1 chains are identified
@> Checking AtomGroup t1: 1 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from t1 (len=2) and Chain A from t1 (len=2):
@>      Match: 2 residues match with 100% sequence identity and 100% overlap.
@> Trying to match chains based on local sequence alignment:
```
I was a bit puzzled by the last line that seem to be incomplete, despite the `pwalign=True`. Looking at the [documentation](http://prody.csb.pitt.edu/manual/reference/proteins/compare.html#prody.proteins.compare.matchChains) and the code
https://github.com/prody/ProDy/blob/258bf94e62f57bed1d3d76929265d2531ed904b2/prody/proteins/compare.py#L646-L650
it is quite clear that the pairwise alignment only happens if the alignment based on residue numbers and names fails. I think it would be less confusing if `@> Trying to match chains based on local sequence alignment:` is not printed at all in such case (or if something like `@> No unmatched chains; sequence alignment skipped.` is printed instead).

I can provide a PR in the coming days if needed.

**Comment by jamesmkrieger** [comment]
Hi,

Yes, that's strange it reports that before the loop, which can then be an empty loop if there's nothing left in unmatched. 

I'm making a pull request so don't worry about that. 

Best wishes
James

**Comment by RMeli** [comment]
Thanks @jamesmkrieger !

**Comment by jamesmkrieger** [comment]
You're welcome

**Comment by jamesmkrieger** [comment]
This should now be fixed by #1465 so issue closed.

You should now be able to install the latest ProDy version 2.0.2 from PyPI with pip. I'm still working on the conda part

**Comment by jamesmkrieger** [comment]
Actually, this is not in the new ProDy release yet as it turned out to be a more complicated issue.

**Comment by jamesmkrieger** [comment]
It is merged into the github version of prody now so you can use it there.

**Comment by RMeli** [comment]
Thanks @jamesmkrieger
