### ISSUE TITLE
fetchPfamMSA gives invalid URL error

### ISSUE THREAD

**Issue by evancresswell** [prody/ProDy#1472]
The following command:
        fasta_file = fetchPfamMSA('PF00186', compressed=True)
gives the following error:

SSLCertVerificationError                  Traceback (most recent call last)
~/anaconda3/envs/DCA_ER/lib/python3.9/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1345             try:
-> 1346                 h.request(req.get_method(), req.selector, req.data, headers,
   1347                           encode_chunked=req.has_header('Transfer-encoding'))

~/anaconda3/envs/DCA_ER/lib/python3.9/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1278         """Send a complete request to the server."""
-> 1279         self._send_request(method, url, body, headers, encode_chunked)
   1280 

....
....
....

OSError: 'https://pfam.xfam.org/family/acc?id=PF00186' could not be opened for reading, invalid URL or no internet connection. Is there an issue with my input of 'PF00186'.. Is this error common? Any insight would be much appreciated..

**Comment by jamesmkrieger** [comment]
This is not a new error. We already have this at #1444. 

I'm sorry we haven't got around to fixing it yet.

**Comment by jamesmkrieger** [comment]
The fix was to use `request.get(url, verify=False)` and now it works. I'll merge the pull request and then you should be able to use it by updating prody from github.

I'll probably make a release soon too as this seems like an important functionality for users to have fixed.
