### ISSUE TITLE
Problem viewing flucts in `view3D`

### ISSUE THREAD

**Issue by ljmartin** [prody/ProDy#1475]
Hi all, 
I'd like to view normal modes in a notebook, like in the example at: https://nbviewer.org/github/3dmol/3Dmol.js/blob/eadee7c5a2f3509c97d6449449f68611859d03ed/py3Dmol/prody.ipynb

For example:

```
prot = prody.parsePDB('3UB5')
anm, sel = prody.calcANM(prot)
prody.showProtein(prot,vecs=anm[0].getArray(),
                  flucts=prody.calcSqFlucts(anm[0]),
                  style={'cartoon':{}})
```

The output doesn't show multiple modes, or arrows - just the static gray cartoon. Actually, it doesn't look like the `flucts` argument gets used in either `showProtein` or `view3D` functions at 
https://github.com/prody/ProDy/blob/9e0e07ffb1c6a060cf2abce855f18d2b41b7d693/prody/proteins/functions.py#L12
and
https://github.com/prody/ProDy/blob/9e0e07ffb1c6a060cf2abce855f18d2b41b7d693/prody/proteins/functions.py#L185

Is that functionality available yet?

Thank you!

**Comment by jamesmkrieger** [comment]
It’s presumably passed on as a kwarg. I’ll have a look. I’m pretty sure I’ve seen these things working before

**Comment by jamesmkrieger** [comment]
Without anim=True, you get arrows instead unless you set arrows=False

**Comment by jamesmkrieger** [comment]
You also don't need the style={'cartoon':{}} part as ProDy adds that automatically if you have all atoms.

**Comment by ljmartin** [comment]
It looks really good! Thanks

**Comment by jamesmkrieger** [comment]
You're welcome
