### ISSUE TITLE
matchAlign bug in 2.0.2? 

### ISSUE THREAD

**Issue by PatWalters** [prody/ProDy#1483]
This block of code gives different results in Prody 2.0 and 2.02

```
from prody import *

ref_prot = prody.parsePDB('5RS7')
ref_prot = ref_prot.select("chain A")
prot = prody.parsePDB("5RVP")
res = '1SQ'
hv = prot.getHierView()
for chain in hv:
    if chain.select(f"resname {res}"):
        prot = chain
        prody.matchAlign(prot, ref_prot)
        break
```

In 2.0 I get an alignment 
```
@> Checking AtomGroup 5RVP: 1 chains are identified
@> Checking AtomGroup 5RS7: 1 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 5RVP (len=168) and Chain A from 5RS7 (len=167):
@> 	Match: 167 residues match with 100% sequence identity and 99% overlap.
@> Alignment is based on 167 atoms matching 'calpha'.
@> Before alignment RMSD: 71.77
@> After alignment  RMSD: 1.06
```

In 2.0.2 I get a bunch of warnings when reading the pdb file and the alignment fails
```
@> WARNING no one-letter mapping found for <Residue: 1SQ 201 from Chain A from 5RVP (19 atoms)>
@> WARNING no one-letter mapping found for <Residue: HOH 301 from Chain A from 5RVP (1 atoms)>
Lots more like this

@> Checking AtomGroup 5RS7: 1 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 5RVP (len=467) and Chain A from 5RS7 (len=372):
@> 	Failed to match chains (seqid=100%, overlap=80%).
@> Trying to match chains based on local sequence alignment:
@>  Comparing Chain A from 5RVP (len=467) and Chain A from 5RS7 (len=372):
@> 	Failed to match chains (seqid=100%, overlap=80%).
```

**Comment by jamesmkrieger** [comment]
That’s odd. It seems like the new version is seeing more atoms than the old one and hence it’s not meeting the overlap threshold. Perhaps, it’s using whole residues rather than calphas or something like that.

I’ll have a look and see what I can do.

**Comment by jamesmkrieger** [comment]
The problem is a change in building the SimpleChain (#1410) that happens in matchChains, which is called by matchAlign. Using matchChains gives exactly the same problem and running the first half of it (up until line 625) shows the following:

ProDy 2.0
```
@> Checking AtomGroup 5RVP: 1 chains are identified
@> Checking AtomGroup 5RS7: 1 chains are identified

In [20]: chains1
Out[20]: [<SimpleChain: Chain A from 5RVP with 168 residues>]

In [21]: chains2
Out[21]: [<SimpleChain: Chain A from 5RS7 with 167 residues>]
```

ProDy 2.0.2
```
@> WARNING no one-letter mapping found for <Residue: 1SQ 201 from Chain A from 5RVP (19 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 301 from Chain A from 5RVP (1 atoms)> 
.
.
.
@> Checking AtomGroup 5RVP: 1 chains are identified
.
.
.
@> WARNING no one-letter mapping found for <Residue: HOH 503 from Chain A from 5RS7 (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 504 from Chain A from 5RS7 (1 atoms)> 
@> Checking AtomGroup 5RS7: 1 chains are identified

In [7]: chains1
Out[7]: [<SimpleChain: Chain A from 5RVP with 467 residues>]

In [8]: chains2
Out[8]: [<SimpleChain: Chain A from 5RS7 with 372 residues>]
```

**Comment by jamesmkrieger** [comment]
Incidentally, this problem also exists in ProDy 2.0.1

**Comment by jamesmkrieger** [comment]
#1484 should fix this. I will merge it and make a new release soon. I have also almost finished parsing mmCIF "header" information, i.e. everything besides the ATOM/HETATM lines such as biomolecular assembly transformations and secondary structures and will release the two together.

**Comment by PatWalters** [comment]
Thanks for taking care of this so quickly

**Comment by jamesmkrieger** [comment]
You're very welcome

**Comment by SHZ66** [comment]
Would this work?
```
ref_prot = prody.parsePDB('5RS7')
ref_prot = ref_prot.select("chain A and protein")
prot = prody.parsePDB("5RVP").select("protein")
```

I thought the change we did with SimpleChain was that it made non-protein residues explicitly logged to prevent unexpected misalignment. The change does require users to explicitly select protein, which is a different behavior from the older versions, but alignment only works for protein (and nucleotides) anyway, so being explicit here may not be a bad thing. Note that superposition would still manipulate the entire AtomGroup, so when the proteins are superposed, the environment (water, ligand, etc.) are also rotated/translated at the same time.

**Comment by jamesmkrieger** [comment]
Yes, that is better practice. We probably have to update some tutorials etc. to reflect that.

However, it could be better to exclude water from the SimpleChain anyhow as a specific exception.

**Comment by SHZ66** [comment]
> Yes, that is better practice. We probably have to update some tutorials etc. to reflect that.
> 
> However, it could be better to exclude water from the SimpleChain anyhow as a specific exception.

Yeah, we should update the tutorial (I should probably go through the tutorials to make sure they reflect the change when I made it back then. Apologies for that!).

It can be very tricky to exclude water/solvent from SimpleChain though because the solvent molecules could have many different "residue" names. I don't think we can enumerate them all. But that is probably another reason for asking the users to pass the protein part they want to align so that they can exclude the water/solvent. This may be one of those cases where manual input is more efficient than automation.

**Comment by PatWalters** [comment]
Is it possible to align the proteins only (as above), get the translation rotation matrix, and apply that to the entire system (protein+solvent+ligand)

**Comment by jamesmkrieger** [comment]
Of course, in this case, you only have one chain anyway so it doesn't make any difference. If I had the following though, then it makes a difference:
```
In [1]: import prody

In [2]: ref_prot = prody.parseMMCIF("3h5v.cif").select("chain A B and protein")
@> 9392 atoms and 1 coordinate set(s) were parsed in 0.24s.
@> Secondary structures were assigned to 693 residues.

In [3]: prot = prody.parseMMCIF("3qel.cif").select("protein")
@> 10737 atoms and 1 coordinate set(s) were parsed in 0.27s.
@> Secondary structures were assigned to 904 residues.

In [4]: match = prody.alignChains(prot, ref_prot)
.
.
.
@> Identified that there exists 2 atommap(s) potentially.
@> At least 2 atommaps requested. Finding alternative solutions.
@> 2 atommaps were found in 0.02s. 2 requested

In [5]: mob_am = match[0]

In [6]: prody.superpose(mob_am, ref_prot, weights=mob_am.getFlags("mapped"))
Out[6]: 
(<AtomMap: (Chain C from 3qel -> Chain B from 3h5v) + (Chain D from 3qel -> Chain A from 3h5v) from 3qel (5992 atoms, 3259 mapped, 2733 dummy)>,
 <prody.measure.transform.Transformation at 0x7f9a8a9f9f40>)

In [7]: prody.calcRMSD(mob_am, ref_prot, weights=mob_am.getFlags("mapped"))
Out[7]: 11.026431229837483
```

Perhaps we could update matchAlign to have an option to use alignChains instead.

**Comment by SHZ66** [comment]
> Is it possible to align the proteins only (as above), get the translation rotation matrix, and apply that to the entire system (protein+solvent+ligand)

Yes, it is actually how the superposition works by default (default meaning if you don't make a copy of the protein instance when you select it from the system/atomgroup). Something like this should work:
```
from prody import *

ref_prot = prody.parsePDB('5RS7')
ref_prot = ref_prot.select("chain A and protein")
prot = prody.parsePDB("5RVP")
port = prot.select("protein")
res = '1SQ'
hv = prot.getHierView()
for chain in hv:
    if chain.select(f"resname {res}"):
        atommaps = prody.alignChains(chain, ref_prot)
        top_atommap = atommaps[0]
        torf_mapped = top_atommap.getFlags("mapped")
        prody.superpose(top_atommap, ref_prot, torf_mapped)
        break
```
This should superpose everything in `prot` onto `ref_prot` based on the residues that are aligned. I used `alignChains` here because it has access to some of the new alignment functions besides sequence alignment, but `matchAlign` should work similarly.

**Comment by jamesmkrieger** [comment]
So, we decided this is a feature not a bug and users just need to adapt accordingly. Issue closed
