### ISSUE TITLE
Error byte have no attritubute read 

### ISSUE THREAD

**Issue by obasekigit** [prody/ProDy#1496]
Anytime i try to parse an MSA file from Pfam i get the error Error byte have no attribute read. any help please
![Screenshot from 2022-03-11 19-42-52](https://user-images.githubusercontent.com/84424732/157996108-517b9d00-cb96-4764-89cf-5062475147a0.png)

**Comment by jamesmkrieger** [comment]
Thanks for reporting. This sounds like a Python 2 vs 3 problem. Should be fairly easy to fix

**Comment by obasekigit** [comment]
Given the latest version of prody can only work for python version 3.8 and greater i tried various method to overcome the problem but was not successful any help will be much appreciated

**Comment by jamesmkrieger** [comment]
That’s not true. ProDy still works with Python 2.7 and there may be parts that only work there

**Comment by jamesmkrieger** [comment]
We will need to look at the code and check

**Comment by obasekigit** [comment]
OK thanks

**Comment by jamesmkrieger** [comment]
Actually, that’s probably not the problem. This seems to be related to a more recent change.

**Comment by jamesmkrieger** [comment]
I've fixed it now and you should be able to access the change if you update your ProDy from github after the pull request is merged. This was related to a problem with url request libraries and pfam website security that I didn't quite fix properly before.

**Comment by obasekigit** [comment]
Thanks for your help is fixed now

**Comment by jamesmkrieger** [comment]
You’re very welcome
