### ISSUE TITLE
error in Evol tutorial

### ISSUE THREAD

**Issue by alexwu66666** [prody/ProDy#1512]
Hi there,

Thank you for the attention.
I met a trouble with the Evol tutorial when running:
>>> fetchPfamMSA('PF00074')
/home/wuchao/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'pfam.xfam.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wuchao/anaconda3/lib/python3.7/site-packages/prody/database/pfam.py", line 432, in fetchPfamMSA
    gunzip(response.read(), filepath)
AttributeError: 'bytes' object has no attribute 'read'

Could you provide any help on this?

Best regards,
Chao

**Comment by jamesmkrieger** [comment]
Hi Chao,

I've just fixed this recently (see #1496 and #1497). If you install the latest ProDy from Github then this error should be gone. 

Sorry it's not in a released version of ProDy yet. We are still organising some things before making the next one.

Best wishes
James

**Comment by alexwu66666** [comment]
Dear James,

Thank you for the reply.
Should I delete the old version installed by pip with other dependencies before install the new version from github?

Best regards,
Chao

**Comment by jamesmkrieger** [comment]
You may not need to. You can try using pip install -Ue . inside the directory you clone from GitHub. U is for upgrade and should uninstall any other version automatically, e is for development install so you can keep using that directory and update it yourself more easily, and the dot is for the current directory.

**Comment by jamesmkrieger** [comment]
If you want to be sure then you could do pip uninstall prody first

**Comment by jamesmkrieger** [comment]
You can also use pip list to check afterwards
