### ISSUE TITLE
Name 'ESSA' not defined

### ISSUE THREAD

**Issue by Shashankpant** [prody/ProDy#1537]
Hi All, 

I am getting an error while trying ESSA tutorial. Steps:

from prody import *
from numpy  import *
from pandas import *
ag = parsePDB('1FGY', compressed=False)
essa = ESSA()

Error : " name 'ESSA' is not defined"

Not sure about the origin of the error. Using: ProdDy 1.11

Thanks

**Comment by jamesmkrieger** [comment]
ESSA is in ProDy 2. Please update your prody.
