### ISSUE TITLE
Random seed for sampling conformations?

### ISSUE THREAD

**Issue by nickjf** [prody/ProDy#1559]
Hi,

I'm using ProDy to sample conformations following this example: http://prody.csb.pitt.edu/tutorials/conformational_sampling/sample.html

Is there a way to set a random seed so that the same conformations are generated from the same input?

Thanks very much!

Nick

**Comment by nickjf** [comment]
Hi James,

Thanks for the quick response. I'll give it a go.

Cheers,

Nick

**Comment by jamesmkrieger** [comment]
You’re welcome
