### ISSUE TITLE
Unable to edit flag definitions using flagDefinition() with FIX.

### ISSUE THREAD

**Issue by VonBoss** [prody/ProDy#1564]
### I can not edit flag definitions using the method from the ProDy tutorial. 
http://prody.csb.pitt.edu/manual/reference/atomic/flags.html#functions

For example, I have tried to add sulfate to the ion flag list like this:
    
<img width="221" alt="flagDefinition_example" src="https://user-images.githubusercontent.com/10247744/176243990-99b1c33c-86e1-426f-895c-ab696722cd75.PNG">

Each time the flag definitions have remained unchanged.
I have also tried to edit the nucleotide flag with no success.

It appears that flagDefinition() is not actually making changes to the DEFINITIONS dictionary. 

I have found a workaround by inserting `DEFINITIONS.update({key : val})` to line 1054 of prody/atomic/flag.py which updates the DEFINITIONS dictionary with the kwarg key and value. 

<img width="523" alt="flag_fix" src="https://user-images.githubusercontent.com/10247744/176244937-41015425-facf-4cd3-9ca5-3c768025376d.PNG">

So far, this fix is working for me with no apparent issues.

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. We'll look into it and add that change if we agree

**Comment by jamesmkrieger** [comment]
I don't think that's the problem. The line above should be using an editor to do this. Something else is presumably broken

**Comment by jamesmkrieger** [comment]
The editor is `changeResnames` in this case, which calls `changeDefinitions`, which in turn calls `updateDefinitions`, which is where the problem is. It had a key `flag_definitions` instead of `flags_definitions`. Now that I've fixed it, it works fine:

```
In [1]: from prody import *

In [2]: flagDefinition("nitrogen")
Out[2]: 'N.*'

In [3]: flagDefinition(nitrogen="N")

In [4]: flagDefinition("nitrogen")
Out[4]: 'N'

In [5]: ion_l = flagDefinition("ion")

In [6]: flagDefinition(ion=ion_l + ["SO4"])

In [7]: ion_l = flagDefinition("ion")

In [8]: ion_l
Out[8]:
['AL',
 'BA',
 'CA',
 'CAL',
 'CD',
 'CES',
 'CL',
 'CLA',
 'CO',
 'CS',
 'CU',
 'CU1',
 'CUA',
 'HG',
 'IN',
 'IOD',
 'K',
 'MG',
 'MN',
 'MN3',
 'NA',
 'PB',
 'POT',
 'PT',
 'RB',
 'SO4',
 'SOD',
 'TB',
 'TL',
 'WO4',
 'YB',
 'ZN',
 'ZN2']

In [9]: flagDefinition(reset="all")

In [10]: flagDefinition("ion")
Out[10]:
['AL',
 'BA',
 'CA',
 'CAL',
 'CD',
 'CES',
 'CL',
 'CLA',
 'CO',
 'CS',
 'CU',
 'CU1',
 'CUA',
 'HG',
 'IN',
 'IOD',
 'K',
 'MG',
 'MN',
 'MN3',
 'NA',
 'PB',
 'POT',
 'PT',
 'RB',
 'SOD',
 'TB',
 'TL',
 'WO4',
 'YB',
 'ZN',
 'ZN2']

In [11]: flagDefinition("nitrogen")
Out[11]: 'N.*'
```

**Comment by jamesmkrieger** [comment]
I will merge this as it passes the checks. Then you will be able to access the fix by installing prody from github. There will probably be a release over the next few days or possibly weeks.
