### ISSUE TITLE
MN is not in ion selection group

### ISSUE THREAD

**Issue by haotianteng** [prody/ProDy#1565]
Hi recently I was working with this PDB complex: 6mk0, and I found that  MN is not in the ion selection group (MN3 is in but MN is not).

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. 

It should now be fixed if you download ProDy from Github (see http://prody.csb.pitt.edu/manual/devel/develop.html).

**Comment by haotianteng** [comment]
Awesome!
