### ISSUE TITLE
missing _atom_site.pdbx_PDB_ins_code field causes errors for some mmCIF files

### ISSUE THREAD

**Issue by aozalevsky** [prody/ProDy#1568]
If `_atom_site.pdbx_PDB_ins_code` is missing, parsing fails because it is hardcoded:

https://github.com/prody/ProDy/blob/3b6a4f736eb4ebd5a909b74ac6cac1643564a954/prody/proteins/ciffile.py#L374

```python
/usr/local/lib/python3.8/dist-packages/prody/proteins/ciffile.py in _parseMMCIFLines(atomgroup, lines, model, chain, subset, altloc_torf, header)
    333 
    334         altlocs[acount] = alt
--> 335         icodes[acount] = line.split()[fields['pdbx_PDB_ins_code']]
    336 
    337         if icodes[acount] == '?':

KeyError: 'pdbx_PDB_ins_code'
```

The presence of this field is not required by the [PDBx/mmCIF dictionary](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Items/_atom_site.pdbx_PDB_ins_code.html) and it is missing in many structures, especially the ones from the [PDB-Dev](https://pdb-dev.wwpdb.org/). [PDBDEV_000000004](https://pdb-dev.wwpdb.org/entry.html?PDBDEV_00000004) can be used as a test case.

**Comment by jamesmkrieger** [comment]
Thanks for letting us know. It should be possible to fix this with a default null value and a try/except to fill it.

**Comment by aozalevsky** [comment]
@jamesmkrieger i've prepared a pull request #1569 with exactly the same approach in mind :)

**Comment by jamesmkrieger** [comment]
Yes, I saw it and approved it
