### ISSUE TITLE
Question about Pertubation Response Scanning

### ISSUE THREAD

**Issue by obasekigit** [prody/ProDy#1577]
I am using the PRS function of Prody but i have been struggling in writing out my data when i want to calculate the sensitivity of just a given residue not the overall sensitivity . the showPerturbresponse function just plots the graph but i want to write out the data.

**Comment by jamesmkrieger** [comment]
You can you writeArray for that. It should be a particular row or column of the PRS matrix. I think there should be something about that in the website or workshop tutorial.

There’s also something in there about writing these values in the b-factor column of a pdb file

**Comment by obasekigit** [comment]
Yea that is the sliceAtomicData , but when i do that, write the data and plot it. the plot is different from using the showPerturbresponse function

**Comment by obasekigit** [comment]
![Screenshot from 2022-08-04 00-18-32](https://user-images.githubusercontent.com/84424732/182762188-2f2d7782-dccc-426d-bdcf-9875c23904b9.png)
for example how do write out this kind of data

**Comment by jamesmkrieger** [comment]
What happens with axis=0? That should be the default for the plotting

**Comment by obasekigit** [comment]
Yea that for effectiveness but i am trying to write out the data of a sensitivity profile from selecting a specific residue

**Comment by jamesmkrieger** [comment]
I don’t understand. Why can’t you use sliceAtomicData with writeArray?

**Comment by jamesmkrieger** [comment]
sliceAtomicData should do the same thing. showPerturbResponse actually uses it

**Comment by jamesmkrieger** [comment]
I can try and have a better look on Friday when I’m back from the iGluR retreat

**Comment by obasekigit** [comment]
![Screenshot from 2022-08-04 00-41-40](https://user-images.githubusercontent.com/84424732/182764657-6b8edfef-3c3a-49b8-a25d-761b68049edd.png)
i tried using sliceAtomicData and write array then I read it and plotted the graph, and it was different from ShowPertubation response.
Thanks James

**Comment by jamesmkrieger** [comment]
Oh, this is because of the 1 on the diagonal. There’s a way of suppressing that, which is included in showPerturbResponse by default:

    suppress_diag = kwargs.pop('suppress_diag', True)
    if suppress_diag:
        prs_matrix = prs_matrix - np.eye(len(prs_matrix))

**Comment by jamesmkrieger** [comment]
you should be able to use that in calcPerturbResponse too but it is set to False by default. I think that was useful for some downstream calculations but I don’t really remember anymore

**Comment by jamesmkrieger** [comment]
I’d also recommend using prody showAtomicLines (aka pplot) instead of pyplot plot so you can include the residue numbers on the x-axis

**Comment by obasekigit** [comment]
> 

Thanks, i don't understand how i can use this with the calcPerturbResponse

**Comment by obasekigit** [comment]
> Oh, this is because of the 1 on the diagonal. There’s a way of suppressing that, which is included in showPerturbResponse by default:
> 
> ```
> suppress_diag = kwargs.pop('suppress_diag', True)
> if suppress_diag:
>     prs_matrix = prs_matrix - np.eye(len(prs_matrix))
> ```

Thanks, i don't understand how i can use this with the calcPerturbResponse

**Comment by obasekigit** [comment]
Thanks it worked.

**Comment by jamesmkrieger** [comment]
You’re welcome. Glad you figured it out
