### ISSUE TITLE
chain.select() not working on >2 characters chains

### ISSUE THREAD

**Issue by yannvm** [prody/ProDy#1597]
When using `.select()` to select a 3 or 4 characters chain on an AtomGroup, the result is always None, while parseMMCIF() works correctly.

#### Works as intended
```python
>>> chain = parseMMCIF("7kwc", chain="AAA")
@> WARNING Could not find _atom_site_anisotrop in lines.
@> WARNING No anisotropic B factors found
@> 3623 atoms and 1 coordinate set(s) were parsed in 0.19s.
``` 

#### Fails
```python
>>> prot = parseMMCIF("7kwc")
@> WARNING Could not find _atom_site_anisotrop in lines.
@> WARNING No anisotropic B factors found
@> 3623 atoms and 1 coordinate set(s) were parsed in 0.13s.
>>> chain = prot.select("chain AAA")
@> WARNING Selection string contains typo(s):
'chain AAA'
       ^ 'AAA' is longer than the maximum characters for data field 'chain'
>>> chain is None
True
``` 

The same issue is observed with 3 and 4 letter chains and multichain files (6zu5_SE0, 6n1d_AL04, ...).

ProDy version 2.2.0

**Comment by jamesmkrieger** [comment]
Apologies. There wasn't support for chains longer than 2 characters. How about extending it to 6?

**Comment by yannvm** [comment]
Until now, I've never seen chains longer than 4 char, but 6 char would be perfect! Thanks!

**Comment by jamesmkrieger** [comment]
good to know. Thanks

**Comment by jamesmkrieger** [comment]
This is now done and merged. You can now access the revised version by installing ProDy from Github
