### ISSUE TITLE
DNA Mutual Information 

### ISSUE THREAD

**Issue by cag1343** [prody/ProDy#1626]
Hi,

You tool is awesome and really easy to follow. My question is regarding the use of mutual information to model covariance, in this case I'm interested in using it for an RNA sequence. Is there any recomendation you would suggest i'm following Evolution Analysis vignette, or is the program only recomended for proteins? 

thank you

**Comment by jamesmkrieger** [comment]
Hi,
It should work for RNA too. Please give it a try and let us know what happens.
Thanks very much
