### ISSUE TITLE
writePDB doesn't include terminals after removing H

### ISSUE THREAD

**Issue by annadiarov** [prody/ProDy#1627]
Hi,

I was interested in removing H from a PDB containing a protein + ligand, so I did the following:
```python
from prody import parsePDB, writePDB
p = parsePDB(pdb_file)
noH = p.select('not hydrogen')
writePDB('test-noH.pdb', noH)
```
But I got a PDB without TER between ATOM and HETATM chain. Here I attach a PDB file in which TERs are not added and the expected output (both saved as txt because GitHub doesn't allow attaching PDB files).

Thank you!
[test-pdb.txt](https://github.com/prody/ProDy/files/10111622/test-pdb.txt)
[expected-output-pdb.txt](https://github.com/prody/ProDy/files/10111632/expected-output-pdb.txt)

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. Does it include TER files when you don’t remove hydrogens?

**Comment by jamesmkrieger** [comment]
Ok, I think we need to update pdbter flags when we make selections

**Comment by annadiarov** [comment]
Hi James,
It includes TER at the end of the chain A (protein) but it misses adding it at the end of the file (just after the HETATM block). I don't really know if it doesn't add the last TER because it's right after a HETATM block or because it's the end of the file. To solve this I just appended TER to the writePDB output.

**Comment by jamesmkrieger** [comment]
What does the original file look like? Is there usually a TER after HETATM blocks?

**Comment by annadiarov** [comment]
Here I attach the original file.
There is only a TER after HETATM blocks if the chain is different; if it's the same chain, then there isn't a TER (eg. https://files.rcsb.org/view/7FRT.pdb).
However, regardless the PDB ends with a HETATM block or an ATOM block, its last line should either be a TER, END, or TER\nEND. Checking the PDB, I found they usually finish with an END line (random example: https://files.rcsb.org/view/7U98.pdb)

[test-orig-pdb.txt](https://github.com/prody/ProDy/files/10112513/test-orig-pdb.txt)

**Comment by jamesmkrieger** [comment]
I've now made a pull request that I think should fix this. It adds a new flag for TER to selections in the last atom that still remains before the one that had it in the original AtomGroup.

Original file:
```
ATOM   4820  OXT VAL A 296     -48.489  19.198   6.313  1.00 29.27           O1-
ATOM   4821  H   VAL A 296     -46.302  17.752   5.706  1.00 29.27           H  
ATOM   4822  HA  VAL A 296     -45.676  19.796   7.833  1.00 29.27           H  
ATOM   4823  HB  VAL A 296     -46.194  21.471   6.188  1.00 29.27           H  
ATOM   4824 HG11 VAL A 296     -44.052  21.282   4.956  1.00 29.27           H  
ATOM   4825 HG12 VAL A 296     -43.831  20.751   6.613  1.00 29.27           H  
ATOM   4826 HG13 VAL A 296     -43.941  19.575   5.308  1.00 29.27           H  
ATOM   4827 HG21 VAL A 296     -46.114  20.624   3.720  1.00 29.27           H  
ATOM   4828 HG22 VAL A 296     -46.608  19.066   4.305  1.00 29.27           H  
ATOM   4829 HG23 VAL A 296     -47.625  20.506   4.527  1.00 29.27           H  
TER    4830      VAL A 296
HETATM 4831  C1  LIG L   1     -34.600  31.462   7.118  1.00 75.15           C  
HETATM 4832  C2  LIG L   1     -35.816  31.094   6.488  1.00 74.87           C 
``` 

New output
```
ATOM   4820  OXT VAL A 296     -48.489  19.198   6.313  1.00 29.27           O1-
TER
HETATM 4831  C1  LIG L   1     -34.600  31.462   7.118  1.00 75.15           C  
HETATM 4832  C2  LIG L   1     -35.816  31.094   6.488  1.00 74.87           C 
```

**Comment by jamesmkrieger** [comment]
You’re welcome

something doesn’t quite work still so I’ll have a look into it more
