### ISSUE TITLE
Question about Coevolution Analysis

### ISSUE THREAD

**Issue by obasekigit** [prody/ProDy#1631]
Good day all, i have a question about carrying out co-evolution analysis of a protein. take for example i have two proteins A & B combined into a single protein and i got their individual MSA and merged them together. how will i refined the merged MSA given i have two different MSA merged into one

**Comment by jamesmkrieger** [comment]
This is a very interesting question and you’d just have to try and see. I imagine you’d refine it in a similar kind of way

**Comment by obasekigit** [comment]
Yeah i tried to refine it similarly as found in the tutorial but the problem is that, the label key word can only accept one argument not two so i  always get an error . i really don't know how to bypass that

**Comment by jamesmkrieger** [comment]
How do you have two labels? What is the file format?

**Comment by obasekigit** [comment]
![MSA](https://user-images.githubusercontent.com/84424732/209375706-0ef49dee-c17f-49d8-b1d9-1fa040a2c1db.png)
i combined two MSA together i am interested in both  HTPG_ECOLI in one and  DNAK_ECOLI in the other. how do i refine them together?

**Comment by jamesmkrieger** [comment]
mergeMSA should merge sequences from the same protein and wouldn’t be useful for that. What you need to do is manually merge them and make merged labels

**Comment by obasekigit** [comment]
How do you merge them manually? i tried refining each proteins individually and then merged them but when i calculated the entropy the values were all negligible i.e 0

**Comment by jamesmkrieger** [comment]
By manually, I meant actually manually: lots of copying and pasting or perhaps some long and detailed code that does the same thing.

You could probably try giving all your sequences hybrid labels (e.g. HTPG_DNAK_ECOLI for both of those two) and then using mergeMSA though.

Good luck

**Comment by jamesmkrieger** [comment]
I hadn’t even heard of mergeMSA before today so I don’t know the details. It sounds like it’s for merging alignments for different parts of a protein belonging to different Pfam families so maybe you should try basing things on that and having labels with residue numbers. I can try and look into the code at some point over the next week or so if you need me to figure it out better

**Comment by obasekigit** [comment]
> 

Thanks for the help that will be nice. will try out your suggestions though

**Comment by jamesmkrieger** [comment]
any luck?

**Comment by jamesmkrieger** [comment]
perhaps, I can make a new function to do this

**Comment by obasekigit** [comment]
Thanks James for getting back to me sorry for the late reply. i tried to combine all the sequence of my protein complex to calculate the co-evolution analysis but it didn't work. i will appreciate if you can create a function for that

**Comment by jamesmkrieger** [comment]
I gave mergeMSA and new kwarg option so that now you can use it as you wished. It is described in the pull request

**Comment by obasekigit** [comment]
Thanks which version of ProDy will this work for?

**Comment by jamesmkrieger** [comment]
At the moment you’d have to check out my specific branch related to that. I’ll probably merge it into the master tomorrow. so, either way a GitHub install.

at some point soon I’ll try and make 2.3.2 or 2.4.0 and then it’ll be part of that

**Comment by jamesmkrieger** [comment]
ok. This is now merged. Here are the instructions for installing from github: http://prody.csb.pitt.edu/manual/devel/develop.html
