### ISSUE TITLE
Error when installing the v2.3.1

### ISSUE THREAD

**Issue by SianXiaoCHN** [prody/ProDy#1639]
I've been using ProDy v2.3.0 for long, today when I try to install v2.3.1 in a new and empty environment as follwing:
```
conda create -n prody_test
conda activate prody_test
pip install prody
```
Then the following error prompts:
```
Collecting prody
  Using cached ProDy-2.3.1.tar.gz (12.8 MB)
ERROR: Files/directories not found in /tmp/pip-install-hz8ji5kb/prody/pip-egg-info
```

**Comment by jamesmkrieger** [comment]
Which operating system are you using?

**Comment by jamesmkrieger** [comment]
It could perhaps be the pyproject.toml that's missing in 2.3.1 that's causing this problem. It instructs the system how to make the egg-info I think.

I'll be making another release soon that should have it back as well as some more fixes and improvements

**Comment by jamesmkrieger** [comment]
ok. Thanks

**Comment by aspitaleri** [comment]
Hi
similar error on my Mac OS M1 Max Ventura:
Collecting prody
  Downloading ProDy-2.3.1.tar.gz (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 14.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in /private/var/folders/7x/w3ltqpbn3y7ckg8hf7szp1600000gq/T/pip-pip-egg-info-mtpwxnso

I have tried also export ARCHFLAGS="-arch x86_64" but it did not work.

**Comment by jamesmkrieger** [comment]
please just use ProDy 2.3.0 for now, everyone

I'll let you know when I have a version where this is fixed

**Comment by aspitaleri** [comment]
Unfortunately did not work on Mac. Other error:

....
  In file included from Bio/Align/_aligners.c:11:
            /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:10: fatal error: 'stdio.h' file not found
            #include <stdio.h>
                     ^~~~~~~~~
            1 error generated.
            error: command '/opt/homebrew/opt/llvm@13/bin/clang' failed with exit code 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      × Encountered error while trying to install package.
      ╰─> biopython

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

probably this is due to the M1 architecture.

**Comment by jamesmkrieger** [comment]
It may also be a problem with biopython. Can you try installing biopython first please and going back versions until you find one that works? ProDy should then be able to use whichever biopython you install.

**Comment by jamesmkrieger** [comment]
please try again with prody 2.4.0 that I just realised

**Comment by SianXiaoCHN** [comment]
> please try again with prody 2.4.0 that I just released

It works!

**Comment by jamesmkrieger** [comment]
Great! Issue closed
