### ISSUE TITLE
matchChains does not work

### ISSUE THREAD

**Issue by sobhanAhmadian** [prody/ProDy#1653]
I implemented precisely the same document code and got a None from the matchChains function. In addition, I've got an error that pairwise2 does not exist.

`
bound = parsePDB('1vrt');
unbound = parsePDB('1dlo');
matches = matchChains(bound, unbound);
`

**Comment by sobhanAhmadian** [comment]
@> WARNING no one-letter mapping found for <Residue: MG 1000 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: MG 1000 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: NVP 999 from Chain A from 1vrt (20 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: NVP 999 from Chain A from 1vrt (20 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1002 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1002 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1010 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1010 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1013 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1013 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1014 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1014 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1015 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1015 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1016 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1016 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1017 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1017 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1018 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1018 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1019 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1019 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1020 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1020 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1021 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1021 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1022 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1022 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1023 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1023 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1024 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1024 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1025 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1025 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1026 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1026 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1027 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1027 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1028 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1028 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1029 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1029 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1030 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1030 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1031 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1031 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1032 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1032 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1033 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1033 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1034 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1034 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1035 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1035 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1036 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1036 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1037 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1037 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1038 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1038 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1039 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1039 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1040 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1040 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1041 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1041 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1042 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1042 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1043 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1043 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1044 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1044 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1045 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1045 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1046 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1046 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1047 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1047 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1048 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1048 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1049 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1049 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1050 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1050 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1051 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1051 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1052 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1052 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1053 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1053 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1054 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1054 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1055 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1055 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1056 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1056 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1057 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1057 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1058 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1058 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1059 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1059 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1060 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1060 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1061 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1061 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1062 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1062 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1063 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1063 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1064 from Chain A from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1064 from Chain A from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1162 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1162 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1163 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1163 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1164 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1164 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1165 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1165 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1201 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1201 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1202 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1202 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1203 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1203 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1204 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1204 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1205 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1205 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1206 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1206 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1207 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1207 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1208 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1208 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1209 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1209 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1210 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1210 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1211 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1211 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1212 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1212 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1213 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1272 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1272 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1273 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1273 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1274 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1274 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1275 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1275 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1276 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1276 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1277 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1277 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1278 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1278 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1279 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1279 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1280 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1280 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1281 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1281 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1282 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1282 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1283 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1283 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1284 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1284 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1285 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1285 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1286 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1286 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1287 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1287 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1288 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1288 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1289 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1289 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1290 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1290 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1291 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1291 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1292 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1292 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1293 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1293 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1294 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1294 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1295 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1295 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1296 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1296 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1297 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1297 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1298 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1298 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1299 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1299 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1300 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1300 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1301 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1301 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1302 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1302 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1303 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1303 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1304 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1304 from Chain B from 1vrt (1 atoms)> 
@> WARNING no one-letter mapping found for <Residue: HOH 1305 from Chain B from 1vrt (1 atoms)> 
WARNING:.prody:WARNING no one-letter mapping found for <Residue: HOH 1305 from Chain B from 1vrt (1 atoms)> 
@> Checking AtomGroup 1vrt: 2 chains are identified
DEBUG:.prody:Checking AtomGroup 1vrt: 2 chains are identified
@> Checking AtomGroup 1dlo: 2 chains are identified
DEBUG:.prody:Checking AtomGroup 1dlo: 2 chains are identified
@> Trying to match chains based on residue numbers and names:
DEBUG:.prody:Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 1vrt (len=688) and Chain A from 1dlo (len=556):
DEBUG:.prody:  Comparing Chain A from 1vrt (len=688) and Chain A from 1dlo (len=556):
@> 	Failed to match chains (seqid=93%, overlap=76%).
DEBUG:.prody:	Failed to match chains (seqid=93%, overlap=76%).
@>   Comparing Chain A from 1vrt (len=688) and Chain B from 1dlo (len=415):
DEBUG:.prody:  Comparing Chain A from 1vrt (len=688) and Chain B from 1dlo (len=415):
@> 	Failed to match chains (seqid=99%, overlap=60%).
DEBUG:.prody:	Failed to match chains (seqid=99%, overlap=60%).
@>   Comparing Chain B from 1vrt (len=545) and Chain A from 1dlo (len=556):
DEBUG:.prody:  Comparing Chain B from 1vrt (len=545) and Chain A from 1dlo (len=556):
@> 	Failed to match chains (seqid=73%, overlap=72%).
DEBUG:.prody:	Failed to match chains (seqid=73%, overlap=72%).
@>   Comparing Chain B from 1vrt (len=545) and Chain B from 1dlo (len=415):
DEBUG:.prody:  Comparing Chain B from 1vrt (len=545) and Chain B from 1dlo (len=415):
@> 	Failed to match chains (seqid=96%, overlap=73%).
DEBUG:.prody:	Failed to match chains (seqid=96%, overlap=73%).
---------------------------------------------------------------------------
`
NameError                                 Traceback (most recent call last)
[<ipython-input-23-d37f1c84d746>](https://localhost:8080/#) in <module>
----> 1 matches = matchChains(bound, unbound)

[/usr/local/lib/python3.8/dist-packages/prody/proteins/compare.py](https://localhost:8080/#) in matchChains(atoms1, atoms2, **kwargs)
    649 
    650     if pwalign or (not matches and (pwalign is None or pwalign)):
--> 651         if pairwise2:
    652             if unmatched:
    653                 LOGGER.debug('Trying to match chains based on {0} sequence '

NameError: name 'pairwise2' is not defined
`

**Comment by jamesmkrieger** [comment]
I think there are a few different problems here.

1. for missing pairwise2, Are you using prody 2.4.0? I changed some things because biopython is removing pairwise2 and it’s possible I missed something

2. you have lots of non-protein atoms and these functions aren’t supposed to work then

3. The failed to match problem is not really a problem at all. You just need to change the seqid and overlap criteria

I’ll have a look more late next week probably

**Comment by jamesmkrieger** [comment]
1. the problem with pairwise2 may well have come up in a recent version and I now have a fix for it.

2. these are just warnings, but having the non-protein residues reduces the overlap so the trivial mapping is not sufficient and this gives rise to the other two problems. I think there was a change made fairly recently that gave rise to this behaviour too.

The way that the code should now be run is the following:
```
In [2]: bound = parsePDB("1vrt")
   ...: unbound = parsePDB("1dlo")
   ...: matches = matchChains(bound.protein, unbound.protein)
@> Connecting wwPDB FTP server RCSB PDB (USA).
@> 1vrt downloaded (1vrt.pdb.gz)
@> PDB download via FTP completed (1 downloaded, 0 failed).
@> 7953 atoms and 1 coordinate set(s) were parsed in 0.14s.
@> Secondary structures were assigned to 492 residues.
@> Connecting wwPDB FTP server RCSB PDB (USA).
@> 1dlo downloaded (1dlo.pdb.gz)
@> PDB download via FTP completed (1 downloaded, 0 failed).
@> 7691 atoms and 1 coordinate set(s) were parsed in 0.13s.
@> Secondary structures were assigned to 481 residues.
@> Checking AtomGroup 1vrt: 2 chains are identified
@> Checking AtomGroup 1dlo: 2 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 1vrt (len=524) and Chain A from 1dlo (len=556):
@>      Match: 524 residues match with 99% sequence identity and 94% overlap.
@>   Comparing Chain A from 1vrt (len=524) and Chain B from 1dlo (len=415):
@>      Failed to match chains (seqid=99%, overlap=78%).
@>   Comparing Chain B from 1vrt (len=401) and Chain A from 1dlo (len=556):
@>      Failed to match chains (seqid=100%, overlap=72%).
@>   Comparing Chain B from 1vrt (len=401) and Chain B from 1dlo (len=415):
@>      Match: 400 residues match with 99% sequence identity and 96% overlap.
```

**Comment by sjrothfuss** [comment]
Thanks for your help with this problem, @jamesmkrieger. Your code works for me. The [Structure Comparison tutorial](http://prody.csb.pitt.edu/tutorials/structure_analysis/compare.html) online instructs to run `matchChains(bound, unbound)` without the `.protein` attributes you used and running that gives me the same issue as @sobhanAhmadian. Can you update that tutorial?

**Comment by jamesmkrieger** [comment]
I am in touch with the lab about updating the website so, yes, I'll include this when we do.

**Comment by mkouzmin** [comment]
Local alignment mapping no longer seems to work. Could you update the site to reflect this change?

**Comment by jamesmkrieger** [comment]
It should work. I’d definitely rather fix it than update the website, and not just because that would be easier

**Comment by jamesmkrieger** [comment]
I’d also say that’s not true. It definitely works in some cases 

I’ll reopen the issue anyhow
