### ISSUE TITLE
About Rankordering in Evol 

### ISSUE THREAD

**Issue by kalyanraj95** [prody/ProDy#1664]
Hi,

I am using Evol to aid my analysis of the protein system I am currently working on. Using rankorder from Evol from command line, I have gotten few pairs with the highest MI. I do not know how to relate them back to a consensus sequence and residues. I have tried following the tutorial on ProDy website but it does not really go into much depth after rank ordering. Could you shed some light on how to follow the analysis or contact someone?

Thank you.

Sincerely,
Abhishek
<img width="532" alt="Rankorder" src="https://user-images.githubusercontent.com/125503811/219163144-0641d36f-4544-4eea-a5ed-953b44bef6cd.png">

**Comment by jamesmkrieger** [comment]
These should be the columns in the refined MSA. If you open that MSA in a viewer such as Unipro UGENE then you can scroll to those positions and see what’s there. 

If you used a pdb structure for the refinement you can also relate it back to that and look in a structure viewer such as PyMOL

**Comment by kalyanraj95** [comment]
Hi,

Thank you so much for the response. I see rows and columns in the rank order where the rows I believe are the sequences in MSA and columns residues of the protein in MSA. If I am looking at pairs with highest MI, then shouldn't they be two columns (corresponding to two residues) unless I am understanding it completely wrong. What does row exactly mean in the rank order of MI that Evol calculates? 

Thank you.

**Comment by jamesmkrieger** [comment]
They are rows and columns of the MI matrix, so yes, they correspond to pairs of columns of the MSA.

**Comment by kalyanraj95** [comment]
Hi,

This was incredibly helpful. 

Thank you so much.

**Comment by jamesmkrieger** [comment]
You’re welcome
