### ISSUE TITLE
PDB output interferences

### ISSUE THREAD

**Issue by davidoskky** [prody/ProDy#1665]
Hello,
I was trying to align the structures of two chains of a protein and noticed some severe inconsistencies.
The PDB coordinate system appears to change every time you perform an operation. For example, matchAlign seems to move the target coordinates.

I would expect that calling any function, such as matchAlign or select would not change the objects it is given as parameters. Moreover, this makes even less sense because the output structure is aligned with the original object and not with the one obtained right after.

Check how the output changes by changing where in the code the PDB file is written even though the variable chain_b is never directly changed.

```
pdb = parsePDB("1j4r")
chain_b = pdb.select('chain B')
writePDB("reference.pdb", chain_b)
chain_d = pdb.select('chain D')
aligned = matchAlign(chain_d, chain_b)[0]
writePDB("aligned.pdb", aligned)
```
![1](https://user-images.githubusercontent.com/13107368/220370714-76bf9f5e-e65d-42cb-a8bf-c7aef2924193.png)

```
pdb = parsePDB("1j4r")
chain_b = pdb.select('chain B')
chain_d = pdb.select('chain D')
aligned = matchAlign(chain_d, chain_b)[0]
writePDB("reference.pdb", chain_b)
writePDB("aligned.pdb", aligned)
```
![3](https://user-images.githubusercontent.com/13107368/220370879-447f3b07-4f47-4a5e-a0fd-c07a9d069b7c.png)

This is even more obvious if we discard chain D altogether and save chain B twice:

```
pdb = parsePDB("1j4r")
chain_b = pdb.select('chain B')
writePDB("reference.pdb", chain_b)
chain_d = pdb.select('chain D')
aligned = matchAlign(chain_d, chain_b)[0]
writePDB("aligned.pdb", chain_b)
```
![4 pdb](https://user-images.githubusercontent.com/13107368/220372115-f3eaaadc-db03-4daa-a6b9-1448a43da667.png)

**Comment by jamesmkrieger** [comment]
I know this is surprising and not behaving the way you'd expect, but this is the general way that ProDy behaves. Selection objects point back to the original AtomGroup objects and do not have any data of their own. If you apply matchAlign or any other transformation to a selection then the whole AtomGroup experiences that transformation. 

If you want to only move some particular region then you should use the `.copy()` method to get a new AtomGroup object:

```
In [3]: pdb = parsePDB("1j4r")
   ...: chain_b = pdb.select('chain B')
   ...: chain_d = pdb.select('chain D').copy()
   ...: aligned = matchAlign(chain_d, chain_b)[0]
   ...: writePDB("reference.pdb", chain_b)
   ...: writePDB("aligned.pdb", aligned)
```
![with_copy](https://user-images.githubusercontent.com/13259162/220377691-eb3d289c-17c2-4d0f-b81c-54d176a9aff4.png)
