### ISSUE TITLE
Division by zero when aligning structures

### ISSUE THREAD

**Issue by davidoskky** [prody/ProDy#1666]
There some problem in the RMSD calculations called when aligning two protein structures read from a CIF file as in some cases a division by 0 error is raised.
It is strange because it works correctly with the PDB file but fails when parsing an mmCIF file.

This works flawlessly
```
structure = parsePDB("2jfz")
chain_a = structure.select('chain A').copy()
chain_b = structure.select('chain B').copy()
aligned = matchAlign(chain_b, chain_a)
```

This fails
```
structure = parseMMCIF("2jfz.cif")
chain_a = structure.select('chain A').copy()
chain_b = structure.select('chain B').copy()
aligned = matchAlign(chain_b, chain_a)
```

Here is the error log:

<details>

```
File ~/.conda/envs/prolif/lib/python3.11/site-packages/prody/proteins/compare.py:507, in matchAlign(mobile, target, **kwargs)
    503     csets = [mobile.getACSIndex()]
    505 LOGGER.info('Alignment is based on {0} atoms matching {1}.'
    506             .format(n_atoms, repr(selstr)))
--> 507 printRMSD(tar._getCoords()[which], mob._getCoordsets()[:, which],
    508           msg='Before alignment ')
    509 for acsi in csets:
    510     mob.setACSIndex(acsi)

File ~/.conda/envs/prolif/lib/python3.11/site-packages/prody/measure/transform.py:452, in printRMSD(reference, target, weights, log, msg)
    450 if msg and msg[-1] != ' ':
    451     msg += ' '
--> 452 rmsd = calcRMSD(reference, target, weights)
    453 if isinstance(rmsd, np.ndarray) and len(rmsd) > 1:
    454     write(msg + 'RMSD: min={0:.2f}, max={1:.2f}, mean={2:.2f}'
    455                 .format(rmsd.min(), rmsd.max(), rmsd.mean()))

File ~/.conda/envs/prolif/lib/python3.11/site-packages/prody/measure/transform.py:408, in calcRMSD(reference, target, weights)
    406     n_csets = 1 if tar.ndim == 2 else len(tar)
    407     weights = checkWeights(weights, n_atoms, n_csets)
--> 408 return getRMSD(ref, tar, weights)

File ~/.conda/envs/prolif/lib/python3.11/site-packages/prody/measure/transform.py:413, in getRMSD(ref, tar, weights)
    411 def getRMSD(ref, tar, weights=None):
    412     if weights is None:
--> 413         divByN = 1.0 / ref.shape[0]
    414         if tar.ndim == 2:
    415             return np.sqrt(((ref-tar) ** 2).sum() * divByN)

ZeroDivisionError: float division by zero
```

</details>

**Comment by jamesmkrieger** [comment]
The problem seems to be something to do with how the chains are labelled in the mmCIF file.
```
list(structure.getHierView())
Out[4]: 
[<Chain: A from Segment A from 2jfz (255 residues, 2012 atoms)>,
 <Chain: B from Segment B from 2jfz (249 residues, 1959 atoms)>,
 <Chain: A from Segment C from 2jfz (1 residues, 33 atoms)>,
 <Chain: A from Segment D from 2jfz (1 residues, 10 atoms)>,
 <Chain: B from Segment E from 2jfz (1 residues, 33 atoms)>,
 <Chain: B from Segment F from 2jfz (1 residues, 10 atoms)>,
 <Chain: A from Segment G from 2jfz (228 residues, 228 atoms)>,
 <Chain: B from Segment H from 2jfz (222 residues, 222 atoms)>]
```

There are several chains A and B with different segments and some of them have no protein in them.

The way to get around this is to specifically ask it to select the protein:
```
structure2 = parseMMCIF("2jfz")
    ...: chain_a = structure2.select("protein and chain A").copy()
    ...: chain_b = structure2.select("protein and chain B").copy()
    ...: aligned = matchAlign(chain_b, chain_a)
```

I will also try and make some check for non-protein chains so it can skip them.

**Comment by davidoskky** [comment]
The CIF file appears correctly redacted to me.
The `_atom_site.label_asym_id` progresses and is different for each of the entities, the `_atom_site.auth_asym_id` assigns the same chain id to all the entities that are related spatially.
Also the PDB file assigns the heteroatoms to chains A and B, however it appends a numeric id to distinguish molecules.

I do want the alignment to be performed on the whole chain, not only on the protein part. Thus, selecting just the protein would not work out for me.

This is possible in the PDB file, the alignment works flawlessly and it also moves the heteroatoms.
```
structure = parsePDB("2jfz")
chain_a = structure.select('chain A').copy()
chain_b = structure.select('chain B').copy()
aligned = matchAlign(chain_b, chain_a)
print("Non protein residues in chain A: " + str(len(chain_a.select('not protein'))))
print("Non protein residues in the aligned chain B: " + str(len(aligned[0].select('not protein'))))
```

Which returns

```
Non protein residues in chain A: 271
Non protein residues in the aligned chain B: 266
```

**Comment by jamesmkrieger** [comment]
I can see a few options here:

1. Copy the whole chain to a new AtomGroup and use a protein selection for the alignment:
```
In [2]: structure = parsePDB("2jfz")
   ...: chain_a = structure.select("chain A").copy()
   ...: chain_b = structure.select("chain B").copy()
   ...: aligned = matchAlign(chain_b.protein, chain_a.protein)
```

2. Do the match and superpose separately then the Translation object is returned and you can use it.
```
In [6]: structure2 = parseMMCIF("2jfz")
   ...: chain_a = structure2.select("protein and chain A").copy()
   ...: chain_b = structure2.select("protein and chain B").copy()
   ...: amap_b, amap_a, seqid, overlap = matchChains(chain_b, chain_a)[0]

In [7]: amap_b, T = superpose(amap_b, amap_a)

In [8]: chain_a = structure2.select("chain A").copy()
   ...: chain_b = structure2.select("chain B").copy()
   ...: aligned = applyTransformation(T, chain_b)
```

3. relabel the chains to have the same segment name so that ProDy can include them together:
```
In [2]: structure = parsePDB("2jfz")
   ...: chain_a = structure.select("chain A").copy()
   ...: chain_b = structure.select("chain B").copy()

In [3]: chain_a.setSegnames("A")

In [4]: chain_b.setSegnames("B")

In [5]: aligned = matchAlign(chain_b, chain_a)
```
 
Perhaps, we could have an option for parseMMCIF to do option 3 automatically.

For now, I'd say the best and easiest option is probably number 1.

**Comment by davidoskky** [comment]
I see, indeed the first option appears to be the easiest. I'll try to proceed in this way.
Thanks!

**Comment by jamesmkrieger** [comment]
You're welcome. 

What do you think of having an option in parseMMCIF saying something like unite_segments for option 3? That would make the parsed AtomGroup the same as the one from the PDB file.

**Comment by davidoskky** [comment]
I do like the idea, that would indeed make it much easier to work with and records would behave as I would expect by having all the atoms in the same chain joined together.
It is something that for example gemmi does by default and that can be optionally disabled (https://project-gemmi.github.io/python-api/index.html#read_structure)

**Comment by jamesmkrieger** [comment]
ok. I'd probably do it the other way round, just because ProDy doesn't do it so far and users may not expect it

**Comment by jamesmkrieger** [comment]
This is now merged into the prody master branch, so you can access it if you install prody from github.

We probably still need a more general fix for the problem though, so I'll keep the issue open

**Comment by jamesmkrieger** [comment]
Actually, I think this issue is solved by giving these suggestions and having this feature.

**Comment by jamesmkrieger** [comment]
Actually, I think I've just found something weird with chain vs segment and label_asym_id vs auth_asym_id, so I guess this is still an open issue.

**Comment by jamesmkrieger** [comment]
> I do like the idea, that would indeed make it much easier to work with and records would behave as I would expect by having all the atoms in the same chain joined together. It is something that for example gemmi does by default and that can be optionally disabled (https://project-gemmi.github.io/python-api/index.html#read_structure)

Actually, I agree. It doesn't make sense to split away glycans and waters into separate chains most of the time.

**Comment by jamesmkrieger** [comment]
> ok. I'd probably do it the other way round, just because ProDy doesn't do it so far and users may not expect it

I imagine mmcif is so new that users don't really have any expectations from experience anyway
