### ISSUE TITLE
What are the possible arguments for getCoords?

### ISSUE THREAD

**Issue by cgseitz** [prody/ProDy#1671]
Hello,

I want to test out some models with different atom selections. When creating ANMs, I have been creating them like this:
```
anm = ANM('Phage')
anm.buildHessian(calphas)
anm.calcModes(n_modes=10, zeros=False, turbo=True)
coords = getCoords(calphas)
```
To build the Hessian, I need to choose some object with the ```getCoords``` method. What are the other possible atom selections apart from ```calphas```? The error message from choosing an undefined selection, or choosing no selection, does not specify what options I have. Similarly, I cannot readily find in the documentation what other selections are available.

Best,
Christian

**Comment by jamesmkrieger** [comment]
Hi Christian,

Nice to hear from you.

The point is that it is flexible. Indeed, any ProDy object with a getCoords (or _getCoords) method is usable and coords themselves as Numpy arrays are too. These include all Atomic objects (AtomGroup, Selection, AtomMap, etc.) and Ensemble objects (including PDBEnsemble), Trajectory objects if they have reference coordinates set.

This means that the method belongs to your object like the following
```
ag = parsePDB("7oca")
coords = ag.getCoords()
```

You can use the getCoords function as you did to try that too and there's also one called checkCoords if you want to use that.

In terms of selections, any should be valid. The ANM is, by no means, limited to calphas. The original version by Monique Tirion used all atoms with a cutoff of 8 A (the two vdW radii plus a bit). It has also been applied to backbone atoms of nucleic acids e.g. `nucleic and name P C4' C2` and could also be used for proteins and nucleic acids together. There is also room to apply it to more coarse grained sets such as every 10th calpha or some pseudoatoms fitted to a density map e.g. with TRN.

I'll also extend the documentation as I spotted indeed that this isn't clear.

Best wishes
James

**Comment by cgseitz** [comment]
Hi James,

Fantastic, thanks for your detailed answer! This answers my question and I was able to finish the models I wanted to finish (and because you gave such a detailed answer I was able to realize why one other puzzling thing was happening in my models and correct it). Hope all is well with you!

Best,
Christian

**Comment by jamesmkrieger** [comment]
I’m glad to hear! Yes, all is well with me
