### ISSUE TITLE
Unable to build wheel when installing.

### ISSUE THREAD

**Issue by SciKidSirish** [prody/ProDy#1673]
Hello, I am trying to install this using pip, and I get a similar error, ending with:
```
ERROR: Could not build wheels for prody, which is required to install pyproject.toml-based projects
```
I am using python 3.11.2. Is the version I'm using the issue? I have pip 23.0.1. I am using Windows 11.
Here's some background:
ProDy is a dependency for a protein-protein docking software (lightdock) I'm trying to install.

**Comment by jamesmkrieger** [comment]
Please try python 3.10 or 3.9 instead. ProDy doesn't yet work completely with Python 3.11 and there isn't a windows wheel for that.
