### ISSUE TITLE
Prody website is not working

### ISSUE THREAD

**Issue by Nandineeprody** [prody/ProDy#1674]
Hello,
I have been facing issue regarding the opening of following url:
prody.csb.pitt.edu/tutorials.

Can you please help me with this.

Thanks
Nandinee

**Comment by jamesmkrieger** [comment]
Can you describe the problem a bit better please? It seems to be working for me although it is a bit slow to load all the icons.

Best wishes
James

**Comment by jamesmkrieger** [comment]
This problem seems fixed to me. Please confirm
