### ISSUE TITLE
Following the example for performing calculations on heterogeneous X-ray structures 

### ISSUE THREAD

**Issue by nickjf** [prody/ProDy#1683]
Hi!

I'm trying to follow the example for performing calculations on heterogeneous X-ray structures (http://prody.csb.pitt.edu/tutorials/ensemble_analysis/xray_calculations.html#anm-calculations). I'm just trying to reproduce what is in the example before using my own data. 

I get to the ensemble preparation stage but the code just hangs and eventually timeouts. Here is an example of the output:

@> 76 PDBs were parsed in 0.55s.
@> Mapping 1LEW_ca to the reference... [ 11%] 2sERROR: Best RMSD found was 1e6.  Broken.
@> WARNING cealign could not align <SimpleChain: Chain A from 1P38_ca with 351 residues> and <SimpleChain: Chain B from 1LEW_ca with 10 residues>
@> Mapping 1LEZ_ca to the reference... [ 13%] 2sERROR: Best RMSD found was 1e6.  Broken.
@> WARNING cealign could not align <SimpleChain: Chain A from 1P38_ca with 351 residues> and <SimpleChain: Chain B from 1LEZ_ca with 8 residues>
@> Mapping 2OZA_ca to the reference... [ 69%] 1s

I'd really appreciate any advice you might have. Please let me know if you need any more info.

best wishes,

Nick

**Comment by nickjf** [comment]
Ah! I just tried removing PDBs to see if a particular structure was causing the issue. 

It seems to be the case as I removed 2OZA and 2ONL and now things seem to be working fine.

**Comment by jamesmkrieger** [comment]
Ok, thanks
