### ISSUE TITLE
Fetch protein files from PDB with report as optional

### ISSUE THREAD

**Issue by AlejandroSanchezCano** [prody/ProDy#1694]
Hello, devs, have been using `prody.fetchPDB`:
```
prody.fetchPDB(
    '5nlt',
    folder = 'PDB files', 
    compressed = False,
    report = False
    ) 
```
In the console is printed the following (because I had already downloaded it):
`@> PDB file is found in working directory (PDB files\5nlt.pdb).`

My suggestion would be to have the option to control whether I would like the report to show in the console or not. I saw in the source code of the function `prody.fetchPDB` something along these lines `if kwargs.get('report', True):`, but when I used this report argument as I show, the verbosity is not controlled. Therefore, I do not know if this is a bug or a suggestion.

**Comment by jamesmkrieger** [comment]
I don’t see that option in the current prody code and don’t remember ever coming across it in all my 10-11 years of using prody. Where did you see it?

what we usually do is use confProDy(verbosity=“none”)

**Comment by jamesmkrieger** [comment]
Maybe you're thinking about this section of the website tutorials where the logger output is referred to as a report?
http://prody.csb.pitt.edu/tutorials/structure_analysis/pdbfiles.html?highlight=report#multiple-files

Anyhow, confProDy(verbosity='none') works and there has been no reply so issue closed. Please feel free to reopen
