### ISSUE TITLE
Meaning of negative Z scores in ESSA

### ISSUE THREAD

**Issue by jlefebre** [prody/ProDy#1696]
Hi, 

the ESSA method frequently produces negative Z-scores. I understand what that means from a statistical point of view. However, what does it mean from a biological point of view? Do residues with a negative Z-score get more rigid, i.e. they reduce global dynamics upon ligation? 

Best, 
Jonathan

**Comment by jamesmkrieger** [comment]
I’d imagine so. @kaynakb?

**Comment by kaynakb** [comment]
Dear Jonathan,

It is important to read the original article of a method to understand the idea behind it. Please see the link for our method ESSA: https://www.sciencedirect.com/science/article/pii/S2001037020303093?via%3Dihub.

A residue with a negative ESSA score, which is provided as a z-score in ESSA, means that it exerts less constrained effect on the global dynamics of the protein upon various perturbations. It is not related to becoming less or more rigid. Technically, being rigid or flexible has different meanings from different perspective. If you want to learn more about the foundations of ESSA, you may want to consult our earlier article: https://pubs.acs.org/doi/10.1021/acs.jcim.8b00946.

Best,
Burak

Note: We are creating issues on Github for code related problems, e.g. bugs. Please use appropriate channels to ask your questions on the method itself.
