### ISSUE TITLE
MMCIF files from PDB-REDO are not parsed correctly

### ISSUE THREAD

**Issue by kalekundert** [prody/ProDy#1709]
Here's a minimal example of the problem:
```
$ wget https://pdb-redo.eu/db/5d8v/5d8v_final.cif
...
$ ls
5d8v_final.cif
$ python
Python 3.10.0 (default, Oct 20 2021, 17:23:57) [Clang 12.0.1 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import prody
>>> prody.__version__
'2.4.0'
>>> prody.parseMMCIF('5d8v_final.cif')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kale/.pyenv/versions/3.10.0/lib/python3.10/site-packages/prody/proteins/ciffile.py", line 117, in parseMMCIF
    result = parseMMCIFStream(cif, chain=chain, **kwargs)
  File "/home/kale/.pyenv/versions/3.10.0/lib/python3.10/site-packages/prody/proteins/ciffile.py", line 190, in parseMMCIFStream
    _parseMMCIFLines(ag, lines, model, chain, subset, altloc)
  File "/home/kale/.pyenv/versions/3.10.0/lib/python3.10/site-packages/prody/proteins/ciffile.py", line 282, in _parseMMCIFLines
    raise MMCIFParseError('mmCIF file contained no atoms.')
prody.proteins.ciffile.MMCIFParseError: mmCIF file contained no atoms.
```

Note that 5d8v is just a representative example, and in fact prody will fail to load any MMCIF files from PDB-REDO.  The reason is that prody only looks for atoms on lines that start with `ATOM` (see line 264 of `prody/proteins/ciffile.py`).  However, this prefix is not required by the MMCIF format.

One potential solution to this problem would be to use the [PDBeCIF](https://pdbeurope.github.io/pdbecif/documentation/quick.html) library to parse MMCIF files.  I've checked that it does parse the files from PDB-REDO correctly, and using a third-party library might simplify the prody codebase substantially.  That said, I don't have much experience with PDBeCIF, so take this suggestion with a grain of salt.

**Comment by jamesmkrieger** [comment]
Thanks for reporting this.

We try not to put too much dependency on too many libraries but it could be an option. There are several others such as gemmi too.

**Comment by jamesmkrieger** [comment]
This is now fixed in a merged pull request, so you should be able to parse these files if you install prody from github. See http://prody.csb.pitt.edu/manual/devel/develop.html

**Comment by kalekundert** [comment]
Thanks for the quick fix!

**Comment by jamesmkrieger** [comment]
You're welcome!
