### ISSUE TITLE
PCA calculation for multiple xtc files

### ISSUE THREAD

**Issue by gweemish** [prody/ProDy#1735]
Hi everyone,

I am very new at using prody and I am wondering how I should proceed if I want to conduct a PCA calculation of the same protein but with multiple different trajectories. The end goal is to produce something like this where different colours represents different trajectories and every point represents the geometry at a particular time step:
<img width="746" alt="image" src="https://github.com/prody/ProDy/assets/142400427/ee51a23e-0ed0-4240-a0e5-33d8471c28f9">

Any help is greatly appreciated!

**Comment by jamesmkrieger** [comment]
You'd first need to convert your xtc files to dcd files, so prody can read them. There are various programs that can do this e.g. mdconvert or VMD. You would also need to provide prody with a pdb file

Then you can follow http://prody.csb.pitt.edu/tutorials/trajectory_analysis/eda.html, using the part for multiple files
