### ISSUE TITLE
How to convert contact selection results to chainID and residue number?

### ISSUE THREAD

**Issue by johnnytam100** [prody/ProDy#1737]
I tried the contact identification example (with slight modifications) as follows:

```
! pip install prody
from prody import *

# load
pdb_path = '1BZQ_H-A_complex.pdb'
pdb = parsePDB(pdb_path)

# select
select_chain_A = pdb.select('chain A').copy()
select_chain_H = pdb.select('chain H').copy()

# get contact
contacts = select_chain_A.select('within 4 of H', H=select_chain_H)

# show
repr(contacts)
```

which gives

`<Selection: 'index 454 to 45... 852 875 to 881' from 1BZQ_H-A_complex Selection 'chain A' (48 atoms)>
`

I wonder how to convert this selection result to chainID and residue number?

**Comment by jamesmkrieger** [comment]
You can use contacts.getResnums() and other functions like that
