### ISSUE TITLE
CATH tutorial error

### ISSUE THREAD

**Issue by Yago52** [prody/ProDy#1742]
The tutorial from [CATH](http://prody.csb.pitt.edu/tutorials/signdy_tutorial/cath.html) is not working for me. When I run the code:
`node = root.getchildren()`

> --------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[27], line 1
----> 1 node = root.children()
      2 node

File ~/miniconda3/envs/python/lib/python3.11/site-packages/prody/database/cath.py:67, in CATHElement.getchildren(self)
     66 def getchildren(self):
---> 67     children = super(CATHElement, self).getchildren()
     68     collection = CATHCollection(children, self)
     69     return collection

AttributeError: 'super' object has no attribute 'getchildren'

**Comment by jamesmkrieger** [comment]
This seems to work for me on Python 3.8.13 and we know that ProDy isn't fully supported on Python 3.11 - do you have a reason for using this version of Python?

**Comment by jamesmkrieger** [comment]
I can confirm that I get this error with Python 3.11 too

**Comment by jamesmkrieger** [comment]
The same error also comes up in Python 3.10 and I see a deprecation warning in Python 3.8:
```
In [3]: root = cath.root

In [4]: self = root

In [5]: super(CATHElement, self)
Out[5]: <super: prody.database.cath.CATHElement, <CATHElement: root (5 members)>>

In [6]: type(super(CATHElement, self))
Out[6]: super

In [7]: node = root.getchildren()

In [8]: sup = super(CATHElement, self)

In [9]: sup.getchildren()
<ipython-input-9-f489d3f25754>:1: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  sup.getchildren()
Out[9]: 
[<CATHElement: 1 (5 members)>,
 <CATHElement: 2 (21 members)>,
 <CATHElement: 3 (14 members)>,
 <CATHElement: 4 (1 members)>,
 <CATHElement: 6 (2 members)>]
```

**Comment by jamesmkrieger** [comment]
ok, I now have a fix at #1743. Once it passes the checks, I'll merge it and you'll be able to use the working version using a developer install from github (see http://prody.csb.pitt.edu/manual/devel/develop.html)

**Comment by jamesmkrieger** [comment]
ok, it's merged now, closing the issue

**Comment by jamesmkrieger** [comment]
You're welcome
