### ISSUE TITLE
Alternate locations not parsed in mmCIF

### ISSUE THREAD

**Issue by sforli** [prody/ProDy#1751]
I'm using ProDy v.2.4.0 installed from PyPi. 

When testing the parsing of structures containing alternate locations I get different results when parsing the same structure from a PDB file or from an mmCIF file.

```
>>> mol_mmcif, header = pd.parseMMCIF("1ejg.cif", header=True, altloc=True)
>>> mol_mmcif 
 <AtomGroup: 1ejg (637 atoms)>  

>>> mol_pdb, header = pd.parsePDB('1ejg.pdb.gz', header=True, altloc=True)
>>> mol_pdb
 <AtomGroup: 1ejg (637 atoms; active #0 of 3 coordsets)> 
```

Both files appear to contain alt locations defined, and this is the content of the mmCIF file
```
ATOM 1   N N    A THR A 1 1  ? 16.885 14.078 3.427  0.82 4.48  ? 1  THR A N    1 
ATOM 2   N N    B THR A 1 1  ? 17.553 14.234 4.214  0.18 5.51  ? 1  THR A N    1 
ATOM 3   C CA   A THR A 1 1  ? 16.938 12.834 4.234  0.82 3.12  ? 1  THR A CA   1 
ATOM 4   C CA   B THR A 1 1  ? 16.985 12.901 4.228  0.18 16.71 ? 1  THR A CA   1 
ATOM 5   C C    . THR A 1 1  ? 15.642 12.760 4.985  1.00 3.28  ? 1  THR A C    1 
```

Unless I am doing something wrong, it appears to be a bug.

**Comment by jamesmkrieger** [comment]
I’d recommend updating to 2.4.1 as 2.4.0 has some problems with alignment

**Comment by jamesmkrieger** [comment]
ok, this is a problem with the documentation then

**Comment by jamesmkrieger** [comment]
I tried adding the True option and it caused problems, so the answer is to use 'all' and the docs are being updated accordingly.

**Comment by sforli** [comment]
That's perfectly fine, as far as the functionality is there and available, we're good. Thanks!

**Comment by jamesmkrieger** [comment]
You're welcome
