### ISSUE TITLE
Issue selecting atoms

### ISSUE THREAD

**Issue by MargotRiggi** [prody/ProDy#1755]
Hello,
I'm new using ProDy so this might be a silly problem, but after following the tutorials on elastic network models I've tried reproducing the workflow with other PDB files, and with some of them I'm running into the issue that the .select function doesn't output anything, but I'm then getting an error message for the following step, either building an Kirchhoff or Hessian matrix. I'll paste the error message below. I have this problem when I try working with the PDB 5NVU, but not 3VKH for example. In both cases parsing the PDB file seems to be successful.
Thank you very much for the help!
Margot

The error message is: 
AttributeError                            Traceback (most recent call last)
File ~/opt/miniconda3/lib/python3.9/site-packages/prody/dynamics/gnm.py:167, in GNM.buildKirchhoff(self, coords, cutoff, gamma, **kwargs)
    165 try:
    166     coords = (coords._getCoords() if hasattr(coords, '_getCoords') else
--> 167               coords.getCoords())
    168 except AttributeError:

AttributeError: 'NoneType' object has no attribute 'getCoords'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
File ~/opt/miniconda3/lib/python3.9/site-packages/prody/utilities/checkers.py:34, in checkCoords(coords, csets, natoms, dtype, name)
     33 try:
---> 34     ndim, shape = coords.ndim, coords.shape
     35 except AttributeError:

AttributeError: 'NoneType' object has no attribute 'ndim'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
File ~/opt/miniconda3/lib/python3.9/site-packages/prody/dynamics/gnm.py:170, in GNM.buildKirchhoff(self, coords, cutoff, gamma, **kwargs)
    169 try:
--> 170     checkCoords(coords)
    171 except TypeError:

File ~/opt/miniconda3/lib/python3.9/site-packages/prody/utilities/checkers.py:36, in checkCoords(coords, csets, natoms, dtype, name)
     35 except AttributeError:
---> 36     raise TypeError('coords must be a numpy.ndarray instance')
     38 ndims = CSETS_NDIMS if csets else COORDS_NDIM

TypeError: coords must be a numpy.ndarray instance

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[35], line 1
----> 1 gnm.buildKirchhoff(calpha)

File ~/opt/miniconda3/lib/python3.9/site-packages/prody/dynamics/gnm.py:172, in GNM.buildKirchhoff(self, coords, cutoff, gamma, **kwargs)
    170         checkCoords(coords)
    171     except TypeError:
--> 172         raise TypeError('coords must be a Numpy array or an object '
    173                         'with `getCoords` method')
    175 cutoff, g, gamma = checkENMParameters(cutoff, gamma)
    176 self._reset()

TypeError: coords must be a Numpy array or an object with `getCoords` method

**Comment by jamesmkrieger** [comment]
These errors aren’t surprising if you’re not selecting anything. Can you give an example of the select step please

**Comment by MargotRiggi** [comment]
Thanks for the reply!
I've for example tried:

dynein = parsePDB('5nvu')  
dynein

which gave the output:
@> Connecting wwPDB FTP server RCSB PDB (USA).
@> 5nvu downloaded (5nvu.pdb.gz)
@> PDB download via FTP completed (1 downloaded, 0 failed).
@> 51453 atoms and 1 coordinate set(s) were parsed in 0.30s.

followed by the select step: 
calphas = dynein.select('calpha')
calphas

or 

calphas = dynein.select('calpha and chain A')
calphas

Thank you for the help!!

**Comment by jamesmkrieger** [comment]
It’s quite possible there’s no chain A in that pdb entry

**Comment by MargotRiggi** [comment]
Could the fact that all amino acids are somehow indicated as unknown - UNK be a problem? (see attached screenshots for comparison of one file that works and one that doesn't) I believe that there is a chain A otherwise, and I have the same issue trying other chains.
Thank you!

<img width="632" alt="Screenshot 2023-09-27 at 16 54 06" src="https://github.com/prody/ProDy/assets/64440328/82feaf67-3610-43aa-a8f3-073569e87201">
<img width="602" alt="Screenshot 2023-09-27 at 16 54 17" src="https://github.com/prody/ProDy/assets/64440328/e1c319fe-a268-4313-8274-1650e5cc4620">

**Comment by jamesmkrieger** [comment]
It could be, yes. Maybe the shortcut “calphas” doesn’t work because of that but “name CA” might.

**Comment by MargotRiggi** [comment]
yes, it works with "name CA", thank you!

**Comment by jamesmkrieger** [comment]
You’re welcome
