### ISSUE TITLE
Ask for some questions about Perturbation Response Scanning (PRS)

### ISSUE THREAD

**Issue by panyue9220** [prody/ProDy#1768]
Dear ProDy Team,
In terms of PRS, I use the matrix made by PCA to carry out the results, and I want to know if it is valid.
As well as, what the scale automatically generated by colorbar means and whether there are units. Furthermore, I've done a lot of MD trajectories analysis using this method, and the scale radically different. May I inquire as to how a meaningful comparison of these images may be made, or what approach can be employed to make them comparable or make them have same scale? 

Kind Regards,
Pan

PS.: My steps are as follows:
from prody import *
from pylab import *
ion()
structure = parsePDB('xx.pdb')
ensemble = parseDCD('xx.dcd')
ensemble.setAtoms(structure)
ensemble.setCoords(structure)
ensemble.superpose()
ensemble.setAtoms(structure.calpha)
pca_trajectory = PCA('XX Trajectory')
pca_trajectory.buildCovariance( ensemble )
pca_trajectory.calcModes('all')
pca_trajectory
show = showPerturbResponse(pca_trajectory, atoms=structure.calpha)
![image](https://github.com/prody/ProDy/assets/112390638/983b94a9-ee05-432a-a921-cdee921659b7)
![image](https://github.com/prody/ProDy/assets/112390638/7c97c6b7-9cf6-400c-a48e-99c439666bf2)

**Comment by jamesmkrieger** [comment]
Yes, PRS from PCA covariance matrices from MD is totally valid. It is described in several of the papers.

It is not implausible that different trajectories give different maximum and minimum sensitivity and effectiveness as this is relative to the overall mobility (mean square fluctuation) of the residues, which may vary. 

You could make all your matrices have the same colour scale by providing keyword arguments `vmin`, `vmax`, and maybe `vcenter` to `showPerturbResponse` though.
