### ISSUE TITLE
showProtein(p38), RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by kinwai0510** [prody/ProDy#178]
HI,

when i use the following script,some error occur:

showProtein(p38);

error:

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    showProtein(p38);
  File "C:\Python32\lib\site-packages\prody\proteins\functions.py", line 126, in showProtein
    for cn, val in cnames.items():  # PY3K: OK
RuntimeError: dictionary changed size during iteration

Would anyone give some advice how to i fix it?
Thanks in advanced.

Tony

**Comment by odovad** [comment]
Same issue. Did you find something to make it work ?

**Comment by odovad** [comment]
Here's how to solve it :
In the file site-packages/prody/proteins/functions.py (line 126)

    to_pop = []
    for cn, val in cnames.items():  # PY3K: OK
        clr = np.array(colors.hex2color(val))
        if clr.sum() > 2.4:
            to_pop.append(cn)
            #cnames.pop(cn)
        elif np.abs(avoid - clr).sum() <= 0.6:
            to_pop.append(cn)
            #cnames.pop(cn)
    for cn in to_pop:
        cnames.pop(cn)
