### ISSUE TITLE
REMARK and END lines in a PDB file created by writePDB/writePDBStream

### ISSUE THREAD

**Issue by Nick-322** [prody/ProDy#1797]
Hi.

I was wondering how I can remove default REMARK and END lines from a PDB file when I create it using writePDB/writePDBStream.

Also, I would like to know how to remove the atom info of TER line, keeping just "TER" in the line.

for example,
what I have:
ATOM   3781  C   PRO A 502     123.805  67.456  46.975  1.00 91.24      1LYL4272
ATOM   3782  O   PRO A 502     124.799  67.133  47.655  1.00 95.49      1LYL4282
ATOM   3783  CB  PRO A 502     122.925  66.038  45.108  1.00 87.46      1LYL4292
ATOM   3784  CG  PRO A 502     122.040  67.059  44.422  1.00 84.54      1LYL423+
ATOM   3785  CD  PRO A 502     120.813  66.935  45.267  1.00 83.84      1LYL4213
TER    3786      PRO A 502                                                      
ATOM   3787  N   PHE C  14      84.561  81.271   3.201  1.00 80.55      1LYL8239
ATOM   3788  CA  PHE C  14      84.995  80.846   4.529  1.00 78.55      1LYL8249
ATOM   3789  C   PHE C  14      84.633  81.932   5.537  1.00 78.58      1LYL8259
ATOM   3790  O   PHE C  14      83.915  81.672   6.502  1.00 80.75      1LYL8269

what I want to have:
ATOM   3781  C   PRO A 502     123.805  67.456  46.975  1.00 91.24      1LYL4272
ATOM   3782  O   PRO A 502     124.799  67.133  47.655  1.00 95.49      1LYL4282
ATOM   3783  CB  PRO A 502     122.925  66.038  45.108  1.00 87.46      1LYL4292
ATOM   3784  CG  PRO A 502     122.040  67.059  44.422  1.00 84.54      1LYL423+
ATOM   3785  CD  PRO A 502     120.813  66.935  45.267  1.00 83.84      1LYL4213
TER                                                        
ATOM   3787  N   PHE C  14      84.561  81.271   3.201  1.00 80.55      1LYL8239
ATOM   3788  CA  PHE C  14      84.995  80.846   4.529  1.00 78.55      1LYL8249
ATOM   3789  C   PHE C  14      84.633  81.932   5.537  1.00 78.58      1LYL8259
ATOM   3790  O   PHE C  14      83.915  81.672   6.502  1.00 80.75      1LYL8269

**Comment by jamesmkrieger** [comment]
At the moment, you can’t do that but I can add an option

**Comment by jamesmkrieger** [comment]
I've now made a pull request adding options for this. If you get the branch at https://github.com/jamesmkrieger/ProDy/tree/ter_etc from github, then you should be able to use it. I'll also merge it with the master branch soon (once it passes the checks), so you should be able to update that then.

I have made an keyword argument for each type of line and the default value is True to maintain the original behaviour, but you can set them to false to get the behaviour you want, e.g.:
```
In [1]: from prody import *

In [2]: ag = parsePDB("3hsy", compressed=False)
@> PDB file is found in working directory (3hsy.pdb).
@> 6508 atoms and 1 coordinate set(s) were parsed in 0.05s.
@> Secondary structures were assigned to 474 residues.

In [3]: writePDB("3hsy_plain", ag, full_ter=False, write_remarks=False, write_ends=False)
Out[3]: '3hsy_plain.pdb'
```

**Comment by jamesmkrieger** [comment]
This is now merged so you can update your prody from github and get these options

**Comment by Nick-322** [comment]
Thank you!

**Comment by jamesmkrieger** [comment]
You’re welcome
