### ISSUE TITLE
ImportError: druggability package was not found. 

### ISSUE THREAD

**Issue by kinwai0510** [prody/ProDy#180]
HI, I have processing the PROBE GRID CALCULATION,but i meet the error:

Traceback (most recent call last):
  File "F:/VMD/drugui_tutorial_files/mdm/mdm_sim/mdm.py", line 21, in <module>
    'to proceed with calculation'.format(**file**))
ImportError: druggability package was not found. Edit F:/VMD/drugui_tutorial_files/mdm/mdm_sim/mdm.py to proceed with calculation
Traceback (most recent call last):
  File "F:/VMD/drugui_tutorial_files/mdm/mdm_sim/mdm.py", line 21, in <module>
    'to proceed with calculation'.format(**file**))
ImportError: druggability package was not found. Edit F:/VMD/drugui_tutorial_files/mdm/mdm_sim/mdm.py to proceed with calculation
    while executing
"exec $pythonexe [file join "$outputdir" "$pyprefix.py"] critical"
    (procedure "::druggability::Assess_druggability" line 20)
    invoked from within
"::druggability::Assess_druggability"
    (procedure "::druggability::Process_system" line 218)
    invoked from within
"::druggability::Process_system"
    invoked from within
".druggui.main_frame.process.button invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .druggui.main_frame.process.button"
    (command bound to event)

Would anyone tell me where is druggability package? Many Thanks.

**Comment by MigueLugo** [comment]
Hi, there. 

I have the drugui plugin installed in::    "../VMD/plugins/noarch/tcl",  
and the requiered command line in:       "../VMD/scripts/vmd/loadplugins.tcl",  
but when I run VMD the messege:     '**The drugui package could not be loaded**"

However, the DruGUI plugin -in fact- appears in the "Modeling" submenu,
but when I try to run the CoMD simulation by  the command:   
" vmd –dispdev text –e my_output_prefix.tcl"
Appears the message **The drugui package could not be loaded**"

Could you help me with this?  Thanks in advance

**Comment by MigueLugo** [comment]
In addition appears the messages:
'ERROR> Could not read file udispdev'
"ERROR> loading of startup molecule files aborted'

Thanks

**Comment by cihankayacihan** [comment]
Hi, 

I do not understand. Do you want to use coMD or drugui? This issue related to drugui I guess it is related to drugui. Can you give more information about error message and your input files. Please check that do you have multiple version of VMD or did you install vmd command line tools when installing. Also, can you put your output_prefix.tcl.

**Comment by MigueLugo** [comment]
*Thanks for your fast replay. CoMD is now working, However, there is a
small typo in the 'installation manual", saying:*

Then, insert following line into $VMDDIR/scripts/vmd/loadplugins.tcl at
line 200:

vmd_install_extension comd comd_tk "Modeling/DruGUI"

*When it should say:*

*vmd_install_extension comd comd_tk "Modeling/CoMD"*


*Thanks again*

2016-02-24 10:23 GMT-05:00 cihankayacihan <notifications@github.com>:

> Hi,
>
> I do not understand. Do you want to use coMD or drugui? This issue related
> to drugui I guess it is related to drugui. Can you give more information
> about error message and your input files. Please check that do you have
> multiple version of VMD or did you install vmd command line tools when
> installing. Also, can you put your output_prefix.tcl.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prody/ProDy/issues/180#issuecomment-188304029>.
>



-- 
*Dr. Miguel Lugo*

Dep. of Molecular and Cellular Biology
University of Guelph
Guelph, ON, N1G 2W1
Canada

**Comment by MigueLugo** [comment]
Hi again.,

However, when CoMD is preparing the system, this error appears:

[image: Imágenes integradas 2]

Indeed, "fino.pdb" remains in the "vmd" folder, which does not
look harmful. I am running  vmd as administrator and still happen

However, I am concerned about if the preparation is complete (e.g., therei
s not any *.py file created).

In this moment I am running the simulation to see

Thanks

2016-02-24 10:49 GMT-05:00 cihankayacihan <notifications@github.com>:

> Closed #180 <https://github.com/prody/ProDy/issues/180>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prody/ProDy/issues/180#event-563816487>.
>



-- 
*Dr. Miguel Lugo*

Dep. of Molecular and Cellular Biology
University of Guelph
Guelph, ON, N1G 2W1
Canada

**Comment by peach-eater** [comment]
I have the same problem that the VMD console show me"Info) E:/vmd/vmd/plugins/WIN32/molfile
The drugui package could not be loaded:",could you please tell me have you solved it and how to solve it?

**Comment by jamesmkrieger** [comment]
This is a different error so please start a new issue for it. Did you install the DruGUI plugin following the instructions on the ProDy website?

**Comment by peach-eater** [comment]
Thank you for your fast replies!I have installed DruGUI plugin&nbsp;following the instructions on the ProDy website.Maybe it has no effect when using it.I will continue study to use VMD.Sorry for excuse you!Thanks again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "prody/ProDy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 下午5:02
收件人:&nbsp;"prody/ProDy"<ProDy@noreply.github.com&gt;;
抄送:&nbsp;"程宏晗"<2351428409@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [prody/ProDy] ImportError: druggability package was not found.  (#180)





 
This is a different error so please start a new issue for it. Did you install the DruGUI plugin following the instructions on the ProDy website?

**Comment by jamesmkrieger** [comment]
It may well be a meaningless error message but it could also mean something. Can you try using the plugin and let me know what happens?

**Comment by peach-eater** [comment]
Perhaps!Don't worry, it worked well.Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "prody/ProDy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 下午5:47
收件人:&nbsp;"prody/ProDy"<ProDy@noreply.github.com&gt;;
抄送:&nbsp;"2351428409"<2351428409@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [prody/ProDy] ImportError: druggability package was not found.  (#180)





 
It may well be a meaningless error message but it could also mean something. Can you try using the plugin and let me know what happens?

**Comment by jamesmkrieger** [comment]
Ok, issue closed again. Thanks
