### ISSUE TITLE
Add write mmtf

### ISSUE THREAD

**Issue by jamesmkrieger** [prody/ProDy#1814]
Not sure if it will be easier to convert directly for mmtf-python or use biopython

**Comment by Waris-95** [comment]
That depends on your preference and the features you need. Both mmtf-python and Biopython can handle pdb and mmtf files, but Biopython has more functionality for bioinformatics analysis, such as sequence alignment, phylogenetics, and molecular modeling. However, mmtf-python is more lightweight and faster for parsing and writing mmtf files. You can try both libraries and see which one suits your needs better. 😊

**Comment by jamesmkrieger** [comment]
Thanks

**Comment by jamesmkrieger** [comment]
See also https://github.com/scipion-em/scipion-em-prody/issues/65 where I initially opened the issue by accident

**Comment by jamesmkrieger** [comment]
Well, of course Bio only includes MMTF in latest versions that aren't compatible with ProDy yet!

**Comment by jamesmkrieger** [comment]
ProDy should now be compatible with the latest Biopython following #1816 and I should be able to use that for writing to mmCIF and mmtf soon

**Comment by jamesmkrieger** [comment]
We still need more features for including numBonds, numAtoms, numModels, etc. 
“””
Hi! I just had time to test it today, and it works great! I was not aware of the biopython mmtf implementation; I was using biotite previously. I still need to figure out some things related to the mmtf, but overall, now the conversation works great! Thanks!

Alright, I think I figured it out. I have never worked with mmtf files, so the concept is new to me. The biotite mmtf only works with mmtf files that are properly annotated and have all the keys filled with proper values.

However, neither ProDy nor Biopython annotate all the fields inside the mmtf file (numBonds, numModels, numAtoms); thus, other software fails. Nevertheless, the conversion works well
“””
