### ISSUE TITLE
rmsds of ClustENMD and issue with OpenMM8

### ISSUE THREAD

**Issue by huangjianxiangzju** [prody/ProDy#1819]
I was kind of confused when I was reading tutorial of ClustENMD.
I would like to try the original sampling with all modes (i.e., v1=True). I read the code and I think the arg should be "rmsd" in the ANM sampling section instead of "rmsds" shown on the tutorial page. I guess it is better to clarify this and add statement such as if v1=True, and "rmsd" can also get a tuple of maxinum rmsd of each generation, just like "maxclust". Please correct me if I guess it wrong.
One more thing, I tried the  ClustENMD tutorial using the lateses OpenMM 8, which did not work properly. It would pop incompatible units warning. I switched to OpenMM7.7 and it workes:). So I think there is a compatibility issue with the latest OpenMM 8.

**Comment by jamesmkrieger** [comment]
> I was kind of confused when I was reading tutorial of ClustENMD. I would like to try the original sampling with all modes (i.e., v1=True). I read the code and I think the arg should be "rmsd" in the ANM sampling section instead of "rmsds" shown on the tutorial page. I guess it is better to clarify this and add statement such as if v1=True, and "rmsd" can also get a tuple of maxinum rmsd of each generation, just like "maxclust". Please correct me if I guess it wrong. 

Yes, you're right. The arg should be rmsd not rmsds. Sorry for the confusion. 

I agree it would be useful to update the tutorial to be clearer about using tuples. These are valid for both v1 and new ClustENMD. What they mean internally is different but the type of input is the same. 

We will update the website when we can.

> One more thing, I tried the ClustENMD tutorial using the lateses OpenMM 8, which did not work properly. It would pop incompatible units warning. I switched to OpenMM7.7 and it workes:). So I think there is a compatibility issue with the latest OpenMM 8.

Yes, ClustENMD is not updated for the latest OpenMM. Is there some feature in OpenMM 8 that would be useful?

**Comment by jamesmkrieger** [comment]
Please check the working version of this webpage at https://github.com/jamesmkrieger/ProDy-website/blob/clustenm_fixes/tutorials/clustenmd_tutorial/clustenmd.rst and let me know if it makes sense now

**Comment by huangjianxiangzju** [comment]
> > I was kind of confused when I was reading tutorial of ClustENMD. I would like to try the original sampling with all modes (i.e., v1=True). I read the code and I think the arg should be "rmsd" in the ANM sampling section instead of "rmsds" shown on the tutorial page. I guess it is better to clarify this and add statement such as if v1=True, and "rmsd" can also get a tuple of maxinum rmsd of each generation, just like "maxclust". Please correct me if I guess it wrong.
> 
> Yes, you're right. The arg should be rmsd not rmsds. Sorry for the confusion.
> 
> I agree it would be useful to update the tutorial to be clearer about using tuples. These are valid for both v1 and new ClustENMD. What they mean internally is different but the type of input is the same.
> 
> We will update the website when we can.
> 
> > One more thing, I tried the ClustENMD tutorial using the lateses OpenMM 8, which did not work properly. It would pop incompatible units warning. I switched to OpenMM7.7 and it workes:). So I think there is a compatibility issue with the latest OpenMM 8.
> 
> Yes, ClustENMD is not updated for the latest OpenMM. Is there some feature in OpenMM 8 that would be useful?

Actually, I have little experience with OpenMM. So I can not offer my opinions on new features of OpenMM8.

**Comment by huangjianxiangzju** [comment]
> Please check the working version of this webpage at https://github.com/jamesmkrieger/ProDy-website/blob/clustenm_fixes/tutorials/clustenmd_tutorial/clustenmd.rst and let me know if it makes sense now

Thanks a lot for your timely reply:) The rst file looks good. Actually I referred to the prody website before. And also I noticed that the compressed file of clustENM tutorial can not be downloaded (http://prody.csb.pitt.edu/tutorials/clustenmd_tutorial/TUTORIAL.zip). I got 404 error.

**Comment by jamesmkrieger** [comment]
Thanks. Ok, hopefully we can fix that too at some point
