### ISSUE TITLE
Any way to predict the structure of a missing domain in state B from a full length structure of state A?

### ISSUE THREAD

**Issue by MargotRiggi** [prody/ProDy#1820]
This isn't an issue but more of a question: I would like to predict the conformational change of a protein for which I have a full length structure in state A but only a partial structure in state B. Is there a method that would allow me to predict the structure/potential structures of the missing region in state B? 
Is there any chance to run aANM or a version of aANM in these conditions or would it always only take into account the residues that are common in both structures? Put naively, is there any way to use the common residues as a target and see how the other residues will evolve?
The  attached pic shows the 2 structures I have and in blue is highlighted a domain with a known conformational change - I was would like to predict the structure of the missing orange "tail".
Thank you very much in advance!
<img width="824" alt="Screen Shot 2024-01-23 at 4 26 20 PM" src="https://github.com/prody/ProDy/assets/64440328/54723b6b-f3c2-49e3-a6be-120cde43ce9d">

**Comment by jamesmkrieger** [comment]
Yes, these should indeed be feasible and sounds like a really nice idea. I can give it a try and let you know some example code.

Best wishes 
James

**Comment by MargotRiggi** [comment]
Awesome thank you so much!!

**Comment by MargotRiggi** [comment]
That'd be great! Do you wanna schedule a time to meet up? I'm leaving early on Wednesday, and my poster session is on Tuesday afternoon, but could fine some time at any other point.

**Comment by jamesmkrieger** [comment]
Sounds good! How about Tuesday at 1:30pm? I'll email you my phone number so we can coordinate better

**Comment by MargotRiggi** [comment]
I've double checked and the poster session is from 1:45-3:45 - would it be possible to try and aim for meeting a bit earlier, maybe around 1pm? (my poster has not much to do with these questions) alternatively if you're free I could meet on Sunday or Monday at some point between 1-4pm. if none of these options work I'll shorten my time at my poster, thank you already for your time!

**Comment by jamesmkrieger** [comment]
Oh, right. I didn't process that correctly. Sorry.

Sunday sounds good, but we'll have to see how things go. Monday would probably work too, although I have a meeting at 1pm and I don't know when it will finish or what will happen after.

If we need to do Tuesday, we can probably manage 1pm, but we can be in touch and see.

**Comment by jamesmkrieger** [comment]
Hello, today from 1pm should work there are a few posters I’d like to see but I guess it doesn’t matter when I get to them. Where shall we meet?

I’m planning to go to the viral spike-receptor interaction cryo-EM talk in ball room B as my last talk of the morning, which should finish around 12:20

**Comment by jamesmkrieger** [comment]
Summary for everyone else: one answer is to compare with sliced modes and then traverse the original modes. 

The other is to modify adaptive ANM to have this functionality (#1826) and this is in progress

**Comment by jamesmkrieger** [comment]
Hi Margot,

It actually turns out that adaptive ANM already has this functionality and I just didn't check properly before. I just tried a case where I removed a portion of the target and the created it as an AtomMap to the initial structure and the adaptive ANM has the missing part in the resulting trajectory.

Sorry for not realising this earlier!!

```
In [1]: from prody import *

In [2]: rest = parsePDB('1ewt', biomol=True, subset='ca')
@> Connecting wwPDB FTP server RCSB PDB (USA).
@> 1ewt downloaded (1ewt.pdb.gz)
@> PDB download via FTP completed (1 downloaded, 0 failed).
@> 912 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Biomolecular transformations were applied to the coordinate data.

In [3]: act = parsePDB('1isr', biomol=True, subset='ca').select('not resnum 375 to 405')
@> Connecting wwPDB FTP server RCSB PDB (USA).
@> 1isr downloaded (1isr.pdb.gz)
@> PDB download via FTP completed (1 downloaded, 0 failed).
@> 449 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Biomolecular transformations were applied to the coordinate data.

In [4]: a = rest

In [5]: b = alignChains(act, rest)[0]
@> Trying to map atoms based on residue numbers and identities:
@>   Comparing Chain A from 1isr_ca biomolecule 1 (len=418) with Chain A from 1ewt_ca biomolecule 1:
@>      Mapped: 417 residues match with 100% sequence identity and 91% overlap.
@> Trying to map atoms based on residue numbers and identities:
@>   Comparing Chain A from 1isr_ca biomolecule 1 (len=418) with Chain A from 1ewt_ca biomolecule 1:
@>      Mapped: 417 residues match with 100% sequence identity and 91% overlap.
@> Trying to map atoms based on residue numbers and identities:
@>   Comparing Chain A from 1isr_ca biomolecule 1 (len=418) with Chain B from 1ewt_ca biomolecule 1:
@>      Mapped: 417 residues match with 100% sequence identity and 91% overlap.
@> Trying to map atoms based on residue numbers and identities:
@>   Comparing Chain A from 1isr_ca biomolecule 1 (len=418) with Chain B from 1ewt_ca biomolecule 1:
@>      Mapped: 417 residues match with 100% sequence identity and 91% overlap.
@> Finding the atommaps based on their coverages...
@> Identified that there exists 1 atommap(s) potentially.

In [6]: a
Out[6]: <AtomGroup: 1ewt_ca biomolecule 1 (912 atoms)>

In [7]: b
Out[7]: <AtomMap: (Chain A from 1isr_ca biomolecule 1 -> Chain B from 1ewt_ca biomolecule 1) + (Chain A from 1isr_ca biomolecule 1 -> Chain A from 1ewt_ca biomolecule 1) from 1isr_ca biomolecule 1 (912 atoms, 834 mapped, 78 dummy)>

In [8]: x = calcAdaptiveANM(a, b, 5, mode=AANM_ONEWAY, f=0.9)
@> Initialized Adaptive ANM with RMSD 10.954

@> 
Starting cycle 1 with initial structure 1ewt_ca biomolecule 1
@> Hessian was built in 0.32s.
@> 20 modes were calculated in 1.29s.
@> Using 1 mode with square overlap 0.597
@> Current RMSD is 6.779

@> 
Starting cycle 2 with initial structure 1ewt_ca biomolecule 1
@> Hessian was built in 0.28s.
@> 20 modes were calculated in 1.25s.
@> Using 2 modes with square cumulative overlap 0.245
@> Current RMSD is 5.877

@> 
Starting cycle 3 with initial structure 1ewt_ca biomolecule 1
@> Hessian was built in 0.29s.
@> 20 modes were calculated in 1.53s.
@> Using 5 modes with square cumulative overlap 0.348
@> Current RMSD is 4.297

@> 
Starting cycle 4 with initial structure 1ewt_ca biomolecule 1
@> Hessian was built in 0.29s.
@> 20 modes were calculated in 1.29s.
@> Using 12 modes with square cumulative overlap 0.565
@> Current RMSD is 2.795

@> 
Starting cycle 5 with initial structure 1ewt_ca biomolecule 1
@> Hessian was built in 0.30s.
@> 20 modes were calculated in 1.34s.
@> Using 20 modes with square cumulative overlap 0.189
@> Current RMSD is 2.507


In [9]: x
Out[9]: <Ensemble: 1ewt_ca biomolecule 1_aANM (6 conformations; 912 atoms)>

In [10]: writePDB('missing_wing_aanm.pdb', x)
Out[10]: 'missing_wing_aanm.pdb'
```

**Comment by jamesmkrieger** [comment]
I've also verified this by saving the selection from the active state and reading in the pdb file with the missing part and the same happens
