### ISSUE TITLE
ProDy align unable to run on different chains of the same protein

### ISSUE THREAD

**Issue by rdluke** [prody/ProDy#183]
I am trying to use the ProDy align command in unix in order to compare 2 chains of the same protein and am unable to get it running.  The command works perfectly for comparing two different proteins but is not allowing me to compare the same protein.  

This is the output I am receiving:

bash-3.2$ prody align 1vpp 1vpp
@> Aligning structures onto: 1vpp
@> PDB file is found in working directory (1vpp.pdb.gz).
@> 2186 atoms and 1 coordinate set(s) were parsed in 0.04s.
@> Selection 'calpha' matched 224 atoms.

Any advice would be much appreciated.

**Comment by jamesmkrieger** [comment]
We have made quite a bit of progress on this and it is definitely achievable now so issue closed.
