### ISSUE TITLE
Normal Mode analysis of trajectory file using anm

### ISSUE THREAD

**Issue by dulalmondal123** [prody/ProDy#1832]
Dear Experts,

I am trying this tutorial below.

http://prody.csb.pitt.edu/tutorials/enm_analysis/anm.html

Is this any way normal mode analysis of the trajectory file?

**Comment by jamesmkrieger** [comment]
Yes, we have a module called signature dynamics (SignDy) or ensemble normal mode analysis, which does exactly that. See http://prody.csb.pitt.edu/tutorials/signdy_tutorial/core.html

To load in a trajectory, it would need to be in DCD format and then you can use the function parseDCD to get a ProDy ensemble object that can be used for SignDy.

I imagine you would not want to run NMA on every frame of a trajectory, but take something like every 100th frame and you can get this by using the step argument in parseDCD.

**Comment by dulalmondal123** [comment]
Thank you for reply.

**Comment by dulalmondal123** [comment]
I also calculate normal mode of water. Then it generate an nmd file. It also calculate three eigen value and eigen vector also. How I find frequency?
