### ISSUE TITLE
Frequency from normal mode analysis

### ISSUE THREAD

**Issue by dulalmondal123** [prody/ProDy#1834]
I also calculate normal mode of water. Then it generate an nmd file. It also calculate three eigen value and eigen vector also. How I find frequency?

**Comment by jamesmkrieger** [comment]
The frequency is the square root of the eigenvalue. However, this frequency is not hugely meaningful as a result of all the approximations included in elastic network model normal mode analysis (see https://github.com/prody/ProDy/issues/1821).

This kind of analysis is also more appropriate for larger systems where chemistry matters less and mechanics matter more. Why did you apply it to water?

**Comment by dulalmondal123** [comment]
I have 10 ns water trajectory file. I want to calculate the nma of water just for check. Since I am trying to calculate nma of NH nond in protein His-64 residue.

**Comment by dulalmondal123** [comment]
Thanks for reply.

**Comment by jamesmkrieger** [comment]
Do you really want NMA of that? Perhaps PCA from your MD trajectory would make more sense?

If you really do want NMA then you'd be better to use a program with a full force field like CHARMM instead of ProDy.
