### ISSUE TITLE
#ModuleNotFoundError: No module named 'StringIO' on tutorial 

### ISSUE THREAD

**Issue by Armanda87** [prody/ProDy#1836]
Good morning 
find a error on tutorial "Evolution of sequence, structure and dynamics with Evol and SignDy"
on  the step below
```python

filename = fetchPfamMSA('PF00074')
filename

```
#ModuleNotFoundError: No module named 'StringIO'

i try in different versions of python and version of prody 
could you help me. 

thanks for your attention. 
I`m looking for your reply.

**Comment by jamesmkrieger** [comment]
Ok, I get this error now too. I'll try and figure it out next week or the following one. Thanks for reporting it

**Comment by atbogetti** [comment]
Hello @Armanda87, I was able to reproduce this error when using the ProDy version 2.4.0 from conda. When installing ProDy version 2.4.1 from source, I was able to resolve this issue. Perhaps you can try downloading ProDy v. 2.4.1 and installing from source. This was with Python 3.11. Please let me know if this does not resolve your issue.

@jamesmkrieger I tried to hunt down the source of the error. It seems the gunzip function contains a line `from StringIO import StringIO` and perhaps this should be `from io import StringIO`? However, the importing from StringIO is also present in v. 2.4.1 so there must be something before that triggering the error. Maybe in pfam.py.

**Comment by jamesmkrieger** [comment]
Thanks Anthony!

I tried checking out v2.4.1 tag from source install with python 3.8 so I don’t think it’s to do with python or ProDy version. I haven’t tried it with latest source though so maybe there’s something fixed for that.

**Comment by atbogetti** [comment]
No problem! Yes, it was the latest source that worked for me. @Armanda87 please try installing from the latest source instead of the tagged v2.4.1.

**Comment by atbogetti** [comment]
I think perhaps this commit fixed it: https://github.com/prody/ProDy/commit/73f5e2081f44fd41be6233404b1e3cf7ce5ded50

**Comment by jamesmkrieger** [comment]
Great! Issue closed then!
