### ISSUE TITLE
Adaptive ANM A to B then B to A, and mode issues

### ISSUE THREAD

**Issue by klmcguire** [prody/ProDy#1838]
I have an issue with the differenct ANM modes.  Structure A (closed state) has 908 atoms and Structure B (open state) has 894 atoms. NOTE: I am new to aANM and its use.

I did `o = parsePDB('Y173A_complex_lid_v4.pdb', subset='ca')` (the open state), `c = parsePDB('v13.pdb', subset='ca')` (closed state), and aligned using the structure with less atoms in the first position and structure with more atoms in the second positoin,  `cmap = alignChains(o, c)[0]`.  For the aANM calculation, I used the ONEWAY mode, `ens = calcAdaptiveANM(c, cmap, 50, mode=AANM_ONEWAY, min_rmsd_diff=0.025)`.  This works just fine and I can see the transition from closed state to open state.  However, if I use the AANM_ALTERNATING or AANM_BOTHWAYS modes, the RMSD plots have a sharp drop-off in the middle or at the end (see image). What would be causing these sharp drops and how can I fix it? Under what circumstances should the different modes be used? Thanks!

Also, side question to this issue.  This calculates the closed to open state, but to calculate the open to close state, do I just swap the c and o in `cmap = alignChains(o, c)[0]` and replace c with o in `ens = calcAdaptiveANM(c, cmap, 50, mode=AANM_ONEWAY, min_rmsd_diff=0.025)`?

![AANM_Modes](https://github.com/prody/ProDy/assets/105521635/dee33174-2b20-4164-91d5-3288fcc07c19)

**Comment by jamesmkrieger** [comment]
This jump in the RMSD plot is to be expected. What you could do is make the jump smaller by setting a smaller target_rmsd. The default value of 1A is a large chunk of an RMSD that’s already as small as 2.2A. 

2.2 A is also such a small starting RMSD that you may want to consider if you really want to use adaptive ANM at all. For these kinds of changes, the atomic details probably matter more and you might be better using targeted MD or even regular MD, at least for catching open to closed. 

If you only go one way then it stops when the RMSD reaches within 1A of the target from that side. It’s possible this wouldn’t happen if you didn’t select enough modes or steps. 

If you go both ways sequentially then it first reaches this structure 1A away and then moves the other structure towards that until it reaches 1A, which it does immediately so there’s a very short part of the graph after the jump. If the first direction hadn’t reached 1A away from the target, then there might be a longer last part of the graph to bring the target structure to within 1A of the intermediate. 

The alternating mode instead keeps moving both structures in an alternating way towards the intermediate structures generated by each of them until these reach within 1A of each other so the jump is in the middle. It could be slightly closer to one side if the modes of one structure are better at driving the transition. 

As for capturing closed to open, you could still keep the same atommap and just swap the order in the adaptive ANM command. The traditional way of running adaptive ANM is the alternating one and in that case, it should be the same whichever structure you start from. Therefore you can just reverse the trajectory and get that result. 

The other modes of running it are about shifting the balance towards more local motions of the first structure by going as far as possible in the mode space of that structure before either stopping (one way) or then following the modes of the other (both ways).

**Comment by klmcguire** [comment]
> This jump in the RMSD plot is to be expected. What you could do is make the jump smaller by setting a smaller target_rmsd. The default value of 1A is a large chunk of an RMSD that’s already as small as 2.2A.
> 
> 2.2 A is also such a small starting RMSD that you may want to consider if you really want to use adaptive ANM at all. For these kinds of changes, the atomic details probably matter more and you might be better using targeted MD or even regular MD, at least for catching open to closed.
> 
> If you only go one way then it stops when the RMSD reaches within 1A of the target from that side. It’s possible this wouldn’t happen if you didn’t select enough modes or steps.
> 
> If you go both ways sequentially then it first reaches this structure 1A away and then moves the other structure towards that until it reaches 1A, which it does immediately so there’s a very short part of the graph after the jump. If the first direction hadn’t reached 1A away from the target, then there might be a longer last part of the graph to bring the target structure to within 1A of the intermediate.
> 
> The alternating mode instead keeps moving both structures in an alternating way towards the intermediate structures generated by each of them until these reach within 1A of each other so the jump is in the middle. It could be slightly closer to one side if the modes of one structure are better at driving the transition.
> 
> As for capturing closed to open, you could still keep the same atommap and just swap the order in the adaptive ANM command. The traditional way of running adaptive ANM is the alternating one and in that case, it should be the same whichever structure you start from. Therefore you can just reverse the trajectory and get that result.
> 
> The other modes of running it are about shifting the balance towards more local motions of the first structure by going as far as possible in the mode space of that structure before either stopping (one way) or then following the modes of the other (both ways).

Great, thanks for the response, that is very helpful!

**Comment by jamesmkrieger** [comment]
You’re welcome

There is also a comd repo with its own issues but it works well keep everything here
