### ISSUE TITLE
Starting troubles

### ISSUE THREAD

**Issue by ragothamanrice** [prody/ProDy#185]
I downloaded ProDy 1.5.1, I have Python 2.7 and NumPy 1.5 installed. There was no error messages reported while installation. But, when I try running prody, I get the error 
$ ./prody 
Traceback (most recent call last):
  File "./prody", line 4, in <module>
    path = imp.find_module('prody')[1]
ImportError: No module named prody

What am I missing?

**Comment by cihankayacihan** [comment]
Thank you for your suggestion. We will fix this issue.
