### ISSUE TITLE
Union on selections in one selstr raises TypeError

### ISSUE THREAD

**Issue by tadsatlawa** [prody/ProDy#1852]
I need to get union of two selections. Having read http://prody.csb.pitt.edu/tutorials/prody_tutorial/selection.html#union I tried to reproduce the code present there:

```
structure = parsePDB('1p38')
betas = structure.select('name CB and protein')
print(len(betas)) # 336

gly_alphas = structure.select('name CA and resname GLY')
print(len(gly_alphas)) # 15 

betas_gly_alphas = betas | gly_alphas
print(len(betas_gly_alphas)) # 351
print(betas_gly_alphas.getSelstr()) # (name CB and protein) or (name CA and resname GLY)

# now try to get this in one selstr
betas_gly_alphas2 = structure.select('(name CB and protein) or (name CA and resname GLY)')
```
This however yields an error `TypeError: can't multiply sequence by non-int of type 'Forward'`.

**Comment by jamesmkrieger** [comment]
You need to have pyparsing 3.1.1 then it should work

**Comment by tadsatlawa** [comment]
Thanks! I had 3.1.2 and after downgrade to 3.1.1 it works.

**Comment by jamesmkrieger** [comment]
Great. We have already made this change on GitHub so it should be fine for future prody installations
