### ISSUE TITLE
Failed to build prody / ERROR: Could not build wheels for prody, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by emilyrkang** [prody/ProDy#1857]
I'm not able to install ProDy.

When running `pip install prody` on Windows I get the following error message:
...
`copying prody\tests\datafiles\mmcif_6zu5.cif -> build\lib.win-amd64-cpython-37\prody\tests\datafiles
     running build_ext
      building 'prody.dynamics.rtbtools' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for prody
Failed to build prody
ERROR: Could not build wheels for prody, which is required to install pyproject.toml-based projects`

I followed the link and installed Microsoft C++ but I'm still getting this error message.

**Comment by jamesmkrieger** [comment]
Try windows 3.8, 3.9 or 3.10 - we provide pre compiled wheels for them for windows

**Comment by jamesmkrieger** [comment]
Any luck with this?

**Comment by emilyrkang** [comment]
I'm running Windows 11 Pro operating system. I assume you mean to try those versions of Python?

I had 3.7 installed then upgraded to the latest stable version (3.12), neither seemed to work. I had to uninstall Python 3.12, but I the install seems to have worked with Python 3.10: 

C:\Windows\System32> py
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

C:\Windows\System32>pip3.10 install prody
Collecting prody
  Downloading ProDy-2.4.1-cp310-cp310-win_amd64.whl (22.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.2/22.2 MB 12.6 MB/s eta 0:00:00
Collecting pyparsing
  Downloading pyparsing-3.1.2-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 5.8 MB/s eta 0:00:00
Collecting numpy<1.24,>=1.10
  Downloading numpy-1.23.5-cp310-cp310-win_amd64.whl (14.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 38.4 MB/s eta 0:00:00
Requirement already satisfied: setuptools in c:\users\emilyrobertskang\appdata\local\programs\python\python310\lib\site-packages (from prody) (65.5.0)
Collecting biopython<=1.79
  Downloading biopython-1.79-cp310-cp310-win_amd64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 1.8 MB/s eta 0:00:00
Collecting scipy
  Downloading scipy-1.13.0-cp310-cp310-win_amd64.whl (46.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 31.1 MB/s eta 0:00:00
Installing collected packages: pyparsing, numpy, scipy, biopython, prody
Successfully installed biopython-1.79 numpy-1.23.5 prody-2.4.1 pyparsing-3.1.2 scipy-1.13.0

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: C:\Users\Emily

**Comment by jamesmkrieger** [comment]
Yes, sorry. Those are python versions

**Comment by jamesmkrieger** [comment]
Glad to hear 3.8 works

**Comment by emilyrkang** [comment]
Yes, thanks for your help!
