### ISSUE TITLE
writing DCD from coordsets

### ISSUE THREAD

**Issue by gol3tron** [prody/ProDy#187]
Hello,

Is there any way to take a set of coordinates (essentially from dcd.getCoordsets() ) and compile them into a DCD file? I'm trying to use the "write()" method within the DCDFile class but can't seem to figure it out.

Can anyone provide a working example of how to use this method, or how to better go about solving this problem?

Thanks,
Adam

**Comment by cihankayacihan** [comment]
You can follow our coMD tutorial to see how to do it. Thanks.
