### ISSUE TITLE
dear all researcher,  can you guide me, I have install ProDy in Windows , using pip install -U prody    and found an error please see the attached file   (Capture-1 and Capture-2)  when opened ProDy in VMD,  i found this error  please see the attached file    because am not able to find the path of ProDy (Capture-3 to 5)

### ISSUE THREAD

**Issue by mohad200** [prody/ProDy#1874]
![Capture-1](https://github.com/prody/ProDy/assets/38758489/1a1b6cc3-6383-4433-b484-2792577ab058)
![Capture-2](https://github.com/prody/ProDy/assets/38758489/1375dd82-7bc4-494c-93a2-556bc63be37f)
![Capture-3](https://github.com/prody/ProDy/assets/38758489/390d2123-4bf0-4a7a-9a41-154f692bebfd)
![Capture-4](https://github.com/prody/ProDy/assets/38758489/e02594e6-6721-4bea-a565-0e9bc169fc43)
![Capture-5](https://github.com/prody/ProDy/assets/38758489/05581838-e81c-442c-828a-5b620b7fa0c6)

**Comment by jamesmkrieger** [comment]
Please use python 3.10 instead of 3.11 to use precompiled windows versions. We suggest you use an anaconda environment to install prody and activate that environment before opening vmd in the same terminal

**Comment by atbogetti** [comment]
@mohad200 Please let us know if your issues with ProDy have been resolved or if we can provide any additional guidance. Thanks.
