### ISSUE TITLE
NMwiz error

### ISSUE THREAD

**Issue by rajankumar999** [prody/ProDy#188]
File "C:/Python27/Scripts/Scripts/prody.bat", line 1
    %~dp0..\python %~dp0\prody %*
    ^
SyntaxError: invalid syntax
  File "C:/Python27/Scripts/Scripts/prody.bat", line 1
    %~dp0..\python %~dp0\prody %*
    ^
SyntaxError: invalid syntax
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody anm --quiet -s all -o "$::NMWiz::outputdir" -p "$prefix" -n $::NMWiz::prodyNModes -c $::NMWiz::prodyCutoff -g $::..."
    (procedure "::NMWiz::prodySubmitANMjob" line 32)
    invoked from within
"::NMWiz::prodySubmitANMjob"
    (procedure "::NMWiz::prodySubmitJob" line 20)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

**Comment by cihankayacihan** [comment]
It is an issue with Windows version of Prody. It will be fixed soon.

**Comment by cihankayacihan** [comment]
please see #246
