### ISSUE TITLE
selection with residues

### ISSUE THREAD

**Issue by comacke** [prody/ProDy#190]
This probably belongs in some sort of help forum instead, but I didn't see a place to post ProDy questions. 

I am trying to select portions of proteins using residues that I have already selected from a structure. In the end I want to write these out to a pdb file. Here's what I'm doing right now. 

```
from prody import *

struct = parsePDB('myPath/3WJF.pdb')

A36 = struct['A', 36]
A15 = struct['A', 15]
B17 = struct['B', 17]

resSel = A36
resSel += A15
resSel += B17

resSel = resSel.copy()
writePDB(myPath/reSel1.pdb', resSel)
```

Alternatively I could use the selection method as follows. 

```
resSel = struct.select('(chain A and resnum 36) or (chain A and resnum 15) or (chain B and resnum 17)').copy()
```

I prefer the first method for my purposes. The selections will be part of a larger function that iteratively selects residues based on some property in a for loop - hence the "+=". Also, when I time tested the two methods, the first appeared to be faster. Are there any differences I should be concerned about between the two selection methods?

**Comment by cihankayacihan** [comment]
Inside select function input is a string. You can write a loop to create a string and use it in select instead.
