### ISSUE TITLE
cKDTree Problem

### ISSUE THREAD

**Issue by rks5854** [prody/ProDy#1900]
I am having trouble creating the Kirchhoff matrix in the GNM tutorial. After entering the command 
> gnm.buildKirchhoff(calphas)
I receive the error:
 AttributeError                            Traceback (most recent call last)
<ipython-input-9-d8080af85447> in <module>
----> 1 gnm.buildKirchhoff(calphas)

/data/rks5854/rxr-fxr/prody/dynamics/gnm.py in buildKirchhoff(self, coords, cutoff, gamma, **kwargs)
    154             kdtree = KDTree(coords)
    155             kdtree.search(cutoff)
--> 156             dist2 = kdtree.getDistances() ** 2
    157             r = 0
    158             for i, j in kdtree.getIndices():

/data/rks5854/rxr-fxr/prody/kdtree/kdtree.py in getDistances(self)
    271         """Returns array of distances."""
    272 
--> 273         if self.getCount():
    274             if self._unitcell is None:
    275                 if self._neighbors is None:

/data/rks5854/rxr-fxr/prody/kdtree/kdtree.py in getCount(self)
    289                 return self._kdtree.get_count()
    290             else:
--> 291                 return self._kdtree.neighbor_get_count()
    292         else:
    293             return len(self._pbcdict)

AttributeError: 'C KDTree' object has no attribute 'neighbor_get_count'

The troubleshooting I have tried for myself has been unsuccessful and I could very much use some help. Thank you!

**Comment by jamesmkrieger** [comment]
It looks like the C extensions aren't installed properly. How did you install prody?

**Comment by jamesmkrieger** [comment]
Hi Riley,

Are you using any kind of conda environment or is this the system python? If it’s the latter and you can only do a user install then it’s possible that’s the problem but I don’t know. 

Probably you have better control of the directories to have a better chance of installing things properly if you do use conda.

Best wishes 
James

**Comment by rks5854** [comment]
Hi James,

I am in a CentOS 7 Linux environment, using ipython in the terminal. As CentOS 7 will no longer be supported, our college of science IT team will be migrating us to Rocky 8, but I am not sure precisely when that will happen. They are also able to install software as admin that I as a student do not have permissions for - the IT person I have been working with is just not sure what needs to be installed!

I am not the most knowledgeable on computing environments, so apologies for any confusion. I am a chemist by training and self-taught in computation.

Thank you for your help!

Riley


Riley Eisert-Sasse (he/they)

Graduate Student, Okafor Group, Department of Chemistry

TA/Supervisory TA, CHEM111

"Knowledge and ability must be combined with ambition as well as with a sense of honesty and a severe conscience" -analytical chemist Carl Remigius Fresenius

________________________________

**Comment by jamesmkrieger** [comment]
The problem could be that your ipython doesn’t match your prody. It would probably be better to create a new environment and install prody and ipython there. 

We all had to learn at some point and the best way to do it is by trying, so well done and keep at it. I came from biochemistry and taught myself too.

It should work to do the following:

conda create -n py39_prody python=3.9 ipython
conda activate py39_prody 
pip install prody

Then you should run the conda activate command before opening ipython and then it should work hopefully. 

Let us know if you have any more problems. Good luck!

**Comment by jamesmkrieger** [comment]
If you have ipython then you probably have conda already but if not you should be able to install it without being an admin e.g. https://docs.anaconda.com/free/miniconda/miniconda-install/

**Comment by rks5854** [comment]
Thank you for the help and encouragement! I did not have conda installed before, installed using the command line instructions in the given link, and then closed and reopened my terminal. Unfortunately, I am still getting the same error.


Riley Eisert-Sasse (he/they)

Graduate Student, Okafor Group, Department of Chemistry

TA/Supervisory TA, CHEM111

"Knowledge and ability must be combined with ambition as well as with a sense of honesty and a severe conscience" -analytical chemist Carl Remigius Fresenius

________________________________

**Comment by jamesmkrieger** [comment]
If all you did was installed miniconda then that won’t fix anything except making everything else easier.

You still need to follow the other instructions I gave to take advantage of it and then remember to activate the environment each time you open a new terminal. 

Hopefully that then helps

**Comment by rks5854** [comment]
Thank you - not all the messages are coming through via email, so I have switched over to Github. I ran the commands you suggested, with the same result 
![image](https://github.com/prody/ProDy/assets/170653735/42f97b94-e618-4bfb-8bdf-6206db3882b4)

**Comment by rks5854** [comment]
> Hi @rks5854, if you run `which python` after your conda install, do you see the python from your miniconda location? Sometimes on my local cluster if there is a module loaded with python it always supersedes my conda environment.

Yes, i see, ~/miniconda3/bin/python

**Comment by jamesmkrieger** [comment]
> > Hi @rks5854, if you run `which python` after your conda install, do you see the python from your miniconda location? Sometimes on my local cluster if there is a module loaded with python it always supersedes my conda environment.
> 
> Yes, i see ~/miniconda3/bin/python

What about after activating the environment?

**Comment by rks5854** [comment]
![image](https://github.com/prody/ProDy/assets/170653735/76aa74b0-88a3-44cd-bcfb-0e05c3ce946e)
i think so

**Comment by jamesmkrieger** [comment]
Ok, that part worked then. @atbogetti, any ideas?

**Comment by jamesmkrieger** [comment]
I meant outside ipython in the regular linux terminal, but this tells us too

**Comment by rks5854** [comment]
> I meant outside ipython in the regular linux terminal, but this tells us too

Both show miniconda

**Comment by jamesmkrieger** [comment]
But you have two conda environments now: the base on and your prody one. The star on the prody one told me that that’s active, but running which python and which ipython outside python in linux with the environment active should show paths for them in that environment

**Comment by jamesmkrieger** [comment]
> Thank you - not all the messages are coming through via email, so I have switched over to Github. I ran the commands you suggested, with the same result ![image](https://private-user-images.githubusercontent.com/170653735/333341481-42f97b94-e618-4bfb-8bdf-6206db3882b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDQyMDYsIm5iZiI6MTcxNjUwMzkwNiwicGF0aCI6Ii8xNzA2NTM3MzUvMzMzMzQxNDgxLTQyZjk3Yjk0LWU2MTgtNGJmYi04YmRmLTYyMDZkYjM4ODJiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMjM4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzI4MTYxYmRiNDY0MTY5OTA0MzU2MDJlOWU1NTc2ZTM1NzM4NDk2Nzg0ZTQ3M2VjNWNkNWY2ZWY1YTE0MDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5U5vHmLd_vhX8yxu8pN3Yyu9pE1dFD1D6scHefcpmBM) ![image](https://private-user-images.githubusercontent.com/170653735/333341751-ee24badc-d5c5-4fc5-a4bf-d3c2b4e6bd8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDQyMDYsIm5iZiI6MTcxNjUwMzkwNiwicGF0aCI6Ii8xNzA2NTM3MzUvMzMzMzQxNzUxLWVlMjRiYWRjLWQ1YzUtNGZjNS1hNGJmLWQzYzJiNGU2YmQ4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMjM4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzA0ZGYzMjJkZjUwOWYxOGVkZmI1YWI1NDUzMDRkNjk1ZTQ0OGViNDZhMmZmNGQ1Yjc3YmRjNzUyOWMyYjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wu_Gwi1ajIN-BDWFwiTMuKIVJjNkWSjrUak184JA4wE)

It’s also possible that the problem comes from prody installing before changing the numpy so the c extensions are compiled against the wrong one. Maybe you can pip uninstall prody and pip install prody again and that would maybe fix it

**Comment by rks5854** [comment]
Ah, I understand what you meant now! When I run which ipython in a normal terminal I do not see miniconda. I will also uninstall and reinstall prody just to be safe

**Comment by rks5854** [comment]
base) [rks5854@e1-054124 rxr-fxr]$ pip install prody
DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/pytraj-2.0.5-py2.7-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/ParmEd-3.2.0-py2.7-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/pdb4amber-1.7.dev0-py2.7.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting prody
  Using cached ProDy-2.4.1.tar.gz (21.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/pytraj-2.0.5-py2.7-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
      DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/ParmEd-3.2.0-py2.7-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
      DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/pdb4amber-1.7.dev0-py2.7.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
      Collecting setuptools
        Using cached setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting numpy<1.24,>=1.10
        Downloading numpy-1.23.5.tar.gz (10.7 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 53.5 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [33 lines of output]
            Traceback (most recent call last):
              File "/home/rks5854/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/home/rks5854/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/rks5854/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
                backend = _build_backend()
                          ^^^^^^^^^^^^^^^^
              File "/home/rks5854/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
                obj = import_module(mod_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/rks5854/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
              File "<frozen importlib._bootstrap_external>", line 995, in exec_module
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "/tmp/pip-build-env-j_j4dfys/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
                import setuptools.version
              File "/tmp/pip-build-env-j_j4dfys/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
                import pkg_resources
              File "/tmp/pip-build-env-j_j4dfys/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
                register_finder(pkgutil.ImpImporter, find_on_path)
                                ^^^^^^^^^^^^^^^^^^^
            AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jamesmkrieger** [comment]
> Ah, I understand what you meant now! When I run which ipython in a normal terminal I do not see miniconda. I will also uninstall and reinstall prody just to be safe

Ok, this is the problem then. Your ipython isn’t linked up to the environment with prody properly 

sometimes deactivating and activating again can help. Otherwise you can try running the right ipython with the full path

/home/rks5854/miniconda3/envs/py39_prody/bin/ipyrhon

**Comment by jamesmkrieger** [comment]
> base) [rks5854@e1-054124 rxr-fxr]$ pip install prody DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/pytraj-2.0.5-py2.7-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at [pypa/pip#12330](https://github.com/pypa/pip/issues/12330) DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/ParmEd-3.2.0-py2.7-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at [pypa/pip#12330](https://github.com/pypa/pip/issues/12330) DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/pdb4amber-1.7.dev0-py2.7.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at [pypa/pip#12330](https://github.com/pypa/pip/issues/12330) Collecting prody Using cached ProDy-2.4.1.tar.gz (21.7 MB) Installing build dependencies ... error error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> [62 lines of output] DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/pytraj-2.0.5-py2.7-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at [pypa/pip#12330](https://github.com/pypa/pip/issues/12330) DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/ParmEd-3.2.0-py2.7-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at [pypa/pip#12330](https://github.com/pypa/pip/issues/12330) DEPRECATION: Loading egg at /usr/local/amber18/lib/python2.7/site-packages/pdb4amber-1.7.dev0-py2.7.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at [pypa/pip#12330](https://github.com/pypa/pip/issues/12330) Collecting setuptools Using cached setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB) Collecting wheel Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB) Collecting numpy<1.24,>=1.10 Downloading numpy-1.23.5.tar.gz (10.7 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 53.5 MB/s eta 0:00:00 Installing build dependencies: started Installing build dependencies: finished with status 'done' Getting requirements to build wheel: started Getting requirements to build wheel: finished with status 'error' error: subprocess-exited-with-error
> 
> ```
>     × Getting requirements to build wheel did not run successfully.
>     │ exit code: 1
>     ╰─> [33 lines of output]
>         Traceback (most recent call last):
>           File "/home/rks5854/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>             main()
>           File "/home/rks5854/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>             json_out['return_val'] = hook(**hook_input['kwargs'])
>                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>           File "/home/rks5854/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
>             backend = _build_backend()
>                       ^^^^^^^^^^^^^^^^
>           File "/home/rks5854/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
>             obj = import_module(mod_path)
>                   ^^^^^^^^^^^^^^^^^^^^^^^
>           File "/home/rks5854/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
>             return _bootstrap._gcd_import(name[level:], package, level)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>           File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>           File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>           File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
>           File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>           File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>           File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>           File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>           File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>           File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>           File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>           File "/tmp/pip-build-env-j_j4dfys/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
>             import setuptools.version
>           File "/tmp/pip-build-env-j_j4dfys/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
>             import pkg_resources
>           File "/tmp/pip-build-env-j_j4dfys/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
>             register_finder(pkgutil.ImpImporter, find_on_path)
>                             ^^^^^^^^^^^^^^^^^^^
>         AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
>         [end of output]
>   
>     note: This error originates from a subprocess, and is likely not a problem with pip.
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> See above for output.
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

This suggests that it’s also the wrong pip as it’s handling other things like parmed that wouldn’t be in the new prody environment

**Comment by jamesmkrieger** [comment]
It seems to be related to a python 2.7 from amber

**Comment by atbogetti** [comment]
@rks5854 Do you have amber installed through `module load amber` on your cluster? Or did you do a local install? Amber downloads and sets up its own miniconda during compilation and that can sometimes interfere with conda environments. I suspect there are some crossed wires here involving amber's python and the local miniconda you have installed. If you are using modulefiles, could you send to output of `module list`? When I module load amber on my cluster, both my python and pip are from amber's minconda and I have to module unload amber before I can use my python and pip, even when I have a conda env activated amber will override that. If you don't have amber installed through modulefile, do you source amber.sh in your bashrc or similar startup file? You could try commenting that line out, re-logging in to reset your environment and see if `which python` and `which pip` both point to your conda environment's versions.

**Comment by atbogetti** [comment]
Just as an example, on my local cluster, I have to `module load amber` to use amber, so I have that "off" by default. I have a local install of miniconda3 in which I made a new conda env for prody `conda create -n prody -c conda-forge prody python=3.8`. I don't install through pip, I usually use conda. If I want to use amber after this, I have to `module load amber` and that will "take over" my python paths so I run my amber programs than after that I have to `module unload amber` to use prody again.

**Comment by rks5854** [comment]
tried running ipython using the full path, result is the same neighbor_get_count error.

python and pip match 
![image](https://github.com/prody/ProDy/assets/170653735/77739d7c-8b0e-498f-a225-0207fffbffbe)

i am unsure how to determine what you are asking about amber - this computer and most of the software on it predates me in the lab. since typing module list gives "bash: module: command not found", i think this means it was a local install. in my amber scripts, i do not explicitly call any function - below is one of my energy minimization scripts 
![image](https://github.com/prody/ProDy/assets/170653735/329d8450-8528-47c5-82b3-52466e29fecd)

**Comment by jamesmkrieger** [comment]
oh, there a problem that your ipython is still using a wrong prody: e.g. /data/rks5854/rxr-fxr/prody/dynamics/gnm.py

**Comment by rks5854** [comment]
(thank you for the prompt responses! i am going to be out of my office for a few hours so don't feel time pressure for now)

**Comment by jamesmkrieger** [comment]
> (thank you for the prompt responses! i am going to be out of my office for a few hours so don't feel time pressure for now)

I will offline for the rest of today now as it's getting towards dinner time here in Spain

**Comment by rks5854** [comment]
I attempted pip install -Ue prody but am definitely having issues caused by files being in the same wd as my data. Will attempt again after download into /usr/bin

**Comment by jamesmkrieger** [comment]
no, don't use /usr/bin - you won't have non-admin access there

You could go inside the prody directory and activate your prody environment and run `python setup.py build_ext --inplace --force` and `pip install -Ue .`

**Comment by rks5854** [comment]
this worked, thank you! other than using conda activate py39_prody before ipython, is there any other step i need to do to run this program in the future?

**Comment by jamesmkrieger** [comment]
Great!

nope, activating the environment should be it

issue closed
