### ISSUE TITLE
Incompatibility with latest SciPy version 1.14.0 

### ISSUE THREAD

**Issue by melschneider** [prody/ProDy#1906]
Hi, I just wanted to point this out in case you haven't noticed, yet.

The ProDy NMA modules are incompatible with the latest SciPy version 1.14.0, as according to the [release notes](https://docs.scipy.org/doc/scipy-1.14.0/release/1.14.0-notes.html#scipy-1-14-0-release-notes) "The turbo and eigvals arguments from scipy.linalg.{eigh,eigvalsh} have been removed." 
SciPy version 1.13.1 still works with ProDy, but when trying to run it with SciPy version 1.14.0 one gets the error:
`TypeError: eigh() got an unexpected keyword argument 'turbo'`.

**Comment by jamesmkrieger** [comment]
Thanks for the reminder. I did see some deprecation warnings about that at some point.

@atbogetti, how about we update the requirements for now?

**Comment by atbogetti** [comment]
@jamesmkrieger That sounds good to me. Thanks.

**Comment by jamesmkrieger** [comment]
The fix pull request should be ready now. The first commit wasn't enough
