### ISSUE TITLE
compatibility between tutorial data and generated data

### ISSUE THREAD

**Issue by juliaggggggg55555** [prody/ProDy#1909]
When carrying out the ensemble tutorial, following exactly the same steps provided, the calculated PCA values ​​were different from the tutorial. how to solve?

**Comment by jamesmkrieger** [comment]
Can you give more detail of what you mean so we can try to reproduce it please?

**Comment by juliaggggggg55555** [comment]
In [23]: abs(svd.getEigvals()[:20] - pca.getEigvals()).max()
Out[23]: 6.661338147750939e-15

In [24]: abs(svd.getEigvals()[:20] - pca.getEigvals()).max()
Out[24]: 6.661338147750939e-15

In [25]: abs(calcOverlap(pca, svd).diagonal()[:20].min())
Out[25]: 1.0000000000000009

In [26]: writeNMD('ubi_pca.nmd',pca[:3], ubi)
Out[26]: 'ubi_pca.nmd'

In [27]: for mode in pca[:4]:
    ...:     print(calcFractVariance(mode).round(3))
    ...:
0.134
0.094
0.083
0.065
these are the results I got.



These are the ones on the website and in the tutorial

In [19]: abs(svd.getEigvals()[:20] - pca.getEigvals()).max()
Out[19]: 7.105427357601002e-15

In [20]: abs(calcOverlap(pca, svd).diagonal()[:20]).min()
Out[20]: 0.9999999999999993

**Comment by jamesmkrieger** [comment]
These are essentially the same numbers. Maximum difference in eigvals is 0 and absolute minimum overlap is 1.
