### ISSUE TITLE
IndexError in searchPfam('xxx')

### ISSUE THREAD

**Issue by devinity1337** [prody/ProDy#192]
I try to use the searchPfam command, just following the tutorial. It says that it completes the search, but right after it gives me an IndexError: child index out of range. 

I don't know how to fix this problem. Error picture attached.
![error](https://cloud.githubusercontent.com/assets/7354486/2751074/c8e359b6-c8ae-11e3-8b33-da5734d1e7f4.png)

**Comment by cihankayacihan** [comment]
This issue is fixed with release of version 1.6.
