### ISSUE TITLE
Cannot Find/Import Interactions module

### ISSUE THREAD

**Issue by ZlatomirTodorov** [prody/ProDy#1924]
Hello,

I have freshly updated (using pip) to prody2.4.1 in a conda environment.
I would like to use the Interactions() module. However, I cannot follow the tutorial because:
(ipython pylab session and the same happens in jupyter notebook)
----> 1 interactions = Interactions()
NameError: name 'Interactions' is not defined.

When I search prody.proteins there is no module 'interactions' or alike (decided to search there as pointed by: http://www.bahargroup.org/prody/manual/reference/proteins/interactions.html#prody.proteins.interactions.Interactions.calcProteinInteractions).
However, in prody.proteins there is the waterbridges.py, this module is listed along InSty onto the Prody home page.

Could you please provide me with instruction on how to import and initialize the Interactions class?

Kind regards,
Zlatomir

**Comment by jamesmkrieger** [comment]
Hello,

Do other prody functionalities work?

**Comment by ZlatomirTodorov** [comment]
Hello James,

Yes, I used ProDy 2.4.0 for about a year or more. Basic use: PDB files manipulations, protein contacts detection , protein 3D transforms and assembling of protein model into single file. All works smoothly.
This is what I have under prody.proteins

***@***.***
And when I attempt to initialize:  Interactions = Interactions()
I get: ImportError: cannot import name 'interactions' from 'prody' (/home/---/anaconda3/envs/---/lib/python3.11/site-packages/prody/__init__.py)

Like the module is not included in the distro. I have just updated using pip within my conda environment.

Cheers,
Zlatomir

**Comment by jamesmkrieger** [comment]
You're right. interactions is missing from prody/proteins/__init__.py in version 2.4.1

Can you do a development install from github instead?

We are still finalising everything with insty and watfinder before making the next release.

Best wishes
James

**Comment by ZlatomirTodorov** [comment]
Thank you for your prompt response!

I noticed that on Git the init.py imports interacations module.
I was simply wondering if I should get the ProDy using pip after an uninstall or get the clone from GitHub (I’ll do the Git way as you suggested).

Best wishes,
Zlatomir

**Comment by jamesmkrieger** [comment]
Yes, please try the git way and let us know if it works

Best wishes
James

**Comment by ZlatomirTodorov** [comment]
Hello!

I got it working until displaying results from calcProteinInteractions(atoms).
Results are gatherer ok. I did not inspected in detail the detections. I will accept it as is and I’ll keep my dev ops around.

However, I had an issue with installing the clone inside my conda environament using : “pip –timeout 1000 git+git://github.com/prody/ProDy.git“ ==> Could not connect to git because of time out (change it to 1000 because the file is large and still failed). To have it working I’ve installed using “pip -U ProDy” under the anaconda env and then replaced the “/home/…/anaconda3/envs/…/lib/side-packages/prody/*” with the content of “ProDy-main/prody/*” from the git-downloaded zip.

Thanks a lot for the assistance, James! And to the team developing ProDy for the awesome software!!!

Kind regards,
Zlatomir

**Comment by jamesmkrieger** [comment]
I didn't know that was an option and I'm sorry it didn't work very well, but I'm glad you got something working in the end.

For future reference, what we usually do is replace `pip install -U prody` with `pip install -Ue .` inside the github directory. The e is for editable and the dot is for the current directory, so this means that it creates a link inside your conda directories to the github directory. This allows us to keep updating the code and having the changes reflected automatically.

You can see more information about this and other options at http://www.bahargroup.org/prody/manual/devel/develop.html

I'll close the issue for now. Please feel free to open it again if you have a related problem or create a new one for something else.

Best wishes
James
