### ISSUE TITLE
showprotein freezing matplotlib

### ISSUE THREAD

**Issue by ahoang519** [prody/ProDy#193]
I'm going through the tutorial for ProDy, but I hit a speedbump every time I try showprotein(p38). The plot would pop up, but there would be an empty gray box and the module would then freeze, forcing me to force close it. I tried running ProDy without importing pylab or ion() and the protein image does show, but I still get the freezing issue.

I am running this on Python 2.7 and Windows 7.

**Comment by cihankayacihan** [comment]
Matplotlib update is already solved this problem.
