### ISSUE TITLE
Troubleshooting COMD on ProDy with VMD 1.9.2

### ISSUE THREAD

**Issue by amarye** [prody/ProDy#1930]
Here's the corrected version of the sentence:

I am trying to use COMD on ProDy. I have installed COMD as instructed using VMD 1.9.2. I am using the tutorial files. When I tried to prepare the files, I got the following error:

Unable to load file 'init.pdb' using file type 'pdb'.
Unable to load file 'init.pdb' using file type 'pdb'.
    while executing
"mol new init.pdb"
    (procedure "::comd::Prepare_system" line 95)
    invoked from within
"::comd::Prepare_system"
    invoked from within
".comdgui.main_frame.prepare.button invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .comdgui.main_frame.prepare.button"
    (command bound to event)

Could you please help me with this issue?

**Comment by jamesmkrieger** [comment]
Did you use the version of comd on the prody website? You could perhaps try the GitHub version and see if that works better.

Do you have any more details on the error?

**Comment by amarye** [comment]
I have used input files along with the tutorial on the ProDy website. However, I encountered an error. I do not know why I got this error.
 
![1_conda_list](https://github.com/user-attachments/assets/e35291c0-a14f-40d8-9075-abf3e1b7e0bf)
![2_comd](https://github.com/user-attachments/assets/d16561b5-d97e-4379-92b4-bda9699cac77)
[3_error.log](https://github.com/user-attachments/files/16536894/3_error.log)
![4_error](https://github.com/user-attachments/assets/bf6ad853-81c6-4271-847f-ac973c9f9ee7)
[test.log](https://github.com/user-attachments/files/16536896/test.log)

**Comment by jamesmkrieger** [comment]
Looks like it might be a file permissions error. Can you definitely save files to that folder from vmd?

**Comment by jamesmkrieger** [comment]
The problem is that it can’t write the file init.pdb

**Comment by amarye** [comment]
It is working now. I have used `sudo ./vmd`. Thank you a lot.

**Comment by jamesmkrieger** [comment]
Ok, good to know. It’s better practice to use a different directory probably
