### ISSUE TITLE
Re-Install

### ISSUE THREAD

**Issue by rks5854** [prody/ProDy#1939]
Hello,

Thank you for being so helpful last time I had issues!

My system has been upgraded from CentOS 7 to Rocky 8, and then the home storage had to be completely wiped because something was weird (nobody knows what).

Although I retained all my prody files, I cannot seem to use prody and my department IT is stumped. I attempted to reinstall prody using pip install prody, and got this error:
![image](https://github.com/user-attachments/assets/691c7bd0-8eef-45fd-b950-3e0a1e5ede4c)

Earlier, I got an error saying I need matplotlib to install pylab, but I cannot seem to install matplotlib either. 
![image](https://github.com/user-attachments/assets/641e64eb-2a79-4920-abea-64460fc8574f)

Please let me know if you have any idea what is happening!

Thanks

**Comment by jamesmkrieger** [comment]
Looks like you haven’t got your compilers installed or configured properly

**Comment by rks5854** [comment]
Thank you! This information helped IT fix and I was able to get past the import statements. I am still not able to use all functions, but am unsure whether I will need more from you or not

![image](https://github.com/user-attachments/assets/f279b039-378e-4c70-8073-166e34bfee41)

**Comment by jamesmkrieger** [comment]
You have a typo. It should be parsePDB not parsePSB

did you install it on a different terminal? This terminal is still showing a problem with the gcc compiler

**Comment by rks5854** [comment]
![image](https://github.com/user-attachments/assets/527815fa-4481-40ba-948d-60dbaa6963c3)

Should have been the same terminal and everything. When my OS was updated they told me it was on a physically different piece of hardware than where I am now

**Comment by jamesmkrieger** [comment]
Strange. Try uninstalling it and installing it again maybe?

**Comment by jamesmkrieger** [comment]
I meant terminal window not terminal machine

**Comment by rks5854** [comment]
Thank you!

In the most recent screenshot, the compiler error is from the previous attempt. That was fixed.

Currently, my problem is with the ion() function, where it says interactive mode is on despite the error. I am also unable to generate a graph. I can go through making a GNM, getting the Kirchhoff matrix, calculating modes, etc. but showMode(gnm[0], hinges=True, zero=True) does not produce any image. I am in the same directory on the local desktop (not remote access) as before. 

![image](https://github.com/user-attachments/assets/78b4fd13-505a-4e30-82e7-7bdaa2730df7)

**Comment by jamesmkrieger** [comment]
I’m glad prody itself is working now.

now you have a matplotlib error. Try changing the matplotlib backend maybe. Your previous error seems to be related to that. Figures are probably being generated and just not shown to you properly. It probably even works to use plt.savefig to save them

You can try this 

import matplotlib
matplotlib.use('qtagg')

This should override the matplotlibrc

**Comment by rks5854** [comment]
Thank you, that worked!

**Comment by jamesmkrieger** [comment]
Great!
