### ISSUE TITLE
calcANM does not pass zeros argument to calcModes

### ISSUE THREAD

**Issue by toliwa** [prody/ProDy#194]
The calcANM method in prody.dynamics.anm has a zeros argument to determine if the zero eigenvalue modes are to be calculated.

    def calcANM(pdb, selstr='calpha', cutoff=15., gamma=1., n_modes=20,
                zeros=False):

This method calls calcModes, but does not pass the zeros argument to it.

    anm.calcModes(n_modes)

This is a bug, it should be:

    anm.calcModes(n_modes, zeros=zeros)

**Comment by SHZ66** [comment]
Already fixed. Thank you!
