### ISSUE TITLE
parseDSSP and parseSTRIDE do not consider biomolecule construction

### ISSUE THREAD

**Issue by nmih** [prody/ProDy#195]
When running either execDSSP or execSTRIDE after constructing a biomolecule, the .dssp and .stride files created are correct, but parsing the files using parseDSSP/parseSTRIDE produces empty numpy arrays. This is because the line:

```
res = ag[(line[11], int(line[5:10]), line[10].strip())]
if res is None:
    continue
```

produces ``` res = None ``` for every residue since the ```AtomGroup``` biomolecule assigns segments for repeating chains. 

A fix would be to have these functions check if they are parsing a DSSP file which was generated from a biomolecule, and in that case have:
```
res = ag[(segId, line[11], int(line[5:10]), line[10].strip())]
```
with segId being the segment letter in the biomolecule. For now I am just using the exec functions to make the DSSP and STRIDE files and analyzing the files independently.

**Comment by cihankayacihan** [comment]
This issue was addressed in one of the old versions. With get data function, the results are not empty arrays instead it is the parsed version.
