### ISSUE TITLE
GNM works but not ANM

### ISSUE THREAD

**Issue by rks5854** [prody/ProDy#1952]
Hi,

Thank you for having been so helpful before.

After the re-install, I did multiple GNM calculations. Unfortunately, trying to do ANM on one of the same systems has led to this message (preceeded by my input)

In [1]: from prody import *

In [2]: from pylab import *

In [3]: fex = parsePDB('comp_min.pdb')
@> 136109 atoms and 1 coordinate set(s) were parsed in 1.77s.

In [4]: fex_ca = fex.select('calpha')

In [5]: fex_anm = ANM('fex_ca')

In [6]: fex_anm.buildHessian('fex_ca')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/miniconda3/envs/py39_prody/lib/python3.9/site-packages/prody/dynamics/anm.py:110, in ANMBase.buildHessian(self, coords, cutoff, gamma, **kwargs)
    108 try:
    109     coords = (coords._getCoords() if hasattr(coords, '_getCoords') else
--> 110               coords.getCoords())
    111 except AttributeError:

AttributeError: 'str' object has no attribute 'getCoords'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
File ~/miniconda3/envs/py39_prody/lib/python3.9/site-packages/prody/utilities/checkers.py:34, in checkCoords(coords, csets, natoms, dtype, name)
     33 try:
---> 34     ndim, shape = coords.ndim, coords.shape
     35 except AttributeError:

AttributeError: 'str' object has no attribute 'ndim'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/py39_prody/lib/python3.9/site-packages/prody/dynamics/anm.py:113, in ANMBase.buildHessian(self, coords, cutoff, gamma, **kwargs)
    112 try:
--> 113     checkCoords(coords)
    114 except TypeError:

File ~/miniconda3/envs/py39_prody/lib/python3.9/site-packages/prody/utilities/checkers.py:36, in checkCoords(coords, csets, natoms, dtype, name)
     35 except AttributeError:
---> 36     raise TypeError('coords must be a numpy.ndarray instance')
     38 ndims = CSETS_NDIMS if csets else COORDS_NDIM

TypeError: coords must be a numpy.ndarray instance

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 fex_anm.buildHessian('fex_ca')

File ~/miniconda3/envs/py39_prody/lib/python3.9/site-packages/prody/dynamics/anm.py:115, in ANMBase.buildHessian(self, coords, cutoff, gamma, **kwargs)
    113         checkCoords(coords)
    114     except TypeError:
--> 115         raise TypeError('coords must be a Numpy array or an object '
    116                         'with `getCoords` method')
    118 cutoff, g, gamma = checkENMParameters(cutoff, gamma)
    119 self._reset()

TypeError: coords must be a Numpy array or an object with `getCoords` method

Please let me know what I can do to remedy this. Thanks!

**Comment by jamesmkrieger** [comment]
The problem is that you provided a string to buildHessian instead of an Atomic object

You have `fex_anm.buildHessian('fex_ca')` with inverted commas around `fex_ca`. What you should have is `fex_anm.buildHessian(fex_ca)` without the inverted commas

Sorry if some tutorial gave them the same name and caused this confusion

**Comment by rks5854** [comment]
OMG I feel dumb. Thanks

**Comment by jamesmkrieger** [comment]
No worries. These things happen sometimes
