### ISSUE TITLE
Error using calcModes()

### ISSUE THREAD

**Issue by Tuyt691** [prody/ProDy#1955]
Hello,
I'm new to prody and I am currently completing the tutorial. My problem is at the Dynamic analysis > PCA calculation, when we want to calculate modes ( `pca.calcModes()`). I get the following error when running the code : `eigh() got an unexpected keyword argument 'turbo'` . Before this command, everything was ok.
I am using python 3.10.14 and prody 2.4.1.
How to solve this issue ?

**Comment by Tuyt691** [comment]
The same error occurs when trying to pass `anm, atoms = calcANM(ubi_selection, selstr='calpha')`.

**Comment by jamesmkrieger** [comment]
Hello, the problem is that you are using a new version of numpy and prody doesn't support that yet. Please try the following
 `pip install numpy==1.23.5`

We have fixed this in the development version of prody but haven't yet sent it to a release

**Comment by DaddyDaddyFish** [comment]
I have the exact same problem. Have tried reinstalling numpy and prody for several times but no luck:

```
$ prody anm 2k39.pdb
@> 1231 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> 76 atoms will be used for ANM calculations.
@> Using gamma 1.0
@> Using cutoff 15.0
@> Hessian was built in 0.02s.
Traceback (most recent call last):
  File "/virtual/venv/bin/prody", line 8, in <module>
    sys.exit(prody_main())
  File "/virtual/venv/lib/python3.10/site-packages/prody/apps/prody_apps/__init__.py", line 58, in prody_main
    namespace.func(namespace)
  File "/virtual/venv/lib/python3.10/site-packages/prody/apps/prody_apps/prody_anm.py", line 341, in <lambda>
    subparser.set_defaults(func=lambda ns: prody_anm(ns.__dict__.pop('pdb'),
  File "/virtual/venv/lib/python3.10/site-packages/prody/apps/prody_apps/prody_anm.py", line 110, in prody_anm
    anm.calcModes(nmodes, zeros=zeros, turbo=turbo, nproc=nproc)
  File "/virtual/venv/lib/python3.10/site-packages/prody/dynamics/anm.py", line 230, in calcModes
    values, vectors, vars = solveEig(self._hessian, n_modes=n_modes, zeros=zeros,
  File "/virtual/venv/lib/python3.10/site-packages/prody/utilities/eigtools.py", line 99, in solveEig
    values, vectors = _eigh(M, eigvals, turbo)
  File "/virtual/venv/lib/python3.10/site-packages/prody/utilities/eigtools.py", line 43, in _eigh
    values, vectors = linalg.eigh(M, turbo=turbo, eigvals=eigvals)
TypeError: eigh() got an unexpected keyword argument 'turbo'
```

I installed prody under venv but I also tried installing it directly. The error is the same.

**Comment by jamesmkrieger** [comment]
Try downgrading scipy too. Linalg could be from either of them

**Comment by jamesmkrieger** [comment]
Scipy 1.11.4 should still have turbo and the latest one doesn’t

**Comment by jamesmkrieger** [comment]
It is removed in scipy 1.14.0: “ The turbo and eigvals arguments from scipy.linalg.{eigh,eigvalsh} have been removed.”

We have this info in earlier versions: “ Deprecated since version 1.5.0: 'eigvalsh' keyword argument turbo is deprecated in favor of driver=gvd option and will be removed in SciPy 1.14.”

I’ll add a try/except block for this but in the meantime any scipy < 1.14.0 should work

**Comment by DaddyDaddyFish** [comment]
> It is removed in scipy 1.14.0: “ The turbo and eigvals arguments from scipy.linalg.{eigh,eigvalsh} have been removed.”
> 
> We have this info in earlier versions: “ Deprecated since version 1.5.0: 'eigvalsh' keyword argument turbo is deprecated in favor of driver=gvd option and will be removed in SciPy 1.14.”
> 
> I’ll add a try/except block for this but in the meantime any scipy < 1.14.0 should work

This works. Thank you so much!!

**Comment by jamesmkrieger** [comment]
You're welcome

**Comment by siljesne** [comment]
I also get an error using anm.calcModes(), the error: TypeError: eigh() got an unexpected keyword argument 'turbo'. I have downgraded numpy to 1.23.5 and scipy to 1.13.1, how can I solve this issue?

**Comment by jamesmkrieger** [comment]
Maybe double check that the numpy and scipy downgrade has really worked in the right environment. It sometimes happens that things get mixed up.

alternatively, you could make a development installation of prody from GitHub. The fix is merged so should be accessible in the main branch

**Comment by MigueLugo** [comment]
Hi!
I got the same problem using Python 10.
and it was solved by using:
pip install numpy==1.23.5
pip install Scipy==1.13.1     (1.14.0 did not work)

ah, and don't forget to restart the kernel

**Comment by jamesmkrieger** [comment]
> Hi! I got the same problem using Python 10. and it was solved by using: pip install numpy==1.23.5 pip install Scipy==1.13.1 (1.14.0 did not work)
> 
> ah, and don't forget to restart the kernel

This is the expected behaviour. The released version of ProDy still has the turbo keyword and requires the older scipy.

Why are you telling us this?

**Comment by MigueLugo** [comment]
> > Hi! I got the same problem using Python 10. and it was solved by using: pip install numpy==1.23.5 pip install Scipy==1.13.1 (1.14.0 did not work)
> > ah, and don't forget to restart the kernel
> 
> This is the expected behaviour. The released version of ProDy still has the turbo keyword and requires the older scipy.
> 
> Why are you telling us this?

Well, I thought that it could be useful to someone else...  sorry

**Comment by pegerto** [comment]
If my undestanding is correct, Spicy uses both numpy ans scipy as linear algebra providers

https://github.com/prody/ProDy/blob/main/prody/utilities/misctools.py#L227-L238


It will prefer spacy over numpy, so if you have spicy install you need to make sure you downgraded it or installed so it takes preference over numpy 

```
pip install scipy==1.13.1
```

**Comment by jamesmkrieger** [comment]
Yes, it needs numpy for some things but can use scipy preferentially for linear algebra
