### ISSUE TITLE
Pytorch 2.4 compatibility

### ISSUE THREAD

**Issue by itrase** [prody/ProDy#1956]
The latest versions of ProDy require numpy<1.24, which is now almost 2 years old. This breaks compatibility with modern versions of many popular packages, including PyTorch. Are there plans to update this dependency to allow 1.26.4 or higher?

**Comment by jamesmkrieger** [comment]
yes, there are plans to do it at some point but we all have lots of things on our plates, so no idea when we'll complete it

**Comment by jamesmkrieger** [comment]
we already have issues about this e.g. #1915 and #1594, so I'm closing this one
