### ISSUE TITLE
Obsolete PDB entries are not mapped to the newer versions

### ISSUE THREAD

**Issue by nmih** [prody/ProDy#196]
Currently when using parsePDB for a PDB entry that has been obsoleted (example: 2BPL), the function throws an 'IOError: PDB file for 2BPL could not be downloaded.') It would be a nice enhancement for it to either somehow download the obsolete entry or download the newer version (in this case 4AMV).

**Comment by SHZ66** [comment]
Now `parsePDB` is able to download obsolete PDBs. We may also add a function to redirect to the new PDB ID in the future.
