### ISSUE TITLE
PRS for Trajectory Analysis Problem

### ISSUE THREAD

**Issue by vahapgazifidan** [prody/ProDy#1980]
Hello,

I want to use PRS for trajectory analysis. First, I do PCA analysis covering all modes. I use the covariant matrix that I obtained as a result of the analysis for analysis. However, when I complete the calculations, I observe that the matrix values ​​are very high (for example 40, 250).

**Comment by jamesmkrieger** [comment]
Hello, 

It’s absolutely fine for the 3Nx3N unnormalised covariance matrix to have high values. This should be fine for PRS. 

If just a few residues have such high values such as loops or termini then you may want to exclude them from the analysis. You can check this by visualising the PCA modes in VMD.

It’s also possible this is due to an issue with the iterative structural superposition step. You may want to repeat that with a particular subset of residues instead or as well.

**Comment by jamesmkrieger** [comment]
I think those values are ok. It’s not that implausible that a residue is 37.8 times more sensitive to perturbations at another site than perturbations directly at that site. Collective motions of domains could lead to large motions at a distance. 

I don’t think the code would help much with diagnosing why you have the behaviour that you do. It’s the input modes that would really determine the results. You’re welcome to share them as an nmd file by email to jamesmkrieger@gmail.com and I can have a glance and see if there’s anything strange there. You can share the code too if you like

**Comment by vahapgazifidan** [comment]
Dear James,

Firstly, thank you very much for your time and assistance. Following our conversation last Tuesday, I have sent the files to you via email. I was wondering if you have had a chance to review them. I sincerely appreciate your help and guidance.

**Comment by jamesmkrieger** [comment]
Hello,

unfortunately I haven’t had a chance yet. It’s been quite a busy week and this coming week will be too. Sorry!

hopefully, I’ll get to it late in the week or early the following week

**Comment by jamesmkrieger** [comment]
Actually, I've managed to have a look now.

The motions in the first 10 modes look very reasonable to me and there clearly is some large relative motion of some domains compared to a very rigid core so it does make sense that you should have some very large and very small numbers. There are no tip effects in the first 20 modes and by then the contribution has fallen to <0.5% of the variance so I wouldn't worry.

The reason for the very high numbers in your final PRS matrix is that the covariance matrix is getting squared so the small numbers become even smaller and then, after summing over the 3x3 blocks, there's a normalisation by the diagonal, which means dividing everything by these really small numbers. 

I think this is absolutely fine, but if you're concerned that this isn't right then you're welcome to try using calcPerturbResponse with turbo=False to directly perturb the covariance with forces instead. In theory it should give the same results in the limit of a large number of random perturbation but perhaps you get something you're happier with in the case of using a smaller number of perturbations.

Best wishes
James

**Comment by vahapgazifidan** [comment]
Dear James,

Thank you very much for reviewing the results. I am delighted to hear that the results are accurate, and I will proceed to incorporate this study into the article I am preparing with my advisor. I am truly grateful for your assistance.

Yours Sincerely,
Vahap

**Comment by jamesmkrieger** [comment]
You’re welcome. Good luck with the manuscript!
