### ISSUE TITLE
backbone atom connectivity is missing in output ensemble pdb files 

### ISSUE THREAD

**Issue by rrchaudhari** [prody/ProDy#201]
Some of the residues in output files are not connected to the protein chain. Wondering what I am missing. 
 
I am using following code. 
#USAGE: python ensembl.py p38.pdb
from prody import *
from pylab import *
import os,sys, subprocess
from prody.utilities import which
import glob
from multiprocessing import Pool
from matplotlib import pyplot as plt
prot = parsePDB(sys.argv[1])
prot_ca=prot.ca 
prot_anm=ANM('prot ca') 
prot_anm.buildHessian(prot_ca) 
prot_anm.calcModes(n_modes=20) 
writeNMD('prot_anm.nmd', prot_anm, prot_ca) 
prot_anm_ext, prot_all = extendModel(prot_anm, prot_ca, prot, norm=True) 
ens = sampleModes(prot_anm_ext, atoms=prot.protein, n_confs=40, rmsd=1.0)
prot.addCoordset(ens.getCoordsets())
prot.all.setBetas(0)
prot.ca.setBetas(1)
prot.ca == prot.beta_1
subprocess.call(["mkdir", "prot_ensemble"])
for i in range(1, prot.numCoordsets()):
    fn = os.path.join('prot_ensemble', 'prot_' + str(i) + '.pdb')
    writePDB(fn, prot, csets=i)

**Comment by cihankayacihan** [comment]
When you pick the protein structure, it has hydrogen atoms. When you pick prot.protein it will reduce the number. You need to get only protein atoms in both ensemble and the protein structure. Basically, you need to pick the protein atoms and save it as another atom group.
