### ISSUE TITLE
PCA Calc. Error from VMD Wizard

### ISSUE THREAD

**Issue by ah7391** [prody/ProDy#204]
I'm trying to run a prody calc. from the NM Wizard in VMD.

I keep getting this error:
    while executing
"animate write dcd $pdbfn beg $::NMWiz::prodyFirstFrame end $end skip $::NMWiz::prodySkipFrame waitfor all sel $sel $::NMWiz::prodyMolid"
    (procedure "::NMWiz::prodySubmitPCAjob" line 29)
    invoked from within
"::NMWiz::prodySubmitPCAjob"
    (procedure "::NMWiz::prodySubmitJob" line 24)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

Let me know what other info. you may need. Thanks in advance!

**Comment by cihankayacihan** [comment]
I know it has been a long time but if you still have same issue please let us know.

**Comment by pt19** [comment]
Hi,
I am having following error when I clicked submit Job in ProDy Interface of NMWiz (in vmd 1.9.2). Please help.

Thank you 

<img width="337" alt="screen shot 2018-06-05 at 1 23 48 pm" src="https://user-images.githubusercontent.com/39964063/40992080-b54d6e78-68c3-11e8-9d0e-ae971a84b54d.png">

@> Building covariance [100%] 0s
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody {*}$args"
    (procedure "::NMWiz::prodySubmitPCAjob" line 61)
    invoked from within
"::NMWiz::prodySubmitPCAjob"
    (procedure "::NMWiz::prodySubmitJob" line 26)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)
