### ISSUE TITLE
NMWiz Window does not show options for Modes and Animation

### ISSUE THREAD

**Issue by biocheming** [prody/ProDy#205]
I tried to load gnm file or calculated through the NMWiz. However, in the window of 'NMWiz - $title', there's no options for:
under $title, 
1. scaling and RMSD;
2. Atom selection;
under 'Actions'
3.  Modes;
4. Animation.

and what's the varible ndim meaning ?
Thank you!

**Comment by cihankayacihan** [comment]
GNM is a 1D model and the information that you get is mean square fluctuations for each residue. You can not have any other info from a 1D model.
