### ISSUE TITLE
import error in vmd nmwiz

### ISSUE THREAD

**Issue by rajibio** [prody/ProDy#206]
Dear Sir,
When i am trying to use prody interface from vmd NMWIz i get the following error. 

Traceback (most recent call last):
  File "/usr/local/bin/prody", line 24, in <module>
    path = [imp.find_module('prody')[1]]
ImportError: No module named prody
Traceback (most recent call last):
  File "/usr/local/bin/prody", line 24, in <module>
    path = [imp.find_module('prody')[1]]
ImportError: No module named prody
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody anm --quiet -s all -o "$::NMWiz::outputdir" -p "$prefix" -n $::NMWiz::prodyNModes -c $::NMWiz::prodyCutoff -g $::..."
    (procedure "::NMWiz::prodySubmitANMjob" line 32)
    invoked from within
"::NMWiz::prodySubmitANMjob"
    (procedure "::NMWiz::prodySubmitJob" line 20)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

And when i am doing from terminal: $python
import prody
i get 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named prody

But $python2.7
import prody works fine.

I installed prody with python2.7. However i have older versions of python also in my linux machine. Is that a problem? If so how can i specify which python to use from nmwiz?

Thank you,
Rajeswari

**Comment by cihankayacihan** [comment]
You have multiple versions of python. Some of them have prody and others not. Try to check version when you start python.
