### ISSUE TITLE
Why are trival modes changing depending on how many modes are requested?

### ISSUE THREAD

**Issue by toliwa** [prody/ProDy#207]
Depending on how many modes are requested to be calculated, the 6 trival (eigenvalue = 0) modes are changed. The non-trival modes remain the same. 

Why are the trival modes changed, shouldn't they also keep identical?

Code adapted straight from: http://prody.csb.pitt.edu/tutorials/enm_analysis/extend.html
Requesting an ANM with 2 non-trival normal modes and also the 6 trival ones.

    p38 = parsePDB('1p38')
    p38_ca = p38.select('calpha')
    anm = ANM('1p38')
    anm.buildHessian(p38_ca)
    anm.calcModes(n_modes=2, zeros=True)

Now a second ANM on the same protein, the only change is to request 3 non-trival modes:

    anm1 = ANM('1p38_1')
    anm1.buildHessian(p38_ca)
    anm1.calcModes(n_modes=3, zeros=True)

Look at the output below: anm.getEigvecs()[0][6] and anm1.getEigvecs()[0][6] are equal (0.039), they correspond to the first x displacement of the first atom of the first non-trival normal mode. Same for anm.getEigvecs()[0][7] and anm1.getEigvecs()[0][7], the values are equal.

BUT, some of the first six modes do not equal each other. Because of their zero eigenvalue, their relative order could be switched (or minus signed flipped), but there are completely different values!

I am putting rounded output below so it is easier to see.

Look at the value -0.08 in anm.getEigvecs()[0]. Its closest value to compare is  -0.074 from anm1.getEigvecs()[0] for example. Looking at the trivial modes in VMD shows that they are not the same displacement vectors, even if I compare them all against each other to account for relative order of zero eigenvalues.  Non-trival modes are not affected by this (as can be seen by comparing the last two elements of the arrays).

Why does ProDy calculate these trivial mode values different? 

    In [18]: anm.getEigvecs()[0].round(3)
    Out[18]: array([ 0.   , -0.002,  0.003, -0.004, -0.08 ,  0.004,  0.039, -0.045])
    In [19]: anm1.getEigvecs()[0][:8].round(3)
    Out[19]: array([-0.   , -0.   ,  0.002, -0.074, -0.03 ,  0.003,  0.039, -0.045])

    In [21]: anm.getEigvecs()[1].round(3)
    Out[21]: array([-0.064,  0.011, -0.001, -0.065, -0.033, -0.031,  0.009, -0.096])
    In [22]: anm1.getEigvecs()[1][:8].round(3)
    Out[22]: array([-0.064,  0.008, -0.014, -0.009, -0.073, -0.027,  0.009, -0.096])

**Comment by SHZ66** [comment]
Thank you for your input! This defect (if it is a defect) is on scipy's side. ProDy uses a function, [eigsh()](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.linalg.eigsh.html), to calculate a certain number of eigenvalues and eigenvectors, and if the eigenvalue is extremely small the function lost its accuracy, which is quite understandable that there will be always a level of numerical accuracy computer programs can reach. Therefore the order of the trivial modes may change in different calculations even though the only change is the number of modes you want to obtain.

You can however find the correspondence of trivial modes in anm and anm1 by using:
showOverlapTable(anm[:6], anm1[:6])
The pairs with high overlap will be the same modes in two calculations.
