### ISSUE TITLE
ImportError: No module named msaio

### ISSUE THREAD

**Issue by akwon** [prody/ProDy#209]
Hi,

I am trying to follow the Evolution Analysis tutorial (http://prody.csb.pitt.edu/tutorials/evol_tutorial/msaanalysis.html) and get this error:

>>> import numpy
>>> numpy.version.version
'1.7.1'
>>> from prody import *
>>> from pylab import *
>>> ion()
>>> msa=parseMSA('/home/esbg/Desktop/totnrtxTK.seq_aln.fasta')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "prody/sequence/msafile.py", line 535, in parseMSA
    from .msaio import parseFasta as parser
ImportError: No module named msaio

Any help? 

Thanks 
Annie

**Comment by protco** [comment]
Any solution to this problem? 
I just installed the current version and also encountered this when calling parseMSA.
Thanks!

**Comment by SHZ66** [comment]
Thank you for your input. I will work on fixing this if it is still existed in the current version.

**Comment by SHZ66** [comment]
It seems that the error is no longer existed in the current ProDy. I am not sure how was this fixed, but I cannot reproduce the error. Please post if the error still exists!

**Comment by SHZ66** [comment]
It occurs to me maybe the issue is because you didn't build the C code within the ProDy. To do so:
$ cd ProDy
$ python setup.py build_ext --inplace --force

Also see here:
http://prody.csb.pitt.edu/manual/devel/develop.html?highlight=github
