### ISSUE TITLE
Redisue iterator

### ISSUE THREAD

**Issue by comacke** [prody/ProDy#211]
Say I have a prody residue for the first residue in a pdb (with residue index 0). The ProDy Residue getPrev() method will return the last residue in the pdb instead of None. It's interesting to note that for the last residue in the pdb, the resNext() method will return none. This behavior does not appear consistent, but perhaps there is a reason for this. I would have expected it to return None in both cases. Here's an example.
```struct = parsePDB('4TS5')```
```chid = struct[0].getChid() # chain id for 1st residue in pdb - 'A' for this protein```
```resnum = struct[0].getResnum() # residue number for 1st residue in pdb - 2 for this protien```
```res = struct[chid, resnum] # get ProDy Residue```
```print res.getPrev() # would expect None here, but instead returns the last residue in the protein```

**Comment by cihankayacihan** [comment]
Thanks for this bug. We will address this as soon as possible.

**Comment by SHZ66** [comment]
Hi this is fixed in #309. Thank you!
