### ISSUE TITLE
searchPfam(sequence): ValueError: failed to parse results XML, check URL:

### ISSUE THREAD

**Issue by juhancires** [prody/ProDy#212]
I tried to follow Evol instruction but searchPfam() did not work giving the ValueError: failed to parse results XML.

**Comment by cihankayacihan** [comment]
This issue is due to the change in pfam database, currently this issue is fixed.

**Comment by TiagoLopesGomes** [comment]
Tried the same command and it gave the same above error.
thank you

**Comment by tylerbakke** [comment]
Unfortunately the error has come back.
