### ISSUE TITLE
How can I turn off the Logger in ipython notebook

### ISSUE THREAD

**Issue by jwillis0720** [prody/ProDy#214]
For some reason, I can shut off the logger just fine in a regular script but can't figure out how to do it in ipython notebook. Has anyone experienced this?

**Comment by cihankayacihan** [comment]
This is not Prody related issue. But for issue tracker you can use following link. Thanks. 

http://ipython.org/ipython-doc/dev/notebook/

**Comment by jwillis0720** [comment]
I think it is a prody related issue.

**Comment by cihankayacihan** [comment]
In here at the bottom Prody verbosity section may help. http://prody.csb.pitt.edu/tutorials/prody_tutorial/basics.html
