### ISSUE TITLE
Alternate locations warning/error messages

### ISSUE THREAD

**Issue by ntropia2** [prody/ProDy#215]
When following the tutorial about alternate locations [1] I get a lot of warning messages:

>>> from prody import *
>>> all_altlocs = parsePDB('1ejg', altloc=True)
@> PDB file is found in working directory (1ejg.pdb.gz).
@> WARNING failed to parse altloc 'B' at line 875, residue name mismatch (expected 'PRO', parsed 'SER')
@> WARNING failed to parse altloc 'B' at line 877, residue name mismatch (expected 'PRO', parsed 'SER')
@> WARNING failed to parse altloc 'B' at line 879, residue name mismatch (expected 'PRO', parsed 'SER')
@> WARNING failed to parse altloc 'B' at line 881, residue name mismatch (expected 'PRO', parsed 'SER')
@> WARNING failed to parse altloc 'B' at line 883, residue name mismatch (expected 'PRO', parsed 'SER')
@> WARNING failed to parse altloc 'B' at line 885, residue name mismatch (expected 'PRO', parsed 'SER')
@> WARNING failed to parse altloc 'B' at line 963, residue name mismatch (expected 'LEU', parsed 'ILE')
@> WARNING failed to parse altloc 'B' at line 967, residue name mismatch (expected 'LEU', parsed 'ILE')
@> WARNING failed to parse altloc 'B' at line 971, residue name mismatch (expected 'LEU', parsed 'ILE')
@> WARNING failed to parse altloc 'B' at line 975, residue name mismatch (expected 'LEU', parsed 'ILE')

[1] http://prody.csb.pitt.edu/tutorials/structure_analysis/pdbfiles.html#alternate-locations

**Comment by SHZ66** [comment]
Hi, these warnings are not a result of bugs or defects. These warnings are simply reminding that the residue names are different in alternative location entries. You can ignore the warnings in this case. Thanks!
