### ISSUE TITLE
How can I run prody in Windows?

### ISSUE THREAD

**Issue by ChaosChiao** [prody/ProDy#216]
I have installed python2.7,numpy1.9 and prody1.5 in Windows7. However, I dont know how to run prody. I write path C:\Python2.7 and C:\Python2.7\script in CMD. I input prody in python, but  it prompts "NameError: name 'prody' is not defined". How can I run prody?

**Comment by MonZop** [comment]
I also have a problem: Windows 64 bits, Python and Numpy all properly installed, but ProDy installer cannot find them.
Any clue?

**Comment by cihankayacihan** [comment]
We addressed this issue in new versions of Prody after 1.7.
