### ISSUE TITLE
i can't calculate different numbers of non-zero modes in gnm.calcModes()

### ISSUE THREAD

**Issue by xxxzxcvb** [prody/ProDy#217]
I tried to follow Elastic Network Models tutorials about always calculate all modes

In [13]: gnm.calcModes()
@> Scipy is not found, all modes are calculated.
@> 69 modes were calculated in 0.00s.

In [14]: gnm.calcModes(50, zeros=True)
@> Scipy is not found, all modes are calculated.
@> 70 modes were calculated in 0.00s.

**Comment by SHZ66** [comment]
Hi I noticed that in the warning message you do not have scipy installed. Installing scipy package will fix the problem. Without the package you can still use ProDy to calculate GNM modes but it will give you all the modes. Then you can get first, say, 50 modes by using index, e.g. first50eigvecs = GNM.getEigvecs()[:50].
