### ISSUE TITLE
why is probe.prm empty in druggui module?

### ISSUE THREAD

**Issue by dynamics77** [prody/ProDy#219]
Job below dies due to missing charmm params. Where are these params located?

namd2 min.conf

FATAL ERROR: DIDN'T FIND vdW PARAMETER FOR ATOM TYPE HB2
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: FATAL ERROR: DIDN'T FIND vdW PARAMETER FOR ATOM TYPE HB2

**Comment by cihankayacihan** [comment]
HB2 is not defined in the parameter file that we provided. If you want you can add lines those lines to your parameter file.

**Comment by jamesmkrieger** [comment]
I guess things are different now. Hongchun or Jiyoung, please comment.

**Comment by jamesmkrieger** [comment]
I'm assuming this is not an issue any more and closing it.
