### ISSUE TITLE
My Dimer is connected after NMA calculation

### ISSUE THREAD

**Issue by amanan00** [prody/ProDy#221]
I am using NMWiz to calculate NMA for my protein dimer. However, after NMA calculation last residue of one subunit is seen to be bonded with first residue of another subunit. I am using VMD plugin option for NMWiz and testing with default settings. How can I overcome this problem?
Thank you.

Anjela.

**Comment by cihankayacihan** [comment]
You can just remove that bond in VMD. In prody we assume that the residues are connected in an order. Obviously, it connects the last residue of the first subunit with the first residue of the second subunit. Assuming that the distance between those two residues are far from each other. They have no contribution to hessians or dynamics. Therefore, it is safe to choose that bond and remove.

**Comment by jamesmkrieger** [comment]
Basically it's a display issue and is not meaningful. The work around is to hide or remove the bond in VMD. This is the same issue as #364 and as I said there, we may work on a proper solution at some point but I think it unlikely. As we have the same issue twice, I'm closing this one.
