### ISSUE TITLE
Bug in the method getCoordsets() from  class "prody.Trajectory"

### ISSUE THREAD

**Issue by stevenio** [prody/ProDy#222]
There seems to be a bug in the method ".getCoordsets()" from "prody.Trajectory". The following simple test will not pass with the current ProDy:

```
import prody, numpy
traj = prody.Trajectory("my.dcd")

frameId = 1
coord1 = traj.getCoordsets(frameId)[0,:,:]
coord2 = traj.getCoordsets()[frameId,:,:]
diff = numpy.abs(coord1 - coord2)
assert numpy.sum(diff) < 1E-7
```

Note that this happens only for frame 1, not for frame 0  or other frames. Somehow frame 0 was used twice, both for frame 0 and 1. The actual frame 1 was skipped. 

Testing environment:
ProDy version: 1.5.1
Python version: 2.7.9
Numpy version: 1.9.1
Platform: MacOS 10.9
Test date: 02-08-2015

**Comment by cihankayacihan** [comment]
Thank you for input. We will try to solve this issue and let you know.

**Comment by SHZ66** [comment]
Hi, please see #299. It should fix the issue. Thank you!
