### ISSUE TITLE
Error message in VMD

### ISSUE THREAD

**Issue by aykdna** [prody/ProDy#223]
Hello to All,
I am trying to use NMWiz tool in VMD. It asks me to locate the prody file and then it gives me the following message. I would appreciate any help. Thanks.
  File "C:/Python27/Scripts/prody.bat", line 1
    %~dp0..\python %~dp0\prody %*
    ^
SyntaxError: invalid syntax
  File "C:/Python27/Scripts/prody.bat", line 1
    %~dp0..\python %~dp0\prody %*
    ^
SyntaxError: invalid syntax
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody anm --quiet -s all -o "$::NMWiz::outputdir" -p "$prefix" -n $::NMWiz::prodyNModes -c $::NMWiz::prodyCutoff -g $::..."
    (procedure "::NMWiz::prodySubmitANMjob" line 32)
    invoked from within
"::NMWiz::prodySubmitANMjob"
    (procedure "::NMWiz::prodySubmitJob" line 20)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

**Comment by Lizelle** [comment]
Hi aykdna,

I am getting the exact same error message when trying to do  PCA in NMWiz.  Did you ever get it to work when specifying the prody.bat file location?

Regards

Lizelle

**Comment by cihankayacihan** [comment]
please see #246
