### ISSUE TITLE
Virtual Screening and DrugGUI

### ISSUE THREAD

**Issue by satchmo001** [prody/ProDy#224]
Hi,

I've run several simulations using DrugGUI and the results seem very promising.  However, I would now like to run a virtual screening against the outputted results, and I'm a little lost as to how to accomplish this.  

Normally, if I have a known binding site, I would run my database against the binding site (or in this case, druggable or ligandable sites) to attempt to find a possible fit.  But, I can't seem to figure out how to get that to operate correctly in the DrugGUI output.

Would you have any information on how this might be accomplished?

Thank you for your help.

MH.

**Comment by sindra123** [comment]
Hi,

You will need to build a pharmacophore using the coordinates of the probes at the binding site.  Once you have that, you can use this to perform virtual screening.
Basically, replace each probe (which is just a carbon atom) at the binding site with the whole organic molecule that the probe represents.  

Indira

**Comment by jamesmkrieger** [comment]
This is something that is still a work in progress but perhaps one of you could describe what people can do so far and then close it please.

**Comment by jamesmkrieger** [comment]
What you need to do is indeed place a probe at each hotspot to generate something that can be submitted as a pharmacophore model for virtual screening. We are developing a toolkit for doing this more easily that should be available soon.

**Comment by jamesmkrieger** [comment]
We now have a tool called Pharmmaker that automates with analysis and finds the best combinations of protein and probe conformations that can be used as seeds for pharmacophore based virtual screening with Pharmit. See https://github.com/prody/pharmmaker.
