### ISSUE TITLE
Non-core probes

### ISSUE THREAD

**Issue by MigueLugo** [prody/ProDy#225]
Hi there

When I use the druggi command with another probes, the job halts when solvating the system, like this

 Command: solvate larvinapo_autopsf.psf larvinapo_autopsf.pdb -o apo6/intermediate -b 2.4 -x 11 -y 11 -z 11 +x 11 +y 11 +z 11 -spdb C:/Program Files (x86)/University of Illinois/VMD/plugins/noarch/tcl/drugui/probe.pdb -spsf C:/Program Files (x86)/University of Illinois/VMD/plugins/noarch/tcl/drugui/probe.psf -stop C:/Program Files (x86)/University of Illinois/VMD/plugins/noarch/tcl/drugui/probe2.top -ks "name OH2" -ws 62.3572 -rotate -rotinc 10 -rotsel {all}
Info) Usage: solvate <psffile> <pdbfile> <option1?> <option2?>...
Info) Usage: solvate <option1?> <option2?>...  to just create a water box

And that also happen even when I select the option -solvent yes (for default probes). However, using the GUI it works well for the core probes.

So, How can I make the command works for non-core probes??   Thanks in advanced

**Comment by jiyounglee22** [comment]
I don't think the command is working. If you want to use other probes (not default), see here: http://prody.csb.pitt.edu/tutorials/drugui_tutorial/cgenff.html. You can use TK console in VMD as explained in the tutorial.

**Comment by jamesmkrieger** [comment]
Seeing as no one has replied in 3 years and there is a solution of sorts as Jiyoung said, I'm closing this issue.
