### ISSUE TITLE
ProDy not working

### ISSUE THREAD

**Issue by Alaksh** [prody/ProDy#226]
Hi,

I am a new user for ProDy. When I try to Import ProDy I get the following error:

ImportError: CKDTree module could not be imported. Reinstall ProDy or install Biopythonto solve the problem. 

I tried reinstalling both ProDy and Biopython but neither seemed to solve the problem. Let me know what can be done.

Regards,
Alaksh

**Comment by odovad** [comment]
I had the same error. Installing Biopython solved the problem. Weird.
Did you use pip ?

**Comment by Alaksh** [comment]
Hi,

I am still facing The same issue with working with ProDy. And I did not use Pip to download it. 

I have tried reinstalling Prody and Biopython multiple times. Can I get some advise.

Regards,
Alaksh

**Comment by wzmao** [comment]
Did you use "python setup.py build" and then "sudo python setup.py install"?

**Comment by Alaksh** [comment]
No, I used to Prody windows installer

**Comment by wzmao** [comment]
Could you try to download the source code of prody, and then use the commands in cwd?

**Comment by wzmao** [comment]
You could go to #236 and have a try.

**Comment by Alaksh** [comment]
Hi, I tried the source code and used setu.py to install, but still facing the same issues. When i tried installing Biopython, it says that it could not find Visual Studio C++ in my path specified. So, currently, I am trying to find a fix for it.

**Comment by cihankayacihan** [comment]
Hi. You need to install biopython and it by default installs KDTree functions.

**Comment by cihankayacihan** [comment]
For biopython you need to use whl files if you want 64 bit version. You can use pip to install whl files and your prody will work. If you are using windows , it is likely the problem.
