### ISSUE TITLE
Installing Prody in Windows

### ISSUE THREAD

**Issue by Lizelle** [prody/ProDy#236]
Hi all, 

I am a new user to ProDy and want to use it for principal component analysis of MD trajectories.  I have installed Numpy1.9.2, Matplotlib1.3.1.win32-py2.7 and Python2.7 but upon trying to install ProDy1.6.1.win32-py2.7 the installer crashes.  The same happens if I try to install biopython-1.65.win32-py2.7.  Any ideas as to why this would be? This program is ideal for analyzing the trajectories on this particular protein target and I am quite desperate to get this working.

Kind regards

Lizelle

**Comment by fongchun** [comment]
Hi Lizelle, 

To install Biopython,  "C++ Compiler for Python 2.7" is required. You can download it from Microsoft: http://www.microsoft.com/en-us/download/details.aspx?id=44266

Hongchun

**Comment by Lizelle** [comment]
Hi Hongchun,

Thanks for recommending the C++ compiler for python2.7.  I have installed it but unfortunately the prody and biopython installers are still crashing

Lizelle

**Comment by fongchun** [comment]
I don't know what error you get. I can tell you how I install Prody in my Win8 system:

C++ compiler should be installed before Biopython. Also, Prody should be installed after Biopython. They should be installed sequentially. Besides, you need to set up the python environment. The anaconda package can install python , numpy and scipy together and the python environment can be set up automatically. If all of these were installed and the environment was also set up correctly, you can skip the step 1. 

1. install Windows 32-bin anaconda - Python 2.7 from 
    http://continuum.io/downloads#all

2. install  "C++ Compiler for Python 2.7" from Microsoft: 
    http://www.microsoft.com/en-us/download/details.aspx?id=44266

3. install Biopython, type:
      pip install -U biopython
 
4. install Prody form ProDy1.6.1.win32-py2.7.exe

**Comment by Lizelle** [comment]
Thanks Honchun, 

I have installed it successfully. The sequence in which I tried it before must have been wrong.
