### ISSUE TITLE
Prody script path

### ISSUE THREAD

**Issue by Lizelle** [prody/ProDy#237]
Hi all,

I have installed ProDy with Python and Numpy to perform normal mode analysis on MD trajectories in VMD.  Upon submitting the calculation to ProDy it asks for the path to python and also to the prody script file.  Am I supposed to select the prody.bat file? Doing so gives the following error message:

File "C:/Python27/Scripts/Scripts/prody.bat", line 1
%~dp0..\python %~dp0\prody %*
^
SyntaxError: invalid syntax
File "C:/Python27/Scripts/Scripts/prody.bat", line 1
%~dp0..\python %~dp0\prody %*
^
SyntaxError: invalid syntax
while executing
"exec $::NMWiz::pybin $::NMWiz::prody anm --quiet -s all -o "$::NMWiz::outputdir" -p "$prefix" -n $::NMWiz::prodyNModes -c $::NMWiz::prodyCutoff -g $::..."
(procedure "::NMWiz::prodySubmitANMjob" line 32)
invoked from within
"::NMWiz::prodySubmitANMjob"
(procedure "::NMWiz::prodySubmitJob" line 20)
invoked from within
"::NMWiz::prodySubmitJob"
invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
("uplevel" body line 1)
invoked from within
"uplevel #0 [list $w invoke]"
(procedure "tk::ButtonUp" line 24)
invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
(command bound to event)

How can I fix this?

Thanks in advance

Lizelle

**Comment by cihankayacihan** [comment]
Just to make sure, you are trying to use prody app instead of prody module. Am I right?

**Comment by Lizelle** [comment]
Thanks for the response.  I am trying to use the prody interface in VMD through the NMWiz

**Comment by ondopasa** [comment]
Hello Lizelle! I am having the same problem that you had installing Prody to be used though NMWiz. Could you solve the problem? Thanks in advance for your comments

**Comment by cihankayacihan** [comment]
please see #246
