### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by rmoffatt25** [prody/ProDy#239]
Hello.

   I just installed "ProDy-1.6.1.tar.gz." Terminal says it was a success, but says I installed ProDy-1.5.1 instead. And now, I cannot find ProDy anywhere on my computer.

I have Mac OS X 10.7, and have already installed Python 2.7, Python 3.0, and NumPy before.

Thanks in advance.

**Comment by cihankayacihan** [comment]
Hi. 

It is a bug that we encounter recently. You already installed 1.6 yet the version still shows 1.5. I will let you know as soon as we will solve this issue.

**Comment by cihankayacihan** [comment]
This issue addressed in version 1.8.
