### ISSUE TITLE
Application error ProDy interface

### ISSUE THREAD

**Issue by lauraatunipr** [prody/ProDy#241]
Hi everybody.

I've just installed VMD 1.9.2 and ProDy 1.6.1.
I'm trying to use the ProDy interface from NMWiz in VMD, but when I submit the job I get the following error message: 

*** libmkl_mc3.so *** failed with error : libmkl_mc3.so: cannot open shared object file: No such file or directory
*** libmkl_def.so *** failed with error : /usr/local/schro2011/mmshare-v20109/lib/Linux-x86_64/libmkl_def.so: undefined symbol: mkl_dft_commit_descriptor_s_c2c_md_omp
MKL FATAL ERROR: Cannot load neither libmkl_mc3.so nor libmkl_def.so
child process exited abnormally

*** libmkl_mc3.so *** failed with error : libmkl_mc3.so: cannot open shared object file: No such file or directory
*** libmkl_def.so *** failed with error : /usr/local/schro2011/mmshare-v20109/lib/Linux-x86_64/libmkl_def.so: undefined symbol: mkl_dft_commit_descriptor_s_c2c_md_omp
MKL FATAL ERROR: Cannot load neither libmkl_mc3.so nor libmkl_def.so
child process exited abnormally
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody {*}$args"
    (procedure "::NMWiz::prodySubmitPCAjob" line 61)
    invoked from within
"::NMWiz::prodySubmitPCAjob"
    (procedure "::NMWiz::prodySubmitJob" line 26)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

Any suggestions about how to fix it?
Many thanks in advance,

Bests

Laura

**Comment by cihankayacihan** [comment]
Are you using a 64 bit or 32 bit machine?

**Comment by cihankayacihan** [comment]
You need the library that is written in the message. Download it from application manager.
