### ISSUE TITLE
Combining EDA modes in prody

### ISSUE THREAD

**Issue by Arko88** [prody/ProDy#242]
Hi,

I was unable to find a way to combine modes in prody. Is there a way it can be done?. Thanks in advance for any input.

Regards,

Arko

**Comment by cihankayacihan** [comment]
Can you be more specific about combining modes? Thanks.

**Comment by Arko88** [comment]
Hi,
I would like to combine (or superpose) the first few significant modes (as indicated by scree plot) corresponding to the eigenvectors with the highest variances (obtained from EDA analysis) to get a sense of the overall domain movements of a protein I am investigating. Is there a way to do that in prody?.
Will be great help if you could indicate how it could be done or suggest a workaround.

Thanks a lot,

Regards,

Arko

**Comment by cihankayacihan** [comment]
I am still not 100% sure that I understand your problem but if you want to make calculation with first couple modes of motion you can use eda[:n] to pick first n-1 modes and do whatever calculation with it.
