### ISSUE TITLE
Python 3.4 & parsePSF()

### ISSUE THREAD

**Issue by tfguclu** [prody/ProDy#245]
/usr/local/lib/python3.4/dist-packages/prody/trajectory/psffile.py in parsePSF(filename, title, ag)
     40     while line:
     41         line = line.strip()
---> 42         if line.endswith('!NATOM'):
     43             n_atoms = int(line.split('!')[0])
     44             break

TypeError: endswith first arg must be bytes or a tuple of bytes, not str

It is alright in python2. But in python3.4 it gives this error.This is ProDy version 1.5.1.

Also i can't install ProDy 1.6.1b in python 3.4 due to indentation issues.

**Comment by cihankayacihan** [comment]
We haven't tested the version under 3.4 and we are aware that there are some issues in code. We will solve as soon as possible for 1.7.1. Thanks.

**Comment by SHZ66** [comment]
Hi, it should be fixed in #303.
