### ISSUE TITLE
Bug when parsing resnum with an insertion code to create an Atom Selection (PDB parser)

### ISSUE THREAD

**Issue by jmbromley** [prody/ProDy#250]
The documentation says that you should be able to select residues with no insertion code by e.g. select('resnum 27_') and select a particular insertion code with e.g. select('resnum 27A').  However in both ProDy 1.5.1 and ProDy 1.6.1b0 the former selects seemingly random residues whilst the latter fails to select anything.  As a workaround the undocumented select('resnum 27 icode _') and select('resnum 27 icode A') can be used.  Example interactive session demonstrating these errors follows below.

    >>> import prody
    >>> print prody.__version__
    1.6.1
    >>> atoms = prody.parsePDB('4jo1')
    @> PDB file is found in working directory (4jo1.pdb.gz).
    @> 7252 atoms and 1 coordinate set(s) were parsed in 0.06s.
    >>> sel = atoms.select('chain L resnum 27 name CA')
    >>> sel.getResnums()
    array([27, 27, 27])
    >>> sel.getIcodes()
    array(['', 'A', 'B'], 
          dtype='|S1')
    >>> sel = atoms.select('chain L resnum 27_ name CA')
    >>> sel.getResnums()
    array([  2, 301, 302])
    >>> sel = atoms.select('chain L resnum 27A name CA')
    >>> sel.getResnums()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'NoneType' object has no attribute 'getResnums'
    >>> sel = atoms.select('chain L resnum 27 icode _ name CA')
    >>> sel.getResnums()
    array([27])
    >>> sel.getIcodes()
    array([''], 
          dtype='|S1')
    >>> sel = atoms.select('chain L resnum 27 icode A name CA')
    >>> sel.getResnums()
    array([27])
    >>> sel.getIcodes()
    array(['A'], 
          dtype='|S1')

**Comment by jmbromley** [comment]
Additionally it would be great if residue numbers with insertion codes were treated as first class citizens, so that e.g. select('resnum >= 27') would pull out 27, 27A, 27B, 28 ... while select('resnum >= 27A') would only pull out 27A, 27B, 28 ... and select('resnum >= 27B') would pull out only 27B, 28, ...

**Comment by jmbromley** [comment]
Just had a quick look at the source code.  I'm pretty sure than line 2267 of select.py should read:

    value = token[:-1]

rather than (as it currently does):

    value = token[:1]

However that on its own wouldn't explain all the errors in the example given above (e.g. it explains why atoms.select('chain L resnum 27_ name CA') pulls out residue 2, but not why it also pulls out residues 301 and 302).

**Comment by jmbromley** [comment]
Also seems to me that line 2295 of select.py should read:

    rnic = zip(resnums[subset], icode[subset])

instead of the current:

    rnic = zip(resnums, icode[subset])

Making this modification and the modification to line 2267 mentioned above would appear to fix the problem for me.  I will try to submit a patch/pull request so those more familiar with the code can look over this solution.

**Comment by SHZ66** [comment]
#290 
Thank you so much.
