### ISSUE TITLE
UnboundLocalError on Pfam search

### ISSUE THREAD

**Issue by Pavellarcrc** [prody/ProDy#255]
Hi,

I kee receivein this error message:

@> Retrieving Pfam search results: http://pfam.xfam.org/protein/PIWI_ARCFU?output=xml
@> Pfam search completed in 0.86s.
@> Query 'PIWI_ARCFU' matched 1 Pfam families.
@> Submitted Pfam search for sequence "PMFIVNTNVPRASVPD...".

Traceback (most recent call last):
  File "/home/pavellar/Documents/TestePfam.py", line 21, in <module>
    matches = searchPfam(sequence)
  File "/usr/local/lib/python2.7/dist-packages/prody/database/pfam.py", line 81, in searchPfam
    xml = openURL(url, timeout=timeout).read()
UnboundLocalError: local variable 'url' referenced before assignment

even when using the tutorial code from ProDy.

Someone get any idea how to solve?

**Comment by shivasi** [comment]
We are working on this problem and will get back to you soon.

**Comment by cihankayacihan** [comment]
We addressed this issue in version 1.8.
