### ISSUE TITLE
How to showCrossCorr for an individual mode?

### ISSUE THREAD

**Issue by klamerz** [prody/ProDy#256]
Hi, I have created modes of a trajectory and I wanted to know if there was a way that I could use showCrossCorr to create a map of an individual mode rather than the average of several modes. For example I wish to showCrossCorr for the second mode. 
Any assistance that is provided is much appreciated!

~Zach

**Comment by shivasi** [comment]
you should be able to do it by: showCrossCorr(anm[0]) or whichever mode you want to visualize.

**Comment by klamerz** [comment]
Ahh yes that did it. Thank you very much, that is much simpler than what I had been trying to do.
