### ISSUE TITLE
Calculating RMSF of multiple trajectory files

### ISSUE THREAD

**Issue by kkapoor7** [prody/ProDy#258]
Hi,

I have a set of large trajectory (DCD) files. I am parsing them one frame at a time using 'Trajectory' function. I am able to calculate the RMSD using frame.getRMSD(). But RMSF calculations only seem to work with ensemble.getRMSFs() and not with frame.getRMSFs(). Is there any workaround this?

Thanks,
Karan

**Comment by shivasi** [comment]
RMSF is usually calculated over an ensemble (mean square fluctuation from an average), whereas RMSD is deviation from a given structure (typically the starting structure).  So, RMSD is calculated for each frame, whereas RMSF is calculated for an ensemble.  Therefore I think you should use ensemble.getRMSFs() to get RMSF for your protein.
