### ISSUE TITLE
EDA class & covariance matrix

### ISSUE THREAD

**Issue by tfguclu** [prody/ProDy#262]
In prody tutorial it is said that buildCovariance() function includes superpose function if align=False. align=false is default so anyone can think that using buildCovariance() function will superpose as default. But it does not superpose the structures. Prody version 1.5.1, Python 2.7.6 . Can you please look at it?

**Comment by cihankayacihan** [comment]
Hi. 

We tried to address this problem in v1.7. It will be released in a couple days and you can try again. Thanks.
