### ISSUE TITLE
parsePDB in Python 3.4

### ISSUE THREAD

**Issue by sixpi** [prody/ProDy#264]
When running ProDy under Python 3.4, parsePDB just gives a warning that "Atomic data could not be parsed, please check the input file." 

I can reproduce by creating a fresh Anaconda environment with python 3.4, numpy 1.10, and then `pip install prody`. Prody actually won't import until I fix a tab error in `atomic/subset.py` and a print function error in `sequence/analysis.py`. I then try to `parsePDB('1acd')` and it is unable to parse the pdb.

**Comment by sixpi** [comment]
Upon further investigation it appears that this might be related to automatic un-gzipping - it works fine if I `gunzip` the downloaded pdb file.

**Comment by cihankayacihan** [comment]
For different versions of gunzip, it may corrupt the pdb file in extraction. What distro you are using?
