### ISSUE TITLE
Prody & Python3

### ISSUE THREAD

**Issue by marcocamma** [prody/ProDy#267]
Hi,

I am trying to use Prody in python3 and run in all sorts of issues:

1. `pip3 install prody` fails with a variety of errors (print statements, mixing of tabs/spaces for indentation, error in except statements:

2. compiling the github version (as of today) with `python3 setup.py build` complains (prody/dynamics/bbenmtools.c:480:9: error: ‘bbenm_methods’ undeclared here)

3. downloading the 1.7 tar.gz and compiling|installing with `python3 setup.py build|install` works; but when trying to import the module (`python3 -m prody`) complains about inconsistent tab/spaces indentation.

I could help out refactor the code if nedded. Thanks for the great work
marco
ps. operating system: uptodate debian sid

**Comment by cihankayacihan** [comment]
We are aware of issues related to Python3. With 1.7.1, all will be fixed.

**Comment by cihankayacihan** [comment]
This issue is fixed with version 1.8.
