### ISSUE TITLE
Create molecules and atoms programatically

### ISSUE THREAD

**Issue by JordiGuasp** [prody/ProDy#270]
Is it possible to create molecules and atoms from Python itself, without reading a PDB file? I have a list of atoms, masses and coordinates that want to use with your normal mode analysis algorithms, but I haven't been able to make it work.

I was thinking about generating a PDB file with 3rd party software, but I want to try to do it in Python directly without the unnecessary disk write. Is it possible at all? 

Thank you, Jordi.

**Comment by wzmao** [comment]
You could find something from [here](http://prody.csb.pitt.edu/tutorials/prody_tutorial/atomgroup.html) using `setCoords`, `setNames`, `setResnums` and `setResnames`.
