### ISSUE TITLE
Memory Error running CoMD

### ISSUE THREAD

**Issue by MigueLugo** [prody/ProDy#273]
Hi there,

During a CoMD simulation, appears the error:

**Traceback (most recent call last):
  File "anmmc.py", line 92, in <module>
    for k in range(N):
MemoryError
child process exited abnormally**

The N values (cycles in the MC loop) is set to 1E6. I decreased to 1E4 and then works. I notice in the script that there is an Ensemble variable that records the coordinates in each iteration by 
                                                   ** ensemble.addCoordset(pdb_ca.getCoords())**
but it is not used in any way. At the exit of the loop, the variable used is 
                                                  ** ensemble_final.addCoordset(pdb_ca.getCoords())**

So, by undisabling the line by 
                                    **#ensemble.addCoordset(pdb_ca.getCoords())**, 
I can set N as high as 1E5.

So, the is that change on anmmc.py Ok? 

Thanks

**Comment by cihankayacihan** [comment]
It makes sense. Thanks.
