### ISSUE TITLE
NaNs appear when building hessian with RTB.buildHessian() (2 residues per block)

### ISSUE THREAD

**Issue by JordiGuasp** [prody/ProDy#277]
I'm using the Rotation Translation Blocks (RTB) class to calculate some normal modes.
When I use a certain molecule (1zik) and I assign 2 residues per block, some NaNs appear in the calculated hessian matrix and then the normal modes can't be processed without exceptions (ValueError, mainly).

I am using the following commands:

```
zik = prody.parsePDB('1zik')
modes = prody.RTB()
```

To make blocks:

```
group = 1
count = 1
for chain in zik.iterChains():
    for residue in chain.iterResidues():
        residue.setBetas(group)
        if count % 2 == 0:
            group += 1
            count = 1
        else:
            count += 1
```

And then, I build and check the hessian:

```
import math
modes.buildHessian(zik.getCoords(),zik.getBetas())
for i, element in enumerate(modes.getHessian()):
    for j, x in enumerate(element):
        if math.isnan(x):
            print i, j
```

It also happens with 5F96 but not with 2N10, for example. So it's driving me crazy. What can be the difference between these systems so they produce such different outcomes? Thank you very much.

**Comment by cihankayacihan** [comment]
I tried to reproduce the error but it is impossible. The way you call may be problematic. My suggestion is to go to the following link http://prody.csb.pitt.edu/tutorials/membrane_anm/

**Comment by jamesmkrieger** [comment]
The problem is that you are including water molecules. Please add the line `zik = zik.select('protein').copy()` to fix the problem.
