### ISSUE TITLE
Error adding coordinate sets to Ensemble objects

### ISSUE THREAD

**Issue by skandel12** [prody/ProDy#278]
There is a strange error with getting coords from an ensemble and adding the coords to another ensemble.

This doesn't work:
```python
pdb = pd.parsePDB(pdbfilename)
ens = pd.parseDCD(dcdfilename)
ens.setAtoms(pdb)

temp_ens = pd.Ensemble()
temp_ens.setAtoms(pdb)

c = ens[0]
temp_ens.addCoordset(c)
```
The error I get is:
```python
"TypeError: coords must be a numpy array or an object with `getCoords` method"
```

However, this works fine:
```python
pdb = pd.parsePDB(pdbfilename)
ens = pd.parseDCD(dcdfilename)
ens.setAtoms(pdb)

temp_ens = pd.Ensemble()
temp_ens.setAtoms(pdb)

c = ens[0]
coords = c.getCoords()
temp_ens.addCoordset(coords)
```

Obviously, the object "c" does have the getCoords method, so I am not sure what is going on.

I am working with ProDy version 1.7.

**Comment by JordiGuasp** [comment]
I think that the error message is wrong. If you look the [docs](http://prody.csb.pitt.edu/manual/reference/ensemble/ensemble.html#prody.ensemble.ensemble.Ensemble) _coords_ have to be a numpy array or an object with `getCoordsets()` method.
You can find more information running `temp_ens?` or looking the [source code](http://prody.csb.pitt.edu/_modules/prody/ensemble/ensemble.html#Ensemble.addCoordset).

Your `ens[0]` don't have `getCoordsets()` method but when you add the coordinates using a numpy array, this is your second example where coords is a numpy array, this works fine.

**Comment by cihankayacihan** [comment]
addCoordset function does not work for conformation class. You need to use get_coords to get the coordinates of conformation. I will mark this one as feature request. In next version, we will use addCoordSet function for conformation class, too.
