### ISSUE TITLE
Overlap Table Segmentation

### ISSUE THREAD

**Issue by sbergmanpitt** [prody/ProDy#280]
Can you explain the gridding separation of boxes when using showOverlapTable please, as shown in the image below?
![figure_1](https://cloud.githubusercontent.com/assets/18123818/14086058/3edb4884-f4f1-11e5-9edf-92ccaae1b040.png)

**Comment by cihankayacihan** [comment]
I am sorry but I do not understand what you mean by gridding separation. Can you be more specific?
