### ISSUE TITLE
Backwards compatibility to Python 2.7.x

### ISSUE THREAD

**Issue by Pavellarcrc** [prody/ProDy#282]
Hi

In the file ProDy/prody/database/pfam.py, line 74: 

request = urllib.request.Request('http://hmmer.janelia.org/search/hmmscan', enc_params)

the method has no attribute "request" in Python 2.11 (https://docs.python.org/2/library/urllib.html)

So its not compatible to the older version.

Regards,

Pedro

**Comment by SHZ66** [comment]
Hi, the compatibility problem should be fixed. Please see the pull request #298.
