### ISSUE TITLE
RTB.calcModes() doesn't calculates the number of modes that I request

### ISSUE THREAD

**Issue by JordiGuasp** [prody/ProDy#286]
Hello,
I'm using RTB to calculate normal modes. When I try to calculate a concrete number of modes, RTB.calcModes() calculates all the modes.

I'm doing:
```
p38 = parsePDB('1p38')
p38_ca = p38.ca
[p38_ca.select('chain A and resnum {} to {}'.format(n, n+3)).setBetas(i) for (i,n) in enumerate(range(1,p38_ca.numAtoms()-3,3))]
coords = p38_ca.getCoords()
rtb = RTB('p38')
rtb.buildHessian(coords, p38_ca.getBetas())
rtb.calcModes(n_modes=10)
```
And I'm getting the following output:
```
@> 699 modes were calculated in 0.30s.
DEBUG:.prody:699 modes were calculated in 0.30s.
```
And when I ask the number of modes:
```
rtb.numModes()
699
```

Thank you in advance for any help you can provide.
Jordi Guasp

**Comment by SHZ66** [comment]
The issue has been fixed and the new version will be released soon. Thanks for your input!
