### ISSUE TITLE
Installing ProDy on Windows

### ISSUE THREAD

**Issue by ismailuddin** [prody/ProDy#301]
The links to installers on the website for Windows appear to be broken, and do not let you download any files (for 32 bit atleast). Furthermore, attempting to install ProDy via pip fails at the last step involving the Visual C++ compiler.

```Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\quirky\\appdata\\local\\temp\\pip-build-bg6adr\\prody\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\quirky\appdata\local\temp\pip-5ivtld-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\quirky\appdata\local\temp\pip-build-bg6adr\prody\```

**Comment by cihankayacihan** [comment]
hi. 
obviously, pypi decided not to provide static links to our binaries. My suggestion to you is go to following website and download 32 bit python executable. Pip will not work on windows because our binaries are not working with visual c++ compiler you need gcc.

**Comment by cihankayacihan** [comment]
website is updated. you can download proper version from pypi page.
