### ISSUE TITLE
Protein-ligand system with hydration shell

### ISSUE THREAD

**Issue by MamtaMohan** [prody/ProDy#304]
Hi Ahmet,

I would like to calculate NMs of a  a protein with ligands structure with a thin hydration shell. Or in general is it possible to calculate NMs of a protein-ligand system with explicit solvent effects via ProDy.

I would appreciate your response.

**Comment by cihankayacihan** [comment]
Currently, we are not using ligand structures but I am adding this one as a feature request and we will try to build a model for this problem. Thanks.

**Comment by MamtaMohan** [comment]
Thank you.

________________________________

**Comment by jamesmkrieger** [comment]
We are planning to implement the mixed-resolution model RESPEC (https://pubs.acs.org/doi/10.1021/acs.jpcb.7b10325) in ProDy soon, which should allow you to include the ligand in the elastic network. We are not planning to include solvation as the elastic network models perform well without it.

**Comment by MamtaMohan** [comment]
Thank you for information.

**Comment by jamesmkrieger** [comment]
You're welcome
