### ISSUE TITLE
Modes selection in extended NMA

### ISSUE THREAD

**Issue by JordiGuasp** [prody/ProDy#307]
I'm using extendModel() to extend normal modes that I have calculated with calphas.
While with the original ANM class I can select the modes with a list, with the extended version it doesn't work.
I'm doing:
```
l2y = parsePDB('1L2Y')
calphas = l2y.select('calpha')
anm = ANM('l2y ANM analysis')
anm.buildHessian(calphas)
anm.calcModes()
anm_ext = extendModel(anm, calphas, l2y, norm=True)
modes_to_select = [0,3,8]
```
and I get:
```
anm[modes_to_select]
<ModeSet: 3 modes from ANM l2y ANM analysis>
anm_ext[modes_to_select]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-1a755fdbd73b> in <module>()
----> 1 anm_ext[modes_to_select]

TypeError: tuple indices must be integers, not list
```
Maybe extendModel() is getting the NMA class from an old version?
Thank you.
Jordi Guasp

**Comment by cihankayacihan** [comment]
Hi. 

Extended model is a list not an NMA object. First element is an NMA object and the second element is atommap. Instead of using anm_ext[modes_to_select] you should use this anm_ext[0][modes_to_select]. We can convert anm_ext objects to dictionaries but currently this is a work around.
