### ISSUE TITLE
Spin labelled Protein

### ISSUE THREAD

**Issue by MamtaMohan** [prody/ProDy#308]
Hi,

I want to use ProDy to analyse NM of a spin label (MTSL) attached to a protein.

I tried that but ProDy skips the label while reading PDB file. It says it is not an amino acid which is correct.

I was wondering if there a way I can read spin label.

I would appreciate your response

Regards.

**Comment by cihankayacihan** [comment]
Currently, ProDy does not parse MTSL label but I add this one as a feature request and we will parse it. Thanks for suggestion.

**Comment by MamtaMohan** [comment]
Dear Cihankayacihan,

I was wondering if parsing of label will be available soon.

Mamta

**Comment by jamesmkrieger** [comment]
It seems to work for me. ProDy should be able to parse any molecule. I ran the following

`with_label = parsePDB('2igc')`

Then I managed to get this:

`In [10]: with_label.select('resname MTN')`
`Out[10]: <Selection: 'resname MTN' from 2igc (12 atoms)>`

**Comment by jamesmkrieger** [comment]
Having had no reply saying there are still problems, I am closing this issue. Feel free to reopen if there are still problems.
