### ISSUE TITLE
Frequency comparison between ProDy ANM results and CHARMM atom VIBRAN DIAG

### ISSUE THREAD

**Issue by jasnyderjr** [prody/ProDy#312]
I am curious about the normal mode frequencies that I get with results using ProDy ANM compared with results using CHARMM VIBRAN with DIAG which, of course, does all-atom diagonalization of Hessian based on energies.  I present the results below [first two (slowest) non-trvial modes] for three proteins [PDB ID's 1GXV (lysozyme, 1LDO (HIV reverse transcriptase), and insulin].  The native crystal structures were energy minimized in charmm until root mean square of energy gradient was less that 10^-06, as is typically necessary for all-atom diag based normal mode analysis.  This was followed by diagonalization of energy Hessian, and normal mode calc.  The minimized structure was also used as input for ProDy ANM.  I am concerned about the differences I see between the eigenvalues (frequencies) for the proteins between the two methods.  First question is am I comparing eigenvalues (lambda) and frequencies with the same units?  I know from CHARMM code that frequencies =sq root (lambda)/pi_c with 1/pi_c =108 and c is in cm/ps.  Does not matter really as output of charmm gives frequencies in cm^-1 and eigenvalues in kcal/g/A^2.  Now, what about Prody?  I am taking the second values in the each line for the modes listed in the .nmd file appearing after the first integer (mode number), and then taking the reciprocal of that to get freq, since  I see that those values are the reciprocal of sq. root(lambda)  and module descriptions for .nmd files call those numbers inverse of frequency (reciprocal?).  Am I comparing with same units?  If so, are  these differences typical.  

```
                           ProDy ANM         CHARMM VIBRAN DIAG
```

HIV
        eigenvalue       0.06107              0.000134
        Freq                 0.25                    1.26

```
                            0.09554              0.000199
                            0.31                     1.53
```

HEWL  
                                1.0995                0.00200
                                1.05                    4.85

```
                            1.26400              0.00265
                            1.12                    5.60
```

INSULIN  
                                 0.3710                0.004508
                                 0.61                    7.29

```
                             1.2001                0.006288
                             1.10                    8.61               
```

  Thank You for any feedback.

J Snyder

**Comment by cihankayacihan** [comment]
Hi. Those values are unitless in ProDy because we are not making an all atom diagonalization instead, we are using a coarse-grained only CA based model with vibrational potential only. You can compare the eigenvalue distribution instead of eigenvalues itself. We use eigenvalues and eigevectors to get the directions and the hinges on the structure.

**Comment by jamesmkrieger** [comment]
I guess there's nothing else we can help with here and I'm closing the issue. Feel free to reopen it if you disagree.
