### ISSUE TITLE
ANM result shows large (physically unrealistic) residue motions

### ISSUE THREAD

**Issue by jasnyderjr** [prody/ProDy#317]
Hello:

I have been using the ProDy ANM Application for several proteins, eg. lysozyme. as follows

prody anm lysozyme.pdb -a -s "protein and name CA" -t all -n 5

After uploading lysozyme_anm_extended_all.nmd into VMD's NMWiz, and playing the animation, I typically see some bonds stretching seemingly to physically unreasonable limits with several modes.  See snapshots below of two selected frames from first mode.  Evidently, some node (CA) atoms, and hence all corresponding residue atoms after extending to all atoms, experience large vector and move very large distances.  Decreasing the cutoff distance to 8.0 seems to solve some of this effect, but that seems like a harsh change and simply (as I understand it) removes (possibly valuable ?) interaction pairs.  Changing force constant seems not to have any effect.  Of course increasing max rmsd just makes effect more or less pronounced in appearance.   I do find that energy minimization will remove these large bond stretches, so perhaps that is the workaround for this. I have included pdb as text file that was used.  Any thoughts?

![lyso_mode1_1](https://cloud.githubusercontent.com/assets/19453208/16828564/de41715c-495e-11e6-8c26-af5c2ac25987.JPG)
![lyso_mode1_2](https://cloud.githubusercontent.com/assets/19453208/16828565/de457856-495e-11e6-95db-da0b2de28a9c.JPG)

[lysozyme.txt](https://github.com/prody/ProDy/files/363035/lysozyme.txt)

**Comment by howiedlut** [comment]
I met the same problem, :(
It might because the atom groups was located away from the other groups whose distance is beyound the cutoff?

**Comment by cihankayacihan** [comment]
It is quiet likely can you please share the pdb with us so that we can try to reproduce the same problem.

**Comment by jasnyderjr** [comment]
It is attached as "lysozyme.txt in my initial comment above.  It won't let me attach a file with .pdb extension, so I have to replace with .txt extension.  I'll attache it again here.
[hivr.txt](https://github.com/prody/ProDy/files/702030/hivr.txt)

**Comment by cihankayacihan** [comment]
Thank you very much. I reproduced the same issue but it looks like there is not a problem in here. Those two residues 46 and 117 are quiet far from the other residues that's why it fluctuates a lot. I changed the cutoff to 20 and one of the huge fluctuation is get lost.
