### ISSUE TITLE
ANM modes differ before and after superposition with another structure

### ISSUE THREAD

**Issue by feliciahjiang** [prody/ProDy#321]
I am calculating the ANM modes of two different conformations of the same protein (let's call them conformation A and B). I find that when I calculate ANM modes of conformation A according to this tutorial (http://prody.csb.pitt.edu/tutorials/enm_analysis/anm.html) without superposing to any other structure, I get a set of modes that look different when visualized in VMD than if I calculated ANM modes of conformation after superposing conformation A to conformation B (according to this tutorial: http://prody.csb.pitt.edu/tutorials/enm_analysis/normalmodes.html). 

I am confused because the translational transformation of conformation A should not change the modes at all. I understand if the correlation values between conformation A and B change based on whether the two structures were aligned or not, but the modes of one structure should not vary visually before and after superimposing with another structure.

**Comment by cihankayacihan** [comment]
It should not change. It could be a visualization problem and in VMD it could be sometimes visually untractable. Can you be more specific about your case and may be share your code so that we can reproduce the same issue. Thanks.
