### ISSUE TITLE
Superposing DCD onto another reference structure

### ISSUE THREAD

**Issue by feliciahjiang** [prody/ProDy#322]
I am trying to perform essential dynamics on two protein trajectories, which are exactly the same except one protein contains a substrate and the other does not. I would like to superpose the trajectory of structure A onto structure B so that I can calculate the overlap between the two different trajectories.

I was able to superpose the pdb files when performing anisotropic network model calculations by following this tutorial (http://prody.csb.pitt.edu/tutorials/enm_analysis/normalmodes.html), by matching chains (after selecting everything but the substrate) and then using superpose(). 

However when I try to align the dcd files using .getCoords() on the reference structure and .setCoords() on the DCD file I am try to align, I get the error that there are different numbers of atoms. I am confused because I made sure to select the same number of atoms (the residue numbers differ but both selections have 946 atoms selected). (Code below)

Is there another way of aligning DCD of one structure onto another? In particular, should I use .setCoords() or superpose() to ensure that I am superposing the parts that both structures share (protein minus substrate)? 

In [34]: structureA = parsePDB('structureA.pdb')
@> 15920 atoms and 1 coordinate set(s) were parsed in 0.11s.

In [35]: structureB = parsePDB('structureB.pdb')
@> 16709 atoms and 1 coordinate set(s) were parsed in 0.10s.

In [36]: dcdB = DCDFile('structureB.dcd')

In [37]: reference = structureA.select('calpha and resid 18 to 979 and not resid 941 to 956')

In [38]: dcdB.link(structureB)

In [39]: dcdB.setAtoms(structure.select( "calpha and segment P1 and resid 47 to 1008 and not resid 970 to 985" ) )

In [40]: dcdB
Out[40]: DCDFile: dcdB (linked to AtomGroup structureB_autopsf ; next 0 of 6233 frames; selected 946 of 16709 atoms)

In [41]: reference
Out[41]: Selection: 'calpha and resi...esid 941 to 956' from 4IOF_closed_aligntothesecoords (946 atoms)

In [42]: coords = reference.getCoords()
## In [43]: dcdB.setCoords(coords)

ValueError                                Traceback (most recent call last)
<ipython-input-44-caff90dfe974> in <module>()
----> 1 dcdB.setCoords(coords)

/Users/labadmin/anaconda/lib/python2.7/site-packages/prody/trajectory/trajbase.pyc in setCoords(self, coords)
    261 
    262         try:
--> 263             checkCoords(coords, natoms=self._n_atoms)
    264         except TypeError:
    265             raise TypeError('coords must be a numpy array or an object '

/Users/labadmin/anaconda/lib/python2.7/site-packages/prody/utilities/checkers.pyc in checkCoords(coords, csets, natoms, dtype, name)
     45 
     46     elif natoms and shape[-2] != natoms:
---> 47         raise ValueError(str(name) + '.shape[-2] must match number of atoms')
     48 
     49     elif dtype:

ValueError: coords.shape[-2] must match number of atoms

**Comment by SHZ66** [comment]
Thanks for posting it.

Can you show me two things?

1. In [39]: dcdB.setAtoms(**structure**.select( "calpha and segment P1 and resid 47 to 1008 and not resid 970 to 985" ) )

What is this "_structure_" variable? Is it _structureA_ or _B_?

2. Can you show me the dimension of the variable _coords_?

**Comment by jamesmkrieger** [comment]
I imagine it should be structureB. Please confirm.

You should use setCoords to select the reference coords and then use superpose. I'm not sure why this doesn't work seeing as you have the same number of atoms. You could maybe try `dcdB.setCoords(reference)` and see if that works.

**Comment by jamesmkrieger** [comment]
Any progress on this?

**Comment by jamesmkrieger** [comment]
I think setCoords only works for the whole set of atoms not the selection. What you could do is convert your DCDFile object into a PDBEnsemble, setCoords and setAtoms with the original structure again, trimPDBEnsemble without any parameters to hard trim, then set coords with the new reference. Alternatively, you could use writeDCD with the selection applied and use parseDCD on the resulting file, which should then only correspond to the selection.

**Comment by jamesmkrieger** [comment]
Seeing as an answer has been given and no more questions have been asked, I'm closing this issue. You can reopen it if you need any more help.
