### ISSUE TITLE
ProDy with Anaconda py

### ISSUE THREAD

**Issue by MamtaMohan** [prody/ProDy#324]
Hello,

I have Anaconda package manager installed. I also have ProDy installed which I installed before Anaconda.

I would like to know how can I call ProDy after I switch to  Anaconda interpreter and start ipython.

Anaconda do not see ProDy when I try to import ProDy.

I will appreciate your response.

**Comment by cihankayacihan** [comment]
I assume, you are using windows. Download executable from https://pypi.python.org/pypi/ProDy/1.8.2. And install prody to proper python.

**Comment by MamtaMohan** [comment]
I am using linux (Ubuntu 14.04 lts).

ProDy works fine in native python environment.

Besides Python I installed Anaconda.

To access ProDy I have to start ipython (native python) from command line and it works fine.

But if I start Anaconda and then start ipython, it does not work. Which I understand because it is not in the list.

I work with in Anaconda environment quite a bit but to use ProDy, I have to switch environments.

I would to setup environment so work is seamlessly with native python and Anaconda.  

Maybe if you can upload ProDy in CONDA omnia then it is helpful for lot of people or maybe if you tell me how shall I access ProDy installed in native python environment via Anaconda python that would be very helpful.

Mamta
