### ISSUE TITLE
How to calculate frequency of the normal modes

### ISSUE THREAD

**Issue by amanan00** [prody/ProDy#326]
Hello,
How can I calculate the frequency of modes from their eigenvalues? 
Thanks
Anjela M.

**Comment by SHZ66** [comment]
Hi Anjela,

Eigenvalues are squared vibrational frequency, so you can take the square root of eigenvalues to obtain the frequency.

Best,
She

**Comment by amanan00** [comment]
She,
Thank you very much for your response. I simply calculated f (cm-1) as  ω/(2πc) ; however my frequency is very low than the range. Do I need to use "t" (one unit of time) = 4.88x10^-14 s as well in my calculation? The article suggested f = ω/(2πct). Any help will be appreciated.

**Comment by SHZ66** [comment]
Anjela,
The unit of the obtained frequency depends on how you set the gamma (force constant), and the unit will be consistent with it. Could you tell me what is "c" in your equation? Or would you show me the article if it is convenient.

She

**Comment by amanan00** [comment]
She,
Sorry for the confusing description. I am using default ProDy gamma value
which is 1 kcal/mol and using cutoff of 12 A. My eigenvalue for first mode
is 0.004. I am trying to get frequency in terms of cm-1.  So first I
calculated Ω as square root of eigenvalue and then I followed the article
attached (please see page 5 "Units". Thank you very much for your help.

Sincerely,
Anjela Manandhar
Graduate Student
Biochemistry Program
Graduate Center, City University of New York
365 Fifth Avenue, NY-10016, USA

**Comment by amanan00** [comment]
Sorry, I meant ω = square root of eigenvalue.

Sincerely,
Anjela Manandhar
Graduate Student
Biochemistry Program
Graduate Center, City University of New York
365 Fifth Avenue, NY-10016, USA

**Comment by SHZ66** [comment]
Sorry Anjela, I couldn't find your attachment. Would you send it to my email instead? 

shz66@pitt.edu

I think the unit that prody uses is arbitrary, therefore the obtained frequencies are relative. However some constraints in unit can make the absolute frequency obtainable. You mentioned the unit is cm-1, so I guess the "c" in the equation is the speed of light and what you want to obtain is the wavenumber.

Best,
She
