### ISSUE TITLE
RTB module error

### ISSUE THREAD

**Issue by mweka007** [prody/ProDy#327]
How to run RTB using rtb.py script .

Error
Traceback (most recent call last):
  File "rtb.py", line 15, in <module>
    from .anm import ANMBase, calcANM, ANM
ValueError: Attempted relative import in non-package

Regards,

**Comment by cihankayacihan** [comment]
http://prody.csb.pitt.edu/tutorials/membrane_anm/imanm.html

**Comment by cihankayacihan** [comment]
I think this issue is solved and I am closing it.
