### ISSUE TITLE
RuntimeError: dictionary changed size during iteration Python3.5

### ISSUE THREAD

**Issue by XuTianhao** [prody/ProDy#328]
Hi, I'm just exploring ProDy, however, I found if I'm using Python3.X, some of the code actually not adapting.
## I'm using Jupyter notebook trying to run showProtein(gag_pol) to view my plot. It has errors as follows:

RuntimeError                              Traceback (most recent call last)
<ipython-input-5-5d1e6fcc72d7> in <module>()
----> 1 showProtein(gag_pol)

/usr/local/lib/python3.5/site-packages/prody/proteins/functions.py in showProtein(_atoms, *_kwargs)
    124     wcolor = kwargs.get('water', 'red').lower()
    125     avoid = np.array(colors.hex2color(cnames.pop(wcolor, cnames.pop('red'))))
--> 126     for cn, val in cnames.items():  # PY3K: OK
    127         clr = np.array(colors.hex2color(val))
    128         if clr.sum() > 2.4:

RuntimeError: dictionary changed size during iteration

I think the for cn, val in **cnames.items()** is making the problem not returning list, and which should be changed to "list(cnames)" from my understanding. Any thoughts how to solve this problem? thank you.

Tianhao.

**Comment by SHZ66** [comment]
Hi Tianhao,

Thank you for your input. We are aware of this problem (#314) and it should be solved in the next version. Also I will look at the problem and post a quick fix.

Best,
She

**Comment by XuTianhao** [comment]
@SHZ66 also the #turn interactive mode on command 

> ion()

 is not working in jupyter notebook.
NameError: name 'ion' is not defined

**Comment by cihankayacihan** [comment]
Ion will not work in notebooks. You should use the following %matplotlib inline

**Comment by SHZ66** [comment]
Hi,

This has been fixed. Please see #336.
