### ISSUE TITLE
.getMasses() function returns None

### ISSUE THREAD

**Issue by jamieAmacpherson** [prody/ProDy#329]
I need to calculate the mass matrix of a pdb structure:
###### 

> > > from prody import *
> > > topology = "free.pdb"
> > > struct = parsePDB(topology)
> > > mass = structure.getMasses()
> > > print mass
> > > None
> > > ###### 
> > > 
> > > I can't find the source code for this function making it difficult to diagnose the problem.

**Comment by SHZ66** [comment]
Hi, the mass is not recorded in PDB files, therefore ProDy calculates it based on the atom type. It wasn't stored when parsing the PDB thus caused this issue. It has been fixed in #337. Thanks for your input.
