### ISSUE TITLE
question about NMWiz parameter

### ISSUE THREAD

**Issue by Terraceguo** [prody/ProDy#330]
i am currently work with with VMD plugin NMWiz to visualize eigenvectors generated from normal mode analysis. But I have a difficult time to understand the second parameter of after the keyword "mode", like, in the NMWiz manual, an example is as follows
...

coordinates 172.541 -33.818 72.141 172.591 -29.981 71.748 171.498 -29.271 ..
mode 1 5.08 0.010 -0.014 -0.030 0.011 -0.013 -0.029 0.006 -0.012 -0.027 ...
mode 2 3.99 -0.003 -0.014 0.007 0.001 -0.016 0.002 0.001 -0.019 0.000 ...
mode 3 2.82 0.010 0.027 0.000 0.006 0.028 0.003 0.005 0.028 0.004 0.002 ...
..

the manual explain this parameter as the " mode length (square root of variance or inverse frequency) " But if it is the inverse frequency, shouldn't it be a very small number (10^-12) for a wave number of about 100cm-1, which is not the case in the manual, I guess what i interpret is not what the manual wants to say. the information i have is the eigenvectors with it cooresponding wavenumber. Can anyone help me understand what does this parameter means, or how can i convert wavenumber to this parameter. Thanks very much!!!

**Comment by cihankayacihan** [comment]
The value that you have as the first number is the reciprocal of the eigenvalue. You should multiply this with 2pi to get the wavenumber.
