### ISSUE TITLE
Unable to install ProDy in Windows 64 or Anaconda2 in Windows

### ISSUE THREAD

**Issue by jedgold** [prody/ProDy#332]
I am unable to see the Anaconda version of Python 2.7 in the ProDy 1.8.2 64-bit Windows installer (I have another version of Python 2.7 installed, which is visible in the register to ProDy). Anaconda 2 works fine, and has scipy, etc. Where is ProDy looking in the registry for Python?

Also, "pip install -U prody" fails even after installing Windows Visual C++ compiler, and does not write a log file as it says it should be doing (failed building the wheel, and setup.py).

**Comment by SHZ66** [comment]
This post may be helpful:
http://stackoverflow.com/questions/17872234/how-to-add-python-to-windows-registry

**Comment by cihankayacihan** [comment]
For windows users, we do not have build from source option or pip installation. You should get the executables from pypi website where the links are shared on the download page.
