### ISSUE TITLE
Units of modes?

### ISSUE THREAD

**Issue by sebassen** [prody/ProDy#333]
Hi, I'm working with VMD and want to obtain the vibration frequencies of a molecule at equilibrium. Using proDy and the normal mode wizard I get 
mode 1 471.92 0.005 -0.002 0.003 0.006 -0.002 0.003 ...
mode 2 443.30 0.003 -0.005 0.004 0.004 -0.004 0.004 ...
Can I obtain the vibration frequency from here in Hz or cm-1 or something?
Thanks a lot!

**Comment by SHZ66** [comment]
The unit of eigenvalue is dependent on the spring constants (k) and the mass of atoms (m). 

eigenvalue ~ frequency^2 ~ k/m

So the vibrational frequency is in Hz if your parameters are in SI. But note that in ProDy, it applies a uniform mass of 1 to all the atoms/residues, and a uniform spring constant of 1 to all the connections. So either you need to apply a scaling factor to approximate the real frequency, or you need to set the actual mass to the residues/atoms.

**Comment by cihankayacihan** [comment]
I marked this issue as solved and closing.
