### ISSUE TITLE
Bug in calcDihedral

### ISSUE THREAD

**Issue by chrisgoedde** [prody/ProDy#343]
There's a bug in getDihedral, which is called by calcDihedral. It sometimes returns a dihedral of 0 when it should return a dihedral of 180. The problem is that the value

porm = np.sign((v1 * a3).sum(-1))

is used to set the sign of the result, but this can be zero when v1 is perpendicular to a3. That case should be explicitly checked for, e.g., instead of the existing code:

    porm = sign((v1 * a3).sum(-1))
    rad = arccos((v1*v2).sum(-1) / ((v1**2).sum(-1) * (v2**2).sum(-1))**0.5)
    if radian:
        return porm * rad
    else:
        return porm * rad * RAD2DEG

one could use

    porm = sign((v1 * a3).sum(-1))
    rad = arccos((v1*v2).sum(-1) / ((v1**2).sum(-1) * (v2**2).sum(-1))**0.5)
    if not porm == 0:
        rad = rad * porm
    if radian:
        return rad
    else:
        return rad * RAD2DEG

**Comment by cihankayacihan** [comment]
Thanks for your comment. It is fixed now.
