### ISSUE TITLE
An overhead issue when running on cluster

### ISSUE THREAD

**Issue by ghost** [prody/ProDy#349]
Dear Admin,

I can apply prody CoMD on my 4 core 8 thread desktop machine without a problem. However, when I do it on a computing cluster, most of the time it could run for a few iterations, but then it would report:

> @> 298 atoms and 1 coordinate set(s) were parsed in 0.00s.
> @> 298 atoms and 1 coordinate set(s) were parsed in 0.00s.
> @> Hessian was built in 0.09s.
> @> 888 modes were calculated in 0.47s.
> @> DCD file was written in 0.00 seconds.
> @> 0.00 MB written at input rate 5.83 MB/s.
> @> 1 coordinate sets written at output rate 1672 frame/s.
> @> 298 atoms and 1 coordinate set(s) were parsed in 0.00s.
> @> 298 atoms and 1 coordinate set(s) were parsed in 0.00s.
> @> Hessian was built in 0.10s.
> @> 888 modes were calculated in 0.46s.
> @> DCD file was written in 0.00 seconds.
> @> 0.00 MB written at input rate 6.57 MB/s.
> @> 1 coordinate sets written at output rate 1883 frame/s.
> psfplugin) Detected a Charmm PSF file
> Info) Using plugin psf for structure file initial_ionized.psf
> Info) Analyzing structure ...
> Info)    Atoms: 22165
> Info)    Bonds: 16452
> Info)    Angles: 14698  Dihedrals: 13128  Impropers: 772  Cross-terms: 296
> Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
> Info)    Residues: 6073
> Info)    Waters: 5771
> Info)    Segments: 5
> Info)    Fragments: 5776   Protein: 1   Nucleic: 0
> Info) Using plugin namdbin for coordinates from file OUT_inimin/initial_minimized3.coor
> Info) Using plugin pdb for structure file final_target.pdb
> Info) Using plugin pdb for coordinates from file final_target.pdb
> Info) Determining bond structure from distance search ...
> Info) Finished with coordinate file final_target.pdb.
> Info) Analyzing structure ...
> Info)    Atoms: 298
> Info)    Bonds: 0
> Info)    Angles: 0  Dihedrals: 0  Impropers: 0  Cross-terms: 0
> Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
> Info)    Residues: 298
> Info)    Waters: 0
> Info)    Segments: 1
> Info)    Fragments: 298   Protein: 0   Nucleic: 0
> dcdplugin) detected standard 32-bit DCD file of native endianness
> dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
> Info) Using plugin dcd for coordinates from file starting_initial.pdb_initial_target.pdb_final_structure.dcd
> psfplugin) Detected a Charmm PSF file
> Info) Using plugin psf for structure file final_ionized.psf
> Info) Analyzing structure ...
> Info)    Atoms: 20104
> Info)    Bonds: 15078
> Info)    Angles: 14011  Dihedrals: 13128  Impropers: 772  Cross-terms: 296
> Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
> Info)    Residues: 5386
> Info)    Waters: 5084
> Info)    Segments: 4
> Info)    Fragments: 5089   Protein: 1   Nucleic: 0
> Info) Using plugin namdbin for coordinates from file OUT_finmin/final_minimized3.coor
> Info) Opened coordinate file initial_adjust.pdb for writing.
> Info) Finished with coordinate file initial_adjust.pdb.
> psfgen) clearing structure, preserving topology and aliases
> psfplugin) Detected a Charmm PSF file
> Info) Using plugin psf for structure file final_ionized.psf
> Info) Analyzing structure ...
> Info)    Atoms: 20104
> Info)    Bonds: 15078
> Info)    Angles: 14011  Dihedrals: 13128  Impropers: 772  Cross-terms: 296
> Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
> Info)    Residues: 5386
> Info)    Waters: 5084
> Info)    Segments: 4
> Info)    Fragments: 5089   Protein: 1   Nucleic: 0
> Info) Using plugin namdbin for coordinates from file OUT_finmin/final_minimized3.coor
> Info) Using plugin pdb for structure file initial_target.pdb
> Info) Using plugin pdb for coordinates from file initial_target.pdb
> Info) Determining bond structure from distance search ...
> Info) Finished with coordinate file initial_target.pdb.
> Info) Analyzing structure ...
> Info)    Atoms: 298
> Info)    Bonds: 0
> Info)    Angles: 0  Dihedrals: 0  Impropers: 0  Cross-terms: 0
> Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
> Info)    Residues: 298
> Info)    Waters: 0
> Info)    Segments: 1
> Info)    Fragments: 298   Protein: 0   Nucleic: 0
> dcdplugin) detected standard 32-bit DCD file of native endianness
> dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
> Info) Using plugin dcd for coordinates from file starting_final.pdb_final_target.pdb_final_structure.dcd
> psfplugin) Detected a Charmm PSF file
> Info) Using plugin psf for structure file initial_ionized.psf
> Info) Analyzing structure ...
> Info)    Atoms: 22165
> Info)    Bonds: 16452
> Info)    Angles: 14698  Dihedrals: 13128  Impropers: 772  Cross-terms: 296
> Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
> Info)    Residues: 6073
> Info)    Waters: 5771
> Info)    Segments: 5
> Info)    Fragments: 5776   Protein: 1   Nucleic: 0
> Info) Using plugin namdbin for coordinates from file OUT_inimin/initial_minimized3.coor
> Info) Opened coordinate file final_adjust.pdb for writing.
> Info) Finished with coordinate file final_adjust.pdb.
> psfplugin) Detected a Charmm PSF file
> Info) Using plugin psf for structure file initial_ionized.psf
> Info) Analyzing structure ...
> Info)    Atoms: 22165
> Info)    Bonds: 16452
> Info)    Angles: 14698  Dihedrals: 13128  Impropers: 772  Cross-terms: 296
> Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
> Info)    Residues: 6073
> Info)    Waters: 5771
> Info)    Segments: 5
> Info)    Fragments: 5776   Protein: 1   Nucleic: 0
> Info) Using plugin namdbin for coordinates from file OUT_inimin/initial_minimized4.coor
> psfplugin) Detected a Charmm PSF file
> Info) Using plugin psf for structure file final_ionized.psf
> Info) Analyzing structure ...
> Info)    Atoms: 20104
> Info)    Bonds: 15078
> Info)    Angles: 14011  Dihedrals: 13128  Impropers: 772  Cross-terms: 296
> Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
> Info)    Residues: 5386
> Info)    Waters: 5084
> Info)    Segments: 4
> Info)    Fragments: 5089   Protein: 1   Nucleic: 0
> Could not open file 'OUT_finmin/final_minimized4.coor' for reading.
> ERROR) Could not read file OUT_finmin/final_minimized4.coor
> Info) Finished with coordinate file OUT_inimin/initial_minimized4.coor.
> Unable to load file 'OUT_finmin/final_minimized4.coor' using file type 'namdbin'.
> 0
> 0
> Info) VMD for LINUXAMD64, version 1.9.2 (December 29, 2014)
> Info) Exiting normally.

Is it an overhead issue? Because when I checked the folder, it reads:

`OUT_inipro:
total 26156
-rw-r--r-- 1     2215 Jan  5 02:02 initial_process0.xst
-rw-r--r-- 1      212 Jan  5 02:02 initial_process0.xsc
-rw-r--r-- 1   531964 Jan  5 02:02 initial_process0.vel
-rw-r--r-- 1  5321476 Jan  5 02:02 initial_process0.dcd
-rw-r--r-- 1   531964 Jan  5 02:02 initial_process0.coor
-rw-r--r-- 1     2215 Jan  5 03:13 initial_process1.xst
-rw-r--r-- 1      212 Jan  5 03:13 initial_process1.xsc
-rw-r--r-- 1   531964 Jan  5 03:13 initial_process1.vel
-rw-r--r-- 1  5321476 Jan  5 03:13 initial_process1.dcd
-rw-r--r-- 1   531964 Jan  5 03:13 initial_process1.coor
-rw-r--r-- 1     2215 Jan  5 03:53 initial_process2.xst
-rw-r--r-- 1      212 Jan  5 03:53 initial_process2.xsc
-rw-r--r-- 1   531964 Jan  5 03:53 initial_process2.vel
-rw-r--r-- 1  5321476 Jan  5 03:53 initial_process2.dcd
-rw-r--r-- 1   531964 Jan  5 03:53 initial_process2.coor
-rw-r--r-- 1      947 Jan  5 04:27 pro.conf  
-rw-r--r-- 1     1375 Jan  5 04:54 FFTW_NAMD_2.11_Linux-x86_64-MPI.txt
-rw-r--r-- 1      213 Jan  5 05:13 res.xsc
-rw-r--r-- 1   531964 Jan  5 05:13 res.vel
-rw-r--r-- 1   531964 Jan  5 05:13 res.coor  
-rw-r--r-- 1    83099 Jan  5 05:13 pro.log
-rw-r--r-- 1     2215 Jan  5 05:13 initial_process3.xst
-rw-r--r-- 1      212 Jan  5 05:13 initial_process3.xsc
-rw-r--r-- 1   531964 Jan  5 05:13 initial_process3.vel
-rw-r--r-- 1  5321476 Jan  5 05:13 initial_process3.dcd
-rw-r--r-- 1   531964 Jan  5 05:13 initial_process3.coor
drwxr-xr-x 2     4096 Jan  5 08:53 .
drwxr-xr-x 7     4096 Jan  5 09:05 ..

OUT_finpro:
total 17984
-rw-r--r-- 1     2299 Jan  5 02:18 final_process0.xst
-rw-r--r-- 1      216 Jan  5 02:18 final_process0.xsc
-rw-r--r-- 1   482500 Jan  5 02:18 final_process0.vel
-rw-r--r-- 1  4826836 Jan  5 02:18 final_process0.dcd
-rw-r--r-- 1   482500 Jan  5 02:18 final_process0.coor
-rw-r--r-- 1     2299 Jan  5 02:54 final_process1.xst
-rw-r--r-- 1      216 Jan  5 02:54 final_process1.xsc
-rw-r--r-- 1   482500 Jan  5 02:54 final_process1.vel
-rw-r--r-- 1  4826836 Jan  5 02:54 final_process1.dcd
-rw-r--r-- 1   482500 Jan  5 02:54 final_process1.coor
-rw-r--r-- 1     1676 Jan  5 03:54 FFTW_NAMD_2.11_Linux-x86_64-MPI.txt
-rw-r--r-- 1      217 Jan  5 04:10 res.xsc
-rw-r--r-- 1   482500 Jan  5 04:10 res.vel
-rw-r--r-- 1   482500 Jan  5 04:10 res.coor  
-rw-r--r-- 1     2299 Jan  5 04:10 final_process2.xst
-rw-r--r-- 1      216 Jan  5 04:10 final_process2.xsc
-rw-r--r-- 1   482500 Jan  5 04:10 final_process2.vel
-rw-r--r-- 1  4826836 Jan  5 04:10 final_process2.dcd
-rw-r--r-- 1   482500 Jan  5 04:10 final_process2.coor
-rw-r--r-- 1      933 Jan  5 04:27 pro.conf
-rw-r--r-- 1      949 Jan  5 04:53 pro.log
drwxr-xr-x 2     4096 Jan  5 08:53 .
drwxr-xr-x 7     4096 Jan  5 09:05 ..
`
Beside something like "after [expr {1000 * 60 * 25}] " inserted into the "prefix".tcl, is there a ready way to do it over? Any experience on computing cluster you can kindly share with us?

Thanks and Regard,
Jordy

**Comment by cihankayacihan** [comment]
Hi Jordy, 

There is a small bug in the code. We are trying to fix it and I will let you know as soon as I fix it.

**Comment by jamesmkrieger** [comment]
Hi Jordy,

Can you try again with the latest CoMD version and let me know if you have any problems please. I have done quite a bit of development of CoMD and it works well for me now.

Best wishes
James

**Comment by jamesmkrieger** [comment]
Seeing as I have been using CoMD so much with no problems, I'm assuming this is not an issue any more and closing it. Feel free to reopen it if you disagree or need more help.
