### ISSUE TITLE
ProDy installation in windows

### ISSUE THREAD

**Issue by marziehphd** [prody/ProDy#350]
Hi
To install ProDy, I performed the following steps: according to the tutorial, I downloaded all requirement software for win32 bit and python 2.7
1-	 python-2.7.13.msi
2-	VCForPython27.msi
3-	numpy-1.12.0rc2+mkl-cp27-cp27m-win32.whl
4-	scipy-0.18.1-cp27-cp27m-win32.whl
5-	ProDy-1.8.2.win32-py2.7.exe   or    pip install ProDy
6-	pip install biopython
7-	finally I append Python and scripts folders (e.g. C:\Python27 and C:\Python27\Scripts) to PATH environment variable.
I think numpy, scipy, biopython have been installed correctly due to after writing “import numpy and etc “to python terminal, they are ok, but prody shows error "**Traceback<most recent call last>:
file "<stdin>" line 1, in <module> importError: No module name ProDy**

please let me know how to fix this problem
thanks a lot
Marzieh

**Comment by SHZ66** [comment]
Please try "import prody" all in lowercase. In case that doesn't work, you can try installing Anaconda which contains scipy, numpy, etc. And then you only need to install biopython and prody.

**Comment by cihankayacihan** [comment]
I think you are able to install prody on windows. Closing it.
