### ISSUE TITLE
how to start prody?

### ISSUE THREAD

**Issue by marziehphd** [prody/ProDy#352]
Hi
thanks a lot for your answer, I installed anaconda and prody on windows, it's ok, but I have one question?
according to the following link related to the tutorial of prody, **http://prody.csb.pitt.edu/tutorials/stiffmech/intro.html**
I can't find out how to start prody? I should use ipython from the start menu then write which command to can calculate Mechstiff, PCA  and other parameters?

please let me know how to solve this problem?

I am looking forward to getting your answer

thanks a lot

**Comment by cihankayacihan** [comment]
yes. you should start from ipython in your start up menu.

**Comment by marziehphd** [comment]
thanks a lot for your guidance,  ipython was worked from the start menu, but I can't understand the following command line?

In [1]: from prody import *

In [2]: from pylab import *

In [3]: ion()

 if it is possible, please explain for me the meaning of the above command ?
thanks a lot
