### ISSUE TITLE
Extract and save all the modes (Eigenvalues and Eigenvectors) 

### ISSUE THREAD

**Issue by mweka007** [prody/ProDy#354]
How to extract and save all the mode (eigenvalue, eigenvector) in external file from ANM prody 
anm.calcModes(x, zeros=True),  
anm.getEigvals().round(3)
 anm.getEigvecs().round(3)

Best Regards,

**Comment by cihankayacihan** [comment]
Hi. 

You can use numpy's savetxt function or you can save an nmd file using writeNMD function. You can find details in the following link. 
http://prody.csb.pitt.edu/manual/reference/dynamics/nmdfile.html

After you print NMD file you can parse it to analyze values.

**Comment by jamesmkrieger** [comment]
Seeing as the original poster has received an answer and not asked for further clarification, I assume this issue is closed.
