### ISSUE TITLE
How to use bbENM?

### ISSUE THREAD

**Issue by noonbluemoon** [prody/ProDy#355]
Dear ProDy developers,

I came across your implementation of bbENM, which is basically dthe tensorial elastic network model published by Srivastava et al.. I installed the latest ProDy version (1.8.2) via pip on my system. 

However, it seems deactivated at the moment. Its import is commented out in prody.dynamics.__init__.py and also the compiled library file prody.dynamics.bbenmtools.so does not exist.

Is the bbENM code not fully functional or untested? Or is there a way how I might use it?

Thanks a lot for your help!

Best,
Ines

**Comment by cihankayacihan** [comment]
Hi, 
We decided to add bbENM but the method needs various parameters and the authors of the method does not want to share their parameters with us. As a result, we forced to stop using it. If you want you can ask the authors of the paper. Thanks.
