### ISSUE TITLE
searchPfam throws an error for specific protein

### ISSUE THREAD

**Issue by cihankayacihan** [prody/ProDy#362]
`searchPfam('1a71A')`
@> PDB file is found in the local folder (/data/prody_tutorials/.../1a71.pdb.gz).
@> UniProt ID code ADHE_HORSE for 1a71 chain A will be used.
@> Retrieving Pfam search results: http://pfam.xfam.org/protein/ADHE_HORSE?output=xml
@> Pfam search completed in 0.28s.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-157-ac83761a4ddf> in <module>()
----> 1 searchPfam('1a71A')

/usr/local/lib/python2.7/dist-packages/prody/database/pfam.pyc in searchPfam(query, **kwargs)
    179             raise ValueError('failed to parse results XML, check URL: ' + url)
    180     else:
--> 181         results = dictElement(root[0], prefix)
    182         try:
    183             xml_matches = results['matches']

IndexError: child index out of range

**Comment by cihankayacihan** [comment]
If pdb_id or uniprot id cannot find anything, we need to rerun with sequence option.

**Comment by jamesmkrieger** [comment]
This is now fixed. See #711
