### ISSUE TITLE
animation is not working

### ISSUE THREAD

**Issue by amanan00** [prody/ProDy#365]
Hi,
While trying to animate modes of my system, the slider bar in vmd main window is moving but nothing is happening in the display. For each modes, I see the arrows but not the motion. 
Any help will be appreciated.
Thanks
Anjela.

**Comment by cihankayacihan** [comment]
Can you be more specific about your problem including os, python version, vmd version and pdb id or link to pdb and the modes that you are trying to visualize.

**Comment by jamesmkrieger** [comment]
I sometimes find that you have to Draw mode arrows before you can Make animations especially if you change the scaling. Have you tried that?

**Comment by jamesmkrieger** [comment]
Without more specific information, we can't help any further so I'm closing this issue.
