### ISSUE TITLE
Can Prody be used to sample pathways of binding/unbinding ligand sites?

### ISSUE THREAD

**Issue by pablorch** [prody/ProDy#367]
Hi,
I would like to know if ProDy, specifically coMD plugin, can be used to sample pathways of ligand binding sites or if there is another software/library more adequate to do it.
Thanks!

**Comment by cihankayacihan** [comment]
I am not sure what you mean by pathways of ligand binding sites. Do you mean a ligand's path to bind a given binding site or all the the binding sites?

**Comment by jamesmkrieger** [comment]
I think the answer is no. You probably want to try some other form of steered or targeted MD.

**Comment by jamesmkrieger** [comment]
It may help for you to look at the work of Albert Lau e.g. https://www.ncbi.nlm.nih.gov/pubmed/29249286 and https://www.ncbi.nlm.nih.gov/pubmed/29665428. The first paper uses long conventional MD simulations on a supercomputer such as Anton. The second reviews his previous work with enhanced sampling methods.

I don't think we can give you more specific advice without understanding exactly what you want to do so I'm closing the issue. Feel free to reopen it if you think there's something in particular we can help with.

Best wishes
James
