### ISSUE TITLE
Change of PDB ID of p38

### ISSUE THREAD

**Issue by SHZ66** [prody/ProDy#380]
[Now the PDB code for 1P38 has been changed to 5UOJ](http://www.rcsb.org/pdb/explore/obsolete.do?obsoleteId=1P38&evtc=Suggest&evta=PDBID&evtl=autosearch_SearchBar_querySuggest). Using the old PDB ID to download the protein will result in an error. Since a lot of our tutorials use this protein, we may need to consider to either change the PDB ID everywhere it appears or find a way to redirect old PDB ID to newer ones. The former is straightforward but requires labour; the latter requires some hard coding. What do you all think?

**Comment by cihankayacihan** [comment]
There should be a way to redirect the link to new PDB or we should be able to figure it out from the output. I will try to debug it. I am sure we can parse the output in a way to figure out the pdb is obsolete and we can switch to fetch the new id.

**Comment by SHZ66** [comment]
Interesting fetchPDBviaHTTP can find the obsolete PDBs, therefore I tweaked the code a little bit to allow using HTTP if FTP couldn't find it. Originally HTTP is used only if FTP throws an error, but now HTTP is used if FTP returns None.
