### ISSUE TITLE
Unit system

### ISSUE THREAD

**Issue by liyigerry** [prody/ProDy#391]
I notice that the units in Prody seem not unified.
For example, distance unit in calcDistance and PCA is Ångström, in RMSD is nm?

**Comment by SHZ66** [comment]
`calcRMSD` should use Angstrom as well. In fact, both `PCA` and `calcRMSD` should use whatever the unit of your PDB file uses. Could you please show me an example that let you think the units are different.

**Comment by liyigerry** [comment]
Hi, @SHZ66 It may my mistakes. I use some other packages at the same time. They confused me.
I will repost this issue if I find the example.
Thanks.
