### ISSUE TITLE
Prody pca error: "Value Error: coordsets must have more than 3 coordinate sets"

### ISSUE THREAD

**Issue by sajad111** [prody/ProDy#406]
Hello Dears,
I am trying make "NMD" files from the PDB produced through PCA analysis in Gromacs. I used the "**g_anaeig -s ../topol.tpr -f ../traj.xtc -v eigenvectors.trr -eig eigenvalues.xvg -proj proj-ev1.xvg -extr ev1.pdb -rmsf rmsf-ev1.xvg -first 1 -last 1**" command and selected the backbone for analysis, to produce the "ev1.pdb" file (attached). Then I used this pdb file as the input in "**prody pca ev1.pdb**" command for producing the NMD file. However, I was faced with the following error. Could you please help me know what I am missing?

**Error:**
**"Value Error: coordsets must have more than 3 coordinate sets"**
[ev1.pdb.txt](https://github.com/prody/ProDy/files/1057554/ev1.pdb.txt)

**Comment by SHZ66** [comment]
How many frames are there in your ev1.pdb?

**Comment by sajad111** [comment]
Thank you very much for your reply. It was two frames and I think it needs at least 3 frames for the analysis. I tried with more frames and it was fixed.
Thank you

**Comment by SHZ66** [comment]
I'm glad that you've already fixed it. I will close this post now, and feel free to reopen it if you have further questions.
