### ISSUE TITLE
Build failing on MacOS 10.12 with anaconda

### ISSUE THREAD

**Issue by chrisgoedde** [prody/ProDy#407]
I'm updating my python distribution and trying to install prody, and it's failing. The error is:

building 'prody.dynamics.saxstools' extension
gcc -bundle -undefined dynamic_lookup -L/Users/goedde/Dropbox/anaconda/lib -L/Users/goedde/Dropbox/anaconda/lib -arch x86_64 -L/Users/goedde/Dropbox/anaconda/lib -o build/lib.macosx-10.7-x86_64-3.6/prody/dynamics/saxstools.cpython-36m-darwin.so
clang: error: no input files
error: command 'gcc' failed with exit status 1

This is in the "python setup.py build" stage. Everything in the build works up to that point. Any suggestions on what might be misconfigured or what I'm doing wrong? Thanks.

**Comment by cihankayacihan** [comment]
Hi, we had some issues about saxstools and we will fix them in next week. If you have urgent need to prody our suggestion is to comment out lines 90,91 and 92 from source files and try to reinstall. Thanks.

**Comment by chrisgoedde** [comment]
Thanks!
