### ISSUE TITLE
parseDCD error in python 3.6

### ISSUE THREAD

**Issue by chrisgoedde** [prody/ProDy#408]
Having gotten prody installed in my python 3.6 installation, I've encountered another error, in parseDCD. The error is:

/Users/goedde/Documents/anaconda/lib/python3.6/site-packages/prody/trajectory/dcdfile.py in parseDCD(filename, start, stop, step, astype)
    497     LOGGER.info('DCD file contains {0} coordinate sets for {1} atoms.'
    498                 .format(n_frames, dcd.numAtoms()))
--> 499     ensemble = dcd[slice(start,stop,step)]
    500     dcd.close()
    501     time_ = time() - time_ or 0.01

/Users/goedde/Documents/anaconda/lib/python3.6/site-packages/prody/trajectory/trajbase.py in __getitem__(self, index)
     53             if isinstance(index, slice):
     54                 ens = Ensemble('{0} ({1[0]}:{1[1]}:{1[2]})'.format(
---> 55                                     self._title, index.indices(len(self))))
     56             else:
     57                 ens = Ensemble('{0} slice'.format(self._title))

TypeError: 'float' object cannot be interpreted as an integer

This works fine on the same file in a python 2.7 installation.

Edit: Looking at more messages, I see that prody is producing the following under python 3.6:

@> 2670 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> WARNING DCD header claims 0 frames, file size indicates there are actually 1000.0 frames.
@> DCD file contains 1000.0 coordinate sets for 2670 atoms.

So the dcd parser is returning a float for the number of frames. The suspect lines seem to be lines 213 and 214 (from dcdfile.py):

        n_csets = (getsize(self._filename) - self._first_byte
                                                    ) / self._bytes_per_frame

This returns an integer under python 2, but a float under python 3, correct? So these lines should be changed or the result cast to an int. Does that seem right?

**Comment by SHZ66** [comment]
Yes, you are right. Thanks for the input and fix. We will fix this in the next release. You can fix your own version on your local machine as well by modifying the source code.

**Comment by SHZ66** [comment]
The new release is [out](https://pypi.org/project/ProDy/#description), so I'm closing this issue for now.
