### ISSUE TITLE
Replacing an existing residue with another

### ISSUE THREAD

**Issue by SG9291** [prody/ProDy#410]
Is it possible to replace a residue with a different one?

**Comment by SHZ66** [comment]
Hi,

You can try setResname() for Residue instances or setResnames() for AtomGroup instances. But it will only change the identity of the residue. The atoms and their positions will not be changed.

**Comment by jamesmkrieger** [comment]
This is possible but not advised. It can be achieved by superposing backbones, setting properties to match and adding Atomgroups as in the example below for making a threonine to alanine mutation:

`ampar = parsePDB('3kg2')`
`bT84 = ampar.select('chain B and resnum 84')`
`bA57 = ampar.select('chain B and resnum 57').copy()`
`T = calcTransformation(bA57.backbone, bT84.backbone)`
`moved_bA57 = applyTransformation(T, bT84)`
`moved_bA57.setResnums(84)`
`ampar_bT84A = ampar.select('not (chain B and resnum 84)').copy() + moved_bA57`

**Comment by jamesmkrieger** [comment]
Please feel free to reopen and ask more questions. For now this issue is closed.

**Comment by jamesmkrieger** [comment]
Actually the last line should be as follows:
`ampar_bT84A = ampar.select('resindex 0 to 852').copy() + moved_bA57 + ampar.select('resindex 854 to {0}'.format(ampar.getResindices()[-1])).copy()`

(T84 in chain B has resindex 853 and this way the new alanine gets it too)
