### ISSUE TITLE
getNormDistFluct

### ISSUE THREAD

**Issue by T-B-F** [prody/ProDy#413]
Hi ProDy's team and thanks for the package.

I think there is may be a problem of indentation in the getNormDistFluct function of gnm.py.
Lines 396 to 400 look like:
```
for i in range(n_atoms):
    for j in range(i+1,n_atoms):
        r_ij[i][j] = coords[j,:] - coords[i,:]
        r_ij[j][i] = r_ij[i][j]
        r_ij_n = LA.norm(r_ij, axis=2)
```
shouldn't it be something like below, with the norm computed on the final r_ij matrix and not at each iteration?
```
for i in range(n_atoms):
    for j in range(i+1,n_atoms):
        r_ij[i][j] = coords[j,:] - coords[i,:]
        r_ij[j][i] = r_ij[i][j]

r_ij_n = LA.norm(r_ij, axis=2)
```

**Comment by jamesmkrieger** [comment]
I agree. Thanks for spotting this. I have updated it in #670 and am closing this issue.
