### ISSUE TITLE
setACSIndex() does not update HierView

### ISSUE THREAD

**Issue by morbalint** [prody/ProDy#414]
```
>>> import prody
>>> pdb = prody.parsePDB("1d3z")
>>> pdb.setACSIndex(0)
>>> pdb.getHierView()._acsi
0
>>> pdb.setACSIndex(1)
>>> pdb.getHierView()._acsi
0
```

the second call of pdb.getHierView()._acsi should return 1. this also gives wrong coordinates when using the HierView

**Comment by SHZ66** [comment]
Thanks for pointing out this. I will see if we can make a quick fix.

**Comment by SHZ66** [comment]
I looked into the code so that apparently acsi is updated when HierView is initialized, but somehow it got forgotten afterward. If you run:
```
hv = pdb.getHierView()
hv.update()
print hv._acsi
```

You can see that the acsi is set correctly to 1. I will try to trace down where acsi is changed.

**Comment by SHZ66** [comment]
The problem is that getHierView() will not create a new HierView if a HierView is built on this atomgroup already. So simply run a HierView.update() will fix your problem.

**Comment by morbalint** [comment]
Thanks!
