### ISSUE TITLE
Problem installing prody in MacOS sierra

### ISSUE THREAD

**Issue by juvenalyosa** [prody/ProDy#415]
I am trying to install prody in MacOS Sierra following the installing ProDy to Chimera Python, everything goes ok (pip installation, scicpy installation) but when I try to installing ProDy I found the next error: 

/Applications/Chimera.app/Contents/MacOS/chimera --nogui --silent --script "/Applications/Chimera.app/Contents/Resources/bin/pip install -U ProDy"
Collecting ProDy
  Using cached ProDy-1.9.tar.gz
    Complete output from command python setup.py egg_info:
    /Applications/Chimera.app/Contents/Resources/share/__main__.py: option -c not recognized
    usage: /Applications/Chimera.app/Contents/Resources/share/__main__.py [--help] [--nogui] [-n] [--nostatus] [--silent] [--nomultisample] [--fullscreen] [-f] [--stereo <mode>] [--bgopacity] [--geometry wxh+x+y] [--title title] [--start <extension name>] [--pypath <directory>] [-P <directory>] [--send <file>] [--preferences <file>] [--visual <visual>] [--screen <screen>] [--script <python file>] [--root] [--release] [--version] [--listfiletypes] [--opt] [--debug] [--debug-opengl] [--embed]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 2 in /private/var/folders/l5/t21bqq7n15x7052mdz4gfl280000gn/T/pip-build-a3MR5u/ProDy/

I can not figure out where is calling the "-c " option which can not be recognized by the __main__.py

thanks in advance for your help

Juvenal

**Comment by cihankayacihan** [comment]
This issue is addressed in 1.9.3
