### ISSUE TITLE
Can ProDy be used to find neighbors of atoms?

### ISSUE THREAD

**Issue by pelegs** [prody/ProDy#423]
I'm trying to perform a calculation which is depended on pairwise particle interactions.
For this I need to know the neighbors of specific atoms (to avoid O(N^2) complexity).
The findNeighbors() method seems to be too general, since it finds any pairs within a radius R, while I'm looking for all atoms within radius R around a specific point.
I there a way to do this, already implemented in ProDy? If not - does ProDy store some sort of cell information so I can easily implement it?

**Comment by SHZ66** [comment]
Hi,

ProDy doesn't have a function for that, however, you can implement it fairly easily with the coordinates of the atoms. Each Chain, AtomGroup, and AtomMap class has a method called getCoords() that you can use to extract the coordinates. It will be a 3-by-n numpy ndarray. Then you can calculate the distance with numpy cdist or pdist or your own formula.

**Comment by jamesmkrieger** [comment]
You could also set your specific point using `getCoords()` or any other array

**Comment by jamesmkrieger** [comment]
Please reply again and reopen the issue if you need any more help. For now I'll consider the issue closed.
