### ISSUE TITLE
Going from nmd to npz

### ISSUE THREAD

**Issue by mfmcronin96** [prody/ProDy#439]
I am currently doing PCA on a protein. I have generated nmd files using NMW's prody extension, but I have a DCD and PSF file so the ensemble tutorials are a little confusing. Is there a simple way to generate a .npz file from .nmd file and PSF and DCD?

**Comment by SHZ66** [comment]
Hi the NMD file contains PCA modes which can be directly calculated from trajectories from DCD and PSF. You could use parsePSF() and parseDCD() to read the files and then perform PCA on them. There is also a function called parseNMD() which can be used to load NMD files into ProDy.

**Comment by jamesmkrieger** [comment]
You should then be able to use saveModel with the output from parseNMD. For example:

`nma, atoms = parseNMD('myANM.nmd', type=ANM)`
`saveModel(nma, 'myANM')`

Please be aware that parseNMD does not use the type argument or handle eigenvalues correctly but the latest version can do this following #674 and this will be in the next release.
