### ISSUE TITLE
ProDy tutorial conformation sampling

### ISSUE THREAD

**Issue by TerezaGerguri** [prody/ProDy#441]
When performing the tutorial for conformational sampling using the p38.pdb (actually any pdb file) I am unable to continue after: showSqFlucts(p38_anm_ext) command, I got the error: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-3c0e3fdbf50f> in <module>()
----> 1 showSqFlucts(p38_anm_ext)
/path/plotting.py in showSqFlucts(modes, *args, **kwargs)
 548 
    549     show_hinge = kwargs.pop('hinge', False)
--> 550     sqf = calcSqFlucts(modes)
    551     if not 'label' in kwargs:
    552         kwargs['label'] = str(modes)

/path/analysis.py in calcSqFlucts(modes)
    253             return (modes._getArray() ** 2)
    254     else:
--> 255         sq_flucts = np.zeros(modes.numAtoms())
    256         if isinstance(modes, VectorBase):
    257             modes = [modes]

TypeError: 'float' object cannot be interpreted as an integer

I followed the tutorial step by step and everything was ok until this command. Then I cannot perform any ampling calculations, I got the "TypeError: 'float' object cannot be interpreted as an integer "

Thank you very much in advance.
TypeError: 'float' object cannot be interpreted as an integer

**Comment by cihankayacihan** [comment]
We are working on it right now. Thanks.

**Comment by SHZ66** [comment]
I believe this problem should relate to #553 and should be fixed in #628.
