### ISSUE TITLE
PCA mode unit

### ISSUE THREAD

**Issue by Dharmes** [prody/ProDy#446]
Hi, I have done PCA analysis with 10 modes. I got the file ABC_pca_proj.txt as output for  10 different modes. i was wondering what is the unit of the values inside this file. I have used pdb which has Angstrom coordinates. So I am guessing it is Angstrom but the value I got like -5.91248e-06 -4.26634e-06 ....so is it in Angstrom?

**Comment by cihankayacihan** [comment]
PCA will return you eigenvectors and vectors have magnitude 1 and the unit is Angstrom but I suggest that the vectors need to be used only as directions and their magnitudes are scaled with corresponding eigenvalues.
