### ISSUE TITLE
PCA projection

### ISSUE THREAD

**Issue by Dharmes** [prody/ProDy#453]
Hi, I am running PCA analysis on NAMD MD simulations trajectory using Prody applications. I got number of output files. I want to plot projection of PC1 vs PC2 on to the common subspace. I plot output file with projection written "sample-pca_proj.txt" but the values in the file is so small such as 3.61147e-06.  Is there something I am missing to plot the projection data? Do I have to multiply with evalues ? I tried but did not get higher value.

**Comment by jamesmkrieger** [comment]
Hi,

The problem is that the projection was normalized by default. This is fixed in the latest ProDy version so I am closing this issue.
