### ISSUE TITLE
ProDy 1.9.3 parseDCD: n must be an integer error

### ISSUE THREAD

**Issue by osercinoglu** [prody/ProDy#454]
I'm getting this error while trying to parse a DCD with a step (ProDy 1.9.3, Python 3.5.2):

`ValueError                                Traceback (most recent call last)
<ipython-input-3-54833b070332> in <module>()
----> 1 traj = parseDCD('trajectory.dcd',step=10)

/usr/local/lib/python3.5/dist-packages/prody/trajectory/dcdfile.py in parseDCD(filename, start, stop, step, astype)
    497     LOGGER.info('DCD file contains {0} coordinate sets for {1} atoms.'
    498                 .format(n_frames, dcd.numAtoms()))
--> 499     ensemble = dcd[slice(start,stop,step)]
    500     dcd.close()
    501     time_ = time() - time_ or 0.01

/usr/local/lib/python3.5/dist-packages/prody/trajectory/trajbase.py in __getitem__(self, index)
     59             if self._weights is not None:
     60                 ens.setWeights(self._weights.copy())
---> 61             ens.addCoordset(self.getCoordsets(index))
     62             ens.setAtoms(self._atoms)
     63             return ens

/usr/local/lib/python3.5/dist-packages/prody/trajectory/dcdfile.py in getCoordsets(self, indices)
    335             return data
    336         else:
--> 337             return TrajFile.getCoordsets(self, indices)
    338 
    339     getCoordsets.__doc__ = TrajBase.getCoordsets.__doc__

/usr/local/lib/python3.5/dist-packages/prody/trajectory/trajfile.py in getCoordsets(self, indices)
    145             diff = index - prev
    146             if diff > 1:
--> 147                 self.skip(diff-1)
    148             xyz = next()
    149             if xyz is None:

/usr/local/lib/python3.5/dist-packages/prody/trajectory/trajfile.py in skip(self, n)
    165             raise ValueError('I/O operation on closed file')
    166         if not isinstance(n, int):
--> 167             raise ValueError('n must be an integer')
    168         if n > 0:
    169             left = self._n_csets - self._nfi

ValueError: n must be an integer`

The trajectory appears to load fine if the default step value (1) is used.

**Comment by jamesmkrieger** [comment]
This issue has been fixed so I am closing it.
