### ISSUE TITLE
pfam hmmscan error

### ISSUE THREAD

**Issue by Lucianoaegypti** [prody/ProDy#456]
I tyed to follow tutorial of alingment and I got this:

In [8]: sequence = ('PMFIVNTNVPRASVPDGFLSELTQQLAQATGKPPQYIAVHVVPDQLMAFGGSSE'
   ...: 'PCALCSLHSIGKIGGAQNRSYSKLLCGLLAERLRISPDRVYINYYDMNAANVGWNNSTFA')

In [9]: matches = searchPfam(sequence) 
@> Submitted Pfam search for sequence "PMFIVNTNVPRASVPD...".
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-e96c3a606518> in <module>()
----> 1 matches = searchPfam(sequence)

/usr/lib64/python2.7/site-packages/prody/database/pfam.pyc in searchPfam(query, **kwargs)
     88             root = ET.XML(xml)
     89         except Exception as err:
---> 90             raise ValueError('failed to parse results XML, check URL: ' + url)
     91         matches = {}
     92         for child in root[0]:

ValueError: failed to parse results XML, check URL: https://www.ebi.ac.uk/Tools/hmmer/search/hmmscan?output=xml

Does anyone have a clue how I could fix it?
Regards.

**Comment by jamesmkrieger** [comment]
I fixed this by using tsv format instead of xml: #688 

This now works so issue closed
