### ISSUE TITLE
No grids generated

### ISSUE THREAD

**Issue by aminsagar** [prody/ProDy#457]
Dear All,
I am trying to generate grids after a drugui simulation. The program exits with a success message but no dx files are generated. I am using the 5 membered rings as probes. I don't have any of the default probes. Can someone please help me with this?
I would be really grateful.
Regards,
Amin.

**Comment by jamesmkrieger** [comment]
Hi Amin,

Could you tell us something more about your probes please. Did you get them from CGenFF?

Best wishes
James

**Comment by jamesmkrieger** [comment]
Currently, DruGUI supports simulations with custom probes but not analysis unless you rename those probes to one of the default ones. If you rename them to one of these 5 e.g. IPRO then it should work to generate grids for them.

**Comment by jamesmkrieger** [comment]
We will develop this further at some point. Right now, we are using current scripts, which Jiyoung or Hongchun could maybe share with you or advise you on. I have assigned both of them to this issue as they are the main people working with DruGUI.

**Comment by aminsagar** [comment]
Thanks a lot for the help. I had this problem quite a while ago and I was
able to solve it. I don’t remember for sure, but it was very likely solved
by following your suggestion of renaming.
May I mention that using drugui, I got the same binding sites that were
discovered using a high throughput crystallisation based screening. And
that too with just one day of computational time.

Thanks again for the help.

Best Regards,
Amin.

**Comment by jamesmkrieger** [comment]
Wow, that's great. Thanks for the positive feedback!
