### ISSUE TITLE
prody path on Mac

### ISSUE THREAD

**Issue by SamanehVasey** [prody/ProDy#458]
Hi all.

I am trying to use the prody interface in VMD through the Normal Mode Wizard to do PCA. I get the error message that I have to specify the prody path. However I am unable to locate the prody executable. Where is this file located on a Mac? My VMD version is 1.9.3 and I have the two nmwiz tcl files located here: /Applications/VMD\ 1.9.3.app/Contents/vmd/plugins/noarch/tcl/nmwiz1.2/

I appreciate your help.
Samaneh

**Comment by jamesmkrieger** [comment]
Hi,

How did you install ProDy? There should be prody/scripts folder that will probably be in site-packages of whichever Python you use it in.

**Comment by jamesmkrieger** [comment]
You may have to manually add this to your PATH if you installed it manually

**Comment by SHZ66** [comment]
The new release is [out](https://pypi.org/project/ProDy/#description), and this problem should be fixed. Could you please confirm.

**Comment by jamesmkrieger** [comment]
I'm assuming this issue is fixed seeing as we have had no further comments here. Please feel free to reopen this is you are still having problems.
