### ISSUE TITLE
prody path in linux

### ISSUE THREAD

**Issue by yccai** [prody/ProDy#460]
I use "Normal Mode Wizard" tool in VMD to analysis my PDB file, but the tool can not find path of prody. How could I solve it? Thank you!

**Comment by jamesmkrieger** [comment]
Please can you run `prody --version` and check that the prody apps are available. How did you install ProDy?

**Comment by jamesmkrieger** [comment]
If you installed it manually you may need to add the location of ProDy/prody/scripts to your path.

**Comment by SHZ66** [comment]
The new release is [out](https://pypi.org/project/ProDy/#description), and this problem should be fixed. Could you please confirm.

**Comment by yccai** [comment]
Thank you very much! The problem had been fixed.

**Comment by SHZ66** [comment]
Thanks for confirming it, I will close the issue for now.
