### ISSUE TITLE
Apply a new mode to a PDB file

### ISSUE THREAD

**Issue by gelusiji** [prody/ProDy#464]
Hi there, I've created the *.nmd file, containing several modes.
I combined those modes together and want to apply on the original molecular to have the updated molecular.
Can anybody tell me how to do that with VMD?
Thanks a lot!

**Comment by jamesmkrieger** [comment]
Use NMWiz to generate an animation for that mode with a particular RMSD then select the animation object for that mode and then click File --> Save coordinates. See http://prody.csb.pitt.edu/tutorials/nmwiz_tutorial/nmwiz.html and http://ambermd.org/tutorials/basic/tutorial2/section7.htm for details
