### ISSUE TITLE
Missing functions in analysis.py

### ISSUE THREAD

**Issue by SHZ66** [prody/ProDy#474]
I just found that dynamics/analysis.py contains two codes that look almost the same and are concatenated. I have merged them (#473) with changes in both duplicates. However, according to the header, there are two functions missing: 

calcEntropyTransfer
calcOverallNetEntropyTransfer

And one dummy function with no actual function:
calcFracDimension

Could someone look into this and check if the implementations were lost during the updates?

**Comment by cihankayacihan** [comment]
calcEntropyTransfer
calcOverallNetEntropyTransfer

moved to entropy.py instead of analysis.py. calcFracDimension is something we started but we never finalized.
