### ISSUE TITLE
Where can I access oanm and ognm text files?

### ISSUE THREAD

**Issue by mayeshh** [prody/ProDy#491]
Hello,

I have just discovered ProDy and am using it with Jupyter Notebooks. I am having trouble completing the Gaussian Network Model and Anisotropic Network Model tutorial available online. It seems I am missing these text files:

oanm_eigvals.txt
oanm_hes.txt
oanm_slwevs.txt
ognm_kirchhoff.txt

Where can I find these files? Or should I be able to generate them, somehow? Any tips to get started are vey welcome, and please excuse the naive question! 

Thanks!

Maya

**Comment by jamesmkrieger** [comment]
Hi Maya,

Apologies you can't find these files. They should be under the ZIP and TGZ links on http://prody.csb.pitt.edu/tutorials/enm_analysis/ but for some reason they are not there. I am now trying to put them there.

Best wishes
James

**Comment by jamesmkrieger** [comment]
I have temporarily fixed this by copying them around on the website. I will look into how to get these files to made and put in the right place automatically so that other tutorial files are there too but at least for now you can access these ones.

**Comment by mayeshh** [comment]
Excellent, thank you!

**Comment by jamesmkrieger** [comment]
This is a separate issue. Please open another one instead of commenting on existing ones
