### ISSUE TITLE
@> WARNING More than 6 zero eigenvalues are calculated

### ISSUE THREAD

**Issue by TerezaGerguri** [prody/ProDy#513]
Hello,

I have a normal pdb file and when trying to calculate ANM a I got this message: '@> WARNING More than 6 zero eigenvalues are calculated'. Could you please explain to me what is wrong with my structure or pdb file? I have never received such a message and I am using ProDy ANM and GNM regularly.

Any help would be appreciated, thank you very much.

**Comment by SHZ66** [comment]
Hi,

Please check if there are disconnectivity in your system. It could be isolated atoms. If you really want those atoms in your system, please try increasing the `cutoff ` in `buildKirchhoff` or 'buildHessian`.

**Comment by jamesmkrieger** [comment]
This is an expected behaviour when the network is poorly connected and I am therefore closing this issue. We will make the warning clearer too.

Best wishes
James
