### ISSUE TITLE
Release 1.9

### ISSUE THREAD

**Issue by sagitter** [prody/ProDy#540]
Hello everyone.

I see a `ProDy-1.9` release (final changes) available, but previous releases (1.9.*) were highter than 1.9.
 Do you consider it like was a definitive release of ProDy?

**Comment by SHZ66** [comment]
Hi,

The most recent release is [1.9.4](https://pypi.org/project/ProDy/). It is a pre-release version so some of the new functions are still developing. We aim to make another release really soon.
