### ISSUE TITLE
extendModel seems to give too many atoms.

### ISSUE THREAD

**Issue by gsrule** [prody/ProDy#636]
Hi
When I use extend model I seem to get 4x the number of atoms., or I don't seem to understand how the command is used

 For example if I use 1ubq with hydrogens added I get the following for just the backbone atoms:
ubi=parsePDB('1ubqH.pdb')
 bb_ubi=ubi.select('backbone')
 anm = ANM('ubi')
 anm.buildHessian(bb_ubi)
 anm.calcModes()
all_anm,all_atoms=extendModel(anm,bb_ubi,ubi.select('all'))

yet the original file only has 1231 atoms.

**Comment by SHZ66** [comment]
Thank you for reporting it. The problem is that extendModel was designed only for extending C-alpha models, and so that in your case because there are four backbone atoms per residue, so each residue is counted four times. We will work on a fix and make a release soon.

**Comment by SHZ66** [comment]
This is fixed and a new version will be released in next week.

**Comment by gsrule** [comment]
Thanks for the fast response.

Gordon

**Comment by SHZ66** [comment]
You are welcome. I will close this issue for now unless you have other problems.
