### ISSUE TITLE
class PDBEnsembleBuilder

### ISSUE THREAD

**Issue by abakan** [prody/ProDy#64]
Implement a class for making PDB ensemble building easier. The class should handle multiple chains ensembles. The class should take reference chains and resolution information. Resolution can be "calpha", "backbone", or "allatom". `addStructure` method should determine with chains match with which chains.

```
class PDBEnsembleBuilder():
    def __init__(refpdb, resolution='ca'):
        pass
    def addStructure(pdb):
       pass
    def getEnsemble():
       pass
```

**Comment by SHZ66** [comment]
I implemented a function `buildPDBEnsemble` instead of a whole class. The function should suffice. #381
