### ISSUE TITLE
prody align and alignPDBEnsemble

### ISSUE THREAD

**Issue by ruska612** [prody/ProDy#665]
The aligned pdb structures seem not so good obtained from alignPDBEnsemble, but actually these two structures share much similarity. And then I used the `prody align` command to test this, the result was not improved. 
`prody align 5amh 4ci1 -i 10 -o 10`  # 5amh_A.pdb and 4ci1_B.pdb
## prody produced:
[image](https://user-images.githubusercontent.com/29448902/39921601-16e10674-554e-11e8-8a62-70746a281222.png)
## realign using pymol
[image](https://user-images.githubusercontent.com/29448902/39921550-ecffd4de-554d-11e8-9f39-709a257fa0d8.png)

So are there any suggestions to improve the alignment ? Thank you.

**Comment by SHZ66** [comment]
We will update prody app in the future, but at this point, you can use cealign inside prody by:

```
from prody import *
prot1 = parsePDB('5amh', chain='A')
prot2 = parsePDB('4ci1', chain='B')

ens = buildPDBEnsemble([prot1, prot2], pwalign='ce', seqid=10)
msa = ens.getMSA()
```

`ens` will be a `PDBEnsemble` containing both conformations, and `msa` will be the sequence alignment. `seqid` is set to 10 as their sequence similarity might be low and it is probably the reason why pairwise alignment has failed.

**Comment by ruska612** [comment]
Thank you very much ! I've tried the method you mentioned, however there were still some problems.
![image](https://user-images.githubusercontent.com/29448902/39976607-4bf33614-5767-11e8-9978-d51f181a636c.png)
![image](https://user-images.githubusercontent.com/29448902/39976633-65514a74-5767-11e8-8e73-e0a7b531e7e3.png)

**Comment by SHZ66** [comment]
Oh, my bad. I forgot to select calpha for the alignment. I also lowered the `coverage` threshold because it seems that one of the protein is much longer than the other and most likely only part of them can be aligned with each other.

Here is updated code:
```
from prody import *
prot1 = parsePDB('5amh', subset='ca', chain='A')
prot2 = parsePDB('4ci1', subset='ca', chain='B')

ens = buildPDBEnsemble([prot1, prot2], pwalign='ce', seqid=10, coverage=10)
msa = ens.getMSA()
```

**Comment by ruska612** [comment]
Thanks, now it works well.
