### ISSUE TITLE
Building Covariance Application Error

### ISSUE THREAD

**Issue by genericsciencer** [prody/ProDy#722]
Hello everyone,

I have VMD 1.9.3 and ProDy 1.10.7 installed on my machine running Ubuntu 16.04 (64 bit). I also have Biopython 1.71 and NumPy 1.14.3.

When trying to use the ProDy interface from NMWiz in VMD, I get the following error message:
`@> Building covariance [  0%] 58s
                                 
_---Many lines of this later ---_
                                
@> Building covariance [ 99%] 1s
                                
@> Building covariance [100%] 0s

@> Building covariance [  0%] 58s

_---Many lines of this later ---_         

@> Building covariance [ 99%] 1s
                                
@> Building covariance [100%] 0s
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody {*}$args"
    (procedure "::NMWiz::prodySubmitPCAjob" line 61)
    invoked from within
"::NMWiz::prodySubmitPCAjob"
    (procedure "::NMWiz::prodySubmitJob" line 26)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)`

This error seemed similar to [Issue 241](https://github.com/prody/ProDy/issues/241), but I didn't get any lines about the library error.

I didn't start having problems until I updated all anaconda packages. I uninstalled and reinstalled ProDy, after receiving some Traceback error messages yesterday. I am not sure what else to try at this point and would appreciate some guidance.

**Comment by jamesmkrieger** [comment]
Hi,

I'll look into this further and try to sort out a fix as soon as possible. Thanks for reporting it.

**Comment by jamesmkrieger** [comment]
This seems to be the same error as #746 so I'm closing this one and please could you follow up on that one.
