### ISSUE TITLE
parsePDB fails to parse chain

### ISSUE THREAD

**Issue by gtzotzos** [prody/ProDy#725]
I'm following the instructions given in the tutorial ProDy/Ensemble Analysis/**Heterogeneous X-ray Structures**

In my example:
pdbids = ['3N7H', '3K1E', '3OGN', '3Q8I']

structures = parsePDB(*pdbids, chain='A', subset='ca', compressed=False)

does not parse the above structures as required (chain A only)

**Comment by jamesmkrieger** [comment]
This works on my system. Please try updating to the latest ProDy version and let me know if you still have a problem.

**Comment by gtzotzos** [comment]
Thank you. I downloaded and installed the latest ProDy version (**see below**)
Processing ProDy-1.10.7-py3.6-macosx-10.7-x86_64.egg
creating /anaconda3/lib/python3.6/site-packages/ProDy-1.10.7-py3.6-macosx-10.7-x86_64.egg
Extracting ProDy-1.10.7-py3.6-macosx-10.7-x86_64.egg to /anaconda3/lib/python3.6/site-packages
Adding ProDy 1.10.7 to easy-install.pth file
Installing evol script to /anaconda3/bin
Installing prody script to /anaconda3/bin

Installed /anaconda3/lib/python3.6/site-packages/ProDy-1.10.7-py3.6-macosx-10.7-x86_64.egg
Processing dependencies for ProDy==1.10.7
Finished processing dependencies for ProDy==1.10.7

Issuing commands:
**pdbids = ['3N7H', '3K1E', '3OGN', '3Q8I']**

**structures = parsePDB(*pdbids, chain='A', subset='ca', compressed=False)**

The problem persists. The downloaded structures 3N7H, etc still consist of two chains (A and B)

**Comment by jamesmkrieger** [comment]
Hi,

Do you mean that the PDB file has two chains? That's to be expected. The chain argument in ProDy is only for parsing into Python.

You can write out a new PDB file with writePDB e.g.

`writePDB('3N7HA', structures[0])`
