### ISSUE TITLE
Error: Searching the PDB with Dali

### ISSUE THREAD

**Issue by gtzotzos** [prody/ProDy#729]
Trying to follow the tutorial: http://prody.csb.pitt.edu/tutorials/signdy_tutorial/data.html

After issuing commands:

from prody import *
from pylab import *
ion()
dali_rec = searchDali('3H5V','A')

I get the following error message: 
/anaconda3/lib/python3.6/site-packages/prody/ensemble/dali.py in getRecord(self, url, localFile, **kwargs)
    115                     else:
    116                         html = urllib2.urlopen(url).read()
--> 117                 if html.find('Status: Queued') > -1:
    118                     log_message = '(Dali searching is queued)...'
    119                 elif html.find('Status: Running') > -1:

**TypeError: a bytes-like object is required, not 'str'**

My environment is:
**Python 3.6.4** |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
**IPython 6.2.1** -- An enhanced Interactive Python. Type '?' for help.

**Comment by fongchun** [comment]
We used Python 3.6.5 | Anaconda (and 2.7) and it works well. I am not sure whether it is a problem for the Python 3.6.4 only.

**Comment by jamesmkrieger** [comment]
I just tried with Python 3.6.4 and I still have no problem with this.

**Comment by gtzotzos** [comment]
I think that Dali has been blocking my proxy.

Thanks for the feedback

**Comment by jamesmkrieger** [comment]
Hmm ok. Thanks for letting us know.
