### ISSUE TITLE
Projection plot to x, y list

### ISSUE THREAD

**Issue by kmarcus89** [prody/ProDy#732]
Hello!
I would like to print a list of all of the coordinates found in a 2D PCA projection (in x, y format). How can this be accomplished? 
Thank you! Amazing program.

**Comment by jamesmkrieger** [comment]
Hi,

You need to use calcProjection. That should return an array that you can print out.

Let me know if you need any more help.

Best wishes
James

**Comment by jamesmkrieger** [comment]
Please let me know if this solved your problem.

**Comment by jamesmkrieger** [comment]
I assume this worked as you haven't said anything else so I'm closing this issue. Feel free to open it again if you need more help.

Best wishes
James
