### ISSUE TITLE
Structure Comparison Error

### ISSUE THREAD

**Issue by m-meli** [prody/ProDy#733]
Hi,

i have vmd 1.9.3, ProDy 1.10.7, ipython 5.7.0, biopython 1.72, numpy 1.14.5, on CentOs 7.0. When i run structure comparison i get this error:

wrong # args: should be "::nmdset0::initialize xyz m d t l i an rn ri ci sn bf"
wrong # args: should be "::nmdset0::initialize xyz m d t l i an rn ri ci sn bf"
    while executing
"${ns}::initialize $coordinates $modes 3 $title $lengths $indices $atomnames $resnames $resids $chainids $bfactors"
    (procedure "::NMWiz::calcDeform" line 42)
    invoked from within
"::NMWiz::calcDeform"
    invoked from within
".nmwizstrcomp.mainFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizstrcomp.mainFrame.prodySubmit"
    (command bound to event)

i try with different structure and file format with the same result.
Thanks in advance for any suggestion.

**Comment by jamesmkrieger** [comment]
I can't even get it to recognise any molecules.

**Comment by jamesmkrieger** [comment]
I'll look into it further at some point in a few weeks.

**Comment by jamesmkrieger** [comment]
Bumping this and I’ll look soon

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. The problem was a missing segnames argument and this is now fixed. Please replace nmwiz.tcl in the plugins directory with the one from https://github.com/prody/NMWiz/ to use the corrected version.
