### ISSUE TITLE
passing variable to ensemble.setAtoms

### ISSUE THREAD

**Issue by msturlese** [prody/ProDy#739]
Hi,

I am having troubles in passing a variable for ensemble.setAtoms
for example, this works:
ensemble.setAtoms(structure.index_2743)

but if I have to place a variable on the index argument, how to deal with it? 

Thanks, Great tool!

**Comment by jamesmkrieger** [comment]
What do you mean index argument? You should be able to do `ensemble.setAtoms(structure)` or `ensemble.setAtoms(structure.ca)` or ensemble.setAtoms(structure.select('resnum 1 to 4'))` or anything like that.

Please could you provide more information on what you're doing.

**Comment by msturlese** [comment]
Sorry, I mean just to iterate over different atoms inside a loop.

Anycase the solution you propose works !
ensemble.setAtoms(structure.select('resnum 1 to 4'))

thanks for your help!

**Comment by jamesmkrieger** [comment]
You're welcome. 

You could do that like this (with appropriate indentation):

for i in [selString1, selString2, selString3]:
    ensemble.setAtoms(structure.select('{0}'.format(i)))
    [do something with the ensemble using those atoms]
