### ISSUE TITLE
PCA job submission error in NMWiz

### ISSUE THREAD

**Issue by JazminOzsvar** [prody/ProDy#746]
Hi all,

I'm currently trying to work through the tutorial files for PCA ensemble analysis on the ProDy website. I'm using Python 2.7.10 and VMD 1.9.3. After loading my files as per the tutorial clicking "submit", NMWiz gives me this error:

@> Superposing  [ 97%] 1s
                         
@> Superposing  [ 98%] 1s
                         
@> Superposing  [ 99%] 1s
                         
@> Superposing  [100%] 0s

while executing
"exec $::NMWiz::pybin $::NMWiz::prody {*}$args"
    (procedure "::NMWiz::prodySubmitPCAjob" line 61)
    invoked from within
"::NMWiz::prodySubmitPCAjob"
    (procedure "::NMWiz::prodySubmitJob" line 26)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

Any clues as to what's going on and how this could be fixed?

**Comment by dwalgenbach** [comment]
I'm having this same problem. I am running it on Windows 10 64 bit .

**Comment by ZhuoLi1986** [comment]
I am facing the same issue, have you figured this out?

**Comment by ZhuoLi1986** [comment]
Thank you very much for the prompt reply. I actually selected a set of residues and CA to do the PCA analysis.  I am not familiar with programming, thus it is hard for me to tell the issue. But I will try to update anything that listed. Thanks a lot.

**Comment by jamesmkrieger** [comment]
I'll look into it and see if I can find the error.

**Comment by derPuntigamer** [comment]
I have the same issue with VMD. I'm not sure if it a VMD related issue or not.

**Comment by hira-jabeen** [comment]
Hi,
 
I am using vmd-1.9.3 and python3.8.0, for PCA analysis through ProDy in VMD.
I am having same issue:

@> Superposing  [ 33%] 1s
                         
@> Superposing  [ 66%] 1s
                         
@> Superposing  [100%] 0s

@> Superposing  [ 33%] 1s
                         
@> Superposing  [ 66%] 1s
                         
@> Superposing  [100%] 0s


@> Superposing  [ 33%] 1s
                         
@> Superposing  [ 66%] 1s
                         
@> Superposing  [100%] 0s

@> Superposing  [ 33%] 1s
                         
@> Superposing  [ 66%] 1s
                         
@> Superposing  [100%] 0s
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody {*}$args"
    (procedure "::NMWiz::prodySubmitPCAjob" line 61)
    invoked from within
"::NMWiz::prodySubmitPCAjob"
    (procedure "::NMWiz::prodySubmitJob" line 26)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)ng same issue:

Kindly advice how to resolve this error.

Many thanks,
Hira

**Comment by jamesmkrieger** [comment]
This is on our to do list for things to fix. We'll let you know when we've sorted it. Sorry for the inconvenience.

**Comment by jamesmkrieger** [comment]
I have a fix now (see #1270).

**Comment by jamesmkrieger** [comment]
This is now merged so issue closed.
