### ISSUE TITLE
python 3 error in parseDCD with step > 1

### ISSUE THREAD

**Issue by chrisgoedde** [prody/ProDy#748]
I get the following error in python 3 when using a step > 1 with parseDCD:

ValueError                                Traceback (most recent call last)

~/anaconda3/lib/python3.6/site-packages/prody/trajectory/dcdfile.py in parseDCD(filename, start, stop, step, astype)
    497     LOGGER.info('DCD file contains {0} coordinate sets for {1} atoms.'
    498                 .format(n_frames, dcd.numAtoms()))
--> 499     ensemble = dcd[slice(start,stop,step)]
    500     dcd.close()
    501     time_ = time() - time_ or 0.01

~/anaconda3/lib/python3.6/site-packages/prody/trajectory/trajbase.py in __getitem__(self, index)
     59             if self._weights is not None:
     60                 ens.setWeights(self._weights.copy())
---> 61             ens.addCoordset(self.getCoordsets(index))
     62             ens.setAtoms(self._atoms)
     63             return ens

~/anaconda3/lib/python3.6/site-packages/prody/trajectory/dcdfile.py in getCoordsets(self, indices)
    335             return data
    336         else:
--> 337             return TrajFile.getCoordsets(self, indices)
    338 
    339     getCoordsets.__doc__ = TrajBase.getCoordsets.__doc__

~/anaconda3/lib/python3.6/site-packages/prody/trajectory/trajfile.py in getCoordsets(self, indices)
    145             diff = index - prev
    146             if diff > 1:
--> 147                 self.skip(diff-1)
    148             xyz = next()
    149             if xyz is None:

~/anaconda3/lib/python3.6/site-packages/prody/trajectory/trajfile.py in skip(self, n)
    165             raise ValueError('I/O operation on closed file')
    166         if not isinstance(n, int):
--> 167             raise ValueError('n must be an integer')
    168         if n > 0:
    169             left = self._n_csets - self._nfi

ValueError: n must be an integer

**Comment by SHZ66** [comment]
I will look into it. Thank you for reporting the bug.

**Comment by SHZ66** [comment]
This bug has been fixed in the dev version and will be released soon. In the meantime, you are welcome to check #753 for a temporary solution.
