### ISSUE TITLE
Evol application issue (like #773)

### ISSUE THREAD

**Issue by cmack2357** [prody/ProDy#764]
When I try installing prody on a mac using the following command 

`pip install prody`

I get the following error

`        gcc -fno-strict-aliasing -I/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iprody/utilities/tnt -I/anaconda2/include/python2.7 -c prody/proteins/ccealign/ccealignmodule.cpp -o build/temp.macosx-10.6-x86_64-2.7/prody/proteins/ccealign/ccealignmodule.o
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from prody/proteins/ccealign/ccealignmodule.cpp:38:
    In file included from prody/proteins/ccealign/ccealignmodule.h:42:
    In file included from prody/utilities/tnt/tnt.h:40:
    prody/utilities/tnt/tnt_math_utils.h:5:10: fatal error: 'cmath' file not found
    #include <cmath>
             ^~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
`

When I copy the compilation command and manually run it using g++ (see command below) in place of gcc it runs without an error.

`g++ -fno-strict-aliasing -I/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iprody/utilities/tnt -I/anaconda2/include/python2.7 -c prody/proteins/ccealign/ccealignmodule.cpp -o build/temp.macosx-10.6-x86_64-2.7/prody/proteins/ccealign/ccealignmodule.o`

Would be nice to have some workaround, even if it meant going into one of the files and modifying something so that it automatically uses g++ instead of gcc.

**Comment by osercinoglu** [comment]
I received the same error when trying to install prody on Mac OS Mojave. I guess this is not really an issue with ProDy but the default gcc compiled used. 

The workaround is to tell setuptools (used for compiling by ProDy) to use a different compiler by setting the `CC` environment variable. In my case using `g++` did not help, but using a different `gcc` did (which was added after installing `build-essential` using homebrew):
 
`export CC=/usr/local/bin/gcc-8`

then run `pip install prody`

**Comment by jamesmkrieger** [comment]
I'm also having an issue with installing Prody on Mac OS Mojave. We are currently working to fix this and will let you know when it is sorted.

I found a workaround for getting most of ProDy to work by removing my xcode and replacing it with version 9.4.1 but the seqtools module still doesn't work. If you don't need to do sequence analysis then you could try doing that for now.

Best wishes
James

**Comment by jamesmkrieger** [comment]
We found a solution to this issue by using MacPorts. There's a package installer on their website. Then you need to update it and install a different gcc that works (I had success with gcc5) and make sure the gcc you installed is the active gcc as follows:

1. `sudo port -d selfupdate` and then you may need to enter another command which your terminal will tell you
2. `sudo port install gcc5` (or any other gcc if you prefer)
3. `port select --list gcc` will list the gcc versions visible to MacPorts
4. `sudo port select --set gcc mp-gcc5` will then make gcc correspond to gcc5 (you would replace this with something else in your list if you prefer)

After this the pip install works for me.

**Comment by gtzotzos** [comment]
Have you tried the evol application in your python 3.7 installation?

See my posting on issue #773. Python 3.7 does not handle the str type. I has replaced this with bytes. As a consequence evol did not work. At least, in my installation.

Best regards

George

**Comment by jamesmkrieger** [comment]
No, I haven't tried the applications. We will look at the apps at some point but don't have time right now.

Oh, also I should note that if you make anaconda environments on this mac version the system python and pip over-ride the conda environment's ones so you have to use the full path for the install to work.

**Comment by jamesmkrieger** [comment]
You can also update your PATH environment variable to sort out the python and pip problem.

Also, you may want to have a python2 environment for installing the applications for now.

**Comment by jamesmkrieger** [comment]
Please try installing the latest ProDy from github and confirm that it works.

Thanks

**Comment by gtzotzos** [comment]
Thank you James,

I’m currently travelling. I should try the installation late next week and will let you know.

Best regards

George

**Comment by gtzotzos** [comment]
I reinstalled ProDy
prody -v
ProDy 1.10.10

I’m running python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

I followed the evol app example. The problem persists. Evol is unable to parse PDB files.
evol rankorder RnaseA_full_refined_mutinfo_corr_apc.txt -p 2w5i_1-121.pdb --seq-sep 3 -o test1
@> Could not parse PDB, ignoring PDB input
@> MSA or PDB not given or does not match mutinfo, using serial indexing
@> Residue numbers start and end with 1-119

I don’t know how relevant this is because although the —seq-sep 3 flag is used the output gives: 
Serial	Row	Column	MI
1	70	63	0.526
2	80	46	0.430
3	70	65	0.314
4	107	69	0.294
5	23	12	0.292
6	31	27	0.264
7	27	23	0.254
8	117	42	0.248

I hope this helps. 

Regards

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. We'll look into it soon.

**Comment by jamesmkrieger** [comment]
This is now the same problem as in #773 and not an installation issue, right?

**Comment by gtzotzos** [comment]
Correct

**Comment by jamesmkrieger** [comment]
Thanks

**Comment by jamesmkrieger** [comment]
Part of the problem here is that this PDB file doesn't exist. Both the online tutorial and the main evol usage examples include it but there is not quite any instruction for writing it. There is instruction for making the relevant selection under http://prody.csb.pitt.edu/tutorials/evol_tutorial/comparison.html#mobility-calculation but no `writePDB` step following it.

**Comment by jamesmkrieger** [comment]
Of course, I still need to work out the `--seq-sep 3` part too.

**Comment by jamesmkrieger** [comment]
Following my fixes, everything works I believe. Please see pull requests #1138 and prody/ProDy-website#65.
