### ISSUE TITLE
covariance matrix

### ISSUE THREAD

**Issue by reillycharles** [prody/ProDy#779]
Hi, when I build a covariance matrix, it produces an matrix that is 3 x the number of atoms.  For example if I have an ensemble with 129 atoms it returns an array with shape (387, 387). Why is it not just (129,129)?  I want to use the covariance matrix in a network analysis pipeline that identifies communities. How do I generate  the  single covariance matrix? Or is it generating a matrix for the x, y and z for each atom?

**Comment by jamesmkrieger** [comment]
What you need is the cross correlation matrix from calcCrossCorr. The covariance matrix has 3x3 submatrices for xx, xy, xz, yx, yy, yz, zx, zy, and zz correlations. I believe this should fix your issue so I am closing it. Please feel free to reopen it if you have any more problems or questions.

Best wishes
James

**Comment by reillycharles** [comment]
Thanks!
