### ISSUE TITLE
Problems residue-specific PRS

### ISSUE THREAD

**Issue by MollyGravett** [prody/ProDy#785]
Hi, 

When trying to work through PRS tutorial but using my own files the sensitivity profile across the whole protein works but it doesn't work when I do the residue-specific sensitivity. 

I keep getting this error:

    raise ValueError('x should be non-negative.')

**ValueError: x should be non-negative.**

Any help or advice on what I should do would be hugely appreciated!!
Thanks!

**Comment by jamesmkrieger** [comment]
Could you please provide your input commands to help me work out what happened.

Best wishes
James

**Comment by MollyGravett** [comment]
```
calphas = parsePDB('monomer.pdb', subset='ca')
anm = ANM('RK ANM analysis')
anm.buildHessian(calphas)
anm.getHessian().round(3)
anm.calcModes()
anm.getEigvals().round(3)
anm.getEigvecs().round(3)
anm.getCovariance().round(2)
show199 = showPerturbResponse(model=anm, atoms=calphas, show_matrix=False, select='chain A and resnum 199')
plt.show199
```

Thanks!!
Molly

**Comment by jamesmkrieger** [comment]
Everything looks fine to me except for the line `plt.show199`. I think you need to type `plt.show()` instead. show199 is an object that contains data about the pyplot objects but it isn't a function that you can run with pyplot.

**Comment by jamesmkrieger** [comment]
I'm assuming this fixed your problem and closing the issue. Feel free to reopen it if you still need help.

Best wishes
James
