### ISSUE TITLE
How to calculate squared inner product (SIP) in prody?

### ISSUE THREAD

**Issue by HimiTar** [prody/ProDy#792]
Hi All

I wanted to know if there is any function (or equivalent) in ProDy to calculate Squared inner product (SIP), which basically gives the similarity between the atomic fluctuations of two proteins? I would like to calculate the correlation between two atomic fluctuation vectors.  Any information in this regard will be useful.

**Comment by SHZ66** [comment]
Sorry, I thought you meant root mean square inner product (RMSIP). I don't think there is a function in ProDy currently for that, but it can be calculated fairly easily as

```
w1 = calcSqFlucts(anm)
w2 = prot.getBetas()

sip = dot(w1, w2)**2 / (dot(w1, w1) * dot(w2, w2))
```

**Comment by HimiTar** [comment]
Hi

Thanks a lot for the reply. I guess this is going to be helpful. :-)

**Comment by jamesmkrieger** [comment]
I have just added pull request #804 with a draft function. This should be able to take in modes or profiles. Please let me know if that satisfies this feature request.

**Comment by jamesmkrieger** [comment]
I'm assuming everything is fine here and closing this issue. Feel free to re-open it if you have any further comments.
