### ISSUE TITLE
B-factors different to that obtained in the web server

### ISSUE THREAD

**Issue by jplanasi** [prody/ProDy#797]
The theoretical B-factors I obtained from the pip installed software and the ANM (http://anm.csb.pitt.edu/cgi-bin/anm2/anm2.cgi) or GNM(http://enm.pitt.edu/) servers are not equal. I used coordinates from 2psf_B to test. 

To obtain theoretical B-factors from ANM server: Enter PDB code and chain, leave all other parameters as per default and press 'Calculate'; when results are displayed click on 'Download Files' and then on 'Theoretical and experimental b-factors'. Downloaded values from the referred page (i.e http://anm.csb.pitt.edu/anm/anmtmp/197841548046719/oanm.bfactors) consider the fourth column for the wanted B-factors. The theoretical values for the first three residues (#10-12 in PDB file numbering) are: 37.6029, 45.8165, and 90.2796

The theoretical B-factors from ProDy were obtained by running:
`prody anm 2PSF -s 'protein and chain B and name CA' -n 20 -b`
and the values obtained for the first three residues are: 27.43, 53.10, and 269.53

To obtain B-factors from GNM server: Enter PDB code and chain, leave all other parameters as per default and press press 'Submit'; when results are displayed click on 'Results in plain text' and then on 'temp_B.bfactor'. Downloaded values from the referred page (http://enm.pitt.edu/work/0121124871/temp_B.bfactor), consider the fourth column for the wanted B-factors. The theoretical values for the first three residues (#10-12 in PDB file numbering) are: 61.7128, 49.5147, and 61.7128

The theoretical B-factors from ProDy were obtained by running:
`prody gnm 2PSF -s 'protein and chain B and name CA' -n 20 -b`
and the values obtained for the first three residues are: 37.63, 36.48, and 165.26

Which command should I use to reproduce the values obtained from the servers? 

Thank you.

**Comment by fongchun** [comment]
On the DynOmics server, the default cutoff used to calculate residue-residue contact map is 7.3 angstrom. While the default value in the ProDy is 10 angstrom. You can configure the cutoff parameter by clicking the "Advanced options" button on the input page.  And, the DynOmics server use all the GNM modes (N-1, N is the number of residues) to calculate the B-factors. In your calculation, you used only the first 20 modes by "-n 20". There are 301 residues in 2PSF_B. You could try 
prody gnm 2PSF -s 'protein and chain B and name CA' -n 300 -b
and you will find the same results as those on DynOmics:
http://enm.pitt.edu/work/0215837017/temp_B.bfactor

It seems that the "-n" parameter only accept the numbers when you are using the prody from a shell command line. You want to input the exact number for all modes. However, in the Python version, you can add a parameter of n_modes with a value of "None" or "all" for all modes in function of calcModes(self, n_modes=20). 
Please check more details in our tutorials:
http://prody.csb.pitt.edu/tutorials/enm_analysis/gnm.html

If you have any problem in the usage of DynOmics, you could check the tutorials also:
http://enm.pitt.edu/Tutorial.php

**Comment by jplanasi** [comment]
Thank you very much for your help.
