### ISSUE TITLE
Inferring bonds in AtomGroups

### ISSUE THREAD

**Issue by npabon** [prody/ProDy#798]
Is there a way to infer covalent bonds from inter-atomic distances in an AtomGroup? Alternatively, can Prody parse the CONECT records in a PDB file?

I'm looking for an alternative to AtomGroup.setBonds() that does not require me to create a list of atom index pairs.

**Comment by SHZ66** [comment]
Hi Nick,

I don't think there is a function in ProDy to do that. Neither does ProDy parse the CONECT records. I am adding this as a feature request.

**Comment by jamesmkrieger** [comment]
Hi Nick,

ProDy does have a bonds module and can parse bond information from PSF files. What you could do is use the AutoPSF module in VMD to generate a PSF file and then use that as input for ProDy.

Inferring bonds would require knowledge about atom types and topologies not just distances, and would be quite extensive to implement in ProDy most likely.

Best wishes
James

**Comment by SHZ66** [comment]
In #961, `parsePDB` is now able to parse the `CONECT` entries. However, we still need to figure out how to infer the covalent bonds within and among standard residues. We could use either bond length or infer from the amino acid types.

**Comment by jamesmkrieger** [comment]
We could maybe use charmm36 topology files. I guess we could also have a wrapper to AutoPSF or OpenBABEL or something.

**Comment by jamesmkrieger** [comment]
I have actually have a solution to this from my MolSSI fellowship bootcamp: https://github.com/jamesmkrieger/MoleCool/blob/master/molecool/molecule.py
