### ISSUE TITLE
Can't use max_n_atoms field of parsePDB() on Mac/Linux (capped at 1e5 atoms)

### ISSUE THREAD

**Issue by alexsaadfalcon** [prody/ProDy#808]

**Comment by jamesmkrieger** [comment]
I've never used the max_n_atoms argument of parsePDB. What you can do instead is to make an AtomGroup object with the right number of atoms and provide it to parsePDB under the ag argument. There are two ways to do this:

1. If you have a psf file:

`struct = parsePSF(psf_filename)`
`struct = parsePDB(pdb_filename, ag=struct)`

2. If you don't have a psf file:

`struct = AtomGroup(some_name)`
`struct._n_atoms = 196856`
`struct = parsePDB('step5_assembly.pdb',ag=struct)`

I hope that helps.

Best wishes
James

**Comment by jamesmkrieger** [comment]
We have now fixed this issue (see #825).
