### ISSUE TITLE
Signature dynamics. Write signature data to file

### ISSUE THREAD

**Issue by gtzotzos** [prody/ProDy#811]
I'm wondering if it is possible to write signature data to file rather than plotting using the
command **show = showSignatureMode(ens_gnms[:,0])**

Thanks in advance for any ideas

George

**Comment by jamesmkrieger** [comment]
Hi George,

It should be possible. You would use `ens_gnms.getEigvec(0)` to get an sdarray containing all the eigenvectors for all the structures and then you can use its mean, std, min and max methods to get the data that gets shown with `showSignatureMode(ens_gnms[:,0])`. You can then write it to a file just like any other data from there.

Best wishes
James

**Comment by gtzotzos** [comment]
Many thanks James,

Great help.

Have a good day

George
