### ISSUE TITLE
Support for writing PDB files with unique identifiers beyond 99999 using Hybrid36

### ISSUE THREAD

**Issue by jamesmkrieger** [prody/ProDy#815]
There's a format at http://cci.lbl.gov/hybrid_36/ that has been designed for that, which we should probably consider.

**Comment by SHZ66** [comment]
Yes, we should. As long as Pymol and VMD support this format then we should support it too.

**Comment by jamesmkrieger** [comment]
Reading is probably fine as we reset serials by counting anyway. I intend to add functionality for reading the serials themselves and then we may need to worry about this again then. 

A first solution to writing is given in #829 - we will need to test it and compare to files from other programs that use this format such as the Phenix structure refinement suite.

**Comment by jamesmkrieger** [comment]
This should be good now.
