### ISSUE TITLE
Selection issue

### ISSUE THREAD

**Issue by KendyP** [prody/ProDy#817]
Hello,
My data consists of 100 pdbs of complexes produced through docking. I'd like to run PCA using ProDy with this data. I am able to read in my list of pdb files; however, I am having issues selecting only the protein residues in my complexes for the calculation. Is there a straightforward way to do this? I  receive the error that my list of atom groups do not have the attribute 'selection'.

**Comment by SHZ66** [comment]
Hi, please share your code so we can help better. But here is what you might want to try:

1. given an AtomGroup instance `ag`, you can do `ag.select('protein')` to select only the protein part;
2. use `.select` instead of `.selection`.

**Comment by jamesmkrieger** [comment]
You could do something like this:
`
proteins = []
for ag in ags:
    proteins.append(ag.select('protein'))

ens = buildPDBEnsemble(proteins)
`

**Comment by jamesmkrieger** [comment]
The list of atomgroups won't have the attribute selection. You have to do the selection on each atomgroup individually as in my suggested code above.

**Comment by KendyP** [comment]
Thanks for your feedback. I apologize for the delayed response. I will try your suggestions. I have 200 complexes produced through rigid-rigid docking of a protein to a nucleic acid structure. I load them in as a list, and would like to only select the protein residues form the complexes and move forward with analysis.
The code I am using to load in the complexes is below:

list = []
for i in range(1,200+1):
        list.append("complex{}_prot.pdb".format(i))

structures = parsePDB(list, compressed = False)

Additionally, could I opt to have an RMSD matrix of the data performed rather than a covariance matrix using ProDy? Would this be done using "calcRMSD()?"

Thank you very much for your help.

**Comment by jamesmkrieger** [comment]
Yes, you can generate an RMSD matrix from the PDBEnsemble I suggested making. The full code would be something like the following:

```
list = []
for i in range(1,200+1):
    list.append("complex{}_prot.pdb".format(i))

structures = parsePDB(list, compressed = False)

proteins = []
for structure in structures:
    proteins.append(ag.select('protein'))

ens = buildPDBEnsemble(proteins)
ens.iterpose()
rmsd_matrix = ens.getRMSDs(pairwise=True)
```

You can also use calcRMSD() yourself but then you would have to make a loop to align the proteins and calculate their RMSDs. The ensemble approach in ProDy handles that. buildPDBEnsemble aligns all the proteins into a PDBEnsemble object and the iterpose method iteratively superposes them until the average RMSD converges. The getRMSDs method then calls calcRMSD() over the ensemble. By default, pairwise=False and it gives the RMSD to the reference coordinates, which come from the first structure in the list initially or the average structure after using iterpose().

**Comment by KendyP** [comment]
I really appreciate your help! Thank you. I will give this a shot.
I will try this and get back to you if I have any further questions.

**Comment by jamesmkrieger** [comment]
You're welcome. Please get back to me if it works and you don't have any questions too.

**Comment by jamesmkrieger** [comment]
I’m assuming you’re fine and closing this issue
