### ISSUE TITLE
download

### ISSUE THREAD

**Issue by olegovich20** [prody/ProDy#818]
Link to download ProDy-1.7.win-amd64-py2.7.exe from http://prody.csb.pitt.edu/downloads/
is not working - cannot download the file to my PC

**Comment by SHZ66** [comment]
For windows, please also use `pip install -U prody`. The binary installers are deprecated.

**Comment by jamesmkrieger** [comment]
We will update the website to make this clearer at some point.

**Comment by SHZ66** [comment]
> We will update the website to make this clearer at some point.

I think I have changed it when we made the release of 1.10.7 but somehow it got changed back.

**Comment by jamesmkrieger** [comment]
This is now fixed again on the website.
