### ISSUE TITLE
AtomMap.getIndices() sometimes fails: list can't be copied

### ISSUE THREAD

**Issue by jamesmkrieger** [prody/ProDy#831]
The problem is related to the fact that atommap._indices and atommap._idarray are lists in some cases. Most of the time, they are arrays and there is no problem. We still need to work out why this happens. It may have something to do with dummy atoms but I'm not sure.

**Comment by SHZ66** [comment]
OK. If there is an example then we can test on it. Or we can try to reproduce it.
