### ISSUE TITLE
Problem with essential dynamics tutorial

### ISSUE THREAD

**Issue by KendyP** [prody/ProDy#862]
Hello,
I am going through the essential dynamics tutorial and I am getting an error. 
http://prody.csb.pitt.edu/tutorials/trajectory_analysis/eda.html

I am currently having an issue in the section concerning plotting results.
mdm2ca_sim1 = trajectory[:500] (This command works fine).
mdm2ca_sim2 = trajectory[500:] (This command returns an error, "n must be an integer").

I have loaded in both trajectory files needed for the tutorial 
trajectory[0:1000] shows I have 1000 frames.
Typing trajectory[#:] where # is any value greater than 0, returns the same error.
Additionally, I tried
 trajectory[#:#] where 0<#<1000, returns the same error. 

Any help would be much appreciated!
Kendy

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. We will look into it and get back to you soon.

Best wishes
James

**Comment by jamesmkrieger** [comment]
This appears to be a problem in python 3 but not python 2. The full error is as follows:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-fcd421aafe67> in <module>()
----> 1 mdm2ca_sim2 = trajectory[500:]

~/Documents/code/ProDy/prody/trajectory/trajbase.py in __getitem__(self, index)
     60             if self._weights is not None:
     61                 ens.setWeights(self._weights.copy())
---> 62             ens.addCoordset(self.getCoordsets(index))
     63             ens.setAtoms(self._atoms)
     64             return ens

~/Documents/code/ProDy/prody/trajectory/trajectory.py in getCoordsets(self, indices)
    163             diff = index - prev
    164             if diff > 1:
--> 165                 self.skip(diff - 1)
    166             coords[i] = next()
    167             prev = index

~/Documents/code/ProDy/prody/trajectory/trajectory.py in skip(self, n)
    249             raise ValueError('I/O operation on closed file')
    250         if not isinstance(n, int):
--> 251             raise ValueError('n must be an integer')
    252         left = self._n_csets - self._nfi
    253         if n > left:

ValueError: n must be an integer`

**Comment by jamesmkrieger** [comment]
This should now be fixed. Thanks again for reporting it. 

I am now closing this issue. Please feel free to reopen it if you still have a problem with this.

**Comment by KendyP** [comment]
Thank you! I will try the tutorial again soon and reach out if there is a problem.

-Kendy
________________________________
