### ISSUE TITLE
select option not working in showPerturbResponse

### ISSUE THREAD

**Issue by jamesmkrieger** [prody/ProDy#874]
![Screenshot from 2019-06-17 17-38-52](https://user-images.githubusercontent.com/51401122/59603178-5b6a7900-9126-11e9-8c8e-1162282b62fd.png)

"select " option in PRS is not giving the expected result. I tried with the '3kg2' example given by you guys. I have attached the error message in the form of  a  picture here. please let me know the mistake.

_Originally posted by @SnehaBheemireddy in https://github.com/prody/ProDy/pull/851#issuecomment-502655779_

**Comment by jamesmkrieger** [comment]
This works for me in both python 2 and python 3. Please can you give us more details about what you did in the earlier steps?

**Comment by jamesmkrieger** [comment]
Hi Sneha,

Could you please look into this more too and let me know any other details to help work out what going wrong please.

Many thanks

**Comment by jamesmkrieger** [comment]
Hi @SnehaBheemireddy,

Have you had a chance to look into this?

**Comment by SnehaBheemireddy** [comment]
Ya . I Could solve the problem just by giving whole ShowPerturbResponse function.

**Comment by jamesmkrieger** [comment]
Could you explain better please. I don't understand what you mean.

**Comment by jamesmkrieger** [comment]
Ok, I guess I'll just accept it's fine then and close the issue
