### ISSUE TITLE
writePSF does not write angles or dihedrals

### ISSUE THREAD

**Issue by alexsaadfalcon** [prody/ProDy#924]
Really throws a wrench in things when trying to manipulate a PDB and PSF and have the results be compatible. I have to edit the PDB in ProDy and then use vmd scripting to edit the PSF, so please fix this.

**Comment by jamesmkrieger** [comment]
ok. We'll look into this soon.

**Comment by jamesmkrieger** [comment]
It seems like we never implemented angles and dihedrals into Atomic objects. I will implement these soon. Sorry for the inconvenience.

**Comment by jamesmkrieger** [comment]
I have started a pull request #933, which includes a start towards this. I will add more to it soon and let you know when I am done.

**Comment by jamesmkrieger** [comment]
Thanks for reminding us about this.

**Comment by jamesmkrieger** [comment]
I believe we are there now.

**Comment by jamesmkrieger** [comment]
We have just merged the pull request introducing these features. Please can you test it and let us know if you have any issues.

**Comment by jamesmkrieger** [comment]
We have another pull request (#1034), which fixes some more issues with this. I think we're basically there now but it would be good if you could test and confirm, please.
