### ISSUE TITLE
alignChains still looks for alternative solutions with match_func=sameChid

### ISSUE THREAD

**Issue by jamesmkrieger** [prody/ProDy#969]
This is a waste of time. If sameChid is provided then that should just be used. Perhaps there should be a keyword for turning on and off this functionality.

**Comment by SHZ66** [comment]
It shouldn't though. If it is a unique mapping, then alignChains should find the optimal solution and stops there.

**Comment by jamesmkrieger** [comment]
You could try 4a0v and 4a0w. I was using a bead model based on 4a0v.

**Comment by jamesmkrieger** [comment]
We decided the problem may be the RMSD cutoff eliminating the only appropriate solution then the algorithm looking for others rather than stopping. Probably the best thing to do would be to turn off the RMSD cutoff when using sameChid

**Comment by jamesmkrieger** [comment]
This issue doesn't seem general so I'm closing it.
