### ISSUE TITLE
Error in `fetchPDB` docstring

### ISSUE THREAD

**Issue by janden** [prody/ProDy#972]
One instance of `fetchPDBviaFTP` should probably be `fetchPDBviaHTTP`:

https://github.com/prody/ProDy/blob/b2293bf055146532e80e4ea171e221e07c3a7a6a/prody/proteins/localpdb.py#L209

**Comment by SHZ66** [comment]
Yes, this is indeed an error. We have fixed in in #973. Thanks a lot for pointing it out.

**Comment by janden** [comment]
Great. Thank you!

**Comment by SHZ66** [comment]
Thank you for reporting! I am closing this issue for now. Feel free to reopen it if there are other questions.
