### ISSUE TITLE
dssp executable is not found in one of system paths

### ISSUE THREAD

**Issue by SherlockedTxh** [prody/ProDy#976]
I installed prody on Ubuntu using "pip install prody" and import is fine,but when I use the execDSSP function it has the error below:

Traceback (most recent call last):
  File "to_dssp.py", line 14, in <module>
    prody.execDSSP(in_dir + '/' + filename, filename, out_dir)
  File "/home/a503tongxueheng/.conda/envs/txh/lib/python3.6/site-packages/prody/proteins/dssp.py", line 42, in execDSSP
    raise EnvironmentError('command not found: dssp executable is not '
OSError: command not found: dssp executable is not found in one of system paths

**Comment by jamesmkrieger** [comment]
I believe you need to install dssp separately and add it to your path yourself. I don't think dssp is included with ProDy. The same applies for ClustalW, which we also have a wrapper script for running.

If you've already installed it then it may be that it's called something else and you may need to make an alias.

**Comment by jamesmkrieger** [comment]
I'm not sure there's anything we can specifically help you with further on this so I'm closing the issue. Feel free to reopen it if you disagree
